/* Yurdunu Bil — semantic effects runtime */
(()=>{'use strict';
if(window.__YB_EFFECTS__)return;window.__YB_EFFECTS__=true;
const prefersReducedMotion=()=>window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
function syncAuthStats(){try{const pool=window.YBQuestionPool,topicCount=pool?.byTopic?Object.keys(pool.byTopic).length:(Array.isArray(window.TOPICS)?window.TOPICS.length:8),questionCount=pool?.total||window.QUESTION_BANK?.length||0;const a=document.getElementById('auth-topic-count'),q=document.getElementById('auth-question-count');if(a&&topicCount)a.textContent=String(topicCount);if(q&&questionCount)q.textContent=questionCount.toLocaleString('tr-TR')+'+'}catch(e){console.warn('auth stats sync',e)}}
const COLORS=['#4bc9ff','#43e1c2','#f5a623','#ef7180','#8e7dff','#4ee2ad','#fff','#ffd700'];
function confetti(duration=2200){if(prefersReducedMotion())return;const wrap=document.createElement('div');wrap.className='yb-confetti-wrap';document.body.appendChild(wrap);for(let i=0;i<72;i++){const p=document.createElement('div');p.className='yb-confetti-piece';p.style.cssText=`left:${Math.random()*100}%;background:${COLORS[Math.floor(Math.random()*COLORS.length)]};width:${6+Math.random()*7}px;height:${8+Math.random()*10}px;animation-duration:${1.2+Math.random()*1.6}s;animation-delay:${Math.random()*.8}s;`;wrap.appendChild(p)}setTimeout(()=>wrap.remove(),duration+800)}
function xpToast(amount,x,y){const value=Number(amount)||0;if(!value)return;const el=document.createElement('div');el.className='yb-xp-toast';el.textContent=`+${value} XP`;el.style.left=(x||window.innerWidth/2-20)+'px';el.style.top=(y||window.innerHeight/2-20)+'px';document.body.appendChild(el);setTimeout(()=>el.remove(),prefersReducedMotion()?500:1600)}
let audioCtx=null;function getAudio(){if(!audioCtx){try{audioCtx=new(window.AudioContext||window.webkitAudioContext)()}catch{return null}}return audioCtx}function playTone(freq,type='sine',duration=.12,vol=.15){const ctx=getAudio();if(!ctx)return;try{if(ctx.state==='suspended')ctx.resume?.();const osc=ctx.createOscillator(),gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.type=type;osc.frequency.value=freq;gain.gain.setValueAtTime(vol,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);osc.start();osc.stop(ctx.currentTime+duration)}catch{}}
const soundCorrect=()=>{playTone(520,'sine',.08,.12);setTimeout(()=>playTone(660,'sine',.1,.12),80)},soundWrong=()=>playTone(260,'sawtooth',.12,.1),soundVictory=()=>[520,660,780,1040].forEach((f,i)=>setTimeout(()=>playTone(f,'sine',.15,.12),i*100)),soundClick=()=>playTone(440,'sine',.06,.06);
let soundEnabled=localStorage.getItem('yb_sound')!=='0';const toggleSound=()=>{soundEnabled=!soundEnabled;localStorage.setItem('yb_sound',soundEnabled?'1':'0');return soundEnabled},safe=fn=>soundEnabled?fn():undefined;
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-answer]');if(!b)return;setTimeout(()=>{if(b.classList.contains('correct')){safe(soundCorrect);const r=b.getBoundingClientRect(),xp=Number(b.dataset.xp||b.closest('[data-xp]')?.dataset.xp||0);if(xp)xpToast(xp,r.left+r.width/2,r.top-20)}else if(b.classList.contains('wrong'))safe(soundWrong)},50)});
window.addEventListener('yb:arena-victory',e=>{if(e.detail?.winner){confetti();safe(soundVictory)}});window.addEventListener('yb:game-complete',e=>{const pct=Number(e.detail?.pct||0);if(pct>=80){confetti(1800);safe(soundVictory)}else safe(soundCorrect)});
function arenaTimerCheck(){if(document.visibilityState!=='visible')return;const el=document.getElementById('yb-arena-timer');if(!el)return;const m=el.textContent.match(/(\d+)/);if(m)el.classList.toggle('yb-arena-critical',Number(m[1])<=5)}
let timerId=null;const startTimer=()=>{if(timerId)return;timerId=setInterval(arenaTimerCheck,1000)};const stopTimer=()=>{if(timerId){clearInterval(timerId);timerId=null}};document.addEventListener('visibilitychange',()=>document.visibilityState==='visible'?startTimer():stopTimer());startTimer();
function mountSoundBtn(){const settings=document.getElementById('view-settings');if(!settings||!settings.classList.contains('active')||settings.querySelector('.yb-sound-toggle'))return;const appearance=settings.querySelector('.settings-appearance-card');if(!appearance)return;const btn=document.createElement('button');btn.className='btn secondary yb-sound-toggle';btn.type='button';btn.textContent=soundEnabled?'🔊 Ses: Açık':'🔇 Ses: Kapalı';btn.onclick=()=>{const on=toggleSound();btn.textContent=on?'🔊 Ses: Açık':'🔇 Ses: Kapalı';if(on)safe(soundClick)};appearance.appendChild(btn)}
document.addEventListener('yb:navigate',e=>{if(e.detail?.view==='settings')setTimeout(mountSoundBtn,200)});window.addEventListener('yb:question-pool-ready',syncAuthStats);window.addEventListener('load',()=>{syncAuthStats();setTimeout(syncAuthStats,300)});
window.YBEffects={confetti,xpToast,soundCorrect,soundWrong,soundVictory,soundClick,toggleSound,isSoundEnabled:()=>soundEnabled,syncAuthStats};
})();
