/* Yurdunu Bil — semantic navigation owner */
(()=>{'use strict';
if(window.__YB98_COHESION__)return;window.__YB98_COHESION__=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const LABELS={home:'Ana Sayfa',library:'Kütüphane',arena:'Arena',events:'Etkinlikler & Oyunlar',settings:'Ayarlar'};
const NAV_LABELS={home:'Ana Sayfa',library:'Kütüphane',arena:'Arena',events:'Etkinlikler'};
const ROUTES=new Set(['home','library','events','settings']);let syncing=false,mapLoading=false;
function loadLearningIndex(){if(window.YBLearningIndex||window.__YB_LEARNING_LOADING__)return;window.__YB_LEARNING_LOADING__=true;const s=document.createElement('script');s.src='data/learning-index.js?v=semantic-1';s.onload=()=>window.__YB_LEARNING_READY__=true;s.onerror=()=>window.__YB_LEARNING_LOADING__=false;document.head.appendChild(s)}
function loadMap(){if(window.YBMapGames?.open){window.YBMapGames.open();return true}if(mapLoading||window.__YB_MAP_LOADING__)return false;mapLoading=true;window.__YB_MAP_LOADING__=true;const s=document.createElement('script');s.src='features/games/map-games.js?v=semantic-1';s.dataset.ybMap='1';s.onload=()=>{mapLoading=false;window.__YB_MAP_LOADING__=false;window.YBMapGames?.open?.()};s.onerror=()=>{mapLoading=false;window.__YB_MAP_LOADING__=false};document.body.appendChild(s);return false}
function closeDrawer(){$('#sidebar')?.classList.remove('open');$('#drawer-backdrop')?.classList.remove('open');document.body.classList.remove('drawer-open')}function closeProfile(){$('#profile-menu')?.classList.add('hidden')}
function syncActive(view){const v=ROUTES.has(view)?view:'home';$$('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));$$('.nav-item[data-view], .yb98-top-link, [data-mobile-view]').forEach(x=>x.classList.toggle('active',(x.dataset.view||x.dataset.mobileView)===v));const t=$('#page-title');if(t)t.textContent=LABELS[v];window.YURDUNUBIL_ROUTE=v;return v}
function safeNavigate(view){if(view==='map'){loadMap();return}if(view==='arena'){window.YBArena?.open?.();closeDrawer();closeProfile();return}if(!ROUTES.has(view))view='home';if(typeof window.YB94Kernel?.navigate==='function'){window.YB94Kernel.navigate(view);closeDrawer();closeProfile();return}const top=$(`.yb98-top-link[data-view="${view}"]`);if(top){top.click();closeDrawer();closeProfile();return}const fallback=$(`[data-view="${view}"]`);if(fallback){fallback.click();closeDrawer();closeProfile();return}syncActive(view);document.dispatchEvent(new CustomEvent('yb:navigate',{detail:{view}}));if(view==='home')setTimeout(()=>window.YB90Home?.render?.(),0)}
function cleanDrawer(){const sidebar=$('#sidebar');if(!sidebar)return;$$('.yb81-arena,#sidebar-arena-btn,.yb81-nav-item,.arena-entry,.events-arena-strip,.yb55-arena-restore,[data-yb55-arena],[data-yb55-social]',sidebar).forEach(x=>x.remove());const nav=$('.side-nav',sidebar);if(nav){$$('[data-view="home"],[data-view="library"],[data-view="events"],[data-view="arena"]',nav).forEach(x=>x.remove());$$('.nav-label',nav).forEach(x=>x.textContent='HESAP')}}
function ensureTopNav(){let top=$('.yb98-top-nav');if(!top){const host=$('.breadcrumbs');if(!host)return;top=document.createElement('nav');top.className='yb98-top-nav';top.setAttribute('aria-label','Ana gezinme');host.insertAdjacentElement('afterend',top)}[['home','⌂'],['library','▤'],['arena','⚔'],['events','◈']].forEach(([view,icon])=>{let b=$(`.yb98-top-link[data-view="${view}"]`,top);if(!b){b=document.createElement('button');b.type='button';b.className='yb98-top-link';b.dataset.view=view;b.innerHTML=`<span class="yb98-icon">${icon}</span><span class="yb98-top-label"></span>`;b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();safeNavigate(view)});top.appendChild(b)}const label=$('.yb98-top-label',b);if(label){label.textContent=NAV_LABELS[view]||LABELS[view];label.title=LABELS[view]}})}
function ensureMobileNav(){let nav=$('#yb98-mobile-nav');if(!nav){nav=document.createElement('nav');nav.id='yb98-mobile-nav';nav.setAttribute('aria-label','Mobil gezinme');nav.innerHTML=[['home','⌂','Ana'],['library','▤','Kütüphane'],['map','🗺','Harita'],['events','🎮','Oyun'],['arena','⚔','Arena']].map(([v,i,l])=>`<button type="button" data-mobile-view="${v}"><span>${i}</span><b>${l}</b></button>`).join('');document.body.appendChild(nav);nav.addEventListener('click',e=>{const b=e.target.closest('[data-mobile-view]');if(!b)return;e.preventDefault();e.stopPropagation();safeNavigate(b.dataset.mobileView)})}const active=$('.view.active')?.id?.replace(/^view-/,'')||'home';$$('[data-mobile-view]',nav).forEach(b=>b.classList.toggle('active',b.dataset.mobileView===active))}
function styleShell(){if($('#yb98-style'))return;const s=document.createElement('style');s.id='yb98-style';s.textContent=`@media(max-width:760px){#yb98-mobile-nav{position:fixed;z-index:9000;left:10px;right:10px;bottom:max(8px,env(safe-area-inset-bottom));display:grid;grid-template-columns:repeat(5,1fr);gap:3px;padding:6px;border:1px solid rgba(95,183,137,.24);border-radius:20px;background:rgba(7,23,16,.97);box-shadow:0 12px 40px rgba(0,0,0,.42);backdrop-filter:blur(18px)}#yb98-mobile-nav button{min-width:0;border:0;border-radius:14px;background:transparent;color:#9bb5a8;padding:6px 2px 5px;font:700 9px/1 Inter,sans-serif;display:flex;flex-direction:column;align-items:center;gap:3px}#yb98-mobile-nav button span{font-size:18px;line-height:1}#yb98-mobile-nav button.active{background:rgba(72,177,119,.17);color:#eaf6ee}}`;document.head.appendChild(s)}
function sync(){if(syncing)return;syncing=true;try{loadLearningIndex();cleanDrawer();ensureTopNav();ensureMobileNav();styleShell()}finally{syncing=false}}
document.addEventListener('yb:navigate',()=>setTimeout(sync,30));window.addEventListener('load',()=>setTimeout(sync,100));new MutationObserver(()=>{if(!syncing)setTimeout(sync,50)}).observe(document.body,{childList:true,subtree:true});window.YBUiRouter={navigate:safeNavigate,openMap:loadMap,sync,labels:LABELS};
})();
