/* Yurdunu Bil — daily progress bridge */
(()=>{'use strict';
if(window.__YB104_PROGRESS__)return;
window.__YB104_PROGRESS__=true;
const KEY='yb104_daily_v1';
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}};
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const dayKey=()=>new Date().toISOString().slice(0,10);
const get=()=>{const old=read(KEY,null);return old&&old.day===dayKey()?old:{day:dayKey(),answers:0,correct:0,games:0,topics:[],xp:0}};
const set=s=>{save(KEY,s);render()};
function render(){const home=document.querySelector('#view-home.active');if(!home)return;let box=document.querySelector('#yb104-progress-loop');const s=get(),target=10,done=Math.min(s.answers,target),pct=Math.round(done/target*100);if(!box){box=document.createElement('section');box.id='yb104-progress-loop';box.className='yb104-progress-loop';const root=home.querySelector('.yb90-home');if(!root)return;root.appendChild(box)}box.innerHTML=`<div class="yb104-progress-head"><div><span class="eyebrow">🎯 BUGÜNÜN HEDEFİ</span><h2>Çalışma zincirini koparma.</h2><p>10 soru çöz, ardından bir oyunla pekiştir.</p></div><strong>${done}/10</strong></div><div class="yb104-progress-track"><i style="width:${pct}%"></i></div><div class="yb104-progress-grid"><button type="button" data-yb104="quiz"><span>🎯</span><b>${Math.max(0,target-done)} soru</b><small>${done>=target?'Hedef tamamlandı':'Hedefe kalan'}</small></button><button type="button" data-yb104="game"><span>🎮</span><b>${s.games?'✓ '+s.games+' oyun':'1 oyun'}</b><small>${s.games?'Bugün oynandı':'Pekiştirmeye geç'}</small></button><button type="button" data-yb104="library"><span>📚</span><b>${s.topics.length} konu</b><small>${s.topics.length?'Bugün dokunuldu':'Bir konu seç'}</small></button></div>`;box.querySelectorAll('[data-yb104]').forEach(b=>b.onclick=()=>{const x=b.dataset.yb104;if(x==='quiz')window.YB88QuestionCenter?.openQuiz?.('all');else if(x==='game')window.navigate?.('events');else window.navigate?.('library')})}
function markAnswer(correct){const s=get();s.answers++;if(correct)s.correct++;s.xp+=correct?10:2;set(s)}
function markGame(){const s=get();s.games++;s.xp+=15;set(s)}
function markTopic(id){if(!id)return;const s=get();if(!s.topics.includes(id))s.topics.push(id);set(s)}
window.YBProgress={answer:markAnswer,game:markGame,topic:markTopic,refresh:render};
document.addEventListener('yb:navigate',e=>{if(e.detail?.view==='home')setTimeout(render,120)});
document.addEventListener('click',e=>{const topic=e.target.closest?.('[data-open-topic]');if(topic)markTopic(topic.dataset.openTopic);if(e.target.closest?.('.yb55-game-card,.yb86-game-card'))setTimeout(render,80)});
window.addEventListener('load',()=>setTimeout(render,500));
})();

/* Settings fallback kept here so settings remains usable even if profile onboarding is skipped. */
(()=>{'use strict';
if(window.__YB105_RUNTIME__)return;
window.__YB105_RUNTIME__=true;
const $=(s,r=document)=>r.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function profile(){try{return window.YBOnboarding?.getProfile?.()||JSON.parse(localStorage.getItem('yb_profile_v1')||'null')||{displayName:'Öğrenci',avatarEmoji:'⭐'}}catch{return{displayName:'Öğrenci',avatarEmoji:'⭐'}}}
function renderSettings(){const v=$('#view-settings');if(!v||!v.classList.contains('active'))return;const p=profile(),name=String(p.displayName||'Öğrenci'),emoji=p.avatarEmoji||'⭐';if(v.querySelector('.yb105-settings'))return;v.innerHTML=`<section class="yb105-settings"><div class="yb105-card"><div class="yb105-profile"><div class="yb105-avatar">${esc(emoji)}</div><div><span class="eyebrow">HESABIN</span><h2>${esc(name)}</h2><p>Profilin ve çalışma tercihlerin burada.</p></div></div><div class="yb105-field"><label for="yb105-name">Kullanıcı adı</label><input id="yb105-name" maxlength="20" value="${esc(name)}" autocomplete="nickname"></div><div class="yb105-actions"><button class="btn primary" id="yb105-save" type="button">Değişiklikleri kaydet</button><button class="btn secondary" id="yb105-profile-reset" type="button">Profil seçimini aç</button></div><div class="yb105-status" id="yb105-status"></div></div><div class="yb105-settings-grid"><div class="yb105-card"><span class="eyebrow">GÖRÜNÜM</span><h2>Tema</h2><p>Arayüz temasını değiştir.</p><div class="yb105-setting-row"><div><b>Tema</b><small>Terra görünümü</small></div><button class="btn secondary" id="yb105-theme" type="button">${document.body.classList.contains('light')?'Koyu moda geç':'Açık moda geç'}</button></div></div><div class="yb105-card"><span class="eyebrow">BİLDİRİMLER</span><h2>Hatırlatmalar</h2><p>Tarayıcı bildirim iznini yönet.</p><div class="yb105-setting-row"><div><b>Tarayıcı bildirimleri</b></div><button class="btn secondary" id="yb105-push" type="button">İzin ver</button></div></div></div></section>`;$('#yb105-save')?.addEventListener('click',async()=>{const n=String($('#yb105-name')?.value||'').trim(),status=$('#yb105-status');if(n.length<2){if(status)status.textContent='Kullanıcı adı en az 2 karakter olmalı.';return}if(n.length>20){if(status)status.textContent='Kullanıcı adı en fazla 20 karakter olabilir.';return}const next={...p,displayName:n};try{localStorage.setItem('yb_profile_v1',JSON.stringify(next));const st=JSON.parse(localStorage.getItem('yb_state_70')||'{}');st.profile={...(st.profile||{}),displayName:n,email:st.profile?.email||''};localStorage.setItem('yb_state_70',JSON.stringify(st));await window.YBOnboarding?.saveSupabase?.(next)}catch{};window.dispatchEvent(new CustomEvent('yb:profile-set',{detail:next}));if(status)status.textContent='✓ Profil kaydedildi.';window.YB90Home?.render?.()});$('#yb105-profile-reset')?.addEventListener('click',()=>window.YBOnboarding?.open?.());$('#yb105-theme')?.addEventListener('click',()=>{document.querySelector('#theme-btn')?.click();setTimeout(renderSettings,40)});$('#yb105-push')?.addEventListener('click',async()=>{const status=$('#yb105-status');if(window.YBNotifications?.requestPush){const ok=await window.YBNotifications.requestPush();if(status)status.textContent=ok?'✓ Bildirim izni etkin.':'Bildirim izni verilemedi veya desteklenmiyor.'}else if(status)status.textContent='Bildirim sistemi henüz yüklenmedi.'})}
window.addEventListener('yb:navigate',e=>{if(e.detail?.view==='settings')setTimeout(renderSettings,80)});
window.addEventListener('load',()=>setTimeout(renderSettings,400));
})();
