/* Canonical Home Feature */
(()=>{'use strict';
if(window.__YB_HOME_FEATURE__)return;window.__YB_HOME_FEATURE__=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const read=(k,d={})=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}};
const EXAM_DATE='2026-10-04T10:15:00+03:00';
function countdown(){const ms=Math.max(0,new Date(EXAM_DATE).getTime()-Date.now());return{d:Math.floor(ms/86400000),h:Math.floor(ms%86400000/3600000),m:Math.floor(ms%3600000/60000)}}
function stats(){const p=read('yb52_progress_v1',{}),r=read('yb_state_70',{}),a=Number(p.answers||0),c=Number(p.correct||0);return{xp:Number(p.xp||0),streak:Number(p.streak||0),best:Number(p.bestStreak||0),answers:a,acc:a?Math.round(c/a*100):0,tests:Array.isArray(r.results)?r.results.length:0}}
function render(){const v=$('#view-home');if(!v||!v.classList.contains('active'))return;const s=stats(),c=countdown(),topics=Array.isArray(window.TOPICS)?window.TOPICS:[],qs=Array.isArray(window.QUESTION_BANK)?window.QUESTION_BANK.length:0;v.innerHTML=`<div class="yb90-home"><section class="yb90-hero"><div class="yb90-hero-copy"><span class="yb90-kicker"><i class="yb90-dot"></i> YURDUNU BİL • KPSS COĞRAFYA 2026</span><h1>Türkiye coğrafyasını <strong>öğren.</strong><br>Bilgini <strong>kanıtla.</strong></h1><p>Konuları öğren, kaliteli sorularla pekiştir, oyunlarla hız kazan ve Arena'da yarış.</p><div class="yb90-actions"><button class="btn primary" data90="library">📚 Çalışmaya başla</button><button class="btn secondary" data90="events">🎮 Oyun merkezine git</button><button class="btn ghost" data90="arena">⚔️ Arena'ya gir</button></div><div class="yb90-proof"><span>📖 ${qs}+ soru</span><span>🗂️ ${topics.length||8} konu</span><span>🎮 9 oyun modu</span><span>⚔️ Canlı Arena</span></div></div><aside class="yb90-hero-side"><div class="yb90-countdown"><span class="eyebrow">SINAVA KALAN SÜRE</span><h3>2026 KPSS Ön Lisans</h3><p>4 Ekim 2026 · 10:15</p><div class="yb90-timer"><div><b data90d>${c.d}</b><span>gün</span></div><div class="yb90-timer-sep">:</div><div><b data90h>${String(c.h).padStart(2,'0')}</b><span>saat</span></div><div class="yb90-timer-sep">:</div><div><b data90m>${String(c.m).padStart(2,'0')}</b><span>dk</span></div></div></div><div class="yb90-user"><span class="eyebrow">İLERLEMEN</span><h3>${s.xp} XP</h3><div class="yb90-user-stats"><div><b>${s.answers}</b><span>Toplam cevap</span></div><div><b>${s.acc}%</b><span>Doğruluk</span></div><div><b>${s.streak}</b><span>Aktif seri</span></div><div><b>${s.tests}</b><span>Test</span></div></div></div></aside></section><section class="yb90-section"><div class="yb90-section-head"><div><span class="eyebrow">HIZLI KONU SEÇ</span><h2>Bugün ne çalışacaksın?</h2><p>Doğrudan istediğin konuya gir.</p></div><button class="btn secondary" data90="library">Tüm kütüphane →</button></div><div class="yb90-topic-row">${topics.slice(0,8).map(t=>`<button class="yb90-topic" data90topic="${String(t.id).replace(/"/g,'&quot;')}"><i>📘</i><span>${String(t.title||t.id)}</span><small>KPSS</small></button>`).join('')}</div></section></div>`;bind(v)}
function bind(v){$$('[data90]',v).forEach(b=>b.addEventListener('click',()=>{const x=b.getAttribute('data90');if(['library','events','settings'].includes(x))window.navigate?.(x);else if(x==='arena')window.YBArena?.open?.()}));$$('[data90topic]',v).forEach(b=>b.addEventListener('click',()=>{const id=b.getAttribute('data90topic');window.navigate?.('library');setTimeout(()=>document.querySelector(`[data-open-topic="${CSS.escape(id)}"]`)?.click(),100)}))}
function tick(){const v=$('#view-home');if(!v?.classList.contains('active'))return;const c=countdown();$('[data90d]',v)?.replaceChildren(c.d);$('[data90h]',v)?.replaceChildren(String(c.h).padStart(2,'0'));$('[data90m]',v)?.replaceChildren(String(c.m).padStart(2,'0'))}
function showHome(){window.navigate?.('home')||render()}
function install(){render();window.YBHome={render,showHome};setInterval(tick,30000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
