/* Yurdunu Bil — v12 Smart Study Center */
(() => {
  'use strict';
  const KEY='yurdunubil_v1', GOAL_KEY='yurdunubil_daily_goal', EXTRA_KEY='yurdunubil_v12_today_extra';
  const $=s=>document.querySelector(s);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const readState=()=>{try{const r=localStorage.getItem(KEY)||localStorage.getItem('kpss_atlas_v2');return r?JSON.parse(r):{}}catch(_){return {}}};
  const today=()=>new Date().toLocaleDateString('en-CA');
  const goal=()=>{const n=Number(localStorage.getItem(GOAL_KEY));return Number.isFinite(n)&&n>=5&&n<=200?n:20};
  const results=s=>Array.isArray(s.results)?s.results:[];
  const total=r=>Number(r?.total??r?.questionCount??r?.count??0)||0;
  const date=r=>String(r?.date??r?.created_at??r?.createdAt??'').slice(0,10);
  const doneToday=rs=>rs.reduce((n,r)=>n+(date(r)===today()?total(r):0),0)+Number(localStorage.getItem(EXTRA_KEY)||0);
  const weak=s=>{const p=s.topicPct&&typeof s.topicPct==='object'?s.topicPct:{};const ts=Array.isArray(window.TOPICS)?window.TOPICS:[];return Object.entries(p).map(([id,v])=>{const t=ts.find(x=>String(x.id??x.key??x.slug??x.name)===String(id));return{name:t?.name||t?.title||id,pct:Math.max(0,Math.min(100,Number(v)||0))}}).sort((a,b)=>a.pct-b.pct).slice(0,3)};
  function style(){if($('#v12-style'))return;const x=document.createElement('style');x.id='v12-style';x.textContent=`.v12-center{margin-top:16px;padding:20px;border:1px solid rgba(255,255,255,.08);border-radius:20px;background:linear-gradient(135deg,rgba(17,34,52,.96),rgba(8,20,33,.96));box-shadow:0 14px 40px rgba(0,0,0,.18)}.v12-head{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-bottom:16px}.v12-kicker{font-size:10px;letter-spacing:.14em;font-weight:800;opacity:.62}.v12-title{margin:3px 0 0;font-size:20px;font-weight:850}.v12-sub{font-size:12px;opacity:.68;margin-top:4px}.v12-grid{display:grid;grid-template-columns:1.2fr 1fr 1fr;gap:12px}.v12-card{min-width:0;padding:15px;border-radius:15px;background:rgba(255,255,255,.045);border:1px solid rgba(255,255,255,.06)}.v12-card h4{margin:0 0 10px;font-size:13px}.v12-big{font-size:28px;font-weight:900;line-height:1}.v12-muted{font-size:11px;opacity:.62}.v12-bar{height:7px;border-radius:99px;background:rgba(255,255,255,.08);overflow:hidden;margin:12px 0 8px}.v12-bar i{display:block;height:100%;border-radius:inherit;background:var(--accent,#55d6a3);transition:width .5s ease}.v12-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.v12-btn{border:0;border-radius:10px;padding:9px 12px;font:inherit;font-size:11px;font-weight:800;cursor:pointer;background:rgba(255,255,255,.08);color:inherit}.v12-btn.primary{background:var(--accent,#55d6a3);color:#041018}.v12-topic{display:flex;justify-content:space-between;gap:10px;font-size:11px;margin:8px 0}.v12-topic b{white-space:nowrap}.v12-empty{font-size:11px;opacity:.6}@media(max-width:760px){.v12-center{padding:15px;border-radius:16px}.v12-head{align-items:flex-start}.v12-grid{grid-template-columns:1fr}.v12-title{font-size:17px}.v12-big{font-size:25px}}`;document.head.appendChild(x)}
  function render(){const dash=$('#view-dashboard');if(!dash||!dash.classList.contains('active'))return;const anchor=dash.querySelector('.topic-progress-panel')||dash.querySelector('.content-grid');if(!anchor||$('.v12-center'))return;style();const s=readState(),rs=results(s),g=goal(),d=doneToday(rs),p=Math.min(100,Math.round(d/g*100)),w=weak(s),streak=Array.isArray(s.streak)?s.streak.length:Number(s.streak)||0;const box=document.createElement('section');box.className='v12-center';box.innerHTML=`<div class="v12-head"><div><div class="v12-kicker">V12 • AKILLI ÇALIŞMA MERKEZİ</div><div class="v12-title">Bugünkü çalışmanı tek ekrandan yönet.</div><div class="v12-sub">Hedefini tamamla, zayıf konularına dön, serini koru.</div></div><button class="v12-btn" id="v12-goal">Hedefi değiştir</button></div><div class="v12-grid"><div class="v12-card"><h4>🎯 Günlük hedef</h4><div><span class="v12-big">${d}</span> <span class="v12-muted">/ ${g} soru</span></div><div class="v12-bar"><i style="width:${p}%"></i></div><div class="v12-muted">${p>=100?'Bugünkü hedef tamamlandı! 🔥':`${Math.max(0,g-d)} soru daha çözersen hedef tamam.`}</div><div class="v12-actions"><button class="v12-btn primary" id="v12-add">+ Soru çözdüm</button></div></div><div class="v12-card"><h4>🧠 Zayıf konular</h4>${w.length?w.map(x=>`<div class="v12-topic"><span>${esc(x.name)}</span><b>%${x.pct}</b></div>`).join(''):'<div class="v12-empty">Test çözdükçe konu performansın burada görünecek.</div>'}<div class="v12-actions"><button class="v12-btn" id="v12-topics">Konulara git →</button></div></div><div class="v12-card"><h4>🔥 Çalışma serisi</h4><div class="v12-big">${streak}</div><div class="v12-muted">günlük seri</div><div class="v12-actions"><button class="v12-btn" id="v12-refresh">Veriyi yenile</button></div></div></div>`;anchor.parentNode.insertBefore(box,anchor);
    $('#v12-goal').onclick=()=>{const v=prompt('Günlük soru hedefin kaç olsun? (5–200)',String(g));if(v!==null){const n=Math.round(Number(v));if(n>=5&&n<=200){localStorage.setItem(GOAL_KEY,String(n));box.remove();render()}}};
    $('#v12-add').onclick=()=>{const n=Math.round(Number(prompt('Bugün kaç soru çözdün?','5')));if(Number.isFinite(n)&&n>0){localStorage.setItem(EXTRA_KEY,String(Number(localStorage.getItem(EXTRA_KEY)||0)+n));box.remove();render()}};
    $('#v12-refresh').onclick=()=>{box.remove();setTimeout(render,0)};
    $('#v12-topics').onclick=()=>{const b=document.querySelector('[data-view="topics"]');if(b)b.click()};
  }
  function start(){let tries=0;const tick=()=>{tries++;try{render()}catch(e){console.warn('V12 merkez hatası',e)}if(tries<30)setTimeout(tick,500)};tick();new MutationObserver(()=>{if(!$('.v12-center'))render()}).observe(document.body,{childList:true,subtree:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();