/* Yurdunu Bil 24.0 — final unified UI kernel */
(() => {
'use strict';
const CFG=window.YURDUNUBIL_CONFIG||{};
const DATA=Array.isArray(window.PROVINCE_DATA)?window.PROVINCE_DATA:[];
const TOPICS=Array.isArray(window.TOPICS)?window.TOPICS:[];
const QUESTIONS=Array.isArray(window.QUESTION_BANK)?window.QUESTION_BANK:[];
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c').trim();
const clone=o=>JSON.parse(JSON.stringify(o));
const initials=n=>String(n||'Öğrenci').trim().split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toLocaleUpperCase('tr-TR')||'Ö';
const KEY='yb_state_24',DEMO='yb_demo_session_24';
const DEFAULT={discovered:[],favorites:[],topicPct:{},results:[],profile:{displayName:'Öğrenci',email:''},theme:'dark'};
let state=loadState(),user=null,sb=null,currentView='dashboard',selected=null,mode='default',geojson=null,quiz=null;
try{if(CFG.SUPABASE_URL&&CFG.SUPABASE_PUBLISHABLE_KEY&&window.supabase)sb=window.supabase.createClient(CFG.SUPABASE_URL,CFG.SUPABASE_PUBLISHABLE_KEY)}catch(e){console.warn(e)}
function province(n){const aliases={'afyon':'Afyonkarahisar'};const q=norm(n);return DATA.find(p=>norm(p.name)===q)||DATA.find(p=>norm(p.name)===norm(aliases[q]||''))||null}
function loadState(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');const s={...clone(DEFAULT),...x,profile:{...DEFAULT.profile,...(x.profile||{})}};s.discovered=[...new Set((x.discovered||[]).map(n=>province(n)?.name).filter(Boolean))].slice(0,81);s.favorites=[...new Set((x.favorites||[]).map(String))];s.results=Array.isArray(x.results)?x.results:[];return s}catch{return clone(DEFAULT)}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){console.warn(e)}}
function topic(id){return TOPICS.find(t=>String(t.id)===String(id))||null}
function discovered(){return Math.min(81,new Set(state.discovered.map(String)).size)}
function solved(){return state.results.reduce((n,r)=>n+(+r.total||0),0)}
function correct(){return state.results.reduce((n,r)=>n+(+r.correct||0),0)}
function score(){return solved()?Math.round(correct()/solved()*100):0}
function toast(msg,type='ok'){const root=$('#toast-root');if(!root)return;const e=document.createElement('div');e.className='toast '+type;e.textContent=msg;root.appendChild(e);requestAnimationFrame(()=>e.classList.add('show'));setTimeout(()=>{e.classList.remove('show');setTimeout(()=>e.remove(),250)},2600)}
function set(id,v){const e=$(id);if(e)e.textContent=v}
function updateUser(){const n=state.profile.displayName||user?.user_metadata?.display_name||user?.email?.split('@')[0]||'Öğrenci',em=state.profile.email||user?.email||'Misafir hesap',av=initials(n);['#side-name','#top-name','#menu-name'].forEach(x=>set(x,n));['#side-email','#menu-email'].forEach(x=>set(x,em));['#side-avatar','#top-avatar','#menu-avatar'].forEach(x=>set(x,av));set('#nav-discovered',discovered())}
function showApp(){document.body.classList.toggle('light',state.theme==='light');$('#auth-screen').classList.add('hidden');$('#app-shell').classList.remove('hidden');updateUser();navigate(currentView)}
function showAuth(){$('#app-shell').classList.add('hidden');$('#auth-screen').classList.remove('hidden')}
async function boot(){if(!sb&&localStorage.getItem(DEMO)==='1'){showApp();return}if(sb){try{const {data}=await sb.auth.getSession();if(data.session){user=data.session.user;await sync();showApp();return}sb.auth.onAuthStateChange(async(_,s)=>{user=s?.user||null;if(user){await sync();showApp()}})}catch(e){console.warn('auth',e)}}showAuth()}
async function sync(){if(!sb||!user)return;try{const [pr,pp,qr,fv]=await Promise.all([sb.from('profiles').select('*').eq('id',user.id).maybeSingle(),sb.from('province_progress').select('*').eq('user_id',user.id),sb.from('quiz_results').select('*').eq('user_id',user.id),sb.from('favorites').select('*').eq('user_id',user.id)]);if(pr.data){state.profile.displayName=pr.data.display_name||state.profile.displayName;state.profile.email=pr.data.email||user.email||''}if(pp.data)state.discovered=[...new Set(pp.data.filter(x=>x.visited).map(x=>province(x.province_name)?.name).filter(Boolean))].slice(0,81);if(qr.data)state.results=qr.data.map(x=>({correct:x.correct,total:x.total,score:x.score,created_at:x.created_at,topic_id:x.topic_id}));if(fv.data)state.favorites=[...new Set(fv.data.map(x=>x.item_id+'|'+x.item_type))];save()}catch(e){console.warn('sync',e)}}
async function upsert(table,payload){if(!sb||!user)return;try{await sb.from(table).upsert(payload)}catch(e){console.warn(table,e)}}
function setupAuth(){$$('.auth-tab').forEach(b=>b.onclick=()=>{const t=b.dataset.authTab;$$('.auth-tab').forEach(x=>x.classList.toggle('active',x===b));$$('.auth-wrap').forEach(x=>x.classList.toggle('active',x.id===t+'-wrap'))});$('#guest-btn').onclick=()=>{state.profile={displayName:'Misafir Öğrenci',email:''};localStorage.setItem(DEMO,'1');save();showApp();toast('Misafir modu hazır.')};$('#login-form').onsubmit=async e=>{e.preventDefault();const email=$('#login-email').value.trim(),password=$('#login-password').value;if(!sb){state.profile={displayName:email.split('@')[0]||'Öğrenci',email};localStorage.setItem(DEMO,'1');save();showApp();return}try{const r=await sb.auth.signInWithPassword({email,password});if(r.error)throw r.error;user=r.data.user;await sync();showApp();toast('Hoş geldin!')}catch(err){set('#login-error',err.message||String(err))}};$('#register-form').onsubmit=async e=>{e.preventDefault();const name=$('#register-name').value.trim(),email=$('#register-email').value.trim(),password=$('#register-password').value;if(!sb){state.profile={displayName:name,email};localStorage.setItem(DEMO,'1');save();showApp();return}try{const r=await sb.auth.signUp({email,password,options:{data:{display_name:name}}});if(r.error)throw r.error;state.profile={displayName:name,email};save();if(r.data.session){user=r.data.user;showApp()}else toast('Kayıt tamamlandı; e-postanı doğrula.')}catch(err){set('#register-error',err.message||String(err))}};$('#forgot-btn').onclick=async()=>{const email=$('#login-email').value.trim();if(!email)return toast('Önce e-posta adresini yaz.','error');if(!sb)return toast('Misafir modunda kullanılamaz.','error');const r=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});toast(r.error?r.error.message:'Sıfırlama bağlantısı gönderildi.',r.error?'error':'ok')};$('#google-btn').onclick=async()=>{if(!sb)return toast('Google girişi için Supabase gerekir.','error');const r=await sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.href}});if(r.error)toast(r.error.message,'error')}}
function setupShell(){document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b){e.preventDefault();navigate(b.dataset.view);closeDrawer();closeProfile()}});$('#menu-btn').onclick=toggleDrawer;$('#sidebar-close').onclick=closeDrawer;$('#drawer-backdrop').onclick=closeDrawer;$('#profile-btn').onclick=()=>$('#profile-menu').classList.toggle('hidden');$('#theme-btn').onclick=()=>{state.theme=state.theme==='light'?'dark':'light';save();document.body.classList.toggle('light',state.theme==='light')};$('#logout-btn').onclick=logout;$('#menu-logout').onclick=logout;$('#global-search').oninput=e=>globalSearch(e.target.value);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#global-search').focus()}if(e.key==='Escape'){closeProfile();closeDrawer()}})}
function toggleDrawer(){$('#sidebar').classList.toggle('open');$('#drawer-backdrop').classList.toggle('open')}function closeDrawer(){$('#sidebar').classList.remove('open');$('#drawer-backdrop').classList.remove('open')}function closeProfile(){$('#profile-menu').classList.add('hidden')}async function logout(){if(sb&&user)await sb.auth.signOut();user=null;localStorage.removeItem(DEMO);showAuth()}
function navigate(v){currentView=v;$$('.view').forEach(x=>x.classList.remove('active'));const el=$('#view-'+v);if(!el)return;el.classList.add('active');$$('.nav-item[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$$('.mobile-nav [data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const labels={dashboard:'Genel Bakış',map:'Türkiye Haritası',topics:'Konu Kütüphanesi',library:'Çalışma Kütüphanesi',quiz:'Mini Test',stats:'İstatistikler',favorites:'Favoriler',settings:'Ayarlar & Profil'};set('#page-title',labels[v]||'Genel Bakış');render(v);const sc=$('#page-wrap');if(sc)sc.scrollTop=0}
function render(v){({dashboard:renderDashboard,map:renderMap,topics:renderTopics,library:renderLibrary,quiz:renderQuiz,stats:renderStats,favorites:renderFavorites,settings:renderSettings}[v]||renderDashboard)();updateUser()}
function heroStats(){return `<div class="stats"><article><span>🗺️</span><b>${discovered()}</b><small>Keşfedilen il <i>/ 81</i></small><em>${Math.round(discovered()/81*100)}%</em></article><article><span>📚</span><b>${TOPICS.filter(t=>(+state.topicPct[t.id]||0)>=100).length}</b><small>Tamamlanan konu <i>/ ${TOPICS.length}</i></small></article><article><span>🏆</span><b>${solved()}</b><small>Çözülen soru</small></article><article><span>🎯</span><b>%${score()}</b><small>Genel başarı</small></article></div>`}
function atlasHead(){return `<div class="atlas-head"><div><span class="eyebrow">İNTERAKTİF ATLAS • 81 İL</span><h2>Türkiye Haritası <mark>3D</mark></h2><p>Katman seç, bir ile tıkla; il yükselsin ve detayları yanında açılsın.</p></div><div class="atlas-meta"><span>SVG ATLAS</span><span>SCROLL YOK</span></div></div>`}
function modeButtons(){return [['default','Standart'],['region','Bölgeler'],['climate','İklim'],['agriculture','Tarım'],['mountains','Dağlar'],['plains','Ovalar'],['water','Su'],['mining','Maden']].map(([id,label])=>`<button type="button" data-mode="${id}" class="${mode===id?'active':''}">${label}</button>`).join('')}
function renderDashboard(){const el=$('#view-dashboard');el.innerHTML=`<div class="hero"><div><span class="eyebrow">ÇALIŞMA PANELİ • 24.0</span><h1>Merhaba, ${esc(state.profile.displayName||'Öğrenci')}! 👋</h1><p>Türkiye'yi haritada keşfet, yüksek getirili bilgileri öğren ve her gün birkaç soru daha çöz.</p></div><div class="hero-actions"><button class="btn secondary" data-view="topics">📚 Konuları keşfet</button><button class="btn primary" id="hero-test">⚡ 5 Soruluk Test</button></div></div>${heroStats()}<div class="dashboard-grid"><section class="atlas-card surface">${atlasHead()}<div class="atlas-shell" id="dash-atlas"><div class="atlas-tools"><label>⌕<input id="dash-search" placeholder="İl ara..."></label><div class="mode-tabs">${modeButtons()}</div></div><div class="legend" id="dash-legend"></div><svg id="dash-svg" class="atlas-svg" viewBox="0 0 1000 520" role="img" aria-label="Türkiye il haritası"></svg><div class="atlas-bottom"><span>💡 İl seç → yükselir → sağdaki bilgi kartı güncellenir.</span><small>81 İL • GEOJSON • SVG</small></div></div></section><aside class="side-stack"><div class="challenge"><span class="eyebrow">⚡ GÜNÜN CHALLENGE'I</span><h3>5 soruda kendini yokla.</h3><p>Hızlı bir tur çöz, bugünkü çalışma ritmini koru.</p><button class="btn primary wide" id="challenge-btn">Hemen Başla →</button></div><div id="selected-panel" class="province-panel">${selected?provincePanel(selected):emptyProvince()}</div><div class="mini-grid"><button data-view="topics">📚<b>Konular</b><small>8 başlık</small></button><button data-view="quiz">✓<b>Mini Test</b><small>120 soru</small></button><button data-view="favorites">☆<b>Favoriler</b><small>${state.favorites.length} kayıt</small></button><button data-view="stats">▥<b>İstatistik</b><small>${score()}%</small></button></div></aside></div><section class="facts surface"><div class="section-head"><div><span class="eyebrow">CANLI HAP BİLGİ</span><h2>Bugünün Coğrafya Hap Bilgileri</h2></div><button id="new-facts" class="link-btn">Yeni bilgi ↻</button></div><div class="fact-grid">${facts().map(f=>`<article><span>${f.icon}</span><small>${esc(f.tag)}</small><h3>${esc(f.q)}</h3><b>→ ${esc(f.a)}</b></article>`).join('')}</div></section>`;bindAtlas('#dash-atlas','#dash-svg','#dash-search','#dash-legend');bindProvincePanel();$('#hero-test').onclick=()=>startQuiz(5);$('#challenge-btn').onclick=()=>startQuiz(5);$('#new-facts').onclick=()=>renderDashboard()}
function renderMap(){const el=$('#view-map');el.innerHTML=`<div class="page-title"><div><span class="eyebrow">81 İL • KATMANLI ATLAS</span><h1>Türkiye Haritası</h1><p>Coğrafi katmanı seç, ili haritadan seç ve bilgiyi aynı ekranda incele.</p></div><button id="clear-selection" class="btn secondary">Seçimi temizle</button></div><div class="map-layout"><section class="atlas-card surface">${atlasHead()}<div class="atlas-shell map-shell" id="map-atlas"><div class="atlas-tools"><label>⌕<input id="map-search" placeholder="İl ara..."></label><div class="mode-tabs">${modeButtons()}</div></div><div class="legend" id="map-legend"></div><svg id="map-svg" class="atlas-svg" viewBox="0 0 1000 520" role="img" aria-label="Türkiye il haritası"></svg><div class="atlas-bottom"><span>🖱️ Haritadaki ile tıkla.</span><small>SCROLL KİLİTLİ • 3D SVG</small></div></div></section><aside class="map-side">${selected?provincePanel(selected):emptyProvince()}</aside></div>`;bindAtlas('#map-atlas','#map-svg','#map-search','#map-legend');bindProvincePanel();$('#clear-selection').onclick=()=>{selected=null;renderMap()}}
function emptyProvince(){return `<div class="empty-province"><div class="empty-icon">⌖</div><h2>Bir il seç</h2><p>Haritadaki herhangi bir ile tıklayarak o ilin KPSS için önemli coğrafi özelliklerini aç.</p><div class="empty-pills"><span>⛰️ Dağlar</span><span>🌾 Ovalar</span><span>💧 Göller</span><span>🌊 Akarsular</span><span>🌱 Tarım</span><span>⛏️ Madenler</span></div></div>`}
function provincePanel(p){const val=(v,d='Belirtilmemiş')=>esc(p[v]||d);return `<div class="province-panel-inner"><div class="province-top"><div class="plate">${esc(p.plate)}</div><div><span class="eyebrow">SEÇİLEN İL • ${esc(p.region)} BÖLGESİ</span><h2>${esc(p.name)}</h2><p>${val('fact','Türkiye coğrafyasında önemli bir il.')}</p></div><button class="icon-btn close-province" data-clear-province>×</button></div><div class="quick-note"><span>🧠 KPSS HIZLI ÖZET</span><b>${val('kpss')}</b></div><div class="geo-grid"><div><small>🌦️ İKLİM</small><b>${val('climate')}</b></div><div><small>⛰️ DAĞLAR / ARAZİ</small><b>${val('terrain')}</b></div><div><small>🌾 OVALAR</small><b>${val('plains',extractField(p,'ova'))}</b></div><div><small>💧 GÖLLER / SULAK ALANLAR</small><b>${val('lakes',extractField(p,'göl'))}</b></div><div><small>🌊 AKARSULAR</small><b>${val('rivers')}</b></div><div><small>🌱 TARIM</small><b>${val('agriculture')}</b></div><div><small>⛏️ MADEN / KAYNAK</small><b>${val('mining')}</b></div><div><small>👥 NÜFUS</small><b>${val('population')}</b></div></div><div class="geography-note"><span>▦ COĞRAFYA NOTU</span><p>${val('fact')}</p></div><div class="memory"><span>⚡ HAFIZA KODU</span><p>${val('kpss')}</p></div><div class="province-actions"><button class="btn primary" data-fav-province="${esc(p.name)}">☆ Favoriye ekle</button><button class="btn secondary" data-province-test="${esc(p.name)}">▣ İli çalış →</button></div></div>`}
function extractField(p,needle){const s=[p.plains,p.terrain,p.lakes,p.rivers,p.fact,p.kpss].filter(Boolean).find(x=>norm(x).includes(norm(needle)));return s||''}
function bindProvincePanel(){document.addEventListener('click',onProvinceAction,{once:true});}
function onProvinceAction(e){const clear=e.target.closest('[data-clear-province]');if(clear){selected=null;renderDashboard();return}const fav=e.target.closest('[data-fav-province]');if(fav){toggleFav(fav.dataset.favProvince+'|province');return}const tst=e.target.closest('[data-province-test]');if(tst){const p=province(tst.dataset.provinceTest);startQuiz(5,p?.name);return}}
async function bindAtlas(rootSel,svgSel,searchSel,legendSel){const root=$(rootSel),svg=$(svgSel);if(!root||!svg)return; if(!geojson){try{const r=await fetch('data/provinces.geojson',{cache:'no-store'});geojson=await r.json()}catch(e){toast('Harita verisi yüklenemedi.','error');return}}renderAtlas(svg,legendSel);const search=$(searchSel);if(search)search.oninput=()=>highlightSearch(svg,search.value);root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;render(vCurrentView());});}
function vCurrentView(){return currentView}
function renderAtlas(svg,legendSel){const features=geojson?.features||[];svg.innerHTML=`<defs><linearGradient id="selectedGradient" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#e5fbff"/><stop offset=".4" stop-color="#65ddff"/><stop offset="1" stop-color="#667cff"/></linearGradient></defs>`;const bounds=geoBounds(features);const paths=[];for(const f of features){const name=f.properties?.name||'';const d=geomPath(f.geometry,bounds);if(!d)continue;const p=province(name), isSel=selected&&p&&norm(p.name)===norm(selected.name);const fill=layerFill(p,mode);const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.innerHTML=`<path class="province-shadow" d="${d}"/><path class="province-shape ${isSel?'selected':''}" data-province="${esc(p?.name||name)}" d="${d}" style="--fill:${fill}"/>`;const shape=g.querySelector('.province-shape');shape.setAttribute('tabindex','-1');shape.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();if(document.activeElement===shape)shape.blur()},{passive:false});shape.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const x=province(shape.dataset.province);if(!x)return;selected=x;state.discovered=[...new Set([...state.discovered,x.name])].slice(0,81);save();render(vCurrentView())});svg.appendChild(g);paths.push({p,shape})}atlas.paths=paths;updateLegend(legendSel,mode)}
function geoBounds(fs){let minX=999,minY=999,maxX=-999,maxY=-999;for(const f of fs){coordsEach(f.geometry,c=>{minX=Math.min(minX,c[0]);maxX=Math.max(maxX,c[0]);minY=Math.min(minY,c[1]);maxY=Math.max(maxY,c[1])})}return{minX,minY,maxX,maxY}}
function coordsEach(g,cb){if(!g)return;if(g.type==='Polygon')g.coordinates.flat().forEach(cb);else if(g.type==='MultiPolygon')g.coordinates.flat(2).forEach(cb)}
function geomPath(g,b){if(!g)return'';const sx=860/(b.maxX-b.minX||1),sy=390/(b.maxY-b.minY||1),s=Math.min(sx,sy);const px=x=>70+(x-b.minX)*s,py=y=>465-(y-b.minY)*s;const ring=a=>a.map((c,i)=>(i?'L':'M')+px(c[0]).toFixed(2)+','+py(c[1]).toFixed(2)).join(' ')+' Z';if(g.type==='Polygon')return g.coordinates.map(ring).join(' ');if(g.type==='MultiPolygon')return g.coordinates.flat().map(ring).join(' ');return''}
function layerFill(p,m){if(!p)return'#4d87d9';if(m==='region')return regionColor(p.region);if(m==='climate')return climateColor(p.climate);if(m==='agriculture')return p.agriculture?'#39cfa1':'#315e74';if(m==='mountains')return /dağ|toros|kackar|köroğlu|ula?dag|ağrı/i.test(p.terrain||'')?'#b48b57':'#416f8d';if(m==='plains')return /ova|çukurova|plato|düzlük|graben/i.test((p.terrain||'')+' '+(p.fact||''))?'#efc65c':'#405f77';if(m==='water')return /ırmak|nehir|göl|sulak|deniz|baraj/i.test((p.rivers||'')+' '+(p.terrain||'')+' '+(p.fact||''))?'#45c9ff':'#385f78';if(m==='mining')return p.mining?'#d88755':'#455f72';return p.color||regionColor(p.region)}
function regionColor(r){const m={Marmara:'#5d8fe5',Ege:'#68b96e',Akdeniz:'#e09b55','İç Anadolu':'#d5a64a','Karadeniz':'#4dc1a4','Doğu Anadolu':'#8c78d9','Güneydoğu Anadolu':'#c66e73'};return m[r]||'#4d87d9'}
function climateColor(c){if(!c)return'#4d87d9';const n=norm(c);if(n.includes('akdeniz'))return'#e68d5e';if(n.includes('karadeniz'))return'#45c9b1';if(n.includes('sert')||n.includes('karasal'))return'#8b7ddd';if(n.includes('gecis'))return'#d0ad62';return'#5f91d4'}
function updateLegend(sel,m){const e=$(sel);if(!e)return;const maps={default:[['#4d87d9','İller'],['#fff','Seçili il']],region:[['#5d8fe5','Marmara / İç Anadolu'],['#68b96e','Ege / Akdeniz'],['#4dc1a4','Karadeniz'],['#8c78d9','Doğu Anadolu'],['#c66e73','Güneydoğu Anadolu']],climate:[['#e68d5e','Akdeniz'],['#45c9b1','Karadeniz'],['#8b7ddd','Karasal'],['#d0ad62','Geçiş']],agriculture:[['#39cfa1','Tarım verisi var'],['#315e74','Düşük/eksik veri']],mountains:[['#b48b57','Dağlık / engebeli'],['#416f8d','Diğer arazi']],plains:[['#efc65c','Ova / plato verisi'],['#405f77','Belirgin veri yok']],water:[['#45c9ff','Su unsuru var'],['#385f78','Belirgin veri yok']],mining:[['#d88755','Maden / kaynak'],['#455f72','Belirgin veri yok']]};e.innerHTML=`<b>HARİTA LEJANTI</b>`+(maps[m]||maps.default).map(x=>`<span><i style="--dot:${x[0]}"></i>${x[1]}</span>`).join('')}
function highlightSearch(svg,q){const n=norm(q);svg.querySelectorAll('.province-shape').forEach(s=>s.classList.toggle('search-hit',!!n&&norm(s.dataset.province).includes(n)))}
function toggleFav(item){const i=state.favorites.indexOf(item);if(i>=0){state.favorites.splice(i,1);toast('Favorilerden çıkarıldı.')}else{state.favorites.push(item);toast('Favorilere eklendi.')}save();if(currentView==='dashboard')renderDashboard()}
function facts(){return[{icon:'🌾',tag:'Tarım',q:'Ordu hangi tarım ürünüyle öne çıkar?',a:'Fındık, kivi, mısır'},{icon:'🌾',tag:'Tarım',q:'Giresun hangi tarım ürünüyle öne çıkar?',a:'Fındık, çay'},{icon:'💧',tag:'Göller',q:'Göller Yöresi hangi bölgede yoğunlaşır?',a:'Akdeniz Bölgesi'},{icon:'🌊',tag:'Akarsular',q:'Türkiye’nin en uzun nehri?',a:'Kızılırmak'}]}
function renderTopics(){const el=$('#view-topics');el.innerHTML=`<div class="page-title"><div><span class="eyebrow">KPSS • KONU KÜTÜPHANESİ</span><h1>Konu Kütüphanesi</h1><p>8 ana konuyu kısa notlar ve testlerle çalış.</p></div></div><div class="topic-grid">${TOPICS.map(t=>`<article class="topic-card surface"><span>${t.icon||'📚'}</span><h3>${esc(t.name||t.title)}</h3><p>${esc(t.description||'KPSS odaklı kısa çalışma notları.')}</p><div class="progress"><i style="width:${Math.max(0,Math.min(100,+(state.topicPct[t.id]||0)))}%"></i></div><small>%${Math.round(state.topicPct[t.id]||0)} tamamlandı</small><button class="btn secondary full" data-topic-test="${esc(t.id)}">Bu konuyu çalış →</button></article>`).join('')}</div>`;$$('[data-topic-test]').forEach(b=>b.onclick=()=>startQuiz(5,b.dataset.topicTest))}
function renderLibrary(){const el=$('#view-library');el.innerHTML=`<div class="page-title"><div><span class="eyebrow">ÇALIŞMA KÜTÜPHANESİ</span><h1>Çalışma Kütüphanesi</h1><p>İl ve konu bazlı hızlı tekrar kartları.</p></div></div><div class="library-grid">${DATA.slice(0,18).map(p=>`<button class="library-item surface" data-open-province="${esc(p.name)}"><span class="plate mini">${esc(p.plate)}</span><div><b>${esc(p.name)}</b><small>${esc(p.region)} • ${esc(p.climate)}</small></div><strong>→</strong></button>`).join('')}</div>`;$$('[data-open-province]').forEach(b=>b.onclick=()=>{selected=province(b.dataset.openProvince);state.discovered=[...new Set([...state.discovered,selected.name])].slice(0,81);save();navigate('dashboard')})}
function startQuiz(count=5,topicOrProvince=''){const pool=topicOrProvince&&topic(topicOrProvince)?QUESTIONS.filter(q=>String(q.topic_id||q.topic)===String(topicOrProvince)):QUESTIONS;const src=[...pool].sort(()=>Math.random()-.5).slice(0,count);quiz={items:src,idx:0,answers:[],correct:0,label:topic(topicOrProvince)?.name||topicOrProvince||'Hızlı Test'};navigate('quiz')}
function renderQuiz(){const el=$('#view-quiz');if(!quiz){el.innerHTML=`<div class="page-title"><div><span class="eyebrow">MİNİ TEST</span><h1>Kendini test et.</h1><p>Konunu seç veya hızlı test başlat.</p></div><button class="btn primary" id="quiz-start">5 Soruluk Test</button></div><div class="quiz-empty surface"><h2>KPSS Coğrafya Mini Test</h2><p>120 soruluk havuzdan karışık bir test oluştur.</p><button id="quiz-start-2" class="btn primary">Teste Başla →</button></div>`;$('#quiz-start').onclick=()=>startQuiz(5);$('#quiz-start-2').onclick=()=>startQuiz(5);return}const q=quiz.items[quiz.idx];if(!q){renderQuizResult();return}el.innerHTML=`<div class="quiz-card surface"><div class="quiz-top"><span>5 SORU • ${esc(quiz.label)}</span><b>${quiz.idx+1} / ${quiz.items.length}</b></div><div class="quiz-progress"><i style="width:${((quiz.idx)/quiz.items.length)*100}%"></i></div><h2>${esc(q.question||q.text)}</h2><div class="answers">${(q.options||q.choices||[]).map((a,i)=>`<button class="answer" data-answer="${i}">${esc(a)}</button>`).join('')}</div><div class="quiz-feedback" id="quiz-feedback"></div><button id="quiz-next" class="btn primary" disabled>Sonraki soru →</button><button id="quiz-exit" class="btn ghost">Çık</button></div>`;$$('.answer').forEach(b=>b.onclick=()=>answerQuiz(+b.dataset.answer,q));$('#quiz-next').onclick=()=>{quiz.idx++;renderQuiz()};$('#quiz-exit').onclick=()=>{quiz=null;renderQuiz()}}
function answerQuiz(i,q){if(quiz.answers[quiz.idx]!=null)return;const correctIndex=q.answer_index??q.correct??0;quiz.answers[quiz.idx]=i;if(i===correctIndex)quiz.correct++;const fb=$('#quiz-feedback');const bs=$$('.answer');bs.forEach((b,k)=>{b.disabled=true;if(k===correctIndex)b.classList.add('correct');if(k===i&&k!==correctIndex)b.classList.add('wrong')});if(fb)fb.textContent=i===correctIndex?'Doğru!':'Yanlış. Doğru cevap işaretlendi.';$('#quiz-next').disabled=false}
function renderQuizResult(){const el=$('#view-quiz');const total=quiz.items.length,c=quiz.correct;state.results.unshift({correct:c,total,score:Math.round(c/total*100),created_at:new Date().toISOString(),topic_id:null});save();el.innerHTML=`<div class="result-card surface"><span class="eyebrow">TEST TAMAMLANDI</span><h1>%${Math.round(c/total*100)}</h1><p>${c} doğru • ${total-c} yanlış</p><button class="btn primary" id="again">Yeni test →</button><button class="btn secondary" id="back-home">Panele dön</button></div>`;$('#again').onclick=()=>startQuiz(5);$('#back-home').onclick=()=>{quiz=null;navigate('dashboard')};quiz=null}
function renderStats(){const el=$('#view-stats');el.innerHTML=`<div class="page-title"><div><span class="eyebrow">İLERLEME</span><h1>İstatistiklerin</h1><p>Çalışma performansını tek ekranda gör.</p></div></div>${heroStats()}<div class="stats-panels"><section class="surface"><h2>Konu ilerlemesi</h2>${TOPICS.map(t=>`<div class="line-progress"><div><b>${esc(t.name||t.title)}</b><span>%${Math.round(state.topicPct[t.id]||0)}</span></div><i><em style="width:${Math.round(state.topicPct[t.id]||0)}%"></em></i></div>`).join('')}</section><section class="surface"><h2>Son testler</h2>${state.results.slice(0,8).map(r=>`<div class="result-row"><b>%${r.score??0}</b><span>${r.correct??0} / ${r.total??0} doğru</span><small>${r.created_at?new Date(r.created_at).toLocaleDateString('tr-TR'):''}</small></div>`).join('')||'<p class="muted">Henüz test sonucu yok.</p>'}</section></div>`}
function renderFavorites(){const items=state.favorites.map(x=>x.split('|')[0]).map(province).filter(Boolean);const el=$('#view-favorites');el.innerHTML=`<div class="page-title"><div><span class="eyebrow">KAYITLARIN</span><h1>Favoriler</h1><p>Tekrar dönmek istediğin iller burada.</p></div></div><div class="library-grid">${items.map(p=>`<button class="library-item surface" data-open-province="${esc(p.name)}"><span class="plate mini">${esc(p.plate)}</span><div><b>${esc(p.name)}</b><small>${esc(p.region)}</small></div><strong>→</strong></button>`).join('')||'<div class="empty-province surface"><h2>Henüz favori yok.</h2><p>Haritadan bir il seçip favorilere ekleyebilirsin.</p></div>'}</div>`;$$('[data-open-province]').forEach(b=>b.onclick=()=>{selected=province(b.dataset.openProvince);navigate('dashboard')})}
function renderSettings(){const el=$('#view-settings');el.innerHTML=`<div class="page-title"><div><span class="eyebrow">HESAP</span><h1>Ayarlar & Profil</h1><p>Profil ve görünüm tercihlerini yönet.</p></div></div><div class="settings-grid"><section class="surface settings-profile"><div class="avatar big">${esc(initials(state.profile.displayName))}</div><h2>${esc(state.profile.displayName)}</h2><p>${esc(state.profile.email||'Misafir hesap')}</p></section><section class="surface"><h2>Görünüm</h2><button class="btn secondary" id="settings-theme">${state.theme==='dark'?'☼ Açık temaya geç':'☾ Koyu temaya geç'}</button><button class="btn danger-btn" id="reset-local">Yerel ilerlemeyi sıfırla</button></section></div>`;$('#settings-theme').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save();document.body.classList.toggle('light',state.theme==='light');renderSettings()};$('#reset-local').onclick=()=>{state=clone(DEFAULT);save();toast('Yerel ilerleme sıfırlandı.');renderSettings()}}
function globalSearch(q){const n=norm(q);if(!n)return;const p=DATA.find(x=>norm(x.name).includes(n));if(p){selected=p;navigate('dashboard')}}
function closeModal(){}
function init(){setupAuth();setupShell();boot()}
init();
})();