/* Yurdunu Bil 23.0 — final unified UI kernel */
(() => {
'use strict';
const CFG=window.YURDUNUBIL_CONFIG||{};
const DATA=Array.isArray(window.PROVINCE_DATA)?window.PROVINCE_DATA:[];
const TOPICS=Array.isArray(window.TOPICS)?window.TOPICS:[];
const QUESTIONS=Array.isArray(window.QUESTION_BANK)?window.QUESTION_BANK:[];
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c').trim();
const clone=o=>JSON.parse(JSON.stringify(o));
const initials=n=>String(n||'Öğrenci').trim().split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toLocaleUpperCase('tr-TR')||'Ö';
const KEY='yb_state_final',DEMO='yb_demo_session_final';
const DEFAULT={discovered:[],favorites:[],topicPct:{},results:[],profile:{displayName:'Öğrenci',email:''},theme:'dark'};
let state=loadState(),user=null,sb=null,currentView='dashboard',selected=null,mode='default',geojson=null,quiz=null;
try{if(CFG.SUPABASE_URL&&CFG.SUPABASE_PUBLISHABLE_KEY&&window.supabase)sb=window.supabase.createClient(CFG.SUPABASE_URL,CFG.SUPABASE_PUBLISHABLE_KEY)}catch(e){console.warn(e)}
function province(n){const aliases={afyon:'Afyonkarahisar'};const q=norm(n);return DATA.find(p=>norm(p.name)===q)||DATA.find(p=>norm(p.name)===norm(aliases[q]||''))||null}
function loadState(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');const s={...clone(DEFAULT),...x,profile:{...DEFAULT.profile,...(x.profile||{})}};s.discovered=[...new Set((x.discovered||[]).map(n=>province(n)?.name).filter(Boolean))].slice(0,81);s.favorites=[...new Set((x.favorites||[]).map(String))];s.results=Array.isArray(x.results)?x.results:[];return s}catch{return clone(DEFAULT)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function topic(id){return TOPICS.find(t=>String(t.id)===String(id))||null}
function discovered(){return state.discovered.length}
function solved(){return state.results.reduce((n,r)=>n+(+r.total||0),0)}
function correct(){return state.results.reduce((n,r)=>n+(+r.correct||0),0)}
function score(){return solved()?Math.round(correct()/solved()*100):0}
function toast(msg,type='ok'){const root=$('#toast-root');if(!root)return;const e=document.createElement('div');e.className='toast '+type;e.textContent=msg;root.appendChild(e);requestAnimationFrame(()=>e.classList.add('show'));setTimeout(()=>{e.classList.remove('show');setTimeout(()=>e.remove(),250)},2600)}
function set(id,v){const e=$(id);if(e)e.textContent=v}
function updateUser(){const n=state.profile.displayName||user?.user_metadata?.display_name||user?.email?.split('@')[0]||'Öğrenci',em=state.profile.email||user?.email||'Misafir hesap',av=initials(n);['#side-name','#top-name','#menu-name'].forEach(x=>set(x,n));['#side-email','#menu-email'].forEach(x=>set(x,em));['#side-avatar','#top-avatar','#menu-avatar'].forEach(x=>set(x,av));set('#nav-discovered',discovered())}
function showApp(){document.body.classList.toggle('light',state.theme==='light');$('#auth-screen').classList.add('hidden');$('#app-shell').classList.remove('hidden');updateUser();navigate(currentView)}
function showAuth(){$('#app-shell').classList.add('hidden');$('#auth-screen').classList.remove('hidden')}
async function boot(){if(!sb&&localStorage.getItem(DEMO)==='1'){showApp();return}if(sb){try{const {data}=await sb.auth.getSession();if(data.session){user=data.session.user;await sync();showApp();return}sb.auth.onAuthStateChange(async(_,s)=>{user=s?.user||null;if(user){await sync();showApp()}})}catch(e){console.warn('auth',e)}}showAuth()}
async function sync(){if(!sb||!user)return;try{const [pr,pp,qr,fv]=await Promise.all([sb.from('profiles').select('*').eq('id',user.id).maybeSingle(),sb.from('province_progress').select('*').eq('user_id',user.id),sb.from('quiz_results').select('*').eq('user_id',user.id),sb.from('favorites').select('*').eq('user_id',user.id)]);if(pr.data){state.profile.displayName=pr.data.display_name||state.profile.displayName;state.profile.email=pr.data.email||user.email||''}if(pp.data)state.discovered=[...new Set(pp.data.filter(x=>x.visited).map(x=>province(x.province_name)?.name).filter(Boolean))].slice(0,81);if(qr.data)state.results=qr.data.map(x=>({correct:x.correct,total:x.total,score:x.score,created_at:x.created_at,topic_id:x.topic_id}));if(fv.data)state.favorites=[...new Set(fv.data.map(x=>x.item_id+'|'+x.item_type))];save()}catch(e){console.warn('sync',e)}}
async function upsert(table,payload){if(!sb||!user)return;try{await sb.from(table).upsert(payload)}catch(e){console.warn(table,e)}}
function setupAuth(){$$('.auth-tab').forEach(b=>b.onclick=()=>{const t=b.dataset.authTab;$$('.auth-tab').forEach(x=>x.classList.toggle('active',x===b));$$('.auth-wrap').forEach(x=>x.classList.toggle('active',x.id===t+'-wrap'))});$('#guest-btn').onclick=()=>{state.profile={displayName:'Misafir Öğrenci',email:''};localStorage.setItem(DEMO,'1');save();showApp();toast('Misafir modu hazır.')};$('#login-form').onsubmit=async e=>{e.preventDefault();const email=$('#login-email').value.trim(),password=$('#login-password').value;if(!sb){state.profile={displayName:email.split('@')[0]||'Öğrenci',email};localStorage.setItem(DEMO,'1');save();showApp();return}try{const r=await sb.auth.signInWithPassword({email,password});if(r.error)throw r.error;user=r.data.user;await sync();showApp();toast('Hoş geldin!')}catch(err){set('#login-error',err.message||String(err))}};$('#register-form').onsubmit=async e=>{e.preventDefault();const name=$('#register-name').value.trim(),email=$('#register-email').value.trim(),password=$('#register-password').value;if(!sb){state.profile={displayName:name,email};localStorage.setItem(DEMO,'1');save();showApp();return}try{const r=await sb.auth.signUp({email,password,options:{data:{display_name:name}}});if(r.error)throw r.error;state.profile={displayName:name,email};save();if(r.data.session){user=r.data.user;showApp()}else toast('Kayıt tamamlandı; e-postanı doğrula.')}catch(err){set('#register-error',err.message||String(err))}};$('#forgot-btn').onclick=async()=>{const email=$('#login-email').value.trim();if(!email)return toast('Önce e-posta adresini yaz.','error');if(!sb)return toast('Misafir modunda kullanılamaz.','error');const r=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});toast(r.error?r.error.message:'Sıfırlama bağlantısı gönderildi.',r.error?'error':'ok')};$('#google-btn').onclick=async()=>{if(!sb)return toast('Google girişi için Supabase gerekir.','error');const r=await sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.href}});if(r.error)toast(r.error.message,'error')}}
function setupShell(){document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b){e.preventDefault();navigate(b.dataset.view);closeDrawer();closeProfile()}});$('#menu-btn').onclick=toggleDrawer;$('#sidebar-close').onclick=closeDrawer;$('#drawer-backdrop').onclick=closeDrawer;$('#profile-btn').onclick=()=>$('#profile-menu').classList.toggle('hidden');$('#theme-btn').onclick=()=>{state.theme=state.theme==='light'?'dark':'light';save();document.body.classList.toggle('light',state.theme==='light')};$('#logout-btn').onclick=logout;$('#menu-logout').onclick=logout;$('#global-search').oninput=e=>globalSearch(e.target.value);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#global-search').focus()}if(e.key==='Escape'){closeProfile();closeDrawer()}})}
function toggleDrawer(){$('#sidebar').classList.toggle('open');$('#drawer-backdrop').classList.toggle('open')}function closeDrawer(){$('#sidebar').classList.remove('open');$('#drawer-backdrop').classList.remove('open')}function closeProfile(){$('#profile-menu').classList.add('hidden')}async function logout(){if(sb&&user)await sb.auth.signOut();user=null;localStorage.removeItem(DEMO);showAuth()}
function navigate(v){currentView=v;$$('.view').forEach(x=>x.classList.remove('active'));const el=$('#view-'+v);if(!el)return;el.classList.add('active');$$('.nav-item[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$$('.mobile-nav [data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const labels={dashboard:'Genel Bakış',map:'Türkiye Haritası',topics:'Konu Kütüphanesi',library:'Çalışma Kütüphanesi',quiz:'Mini Test',stats:'İstatistikler',favorites:'Favoriler',settings:'Ayarlar & Profil'};set('#page-title',labels[v]||'Genel Bakış');render(v);const sc=$('#page-wrap');if(sc)sc.scrollTop=0}
function render(v){({dashboard:renderDashboard,map:renderMap,topics:renderTopics,library:renderLibrary,quiz:renderQuiz,stats:renderStats,favorites:renderFavorites,settings:renderSettings}[v]||renderDashboard)();updateUser()}
function heroStats(){return `<div class="stats"><article><span>🗺️</span><b>${discovered()}</b><small>Keşfedilen il <i>/ 81</i></small><em>${Math.round(discovered()/81*100)}%</em></article><article><span>📚</span><b>${TOPICS.filter(t=>(+state.topicPct[t.id]||0)>=100).length}</b><small>Tamamlanan konu <i>/ ${TOPICS.length}</i></small></article><article><span>🏆</span><b>${solved()}</b><small>Çözülen soru</small></article><article><span>🎯</span><b>%${score()}</b><small>Genel başarı</small></article></div>`}
function atlasHead(){return `<div class="atlas-head"><div><span class="eyebrow">İNTERAKTİF ATLAS • 81 İL</span><h2>Türkiye Haritası <mark>3D</mark></h2><p>Katman seç, bir ile tıkla; il yükselsin ve detayları yanında açılsın.</p></div><div class="atlas-meta"><span>SVG ATLAS</span><span>SCROLL YOK</span></div></div>`}
function modeButtons(){return [['default','Standart'],['region','Bölgeler'],['climate','İklim'],['agriculture','Tarım'],['mountains','Dağlar'],['plains','Ovalar'],['water','Su'],['mining','Maden']].map(([id,label])=>`<button type="button" data-mode="${id}" class="${mode===id?'active':''}">${label}</button>`).join('')}
function renderDashboard(){const el=$('#view-dashboard');el.innerHTML=`<div class="hero"><div><span class="eyebrow">ÇALIŞMA PANELİ • 23.0</span><h1>Merhaba, ${esc(state.profile.displayName||'Öğrenci')}! 👋</h1><p>Türkiye'yi haritada keşfet, yüksek getirili bilgileri öğren ve her gün birkaç soru daha çöz.</p></div><div class="hero-actions"><button class="btn secondary" data-view="topics">📚 Konuları keşfet</button><button class="btn primary" id="hero-test">⚡ 5 Soruluk Test</button></div></div>${heroStats()}<div class="dashboard-grid"><section class="atlas-card surface">${atlasHead()}<div class="atlas-shell" id="dash-atlas"><div class="atlas-tools"><label>⌕<input id="dash-search" placeholder="İl ara..."></label><div class="mode-tabs">${modeButtons()}</div></div><div class="legend" id="dash-legend"></div><svg id="dash-svg" class="atlas-svg" viewBox="0 0 1000 520" role="img" aria-label="Türkiye il haritası"></svg><div class="atlas-bottom"><span>💡 İl seç → yükselir → sağdaki bilgi kartı güncellenir.</span><small>81 İL • GEOJSON • SVG</small></div></div></section><aside class="side-stack"><div class="challenge"><span class="eyebrow">⚡ GÜNÜN CHALLENGE'I</span><h3>5 soruda kendini yokla.</h3><p>Hızlı bir tur çöz, bugünkü çalışma ritmini koru.</p><button class="btn primary wide" id="challenge-btn">Hemen Başla →</button></div><div id="selected-panel" class="province-panel">${selected?provincePanel(selected):emptyProvince()}</div><div class="mini-grid"><button data-view="topics">📚<b>Konular</b><small>8 başlık</small></button><button data-view="quiz">✓<b>Mini Test</b><small>120 soru</small></button><button data-view="favorites">☆<b>Favoriler</b><small>${state.favorites.length} kayıt</small></button><button data-view="stats">▥<b>İstatistik</b><small>${score()}%</small></button></div></aside></div><section class="facts surface"><div class="section-head"><div><span class="eyebrow">CANLI HAP BİLGİ</span><h2>Bugünün Coğrafya Hap Bilgileri</h2></div><button id="new-facts" class="link-btn">Yeni bilgi ↻</button></div><div class="fact-grid">${facts().map(f=>`<article><span>${f.icon}</span><small>${esc(f.tag)}</small><h3>${esc(f.q)}</h3><b>→ ${esc(f.a)}</b></article>`).join('')}</div></section>`;bindAtlas('#dash-atlas','#dash-svg','#dash-search','#dash-legend');bindProvincePanel();$('#hero-test').onclick=()=>startQuiz(5);$('#challenge-btn').onclick=()=>startQuiz(5);$('#new-facts').onclick=()=>renderDashboard()}
function renderMap(){const el=$('#view-map');el.innerHTML=`<div class="page-title"><div><span class="eyebrow">81 İL • KATMANLI ATLAS</span><h1>Türkiye Haritası</h1><p>Coğrafi katmanı seç, ili haritadan seç ve bilgiyi aynı ekranda incele.</p></div><button id="clear-selection" class="btn secondary">Seçimi temizle</button></div><div class="map-layout"><section class="atlas-card surface">${atlasHead()}<div class="atlas-shell map-shell" id="map-atlas"><div class="atlas-tools"><label>⌕<input id="map-search" placeholder="İl ara..."></label><div class="mode-tabs">${modeButtons()}</div></div><div class="legend" id="map-legend"></div><svg id="map-svg" class="atlas-svg" viewBox="0 0 1000 520" role="img" aria-label="Türkiye il haritası"></svg><div class="atlas-bottom"><span>🖱️ Haritadaki ile tıkla.</span><small>SCROLL KİLİTLİ • 3D SVG</small></div></div></section><aside class="map-side">${selected?provincePanel(selected):emptyProvince()}</aside></div>`;bindAtlas('#map-atlas','#map-svg','#map-search','#map-legend');bindProvincePanel();$('#clear-selection').onclick=()=>{selected=null;renderMap()}}
function emptyProvince(){return `<div class="province-panel"><div class="empty-province"><div class="empty-icon">⌖</div><span class="eyebrow">İL DETAYI</span><h2>Haritadan bir il seç.</h2><p>Seçtiğin il haritada yükselir; sağdaki panelde KPSS için gerekli coğrafi unsurlarını birlikte görürsün.</p><div class="empty-pills"><span>⛰️ Dağlar</span><span>🌾 Ovalar</span><span>💧 Göller</span><span>🌊 Akarsular</span><span>⛏️ Maden</span></div></div></div>`}
function provincePanel(p){const fav=state.favorites.includes(p.name+'|province');const val=(v,fallback='Belirtilmemiş')=>esc(v||fallback);return `<div class="province-panel-inner"><div class="province-top"><div class="plate">${val(p.plate,'—')}</div><div><span class="eyebrow">SEÇİLEN İL • ${val(p.region)} BÖLGESİ</span><h2>${val(p.name)}</h2><p>${val(p.fact||p.geographyNote,'Türkiye coğrafyasında önemli bir il.')}</p></div><button type="button" class="icon-btn close-province" aria-label="Seçimi temizle">×</button></div><div class="quick-note"><span>🧠 KPSS HIZLI ÖZET</span><b>${val(p.kpss||p.fact||p.geographyNote)}</b></div><div class="geo-grid"><div><small>🌦️ İKLİM</small><b>${val(p.climate)}</b></div><div><small>⛰️ DAĞLAR</small><b>${val(p.mountains||extract(p.terrain,/dağ|tepe|yayla/i))}</b></div><div><small>🌱 OVALAR</small><b>${val(p.plains||extract(p.terrain,/ova|düzlük/i))}</b></div><div><small>💧 GÖLLER / SULAK</small><b>${val(p.lakes)}</b></div><div><small>🌊 AKARSULAR</small><b>${val(p.rivers)}</b></div><div><small>🌾 TARIM</small><b>${val(p.agriculture)}</b></div><div><small>⛏️ MADEN / KAYNAK</small><b>${val(p.mining)}</b></div><div><small>👥 2025 NÜFUSU</small><b>~${val(p.population,'—')}</b></div></div><div class="geography-note"><span>▣ COĞRAFYA NOTU</span><p>${val(p.geographyNote||p.fact)}</p></div><div class="memory"><span>⚡ HAFIZA KODU</span><p>${val(p.kpss||p.fact,'Bu ilin öne çıkan coğrafi özelliklerini tekrar et.')}</p></div><div class="province-actions"><button class="btn primary" id="fav-province">${fav?'★ Favorilerden çıkar':'☆ Favoriye ekle'}</button><button class="btn secondary" id="study-province">📖 İli çalış →</button></div></div>`}
function extract(text,re){if(!text)return'';return String(text).split(';').find(x=>re.test(x))?.trim()||''}
function facts(){const list=DATA.map(p=>({icon:'🌾',tag:'Tarım',q:`${p.name} hangi ürünlerle öne çıkar?`,a:p.agriculture})).filter(x=>x.a);const pick=i=>list[(Math.floor(Math.random()*Math.max(1,list.length))+i)%Math.max(1,list.length)]||null;return [pick(0)||{icon:'🧭',tag:'Konum',q:'Türkiye hangi enlemler arasındadır?',a:'36°–42° kuzey paralelleri'},pick(1)||{icon:'⛰️',tag:'Dağ',q:'Türkiye’nin en yüksek dağı?',a:'Ağrı Dağı'}, {icon:'💧',tag:'Göller',q:'Göller Yöresi hangi bölgede yoğunlaşır?',a:'Akdeniz Bölgesi'}, {icon:'🌊',tag:'Akarsular',q:'Türkiye’nin en uzun nehri?',a:'Kızılırmak'}]}
async function loadGeo(){if(geojson)return geojson;try{const r=await fetch(`data/provinces.geojson?v=${encodeURIComponent(CFG.APP_VERSION||'23.0.0')}`,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);geojson=await r.json();return geojson}catch(e){toast('Harita verisi yüklenemedi.','error');return null}}
function walk(a,o){if(!Array.isArray(a))return;if(typeof a[0]==='number'){o.push(a);return}a.forEach(x=>walk(x,o))}
function bounds(features){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;features.forEach(f=>{const c=[];walk(f.geometry?.coordinates,c);c.forEach(([x,y])=>{minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)})});return{minX,minY,maxX,maxY}}
function pathD(f,b){const rings=[];function ring(a){if(!Array.isArray(a))return;if(Array.isArray(a[0])&&typeof a[0][0]==='number'){rings.push(a);return}a.forEach(ring)}ring(f.geometry?.coordinates);return rings.map(r=>r.map(([x,y],i)=>`${i?'L':'M'}${(((x-b.minX)/(b.maxX-b.minX))*930+35).toFixed(2)},${(((b.maxY-y)/(b.maxY-b.minY))*430+45).toFixed(2)}`).join(' ')+' Z').join(' ')}
function dataText(p,field){return norm(p?.[field]||'')}
function level(text){const s=String(text||'');const n=s.split(/[,;•]/).map(x=>x.trim()).filter(Boolean).length;return n>=4?'high':n>=2?'mid':'low'}
function fillFor(p){if(mode==='default')return state.discovered.includes(p.name)?'#3fcfb2':'#4e8eea';if(mode==='region')return ({'Marmara':'#56b7ff','Ege':'#4ed5b2','Akdeniz':'#63c7f2','İç Anadolu':'#9b8cf4','Karadeniz':'#35d2bd','Doğu Anadolu':'#7c9cff','Güneydoğu Anadolu':'#f2b55e'})[p.region]||'#5979d9';if(mode==='climate'){const s=dataText(p,'climate');if(s.includes('akdeniz'))return'#ef9369';if(s.includes('karadeniz'))return'#35d2bd';if(s.includes('karasal'))return'#8e9ff4';return'#5dbedb'}if(mode==='agriculture'){const s=dataText(p,'agriculture');if(/pamuk|zeytin|narenciye|incir|üzüm/.test(s))return'#35d5a5';if(/buğday|arpa|mercimek|nohut/.test(s))return'#70c98e';if(/fındık|çay/.test(s))return'#2abbb0';return'#4d8fbd'}if(mode==='mountains')return level(p.mountains||p.terrain)==='high'?'#876fe0':level(p.mountains||p.terrain)==='mid'?'#9b86ee':'#536681';if(mode==='plains')return level(p.plains||extract(p.terrain,/ova|düzlük/i))==='high'?'#e5b74e':level(p.plains||extract(p.terrain,/ova|düzlük/i))==='mid'?'#d4ae55':'#536681';if(mode==='water'){const s=`${p.lakes||''};${p.rivers||''}`;return level(s)==='high'?'#3ebcf1':level(s)==='mid'?'#55c8e9':'#536681'}if(mode==='mining'){const s=dataText(p,'mining');return /petrol|doğal gaz/.test(s)?'#ef8e62':/kömür|linyit/.test(s)?'#d49b58':s?'#f0ad65':'#536681'}return'#4e8eea'}
function legendConfig(){if(mode==='region')return {title:'Bölgeler',items:[['Marmara','#56b7ff'],['Ege','#4ed5b2'],['Akdeniz','#63c7f2'],['İç Anadolu','#9b8cf4'],['Karadeniz','#35d2bd'],['Doğu Anadolu','#7c9cff'],['Güneydoğu Anadolu','#f2b55e']]};if(mode==='climate')return{title:'İklim',items:[['Akdeniz','#ef9369'],['Karadeniz','#35d2bd'],['Karasal','#8e9ff4'],['Geçiş / diğer','#5dbedb']]};if(mode==='agriculture')return{title:'Tarım',items:[['Sanayi bitkileri','#35d5a5'],['Tahıllar','#70c98e'],['Çay / fındık','#2abbb0'],['Diğer','#4d8fbd']]};if(mode==='mountains')return{title:'Dağlar',items:[['Çok belirgin','#876fe0'],['Belirgin','#9b86ee'],['Az / sınırlı','#536681']]};if(mode==='plains')return{title:'Ovalar',items:[['Birden çok ova','#e5b74e'],['Ova / düzlük','#d4ae55'],['Sınırlı','#536681']]};if(mode==='water')return{title:'Su',items:[['Çok sayıda unsur','#3ebcf1'],['Su unsuru','#55c8e9'],['Sınırlı','#536681']]};if(mode==='mining')return{title:'Maden',items:[['Petrol / doğal gaz','#ef8e62'],['Kömür / linyit','#d49b58'],['Diğer kaynak','#f0ad65']]};return{title:'Atlas',items:[['Keşfedilen il','#3fcfb2'],['Diğer iller','#4e8eea']]}}
function renderLegend(sel){const el=$(sel);if(!el)return;const cfg=legendConfig();el.innerHTML=`<b>HARİTA LEJANTI</b>${cfg.items.map(([t,c])=>`<span><i style="--dot:${c}"></i>${esc(t)}</span>`).join('')}<span><i class="selected-dot"></i>Seçili il</span>`}
function bindAtlas(root,svgSel,searchSel,legendSel){const rootEl=$(root),svg=$(svgSel);if(!svg)return;rootEl?.addEventListener('click',e=>{if(e.target.closest('button,input,label'))return});loadGeo().then(g=>{if(!g?.features?.length)return;const b=bounds(g.features);svg.innerHTML='<defs><linearGradient id="selectedGradient" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#efffff"/><stop offset=".38" stop-color="#53dcff"/><stop offset="1" stop-color="#7180ff"/></linearGradient></defs>';g.features.forEach(f=>{const p=province(f.properties?.name);if(!p)return;const d=pathD(f,b);const shadow=document.createElementNS('http://www.w3.org/2000/svg','path');shadow.setAttribute('d',d);shadow.setAttribute('class','province-shadow');svg.appendChild(shadow);const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',d);path.dataset.name=p.name;path.dataset.plate=p.plate;path.setAttribute('class','province-shape '+(selected?.name===p.name?'selected':''));path.style.setProperty('--fill',fillFor(p));path.setAttribute('aria-label',`${p.name} ${p.plate}`);path.addEventListener('pointerdown',e=>{e.preventDefault();path.blur?.()},{passive:false});path.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();path.blur?.();selectProvince(p)});svg.appendChild(path)});if(selected){const p=selected;const f=g.features.find(x=>province(x.properties?.name)?.name===p.name);if(f){const c=centerOf(f,b);const text=document.createElementNS('http://www.w3.org/2000/svg','text');text.setAttribute('x',c[0]);text.setAttribute('y',c[1]-20);text.setAttribute('text-anchor','middle');text.setAttribute('class','province-label');text.textContent=`${p.name} · ${p.plate}`;svg.appendChild(text)}}renderLegend(legendSel)});rootEl?.querySelectorAll('[data-mode]').forEach(btn=>btn.onclick=()=>{mode=btn.dataset.mode;render(currentView)});const input=$(searchSel);if(input)input.oninput=()=>highlight(input.value,svg)}
function centerOf(f,b){const c=[];walk(f.geometry?.coordinates,c);if(!c.length)return[500,260];const avg=c.reduce((a,[x,y])=>[a[0]+x,a[1]+y],[0,0]);const x=avg[0]/c.length,y=avg[1]/c.length;return [((x-b.minX)/(b.maxX-b.minX))*930+35,((b.maxY-y)/(b.maxY-b.minY))*430+45]}
function highlight(q,svg){const n=norm(q);$$('.province-shape',svg).forEach(p=>p.classList.toggle('search-hit',!!n&&norm(p.dataset.name).includes(n)))}
function selectProvince(p){selected=p;state.discovered=[...new Set([...state.discovered,p.name])].filter(n=>province(n)).slice(0,81);save();updateUser();if(sb&&user)upsert('province_progress',{user_id:user.id,province_name:p.name,visited:true});render(currentView);toast(`${p.name} keşfedildi!`)}
function bindProvincePanel(){if(!selected)return;$('#fav-province')?.addEventListener('click',()=>toggleFav(selected));$('#study-province')?.addEventListener('click',()=>{openProvinceStudy(selected)});$('.close-province')?.addEventListener('click',()=>{selected=null;render(currentView)})}
function toggleFav(p){const key=p.name+'|province',i=state.favorites.indexOf(key);if(i>=0)state.favorites.splice(i,1);else state.favorites.push(key);save();if(sb&&user){if(i<0)upsert('favorites',{user_id:user.id,item_id:p.name,item_type:'province'});else sb.from('favorites').delete().eq('user_id',user.id).eq('item_id',p.name).eq('item_type','province').then(()=>{})}render(currentView);toast(i<0?'Favorilere eklendi.':'Favorilerden çıkarıldı.')}
function openProvinceStudy(p){const topicId='konum';const has=QUESTIONS.some(q=>String(q.topic)===topicId);if(has)startQuiz(5,topicId);else startQuiz(5);toast(`${p.name} için mini çalışma başladı.`)}
function renderTopics(){const el=$('#view-topics');el.innerHTML=`<div class="page-title"><div><span class="eyebrow">KPSS • 8 ANA KONU</span><h1>Konu Kütüphanesi</h1><p>En yüksek getirili başlıkları kısa, net ve görsel biçimde çalış.</p></div></div><div class="topic-grid">${TOPICS.map(t=>`<article class="topic-card"><div class="topic-icon">${t.icon}</div><div class="topic-meta"><span>${esc(t.level||'KPSS')}</span><small>${t.minutes||15} dk</small></div><h2>${esc(t.title)}</h2><p>${esc(t.desc)}</p><div class="progress"><i style="width:${Math.min(100,+state.topicPct[t.id]||0)}%"></i></div><footer><span>%${Math.round(+state.topicPct[t.id]||0)} tamamlandı</span><button class="btn secondary" data-topic="${esc(t.id)}">Çalış →</button></footer></article>`).join('')}</div>`;$$('[data-topic]').forEach(b=>b.onclick=()=>openTopic(b.dataset.topic))}
function openTopic(id){const t=topic(id);if(!t)return;$('#modal-root').innerHTML=`<div class="modal-backdrop" id="topic-modal"><div class="study-modal"><button class="icon-btn modal-close">×</button><span class="eyebrow">${esc(t.level||'KPSS')} • ${t.minutes||15} DK</span><h2>${t.icon} ${esc(t.title)}</h2><p>${esc(t.desc)}</p><h3>Bilmen gerekenler</h3><ul>${(t.bullets||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="memory"><span>🧠 HAFIZA KODU / KPSS İPUCU</span><p>${esc(t.tip||'Bu konuyu soru çözerek pekiştir.')}</p></div><div class="modal-actions"><button class="btn secondary modal-close">✓ Bu konuyu çalıştım</button><button class="btn primary" id="topic-test">Bu konudan test çöz →</button></div></div></div>`;$('#topic-modal').onclick=e=>{if(e.target.id==='topic-modal')closeModal()};$$('.modal-close').forEach(x=>x.onclick=()=>{state.topicPct[id]=100;save();closeModal();renderTopics()});$('#topic-test').onclick=()=>{closeModal();startQuiz(5,id)}}
function closeModal(){$('#modal-root').innerHTML=''}
function renderLibrary(){const el=$('#view-library');el.innerHTML=`<div class="page-title"><div><span class="eyebrow">ÇALIŞMA KÜTÜPHANESİ • 81 İL</span><h1>İl Notları</h1><p>Her ilin dağ, ova, göl, akarsu, iklim, tarım ve maden bilgisini hızlıca tekrar et.</p></div></div><div class="library-grid">${DATA.map(p=>`<button class="library-card" data-province="${esc(p.name)}"><span>${String(p.plate).padStart(2,'0')}</span><div><b>${esc(p.name)}</b><small>${esc(p.region)}</small><p>${esc(p.geographyNote||p.fact||'')}</p><em>⛰ ${esc(p.mountains)} • 🌾 ${esc(p.plains)}</em></div></button>`).join('')}</div>`;$$('[data-province]').forEach(b=>b.onclick=()=>{selected=province(b.dataset.province);navigate('map')})}
function startQuiz(n=5,topicId=null){const pool=QUESTIONS.filter(q=>!topicId||String(q.topic)===String(topicId));const source=pool.length?pool:QUESTIONS;const arr=[...source].sort(()=>Math.random()-.5).slice(0,Math.min(n,source.length));quiz={items:arr,index:0,correct:0,answered:false};navigate('quiz')}
function renderQuiz(){const el=$('#view-quiz');if(!quiz){el.innerHTML=`<div class="page-title"><div><span class="eyebrow">KPSS • MİNİ TEST</span><h1>Hızlı Test</h1><p>5 soruluk kısa bir turla bilgini ölç.</p></div><button class="btn primary" id="start-quiz">5 Soruyu Başlat →</button></div><div class="quiz-start surface"><div>⚡</div><h2>Hazırsan başlayalım.</h2><p>Her sorudan sonra kısa bir açıklama göreceksin.</p></div>`;$('#start-quiz').onclick=()=>startQuiz(5);return}const q=quiz.items[quiz.index];el.innerHTML=`<div class="quiz-head"><span>SORU ${quiz.index+1} / ${quiz.items.length}</span><div><i style="width:${quiz.index/quiz.items.length*100}%"></i></div><b>${esc(topic(q.topic)?.title||'KPSS Coğrafya')}</b></div><section class="quiz-card surface"><span class="eyebrow">${esc(topic(q.topic)?.title||'COĞRAFYA')}</span><h1>${esc(q.q)}</h1><div class="options">${q.options.map((o,i)=>`<button type="button" data-answer="${i}"><strong>${String.fromCharCode(65+i)}</strong><span>${esc(o)}</span></button>`).join('')}</div><div id="answer-note"></div></section>`;$$('[data-answer]').forEach(b=>b.onclick=()=>answer(+b.dataset.answer,q))}
function answer(i,q){if(!quiz||quiz.answered)return;quiz.answered=true;const ok=i===q.answer;if(ok)quiz.correct++;$$('[data-answer]').forEach((b,n)=>{b.disabled=true;if(n===q.answer)b.classList.add('correct');if(n===i&&!ok)b.classList.add('wrong')});$('#answer-note').innerHTML=`<div class="answer-note ${ok?'ok':'bad'}"><b>${ok?'✓ Doğru!':'✕ Yanlış.'}</b><span>${esc(q.explain||'Doğru cevabı tekrar ederek pekiştir.')}</span><button class="btn primary" id="next-q">${quiz.index+1===quiz.items.length?'Sonucu gör':'Sonraki soru →'}</button></div>`;$('#next-q').onclick=()=>{if(quiz.index+1===quiz.items.length){state.results.unshift({correct:quiz.correct,total:quiz.items.length,score:Math.round(quiz.correct/quiz.items.length*100),created_at:new Date().toISOString(),topic_id:q.topic});save();if(sb&&user)upsert('quiz_results',{user_id:user.id,correct:quiz.correct,total:quiz.items.length,score:Math.round(quiz.correct/quiz.items.length*100),topic_id:q.topic});quiz=null;renderQuiz()}else{quiz.index++;quiz.answered=false;renderQuiz()}}}
function renderStats(){const el=$('#view-stats');el.innerHTML=`<div class="page-title"><div><span class="eyebrow">İLERLEME</span><h1>İstatistikler</h1><p>Çalışma ritmini ve güçlü olduğun alanları takip et.</p></div></div><div class="stats-large"><article><span>🎯</span><b>%${score()}</b><small>Genel başarı</small></article><article><span>✓</span><b>${correct()}</b><small>Doğru cevap</small></article><article><span>📝</span><b>${solved()}</b><small>Toplam soru</small></article><article><span>🗺️</span><b>${discovered()} / 81</b><small>Keşfedilen il</small></article></div><section class="surface progress-panel"><h2>Konu ilerlemesi</h2>${TOPICS.map(t=>`<div class="topic-progress"><div><b>${t.icon} ${esc(t.title)}</b><span>%${Math.round(+state.topicPct[t.id]||0)}</span></div><i><em style="width:${Math.min(100,+state.topicPct[t.id]||0)}%"></em></i></div>`).join('')}</section>`}
function renderFavorites(){const fav=state.favorites.map(x=>x.split('|')[0]).map(province).filter(Boolean);$('#view-favorites').innerHTML=`<div class="page-title"><div><span class="eyebrow">KAYITLARIN</span><h1>Favoriler</h1><p>Tekrar dönmek istediğin illeri burada tut.</p></div></div>${fav.length?`<div class="favorite-grid">${fav.map(p=>`<article class="favorite-card"><span>${String(p.plate).padStart(2,'0')}</span><div><b>${esc(p.name)}</b><small>${esc(p.region)}</small><p>${esc(p.geographyNote||p.fact||'')}</p></div><button data-fav="${esc(p.name)}">Aç →</button></article>`).join('')}</div>`:`<div class="empty-state surface"><div>☆</div><h2>Henüz favorin yok.</h2><p>Haritadan bir il seçip favoriye eklediğinde burada görünecek.</p><button class="btn primary" data-view="map">Haritaya git →</button></div>`}`;$$('[data-fav]').forEach(b=>b.onclick=()=>{selected=province(b.dataset.fav);navigate('map')})}
function renderSettings(){const el=$('#view-settings');el.innerHTML=`<div class="page-title"><div><span class="eyebrow">HESAP</span><h1>Ayarlar & Profil</h1><p>Profilini ve yerel çalışma verilerini yönet.</p></div></div><section class="surface settings-card"><div class="settings-user"><span class="avatar big">${initials(state.profile.displayName)}</span><div><h2>${esc(state.profile.displayName)}</h2><p>${esc(state.profile.email||'Misafir hesap')}</p></div></div><label>Görünen ad<input id="setting-name" value="${esc(state.profile.displayName)}"></label><label>E-posta<input value="${esc(state.profile.email||'')}" disabled></label><div class="setting-row"><div><b>Görünüm</b><small>Koyu / açık tema</small></div><button id="setting-theme" class="btn secondary">${state.theme==='dark'?'☀ Açık temaya geç':'☾ Koyu temaya geç'}</button></div><button id="save-profile" class="btn primary">Profili kaydet</button><button id="reset-data" class="btn danger-btn">Yerel çalışma verilerini sıfırla</button></section>`;$('#save-profile').onclick=()=>{state.profile.displayName=$('#setting-name').value.trim()||'Öğrenci';save();updateUser();toast('Profil güncellendi.')};$('#setting-theme').onclick=()=>{$('#theme-btn').click();renderSettings()};$('#reset-data').onclick=()=>{if(confirm('Yerel çalışma verilerin silinsin mi?')){state=clone(DEFAULT);save();selected=null;renderSettings();updateUser();toast('Veriler sıfırlandı.')}}}
function globalSearch(q){const n=norm(q);if(n.length<2)return;const p=DATA.find(x=>norm(x.name).includes(n));const t=TOPICS.find(x=>norm(x.title).includes(n));if(p){selected=p;navigate('map');return}if(t){navigate('topics');setTimeout(()=>openTopic(t.id),20)}}
function init(){setupAuth();setupShell();if(location.search.includes('auth=register'))$('.auth-tab[data-auth-tab="register"]')?.click();boot()}
init();
})();
