/* Yurdunu Bil 21.2 — rebuilt application core */
(() => {
  'use strict';
  const CFG = window.YURDUNUBIL_CONFIG || {};
  const DATA = Array.isArray(window.PROVINCE_DATA) ? window.PROVINCE_DATA : [];
  const TOPICS = Array.isArray(window.TOPICS) ? window.TOPICS : [];
  const QUESTIONS = Array.isArray(window.QUESTION_BANK) ? window.QUESTION_BANK : [];
  const $ = (s,r=document) => r.querySelector(s);
  const $$ = (s,r=document) => [...r.querySelectorAll(s)];
  const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const norm = v => String(v||'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c').trim();
  const today = () => new Date().toLocaleDateString('en-CA');
  const initials = n => String(n||'Öğrenci').trim().split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toLocaleUpperCase('tr-TR')||'Ö';
  const clone = o => JSON.parse(JSON.stringify(o));
  const DEFAULT = {discovered:[],favorites:[],topicPct:{},results:[],streak:[],profile:{displayName:'Öğrenci',email:''},theme:'dark'};
  let state = loadState();
  let currentView = 'dashboard';
  let geojson = null;
  let atlas = {paths:[],bounds:null,mode:'default'};
  let selectedProvince = null;
  let quiz = null;
  let pomodoro = {seconds:25*60,total:25*60,running:false,timer:null};
  let sb = null, user = null;
  const DEMO_SESSION_KEY = 'yb_demo_session_21';
  try { if(CFG.SUPABASE_URL && CFG.SUPABASE_PUBLISHABLE_KEY && window.supabase) sb=window.supabase.createClient(CFG.SUPABASE_URL,CFG.SUPABASE_PUBLISHABLE_KEY); } catch(e){ console.warn(e); }
  function loadState(){try{const raw=JSON.parse(localStorage.getItem('yb_state_21')||'{}');const next={...clone(DEFAULT),...raw,profile:{...DEFAULT.profile,...(raw.profile||{})},topicPct:{...(raw.topicPct||{})},results:Array.isArray(raw.results)?raw.results:[],streak:Array.isArray(raw.streak)?raw.streak:[]};next.discovered=[...new Set((Array.isArray(raw.discovered)?raw.discovered:[]).map(String))];next.favorites=[...new Set((Array.isArray(raw.favorites)?raw.favorites:[]).map(String))];return next}catch(_){return clone(DEFAULT)}}
  function saveState(){try{localStorage.setItem('yb_state_21',JSON.stringify(state))}catch(_){}}
  function toast(msg,type='ok'){const root=$('#toast-root');const el=document.createElement('div');el.className='toast '+type;el.textContent=msg;root.appendChild(el);requestAnimationFrame(()=>el.classList.add('show'));setTimeout(()=>{el.classList.remove('show');setTimeout(()=>el.remove(),250)},2600)}
  function province(name){const aliases={'afyon':'Afyonkarahisar'};const key=norm(name);return DATA.find(p=>norm(p.name)===key)||DATA.find(p=>norm(p.name)===norm(aliases[key]||''))||null}
  function topic(id){return TOPICS.find(t=>String(t.id)===String(id))||null}
  function pctFor(id){return Math.max(0,Math.min(100,Number(state.topicPct?.[id]||0)))}
  function discoveredCount(){return new Set(state.discovered.map(String)).size}
  function solved(){return state.results.reduce((n,r)=>n+(Number(r.total)||0),0)}
  function correct(){return state.results.reduce((n,r)=>n+(Number(r.correct)||0),0)}
  function score(){const t=solved();return t?Math.round(correct()/t*100):0}
  function setText(id,text){const el=$(id);if(el)el.textContent=text}
  function setProfileUI(){const name=state.profile.displayName||user?.user_metadata?.display_name||user?.email?.split('@')[0]||'Öğrenci';const email=state.profile.email||user?.email||'Misafir hesap';const av=initials(name);['#side-name','#top-name','#menu-name'].forEach(s=>setText(s,name));['#side-email','#menu-email'].forEach(s=>setText(s,email));['#side-avatar','#top-avatar','#menu-avatar'].forEach(s=>setText(s,av));setText('#nav-discovered',String(discoveredCount()))}
  function showApp(){ $('#auth-screen').classList.add('hidden');$('#app-shell').classList.remove('hidden');setProfileUI();navigate(currentView||'dashboard'); }
  function showAuth(){ $('#app-shell').classList.add('hidden');$('#auth-screen').classList.remove('hidden'); }
  async function bootAuth(){
    if(!sb && localStorage.getItem(DEMO_SESSION_KEY)==='1'){showApp();return}
    if(sb){try{const {data}=await sb.auth.getSession();if(data.session){user=data.session.user;await syncRemote();showApp();return}sb.auth.onAuthStateChange(async(_e,session)=>{user=session?.user||null;if(user){await syncRemote();showApp()}})}catch(e){console.warn(e)}}
    showAuth();
  }
  async function syncRemote(){if(!sb||!user)return;try{const [{data:pr},{data:pp},{data:qr},{data:fv}]=await Promise.all([sb.from('profiles').select('*').eq('id',user.id).maybeSingle(),sb.from('province_progress').select('*').eq('user_id',user.id),sb.from('quiz_results').select('*').eq('user_id',user.id).order('created_at',{ascending:false}),sb.from('favorites').select('*').eq('user_id',user.id)]);if(pr){state.profile.displayName=pr.display_name||state.profile.displayName;state.profile.email=pr.email||user.email||''}if(pp)state.discovered=pp.filter(x=>x.visited).map(x=>x.province_name);if(qr)state.results=qr.map(x=>({correct:x.correct,total:x.total,score:x.score,created_at:x.created_at,topic_id:x.topic_id}));if(fv)state.favorites=fv.map(x=>x.item_id+'|'+x.item_type);saveState();setProfileUI()}catch(e){console.warn('remote sync',e)}}
  async function remoteInsert(table,payload){if(!sb||!user)return;try{await sb.from(table).upsert(payload)}catch(e){console.warn(e)}}
  function setupAuth(){
    const requested=new URLSearchParams(location.search).get('auth');
    if(requested==='register'){const b=$('[data-auth-tab=register]');if(b)b.click()}
    $$('.auth-tab').forEach(b=>b.addEventListener('click',()=>{const tab=b.dataset.authTab;$$('.auth-tab').forEach(x=>x.classList.toggle('active',x===b));$('#login-wrap').classList.toggle('active',tab==='login');$('#register-wrap').classList.toggle('active',tab==='register')}));
    $('.password-toggle')?.addEventListener('click',e=>{const i=$('#'+e.currentTarget.dataset.target);i.type=i.type==='password'?'text':'password';e.currentTarget.textContent=i.type==='password'?'Göster':'Gizle'});
    $('#guest-btn').onclick=()=>{state.profile={displayName:'Misafir Öğrenci',email:''};localStorage.setItem(DEMO_SESSION_KEY,'1');saveState();showApp();toast('Misafir olarak devam ediyorsun. Verilerin bu cihazda saklanır.');};
    $('#login-form').addEventListener('submit',async e=>{e.preventDefault();const email=$('#login-email').value.trim(),password=$('#login-password').value;if(!sb){state.profile={displayName:email.split('@')[0]||'Öğrenci',email};localStorage.setItem(DEMO_SESSION_KEY,'1');saveState();showApp();return}try{const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;user=data.user;await syncRemote();showApp();toast('Hoş geldin!')}catch(err){$('#login-error').textContent=authError(err)}});
    $('#register-form').addEventListener('submit',async e=>{e.preventDefault();const name=$('#register-name').value.trim(),email=$('#register-email').value.trim(),password=$('#register-password').value;if(!sb){state.profile={displayName:name,email};saveState();showApp();return}try{const {data,error}=await sb.auth.signUp({email,password,options:{data:{display_name:name}}});if(error)throw error;state.profile={displayName:name,email};saveState();if(data.session){user=data.user;showApp()}else{toast('Kayıt tamamlandı. E-postanı doğrula.')} }catch(err){$('#register-error').textContent=authError(err)}});
    $('#forgot-btn').onclick=async()=>{const email=$('#login-email').value.trim();if(!email)return toast('Önce e-posta adresini yaz.','error');if(!sb)return toast('Misafir modunda şifre sıfırlama yok.','error');try{const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(error)throw error;toast('Şifre sıfırlama bağlantısı gönderildi.')}catch(e){toast(authError(e),'error')}};
    $('#google-btn').onclick=async()=>{if(!sb)return toast('Google girişi için Supabase bağlantısı gerekir.','error');try{const {error}=await sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.href}});if(error)throw error}catch(e){toast(authError(e),'error')}};
  }
  function authError(e){const m=String(e?.message||e||'');if(/invalid login credentials/i.test(m))return'E-posta veya şifre hatalı.';if(/already registered/i.test(m))return'Bu e-posta zaten kayıtlı.';return m||'İşlem sırasında bir hata oluştu.'}
  function setupNavigation(){
    document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b){e.preventDefault();navigate(b.dataset.view);closeProfile();closeDrawer()} });
    $('#logout-btn').onclick=logout;$('#menu-logout').onclick=logout;$('#profile-btn').onclick=()=>$('#profile-menu').classList.toggle('hidden');$('#theme-btn').onclick=toggleTheme;$('#menu-btn').onclick=toggleDrawer;$('#drawer-backdrop').onclick=closeDrawer;
    document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#global-search')?.focus()}if(e.key==='Escape'){closeProfile();closeModal();closeDrawer()}});
    $('#global-search').addEventListener('input',e=>globalSearch(e.target.value));
  }
  function closeProfile(){$('#profile-menu').classList.add('hidden')}
  function toggleDrawer(){$('#sidebar').classList.toggle('open');$('#drawer-backdrop').classList.toggle('open')}
  function closeDrawer(){$('#sidebar').classList.remove('open');$('#drawer-backdrop').classList.remove('open')}
  function toggleTheme(){state.theme=state.theme==='light'?'dark':'light';saveState();document.body.classList.toggle('light',state.theme==='light');toast(state.theme==='light'?'Açık tema hazır.':'Koyu tema hazır.')}
  async function logout(){closeProfile();if(sb&&user)await sb.auth.signOut();user=null;localStorage.removeItem(DEMO_SESSION_KEY);showAuth();toast('Oturum kapatıldı.')}
  function navigate(view){currentView=view;$$('.view').forEach(v=>v.classList.remove('active'));const el=$('#view-'+view);if(!el)return;el.classList.add('active');$$('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('.mobile-nav [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const labels={dashboard:'Genel Bakış',map:'Türkiye Haritası',topics:'Konu Kütüphanesi',library:'Çalışma Kütüphanesi',quiz:'Mini Test',stats:'İstatistikler',favorites:'Favoriler',settings:'Ayarlar & Profil'};setText('#page-title',labels[view]||'Genel Bakış');renderView(view)}
  function renderView(view){if(view==='dashboard')renderDashboard();if(view==='map')renderMapView();if(view==='topics')renderTopics();if(view==='library')renderLibrary();if(view==='quiz')renderQuiz();if(view==='stats')renderStats();if(view==='favorites')renderFavorites();if(view==='settings')renderSettings();setProfileUI()}
  function renderDashboard(){
    const el=$('#view-dashboard');
    const fact=pickFact();
    const selected=selectedProvince;
    const regionStats={};
    DATA.forEach(p=>{regionStats[p.region]=(regionStats[p.region]||0)+1});
    const regionCount=Object.keys(regionStats).length;
    el.innerHTML=`
      <div class="dashboard-hero">
        <div class="hero-title"><span class="kicker">ÇALIŞMA PANELİ • 21.7</span><h1>Merhaba, ${esc(state.profile.displayName||'Öğrenci')}! 👋</h1><p>Türkiye'yi haritada keşfet, yüksek getirili bilgileri öğren ve her gün birkaç soru daha çöz.</p></div>
        <div class="hero-actions"><button class="btn btn-secondary" data-view="topics">📚 Konuları keşfet</button><button class="btn btn-primary" id="hero-test">⚡ 5 Soruluk Test</button></div>
      </div>
      <div class="stat-row dashboard-stats">
        <div class="stat stat-featured"><div class="stat-icon">🗺️</div><div><b>${discoveredCount()}</b><span>Keşfedilen İl <em>/ 81</em></span></div><i>${Math.round(discoveredCount()/81*100)}%</i></div>
        <div class="stat"><div class="stat-icon">📚</div><div><b>${TOPICS.filter(t=>pctFor(t.id)>=100).length}</b><span>Tamamlanan Konu <em>/ ${TOPICS.length}</em></span></div></div>
        <div class="stat"><div class="stat-icon">🏆</div><div><b>${solved()}</b><span>Çözülen Soru</span></div></div>
        <div class="stat"><div class="stat-icon">🎯</div><div><b>%${score()}</b><span>Genel Başarı</span></div></div>
      </div>
      <div class="dashboard-bento">
        <section class="surface map-card dashboard-map-card">
          <div class="map-head"><div><span class="kicker">İNTERAKTİF ATLAS</span><h2>Türkiye Haritası <span class="badge">3D</span></h2><p>Bir ile tıkla. İl yükselsin, detayları yanında açılsın.</p></div><div class="map-tabs">${['default','region','climate','agriculture','mountains','plains','water','mining'].map((m,i)=>`<button class="map-tab ${i===0?'active':''}" data-map-mode="${m}">${['Standart','Bölgeler','İklim','Tarım','Dağlar','Ovalar','Su','Maden'][i]}</button>`).join('')}</div></div>
          <div class="atlas-wrap dashboard-atlas" id="dashboard-atlas"><div class="atlas-grid"></div><div class="atlas-stars"></div><div class="map-search"><span>⌕</span><input id="map-search-dashboard" placeholder="İl ara..." aria-label="İl ara"></div><div class="map-legend"><b>HARİTA LEJANTI</b><div id="dash-legend-items"></div></div><div class="atlas-hint">💡 İl seçtiğinde kartı burada sağ tarafta görürsün.</div><div class="atlas-status">81 İL • GEOJSON • 3D SVG • İNTERAKTİF</div><svg class="atlas-svg" id="dashboard-svg" viewBox="0 0 1000 520" preserveAspectRatio="xMidYMid meet"></svg></div>
          <div class="map-footer-strip"><div><span>🧭</span><b>${regionCount} coğrafi bölge</b><small>Türkiye genelini keşfet</small></div><div><span>⚡</span><b>${discoveredCount()} il keşfedildi</b><small>Haritada işaretli</small></div><button class="btn btn-ghost" data-view="map">Büyük atlası aç →</button></div>
        </section>
        <aside class="dashboard-rail">
          <section id="dashboard-province-card" class="surface selected-province-card ${selected?'has-selection':'no-selection'}">${selected?dashboardProvinceCard(selected):dashboardProvinceEmpty()}</section>
          <div class="rail-grid">
            <section class="side-widget challenge"><div class="widget-kicker">⚡ GÜNÜN CHALLENGE'I</div><h3>5 soruda kendini yokla.</h3><p>Hızlı bir tur çöz, bugünkü ritmini koru.</p><button class="btn btn-primary full" id="challenge-btn">Hemen Başla →</button></section>
            <section class="side-widget compact-target"><div class="widget-kicker">🎯 BUGÜNKÜ HEDEF</div><div class="target-value"><b>${Math.min(20,solved()%21)}</b><span>/ 20 soru</span></div><div class="progress-line"><i style="width:${Math.min(100,solved()/20*100)}%"></i></div><small>Bugün 20 soruya ulaş.</small></section>
          </div>
          <section class="side-widget focus-widget"><div class="widget-title"><h3>◷ Çalışma İstasyonu</h3><span>ODAK</span></div><div class="focus-inline"><strong id="dash-timer">25:00</strong><div><button class="btn btn-secondary" id="timer-start">▶ Başlat</button><button class="btn btn-ghost" id="timer-reset">↺</button></div></div></section>
          <section class="side-widget quick-widget"><div class="widget-title"><h3>⚡ Hızlı Erişim</h3><button class="link-btn" data-view="topics">Tümü →</button></div><div class="quick-links quick-links-compact"><button class="quick-link" data-view="topics"><b>📚 Konular</b><span>8 başlık</span></button><button class="quick-link" data-view="quiz"><b>✓ Mini Test</b><span>120 soru</span></button><button class="quick-link" data-view="favorites"><b>💛 Favoriler</b><span>${state.favorites.length} kayıt</span></button><button class="quick-link" data-view="stats"><b>▥ İstatistik</b><span>İlerlemen</span></button></div></section>
        </aside>
      </div>
      <section class="surface facts dashboard-facts"><div class="facts-head"><div><span class="kicker">CANLI HAP BİLGİ</span><h2>🧠 Bugünün Coğrafya Hap Bilgileri</h2><p>KPSS için kısa, net ve ezberlenebilir bilgiler.</p></div><button class="link-btn" id="new-fact">Yeni bilgi ↻</button></div><div class="card-grid" id="fact-grid">${factCards(fact)}</div></section>
      <section class="dashboard-bottom-grid"><section class="surface library-banner"><div><span class="kicker">ÇALIŞMA KÜTÜPHANESİ</span><b>Yüksek getirili notlara geç.</b><p>Konuları düzenli çalış, tamamladıkça ilerleme çubuğun dolsun.</p></div><button class="btn btn-secondary" data-view="library">Kütüphaneyi aç →</button></section><section class="surface exam-widget"><div><span class="kicker">2026 KPSS</span><b>Sınava kalan süre</b></div><strong id="dashboard-countdown">—</strong><button class="btn btn-ghost" data-view="settings">Sayacı görüntüle →</button></section></section>`;
    renderAtlas($('#dashboard-svg')); bindDashboard(); updateDashboardCountdown();
  }
  function dashboardProvinceEmpty(){return `<div class="province-empty"><div class="empty-map-icon">⌖</div><span class="kicker">İL DETAYI</span><h3>Haritadan bir il seç</h3><p>Seçtiğin il haritada yükselir; iklim, dağ, ova, göl, akarsu, tarım ve maden bilgileri burada açılır.</p><div class="empty-hint">↖ Bir il seçerek başla</div></div>`}
  function dashboardProvinceCard(p){const fav=isFav(p.name,'province');return `<div class="dashboard-province-head"><div class="province-emblem large">${String(p.plate).padStart(2,'0')}</div><div><span class="kicker">SEÇİLEN İL • ${esc(p.region)} BÖLGESİ</span><h3>${esc(p.name)}</h3><p>${esc(p.fact||'KPSS odaklı il özeti')}</p></div><button class="icon-btn province-clear" id="dashboard-clear-province" title="Seçimi temizle">×</button></div><div class="province-mini-summary"><span>🧠 KPSS HIZLI ÖZET</span><b>${esc(p.kpss||p.fact||'Kısa KPSS özeti')}</b></div><div class="province-mini-grid"><div><span>🌦️ İklim</span><b>${esc(p.climate||'—')}</b></div><div><span>⛰️ Dağlar</span><b>${esc(p.mountains||p.terrain||'—')}</b></div><div><span>🌾 Ovalar</span><b>${esc(p.plains||'—')}</b></div><div><span>💧 Göller</span><b>${esc(p.lakes||'—')}</b></div><div><span>🌊 Akarsular</span><b>${esc(p.rivers||'—')}</b></div><div><span>⛏️ Maden</span><b>${esc(p.mining||'—')}</b></div></div><div class="province-card-foot"><div><span>👥 Nüfus</span><b>${esc(p.population||'—')}</b></div><div class="province-actions-inline"><button class="btn ${fav?'btn-secondary':'btn-primary'}" data-fav-province="${esc(p.name)}">${fav?'★ Favoriden çıkar':'☆ Favoriye ekle'}</button><button class="btn btn-secondary" data-study-province="${esc(p.name)}">İli çalış →</button></div></div>`}
  const facts=[['🌲','Bitki Örtüsü',"Türkiye'de ormanların en geniş yer kapladığı bölge hangisidir?",'Karadeniz Bölgesi'],['🏭','Sanayi',"Türkiye'de sanayinin en fazla geliştiği bölge hangisidir?",'Marmara Bölgesi'],['🫒','Tarım',"Zeytin üretiminde Türkiye'de öne çıkan bölge hangisidir?",'Ege Bölgesi'],['💧','Akarsular',"Türkiye'nin en uzun akarsuyu hangisidir?",'Kızılırmak'],['🍵','Tarım','Çay tarımının temel merkezi neresidir?','Doğu Karadeniz'],['⛏️','Maden','Bor yatakları hangi alanlarda yoğundur?','Eskişehir, Kütahya, Balıkesir, Bursa'],['🏔️','Türkiye’nin Enleri','Türkiye’nin en yüksek dağı hangisidir?','Ağrı Dağı — 5.137 m'],['🌻','Tarım','Ayçiçeği üretiminde öne çıkan alan neresidir?','Trakya']];
  function pickFact(){const shuffled=facts.slice().sort(()=>Math.random()-.5);return shuffled.slice(0,4)}
  function factCards(list){return list.map(f=>`<article class="info-card"><div class="fact-icon">${f[0]}</div><span class="badge">${esc(f[1])}</span><h3>${esc(f[2])}</h3><span class="fact-answer">→ ${esc(f[3])}</span></article>`).join('')}
  function bindDashboard(){$$('.map-tab').forEach(b=>b.onclick=()=>{$$('.map-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');atlas.mode=b.dataset.mapMode;renderAtlas($('#dashboard-svg'))});$('#map-search-dashboard').oninput=e=>highlightSearch(e.target.value);$('#new-fact').onclick=()=>{$('#fact-grid').innerHTML=factCards(pickFact())};$('#challenge-btn').onclick=()=>startChallenge();$('#hero-test').onclick=()=>startChallenge();$('#timer-start').onclick=toggleTimer;$('#timer-reset').onclick=resetTimer;$('#dashboard-clear-province')?.addEventListener('click',()=>{selectedProvince=null;renderDashboard()})}
  function regionClass(region){const n=norm(region);if(n.includes('marmara'))return'region-marmara';if(n.includes('ege'))return'region-ege';if(n.includes('akdeniz'))return'region-akdeniz';if(n.includes('karadeniz'))return'region-karadeniz';if(n.includes('dogu'))return'region-dogu';if(n.includes('guney'))return'region-guney';return'region-ic'}
  function loadGeo(){if(geojson)return Promise.resolve(geojson);return fetch('data/provinces.geojson',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('GeoJSON yüklenemedi');return r.json()}).then(j=>{geojson=j;atlas.paths=makePaths(j);return j})}
  function coordsOfGeometry(g){const arr=[];if(!g)return arr;const pushRing=r=>r.forEach(pt=>arr.push(pt));if(g.type==='Polygon')g.coordinates.forEach(pushRing);if(g.type==='MultiPolygon')g.coordinates.forEach(poly=>poly.forEach(pushRing));return arr}
  function makePaths(j){const pts=j.features.flatMap(f=>coordsOfGeometry(f.geometry));const xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]);const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);const pad=42;const sx=(1000-pad*2)/(maxX-minX),sy=(520-pad*2)/(maxY-minY),s=Math.min(sx,sy);const ox=(1000-(maxX-minX)*s)/2,oy=(520-(maxY-minY)*s)/2;const project=p=>[(p[0]-minX)*s+ox,520-((p[1]-minY)*s+oy)];const ringPath=r=>r.map((p,i)=>{const q=project(p);return(i?'L':'M')+q[0].toFixed(2)+' '+q[1].toFixed(2)}).join(' ')+' Z';const dOf=g=>g.type==='Polygon'?g.coordinates.map(ringPath).join(' '):g.coordinates.map(poly=>poly.map(ringPath).join(' ')).join(' ');return j.features.map((f,i)=>{const name=f.properties?.name||f.properties?.NAME||`İl ${i+1}`;const raw=coordsOfGeometry(f.geometry);const center=raw.length?[raw.reduce((a,p)=>a+p[0],0)/raw.length,raw.reduce((a,p)=>a+p[1],0)/raw.length]:[35,39];const c=project(center);return{name,d:dOf(f.geometry),cls:regionClass(province(name)?.region||''),feature:f,cx:c[0],cy:c[1]}})}
  function hasData(v){return !!v&&v!=='—'&&v!=='Belirtilmemiş'}
  function modeFill(p){const pr=province(p.name);if(!pr)return '#2b73ad';const m=atlas.mode;
    if(m==='region'){const r=norm(pr.region);if(r.includes('marmara'))return '#4c8dff';if(r.includes('ege'))return '#a77bff';if(r.includes('akdeniz'))return '#ff876f';if(r.includes('karadeniz'))return '#35c9ad';if(r.includes('dogu'))return '#7b8dff';if(r.includes('guney'))return '#d86f9d';return '#f0b84d'}
    if(m==='agriculture'){const s=norm(pr.agriculture);if(/çay|findik|fındık|zeytin|pamuk|üzüm|kayisi|kayısı|narenciye|mısır|misir|bugday|buğday|arpa|şeker|seker/.test(s))return '#35c7a4';return hasData(pr.agriculture)?'#347fb5':'#253f59'}
    if(m==='climate'){const s=norm(pr.climate);if(s.includes('akdeniz'))return '#ef8a68';if(s.includes('karadeniz'))return '#35c9ad';if(s.includes('karasal'))return '#8c82ef';if(s.includes('gecis'))return '#d0ad58';return '#4f82c6'}
    if(m==='mountains')return hasData(pr.mountains)?'#8d76e8':'#27455f';
    if(m==='plains')return hasData(pr.plains)?'#55c982':'#27455f';
    if(m==='water')return (hasData(pr.lakes)||hasData(pr.rivers))?'#36bce8':'#27455f';
    if(m==='mining')return hasData(pr.mining)?'#d39a4d':'#27455f';
    return null}
  function legendForMode(){const maps={default:[['#2ec9a4','Keşfedilen il'],['#54d8ff','Seçili il']],region:[['#4c8dff','Marmara'],['#a77bff','Ege'],['#ff876f','Akdeniz'],['#35c9ad','Karadeniz'],['#f0b84d','İç Anadolu'],['#7b8dff','Doğu Anadolu'],['#d86f9d','Güneydoğu']],climate:[['#ef8a68','Akdeniz'],['#35c9ad','Karadeniz'],['#8c82ef','Karasal'],['#d0ad58','Geçiş']],agriculture:[['#35c7a4','Öne çıkan tarım'],['#347fb5','Tarım verisi'],['#253f59','Belirgin veri yok']],mountains:[['#8d76e8','Dağ bilgisi var'],['#27455f','Belirgin veri yok']],plains:[['#55c982','Ova bilgisi var'],['#27455f','Belirgin veri yok']],water:[['#36bce8','Göl / akarsu var'],['#27455f','Belirgin veri yok']],mining:[['#d39a4d','Maden / kaynak var'],['#27455f','Belirgin veri yok']]};return maps[atlas.mode]||maps.default}
  function renderLegend(rootId){const root=$(rootId);if(!root)return;root.innerHTML=legendForMode().map(([c,t])=>`<div class="legend-row"><i class="legend-dot" style="background:${c}"></i>${t}</div>`).join('')}
  function addLocal(NS,tag,attrs,parent){const x=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>x.setAttribute(k,v));if(parent)parent.appendChild(x);return x}
  function renderAtlas(svg){
    if(!svg)return;
    loadGeo().then(()=>{
      svg.innerHTML='';
      const NS='http://www.w3.org/2000/svg';
      const defs=addLocal(NS,'defs',{},svg);
      const grad=addLocal(NS,'linearGradient',{id:'selectedProvinceGradient',x1:'0',y1:'0',x2:'0.85',y2:'1'},defs);
      addLocal(NS,'stop',{offset:'0%','stop-color':'#78ecff'},grad);
      addLocal(NS,'stop',{offset:'55%','stop-color':'#43c6ff'},grad);
      addLocal(NS,'stop',{offset:'100%','stop-color':'#347cf4'},grad);
      atlas.paths.forEach(p=>addLocal(NS,'path',{d:p.d,class:'province-shadow',transform:'translate(-4 15)'},svg));
      atlas.paths.forEach(p=>addLocal(NS,'path',{d:p.d,class:'province-side '+p.cls,transform:'translate(0 9)'},svg));
      atlas.paths.forEach(p=>{
        const isSelected=!!(selectedProvince&&norm(selectedProvince.name)===norm(p.name));
        const isDiscovered=state.discovered.some(n=>norm(n)===norm(p.name));
        const x=addLocal(NS,'path',{d:p.d,class:'province-shape '+p.cls+(isDiscovered?' discovered':'')+(isSelected?' selected':'')},svg);
        x.dataset.province=p.name;
        x.setAttribute('focusable','false');
        x.setAttribute('role','img');
        x.setAttribute('aria-label',p.name);
        const fill=modeFill(p); if(fill)x.style.fill=isSelected?'url(#selectedProvinceGradient)':fill;
        x.addEventListener('click',()=>selectProvince(p.name));
        x.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectProvince(p.name)}});
      });
      renderLegend('#dash-legend-items');renderLegend('#full-legend-items');
      if(selectedProvince){
        const p=atlas.paths.find(x=>norm(x.name)===norm(selectedProvince.name));
        if(p){
          const lift=14;
          const lifted=addLocal(NS,'path',{d:p.d,class:'province-lifted',transform:`translate(0 -${lift})`,fill:'url(#selectedProvinceGradient)'},svg);
          lifted.dataset.province=p.name;
          lifted.setAttribute('aria-hidden','true');
          lifted.addEventListener('click',()=>selectProvince(p.name));
          const group=addLocal(NS,'g',{class:'province-label-group',transform:`translate(${p.cx} ${p.cy-lift-18})`},svg);
          const w=Math.max(96,selectedProvince.name.length*8+46);
          addLocal(NS,'rect',{x:-w/2,y:-17,width:w,height:30,rx:10,class:'province-label-bg'},group);
          const text=addLocal(NS,'text',{x:0,y:4,class:'province-label','text-anchor':'middle'},group);
          text.textContent=`${selectedProvince.name} • ${String(selectedProvince.plate||'').padStart(2,'0')}`;
        }
      }
    }).catch(e=>{
      svg.innerHTML='<text x="500" y="260" text-anchor="middle" fill="#a8bbcf" font-size="20">Harita verisi yüklenemedi.</text>';
      console.warn(e);
    });
  }
  function highlightSearch(q){const n=norm(q);$$('.province-shape').forEach(x=>{x.style.opacity=!n||norm(x.dataset.province).includes(n)?'1':'.2'})}
  function selectProvince(name){const p=province(name);if(!p)return;selectedProvince=p;state.discovered=[...new Set([...(state.discovered||[]),p.name])].filter(Boolean).slice(0,81);saveState();setProfileUI();if(currentView==='map')renderMapView();else if(currentView==='dashboard')renderDashboard();else renderProvinceModal(p);toast(`${p.name} keşfedildi.`);remoteInsert('province_progress',{user_id:user?.id,province_name:p.name,visited:true,updated_at:new Date().toISOString()})}
  function renderProvinceModal(p){const fav=state.favorites.includes(p.name+'|province');openModal(`<div class="province-modal"><div class="province-modal-head"><div class="province-emblem">${String(p.plate).padStart(2,'0')}</div><div class="province-title"><span class="kicker">${esc(p.region)} BÖLGESİ • İL ${String(p.plate).padStart(2,'0')}</span><h2>${esc(p.name)}</h2><p>${esc(p.fact||'Türkiye haritasındaki konumunu ve KPSS notlarını hızlıca öğren.')}</p></div><button class="modal-close" data-close-modal>×</button></div><div class="province-kpss"><span>🧠 KPSS HIZLI ÖZET</span><strong>${esc(p.kpss||p.fact||'Bu il için kısa KPSS özeti hazır.')}</strong></div><div class="province-facts province-facts-premium province-facts-rich"><div class="province-fact"><span>🌦️ İklim</span><b>${esc(p.climate||'Belirtilmemiş')}</b></div><div class="province-fact"><span>⛰️ Dağlar</span><b>${esc(p.mountains||p.terrain||'Belirtilmemiş')}</b></div><div class="province-fact"><span>🌾 Ovalar</span><b>${esc(p.plains||'Belirtilmemiş')}</b></div><div class="province-fact"><span>💧 Göller / Sulak Alanlar</span><b>${esc(p.lakes||'Büyük doğal göl bulunmuyor; baraj/göletler mevcut.')}</b></div><div class="province-fact"><span>🌊 Akarsular</span><b>${esc(p.rivers||'Belirgin akarsu yok')}</b></div><div class="province-fact"><span>🌾 Tarım</span><b>${esc(p.agriculture||'Belirtilmemiş')}</b></div><div class="province-fact"><span>⛏️ Maden / Kaynak</span><b>${esc(p.mining||'Belirtilmemiş')}</b></div><div class="province-fact"><span>👥 2025 Nüfusu</span><b>${esc(p.population||'Belirtilmemiş')}</b></div></div><div class="province-geography-note"><span>🗺️ COĞRAFYA NOTU</span><p>${esc(p.geographyNote||p.fact||'Bu il için başlıca coğrafi unsurlar yukarıda listelenmiştir.')}</p></div><div class="province-memory"><span>⚡ HAFIZA KODU</span><p>${esc(p.kpss||p.fact||'İli haritada seçtiğinde bu bilgiler üzerinden tekrar yapabilirsin.')}</p></div><div class="province-actions"><button class="btn ${fav?'btn-secondary':'btn-primary'}" data-fav-province="${esc(p.name)}">${fav?'★ Favoriden çıkar':'☆ Favoriye ekle'}</button><button class="btn btn-secondary" data-view="quiz" data-province-topic="${esc(p.name)}">Bu il hakkında test çöz →</button></div></div>`)}
  function renderMapView(){const el=$('#view-map');el.innerHTML=`<div class="section-head"><div><span class="kicker">81 İL • 3D ETKİLEŞİMLİ ATLAS</span><h1>Türkiye Haritası</h1><p>Altlık harita yok. İl sınırları doğrudan GeoJSON'dan SVG olarak çiziliyor.</p></div><button class="btn btn-secondary" id="reset-selection">Seçimi temizle</button></div><div class="full-map-layout"><section class="surface full-map-card"><div class="atlas-wrap full-atlas" id="full-atlas"><div class="atlas-grid"></div><div class="atlas-stars"></div><div class="map-search"><span>⌕</span><input id="map-search-full" placeholder="İl ara..."></div><div class="map-legend"><b>HARİTA LEJANTI</b><div id="full-legend-items"></div></div><div class="atlas-hint">Bir ile tıkla → detay kartı açılır.</div><svg class="atlas-svg" id="full-svg" viewBox="0 0 1000 520" preserveAspectRatio="xMidYMid meet"></svg></div></section><aside id="province-panel" class="surface province-panel ${selectedProvince?'':'empty-state'}">${selectedProvince?provincePanelHtml(selectedProvince):'<div><div style="font-size:38px">⌖</div><h2>Bir il seç</h2><p>Haritadaki herhangi bir ile tıklayarak KPSS odaklı il özetini burada görüntüleyebilirsin.</p></div>'}</aside></div>`;renderAtlas($('#full-svg'));$('#map-search-full').oninput=e=>highlightSearch(e.target.value);$('#reset-selection').onclick=()=>{selectedProvince=null;renderMapView()}}
  function provincePanelHtml(p){const fav=state.favorites.includes(p.name+'|province');return`<div class="province-panel-inner"><div class="province-panel-hero"><div class="province-emblem large">${String(p.plate).padStart(2,'0')}</div><div><span class="kicker">SEÇİLEN İL • ${esc(p.region)} BÖLGESİ</span><h2>${esc(p.name)}</h2><p>${esc(p.fact||'KPSS için il özeti')}</p></div></div><div class="province-kpss"><span>🧠 KPSS HIZLI ÖZET</span><strong>${esc(p.kpss||p.fact||'Bu il için kısa KPSS özeti hazır.')}</strong></div><div class="province-facts province-facts-premium"><div class="province-fact"><span>🌦️ İklim</span><b>${esc(p.climate||'Belirtilmemiş')}</b></div><div class="province-fact"><span>⛰️ Dağlar</span><b>${esc(p.mountains||p.terrain||'Belirtilmemiş')}</b></div><div class="province-fact"><span>🌾 Ovalar</span><b>${esc(p.plains||'Belirtilmemiş')}</b></div><div class="province-fact"><span>💧 Göller / Sulak Alanlar</span><b>${esc(p.lakes||'Büyük doğal göl bulunmuyor; baraj/göletler mevcut.')}</b></div><div class="province-fact"><span>🌊 Akarsular</span><b>${esc(p.rivers||'Belirgin akarsu yok')}</b></div><div class="province-fact"><span>🌾 Tarım</span><b>${esc(p.agriculture||'Belirtilmemiş')}</b></div><div class="province-fact"><span>⛏️ Maden / Kaynak</span><b>${esc(p.mining||'Belirtilmemiş')}</b></div><div class="province-fact"><span>👥 2025 Nüfusu</span><b>${esc(p.population||'Belirtilmemiş')}</b></div></div><div class="province-geography-note"><span>🗺️ COĞRAFYA NOTU</span><p>${esc(p.geographyNote||p.fact||'Bu il için başlıca coğrafi unsurlar yukarıda listelenmiştir.')}</p></div><div class="province-memory"><span>⚡ HAFIZA KODU</span><p>${esc(p.kpss||p.fact||'Haritada seçtiğin ili bu kart üzerinden tekrar edebilirsin.')}</p></div><div class="province-actions"><button class="btn ${fav?'btn-secondary':'btn-primary'}" data-fav-province="${esc(p.name)}">${fav?'★ Favoriden çıkar':'☆ Favoriye ekle'}</button><button class="btn btn-secondary" data-study-province="${esc(p.name)}">Bu ili çalış →</button></div></div>`}
  function renderTopics(){const el=$('#view-topics');el.innerHTML=`<div class="section-head"><div><span class="kicker">KPSS COĞRAFYA</span><h1>Konu Kütüphanesi</h1><p>Önce öğren, sonra testte uygula. İlerlemen otomatik kaydedilir.</p></div><button class="btn btn-primary" data-view="quiz">Hızlı test →</button></div><div class="topics-grid">${TOPICS.map(t=>`<article class="topic-card" data-topic="${esc(t.id)}"><div class="topic-icon">${esc(t.icon||'🧭')}</div><h3>${esc(t.title)}</h3><p>${esc(t.desc||'')}</p><div class="topic-meta"><span class="badge">${esc(t.level||'KPSS')}</span><span class="muted" style="font-size:7px">${pctFor(t.id)}%</span></div><div class="topic-progress"><i style="width:${pctFor(t.id)}%"></i></div></article>`).join('')}</div>`;$$('.topic-card').forEach(c=>c.onclick=()=>openTopic(c.dataset.topic))}
  function openTopic(id){const t=topic(id);if(!t)return;openModal(`<div class="modal-head"><div><span class="kicker">${esc(t.level||'KPSS')} • ${t.minutes||10} DK</span><h2>${esc(t.icon||'🧭')} ${esc(t.title)}</h2></div><button class="modal-close" data-close-modal>×</button></div><p>${esc(t.desc||'')}</p><h3 class="modal-section-title">Bilmen gerekenler</h3><ul>${(t.bullets||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="province-hero"><b>🧠 HAFIZA KODU / KPSS İPUCU</b><p>${esc(t.tip||'')}</p></div><div class="widget-actions"><button class="btn btn-secondary" data-study-topic="${esc(id)}">✓ Bu konuyu çalıştım</button><button class="btn btn-primary" data-quiz-topic="${esc(id)}">Bu konudan test çöz →</button></div>`)}
  function markTopic(id){state.topicPct[id]=Math.min(100,pctFor(id)+25);saveState();toast('Konu ilerlemesi kaydedildi.');closeModal();if(currentView==='topics')renderTopics();remoteInsert('profiles',{id:user?.id,display_name:state.profile.displayName,email:state.profile.email,updated_at:new Date().toISOString()})}
  function renderLibrary(){const el=$('#view-library');const q=el.dataset.q||'';const list=TOPICS.filter(t=>!q||norm(t.title).includes(norm(q))||norm(t.desc).includes(norm(q)));el.innerHTML=`<div class="section-head"><div><span class="kicker">ÇALIŞMA ALANI</span><h1>Çalışma Kütüphanesi</h1><p>Yüksek getirili konu kartlarını aç, çalıştım diye işaretle ve ilerle.</p></div><button class="btn btn-secondary" data-view="topics">Konu görünümü</button></div><div class="filter-row">${['Tümü','Yüksek Getiri','Orta','Başlangıç'].map((x,i)=>`<button class="filter-chip ${i===0?'active':''}" data-filter="${x}">${x}</button>`).join('')}</div><div class="topic-list">${list.map(t=>`<article class="study-row"><div class="row-icon">${esc(t.icon||'📚')}</div><div><h3>${esc(t.title)}</h3><p>${esc(t.desc||'')}</p></div><div class="row-actions"><button class="btn btn-secondary" data-open-topic="${esc(t.id)}">Oku</button><button class="btn btn-primary" data-quick-study="${esc(t.id)}">Çalıştım</button></div></article>`).join('')}</div>`;$$('[data-open-topic]').forEach(b=>b.onclick=()=>openTopic(b.dataset.openTopic));$$('[data-quick-study]').forEach(b=>b.onclick=()=>markTopic(b.dataset.quickStudy));$$('[data-filter]').forEach(b=>b.onclick=()=>{const f=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.study-row').forEach(r=>{const id=r.querySelector('[data-open-topic]')?.dataset.openTopic;const t=topic(id);r.style.display=(f==='Tümü'||!t||t.level===f||f==='Yüksek Getiri'&&t.level?.includes('Yüksek'))?'grid':'none'})})}
  function renderQuiz(){const el=$('#view-quiz');if(!quiz){el.innerHTML=`<div class="quiz-shell"><div class="quiz-card quiz-result"><span class="kicker">KPSS • KARIŞIK COĞRAFYA</span><div class="quiz-icon">🧠</div><h1 class="quiz-ready-title">Hazır mısın?</h1><p class="muted quiz-ready-note">5 soruluk kısa test ile bugün ne kadarını hatırladığını gör.</p><div class="widget-actions" style="max-width:420px;margin:20px auto"><button class="btn btn-primary" id="start-quiz">Teste Başla →</button><button class="btn btn-secondary" id="start-daily">Günün Challenge'ı</button></div></div></div>`;$('#start-quiz').onclick=()=>startQuiz();$('#start-daily').onclick=()=>startChallenge();return}renderQuizQuestion()}
  function startQuiz(topicId=null){let bank=QUESTIONS.filter(q=>!topicId||q.topic===topicId);if(bank.length<5)bank=QUESTIONS.slice();bank=bank.slice().sort(()=>Math.random()-.5).slice(0,5);quiz={topicId,questions:bank,index:0,correct:0,answered:false};renderQuiz()}
  function startChallenge(){startQuiz();toast('Günün 5 soruluk challenge başladı.');}
  function renderQuizQuestion(){const q=quiz.questions[quiz.index],el=$('#view-quiz');const progress=Math.round((quiz.index/quiz.questions.length)*100);el.innerHTML=`<div class="quiz-shell"><div class="quiz-card"><div class="quiz-top"><span>5 SORU • ${quiz.topicId?esc(topic(quiz.topicId)?.title||'KONU'): 'KARIŞIK COĞRAFYA'}</span><b>${quiz.index+1} / ${quiz.questions.length}</b></div><div class="quiz-progress"><i style="width:${progress}%"></i></div><h2 class="question">${esc(q.q)}</h2><div class="answers">${q.options.map((a,i)=>`<button class="answer" data-answer="${i}">${esc(a)}</button>`).join('')}</div><div id="quiz-explain"></div><div class="quiz-actions"><button class="btn btn-secondary" data-view="dashboard">Çık</button></div></div></div>`;$$('.answer').forEach(b=>b.onclick=()=>answerQuestion(Number(b.dataset.answer)));}
  function answerQuestion(i){if(!quiz||quiz.answered)return;quiz.answered=true;const q=quiz.questions[quiz.index],correctAnswer=Number(q.answer);$$('.answer').forEach((b,n)=>{if(n===correctAnswer)b.classList.add('correct');if(n===i&&i!==correctAnswer)b.classList.add('wrong')});if(i===correctAnswer)quiz.correct++;$('#quiz-explain').innerHTML=`<div class="quiz-explain"><b>${i===correctAnswer?'Doğru!':'Yanlış.'}</b> ${esc(q.explain||'Cevap açıklaması mevcut değil.')}</div><div class="quiz-actions"><button class="btn btn-primary" id="next-question">${quiz.index===quiz.questions.length-1?'Sonucu gör':'Sonraki soru →'}</button></div>`;$('#next-question').onclick=nextQuestion}
  async function nextQuestion(){if(!quiz)return;if(quiz.index===quiz.questions.length-1){const result={topic_id:quiz.topicId||'mixed',correct:quiz.correct,total:quiz.questions.length,score:Math.round(quiz.correct/quiz.questions.length*100),created_at:new Date().toISOString()};state.results.unshift(result);state.results=state.results.slice(0,50);saveState();await remoteInsert('quiz_results',{user_id:user?.id,...result});const sc=result.score;quiz=null;renderQuizResult(sc,result.correct,result.total);return}quiz.index++;quiz.answered=false;renderQuizQuestion()}
  function renderQuizResult(sc,c,t){$('#view-quiz').innerHTML=`<div class="quiz-shell"><div class="quiz-card quiz-result"><span class="kicker">TEST TAMAMLANDI</span><div class="quiz-score">%${sc}</div><h2 class="result-title">${c} / ${t} doğru</h2><p class="muted result-note">Sonucun kaydedildi. Bir sonraki testte daha iyisini hedefle.</p><div class="widget-actions" style="max-width:420px;margin:20px auto"><button class="btn btn-primary" id="again">Tekrar çöz</button><button class="btn btn-secondary" data-view="stats">İstatistiklere git</button></div></div></div>`;$('#again').onclick=()=>startQuiz()}
  function renderStats(){const el=$('#view-stats');const bars=state.results.slice(0,10).reverse();el.innerHTML=`<div class="section-head"><div><span class="kicker">İLERLEME</span><h1>İstatistikler</h1><p>Çalışma ritmini ve test performansını burada takip et.</p></div></div><div class="stats-grid"><div class="stat-big"><span>Keşfedilen İl</span><b>${discoveredCount()} / 81</b></div><div class="stat-big"><span>Çözülen Soru</span><b>${solved()}</b></div><div class="stat-big"><span>Doğru</span><b>${correct()}</b></div><div class="stat-big"><span>Başarı</span><b>%${score()}</b></div></div><section class="surface chart-card"><h3 style="font-size:12px;margin:0">Son test sonuçları</h3><div class="bar-chart">${bars.length?bars.map((r,i)=>`<div class="bar" style="height:${Math.max(10,Number(r.score)||0)}%"><small>%${Number(r.score)||0}</small></div>`).join(''):'<div class="empty" style="width:100%"><b>Henüz test sonucu yok</b>Bir test çözünce performans grafiğin burada oluşacak.</div>'}</div></section><section class="surface chart-card"><h3 style="font-size:12px;margin:0 0 12px">Konu ilerlemesi</h3>${TOPICS.map(t=>`<div style="display:grid;grid-template-columns:150px 1fr 35px;gap:8px;align-items:center;margin:9px 0"><span style="font-size:8px">${esc(t.title)}</span><div class="progress-line" style="margin:0"><i style="width:${pctFor(t.id)}%"></i></div><b style="font-size:8px;text-align:right">${pctFor(t.id)}%</b></div>`).join('')}</section>`}
  function isFav(item,type='province'){return state.favorites.includes(item+'|'+type)}
  async function toggleFav(item,type='province'){const key=item+'|'+type;if(isFav(item,type))state.favorites=state.favorites.filter(x=>x!==key);else state.favorites.push(key);saveState();if(user){if(isFav(item,type))await remoteInsert('favorites',{user_id:user.id,item_id:item,item_type:type});else try{await sb.from('favorites').delete().eq('user_id',user.id).eq('item_id',item).eq('item_type',type)}catch(e){console.warn(e)}}toast(isFav(item,type)?'Favorilere eklendi.':'Favorilerden çıkarıldı.');if(currentView==='favorites')renderFavorites();if(currentView==='map')renderMapView()}
  function renderFavorites(){const el=$('#view-favorites');const items=state.favorites.map(x=>{const [id,type]=x.split('|');return{item:id,type}});el.innerHTML=`<div class="section-head"><div><span class="kicker">KAYDEDİLENLER</span><h1>Favoriler</h1><p>Tekrar bakmak istediğin il ve konuları burada tut.</p></div></div>${items.length?`<div class="favorite-grid">${items.map(x=>x.type==='province'?favProvince(x.item):favTopic(x.item)).join('')}</div>`:'<div class="empty"><b>Henüz favorin yok.</b>Haritada bir il seçip yıldızla favorine ekleyebilirsin.<br><button class="btn btn-primary" data-view="map">Haritaya git →</button></div>'}`;$$('[data-remove-fav]').forEach(b=>b.onclick=()=>toggleFav(b.dataset.removeFav,b.dataset.type))}
  function favProvince(n){const p=province(n);return`<article class="favorite-card"><span class="badge">İL • ${p?.region||''}</span><h3>📍 ${esc(n)}</h3><p>${esc(p?.fact||p?.kpss||'')}</p><button class="btn btn-secondary" style="margin-top:10px;width:100%" data-remove-fav="${esc(n)}" data-type="province">★ Favoriden çıkar</button></article>`}
  function favTopic(id){const t=topic(id);return`<article class="favorite-card"><span class="badge">KONU</span><h3>${esc(t?.icon||'📚')} ${esc(t?.title||id)}</h3><p>${esc(t?.desc||'')}</p><button class="btn btn-secondary" style="margin-top:10px;width:100%" data-remove-fav="${esc(id)}" data-type="topic">★ Favoriden çıkar</button></article>`}
  function renderSettings(){const el=$('#view-settings');el.innerHTML=`<div class="section-head"><div><span class="kicker">HESAP</span><h1>Ayarlar & Profil</h1><p>Profilini, tema tercihini ve yerel çalışma verilerini yönet.</p></div></div><div class="settings-grid"><section class="surface settings-card"><h3>Profil</h3><div class="setting-row"><span>Ad Soyad</span><input id="settings-name" class="setting-input" value="${esc(state.profile.displayName||'')}" /></div><div class="setting-row"><span>E-posta</span><b>${esc(state.profile.email||user?.email||'Misafir')}</b></div><button class="btn btn-primary full" id="save-profile">Profili kaydet</button></section><section class="surface settings-card"><h3>Görünüm</h3><div class="setting-row"><span>Tema</span><button class="btn btn-secondary" id="settings-theme">${state.theme==='light'?'Açık':'Koyu'} tema</button></div><div class="setting-row"><span>Uygulama sürümü</span><b>v${esc(CFG.APP_VERSION||'21.3.0')}</b></div></section><section class="surface settings-card"><h3>Veri</h3><div class="setting-row"><span>Yerel ilerleme</span><b>${discoveredCount()} il • ${solved()} soru</b></div><button class="btn btn-secondary full" id="export-data">Verilerimi dışa aktar</button><button class="btn full" style="margin-top:7px;color:#ff9aa4;border-color:rgba(255,115,130,.25)" id="reset-data">Yerel verileri sıfırla</button></section><section class="surface settings-card"><h3>KPSS Sayacı</h3><div class="setting-row"><span>Sınav</span><b id="exam-countdown">Hesaplanıyor…</b></div><p class="muted" style="font-size:8px;line-height:1.6">Hedef tarihi config.js içindeki EXAM_DATE değerinden alınır.</p></section></div>`;$('#save-profile').onclick=()=>{const n=$('#settings-name').value.trim()||'Öğrenci';state.profile.displayName=n;saveState();setProfileUI();toast('Profil kaydedildi.');remoteInsert('profiles',{id:user?.id,display_name:n,email:state.profile.email||user?.email||'',updated_at:new Date().toISOString()})};$('#settings-theme').onclick=toggleTheme;$('#export-data').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='yurdunu-bil-veriler.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};$('#reset-data').onclick=()=>{if(confirm('Bu cihazdaki yerel ilerleme, favoriler ve test sonuçları silinsin mi?')){state=clone(DEFAULT);saveState();selectedProvince=null;quiz=null;toast('Yerel veriler sıfırlandı.');renderSettings();setProfileUI()}};updateCountdown()}
  function updateCountdown(){const el=$('#exam-countdown');if(!el)return;const d=new Date(CFG.EXAM_DATE||'2026-10-04T10:15:00+03:00');const diff=d-new Date();if(diff<=0){el.textContent='Sınav günü geldi';return}const days=Math.floor(diff/864e5),hours=Math.floor(diff/36e5)%24;el.textContent=`${days} gün ${hours} saat`}
  function updateDashboardCountdown(){const el=$('#dashboard-countdown');if(!el)return;const d=new Date(CFG.EXAM_DATE||'2026-10-04T10:15:00+03:00');const diff=d-new Date();if(diff<=0){el.textContent='Sınav günü';return}const days=Math.floor(diff/864e5),hours=Math.floor(diff/36e5)%24;el.textContent=`${days}g ${hours}s`}
  function globalSearch(q){const n=norm(q);if(!n){return}const p=DATA.find(x=>norm(x.name).includes(n));const t=TOPICS.find(x=>norm(x.title).includes(n));if(p){navigate('map');setTimeout(()=>selectProvince(p.name),60);return}if(t){navigate('topics');setTimeout(()=>openTopic(t.id),60);return}const qx=QUESTIONS.find(x=>norm(x.q).includes(n));if(qx){navigate('quiz');startQuiz(qx.topic);return}}
  function openModal(html){const root=$('#modal-root');root.innerHTML=`<div class="modal-backdrop"><div class="modal">${html}</div></div>`;root.querySelector('[data-close-modal]')?.addEventListener('click',closeModal);root.querySelector('.modal-backdrop').addEventListener('click',e=>{if(e.target.classList.contains('modal-backdrop'))closeModal()});root.querySelector('[data-fav-province]')?.addEventListener('click',e=>toggleFav(e.currentTarget.dataset.favProvince,'province'));root.querySelector('[data-study-topic]')?.addEventListener('click',e=>markTopic(e.currentTarget.dataset.studyTopic));root.querySelector('[data-quiz-topic]')?.addEventListener('click',e=>{const id=e.currentTarget.dataset.quizTopic;closeModal();navigate('quiz');startQuiz(id)});root.querySelector('[data-view]')?.addEventListener('click',e=>{const p=e.currentTarget.dataset.provinceTopic;closeModal();navigate('quiz');startQuiz()})}
  function closeModal(){$('#modal-root').innerHTML=''}
  function toggleTimer(){if(pomodoro.running){clearInterval(pomodoro.timer);pomodoro.running=false}else{pomodoro.running=true;pomodoro.timer=setInterval(()=>{pomodoro.seconds--;if(pomodoro.seconds<=0){clearInterval(pomodoro.timer);pomodoro.running=false;toast('Odak oturumu tamamlandı!');pomodoro.seconds=pomodoro.total}updateTimerUI()},1000)}updateTimerUI()}
  function resetTimer(){clearInterval(pomodoro.timer);pomodoro.running=false;pomodoro.seconds=pomodoro.total;updateTimerUI()}
  function updateTimerUI(){const s=pomodoro.seconds,m=Math.floor(s/60),sec=s%60;setText('#dash-timer',`${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`);const b=$('#timer-start');if(b)b.textContent=pomodoro.running?'Ⅱ Duraklat':'▶ Başlat'}
  function setupGlobalDelegates(){document.addEventListener('click',e=>{const fav=e.target.closest('[data-fav-province]');if(fav&&!$('#modal-root .modal'))toggleFav(fav.dataset.favProvince,'province');const study=e.target.closest('[data-study-province]');if(study){const p=province(study.dataset.studyProvince);if(p){closeModal();navigate('map');selectedProvince=p;renderMapView()}}})}
  function init(){setupAuth();setupNavigation();setupGlobalDelegates();document.body.classList.toggle('light',state.theme==='light');bootAuth();}
  init();
})();
