/* Yurdunu Bil Arena v1 — realtime 1v1 multiplayer */
(()=>{'use strict';
if(window.__YB_ARENA_V1__)return;window.__YB_ARENA_V1__=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const CFG=window.YURDUNUBIL_CONFIG||{};let sb=null,user=null,match=null,me=null,opponent=null,channel=null,questions=[],questionStarted=0,timer=null,answered=false,poll=null;
try{if(CFG.SUPABASE_URL&&CFG.SUPABASE_PUBLISHABLE_KEY&&window.supabase)sb=window.supabase.createClient(CFG.SUPABASE_URL,CFG.SUPABASE_PUBLISHABLE_KEY)}catch(e){console.warn(e)}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const name=()=>{const n=window.YURDUNUBIL_STATE?.profile?.displayName||localStorage.getItem('yb_arena_name')||'Oyuncu';return String(n).trim()||'Oyuncu'};
const toast=t=>{const root=$('#toast-root');if(!root)return;const e=document.createElement('div');e.className='toast ok';e.textContent=t;root.appendChild(e);requestAnimationFrame(()=>e.classList.add('show'));setTimeout(()=>{e.classList.remove('show');setTimeout(()=>e.remove(),220)},2200)};
function getPool(){const raw=Array.isArray(window.QUESTION_BANK)?window.QUESTION_BANK:[];return raw.map((x,i)=>({id:String(x.id||i),q:x.q||x.question||'',opts:Array.isArray(x.options)?x.options:[],a:Number.isInteger(x.answer)?x.answer:0,ex:x.explain||'',topic:x.topic||'genel'})).filter(x=>x.q&&x.opts.length>=2&&x.a>=0&&x.a<x.opts.length)}
function seedRand(seed){let h=2166136261;for(const c of String(seed)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return()=>{h+=0x6D2B79F5;let t=h;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function buildQuestions(){const p=getPool(),r=seedRand(match?.id||'arena'),a=[...p];for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a.slice(0,Math.min(match?.question_count||10,20)).map(x=>{const opts=x.opts.map((v,i)=>({v,i}));for(let i=opts.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[opts[i],opts[j]]=[opts[j],opts[i]]}return {...x,displayOpts:opts}})}
async function auth(){if(!sb){toast('Arena sunucusu hazır değil.','error');return null}const r=await sb.auth.getSession();user=r.data?.session?.user||null;if(!user){toast('Arena için giriş yapmalısın.','error');return null}return user}
function goEvents(){try{if(typeof window.navigate==='function')window.navigate('events')}catch{}}
function view(){return $('#view-events')}
function profileRow(players,uid){return players.find(p=>p.user_id===uid)||players.find(p=>p.id===uid)||null}
async function loadMatchPlayers(){if(!match)return;const r=await sb.from('arena_players').select('*').eq('match_id',match.id).order('joined_at',{ascending:true});const ps=r.data||[];me=profileRow(ps,user.id);opponent=ps.find(p=>p.user_id!==user.id)||null}
function cleanup(){if(timer){clearInterval(timer);timer=null}if(poll){clearInterval(poll);poll=null}if(channel){sb?.removeChannel(channel);channel=null}}
function shell(content){const v=view();if(!v)return;v.innerHTML='<div class="ybArena">'+content+'</div>'}
async function hub(){cleanup();match=null;me=null;opponent=null;await loadRating();shell(`<section class="ybArenaHero"><span class="ybArenaKicker">YURDUNU BİL • ARENA</span><h1>Bilgini rakibine karşı kanıtla.</h1><p>Gerçek zamanlı 1 VS 1. Aynı sorular, aynı tur, canlı skor ve reyting.</p><div class="ybArenaStats"><div><b>1 VS 1</b><small>Canlı düello</small></div><div><b>+25</b><small>Galibiyet reytingi</small></div><div><b>10</b><small>Tur</small></div><div><b>⚡</b><small>Hız bonusu</small></div></div></section><section class="ybArenaGrid"><article class="ybArenaCard featured"><div class="ybArenaIcon">⚔️</div><span class="ybArenaTag">EN HIZLI</span><h3>Rakip Bul</h3><p>Bekleyen bir oyuncuya otomatik eşleş. 1–2 saniyede tekrar dene.</p><button class="btn primary" data-arena-action="matchmake">Rakip Bul →</button></article><article class="ybArenaCard"><div class="ybArenaIcon">🔐</div><h3>Oda Oluştur</h3><p>Arkadaşınla aynı kodu paylaş. Özel 1 VS 1 odanı kur.</p><div class="ybArenaModes"><button data-arena-mode="duel" class="active">Klasik</button><button data-arena-mode="speed">Hız</button><button data-arena-mode="chain">Bilgi Zinciri</button></div><button class="btn secondary" data-arena-action="create">Oda Kodu Oluştur</button></article><article class="ybArenaCard"><div class="ybArenaIcon">🎟️</div><h3>Koda Katıl</h3><p>Arkadaşının verdiği 6 haneli Arena kodunu gir.</p><div class="ybArenaJoin"><input id="ybArenaCode" maxlength="6" inputmode="text" placeholder="ABC123"><button class="btn secondary" data-arena-action="join">Katıl</button></div></article></section><section class="ybArenaBoard"><div><span class="ybArenaKicker">LİGLER</span><h2>Reyting merdiveni</h2><p>1000 başlangıç puanı. Galibiyet +25, mağlubiyet −18, beraberlik +5.</p></div><div class="ybArenaLeague" id="ybArenaLeague">Yükleniyor…</div></section>`);$$('.ybArenaModes button').forEach(b=>b.onclick=()=>{$$('.ybArenaModes button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});$$('[data-arena-action]',view()).forEach(b=>b.onclick=()=>arenaAction(b.dataset.arenaAction))}
async function loadRating(){if(!sb)return;user=user||await auth();if(!user)return;await sb.from('arena_ratings').upsert({user_id:user.id},{onConflict:'user_id'});const r=await sb.from('arena_ratings').select('*').eq('user_id',user.id).maybeSingle();const d=r.data||{rating:1000,wins:0,losses:0,draws:0,matches:0,best_streak:0};const league=d.rating>=1500?'Elit':d.rating>=1300?'Usta':d.rating>=1150?'Uzman':d.rating>=1000?'Yükselen':'Çaylak';const e=$('#ybArenaLeague');if(e)e.innerHTML=`<strong>${league}</strong><span>${d.rating} RP</span><small>🏆 ${d.wins} G • ${d.losses} M • 🔥 ${d.best_streak} seri</small>`}
async function arenaAction(action){user=await auth();if(!user)return;const mode=$('.ybArenaModes button.active')?.dataset.arenaMode||'duel';if(action==='matchmake')await matchmake(mode);if(action==='create')await create(mode);if(action==='join')await join($('#ybArenaCode')?.value||'')}
async function create(mode){const r=await sb.rpc('arena_create_match',{p_mode:mode,p_topic:null,p_question_count:10});if(r.error){toast(r.error.message,'error');return}match=r.data;await loadMatchPlayers();showWaitingMatch();subscribe()}
async function join(code){code=String(code).trim().toUpperCase();if(code.length<4){toast('6 haneli Arena kodunu gir.','error');return}const r=await sb.rpc('arena_join_match',{p_code:code});if(r.error){toast(r.error.message==='match_not_found'?'Oda bulunamadı.':r.error.message,'error');return}match=r.data;await loadMatchPlayers();if(match.status==='active')renderArenaGame();else showWaitingMatch();subscribe()}
async function matchmake(mode){shell(`<section class="ybArenaWait"><div class="ybArenaPulse">⚔️</div><span class="ybArenaKicker">EŞLEŞME ARANIYOR</span><h1>Rakip aranıyor…</h1><p>Reytingine yakın bir oyuncu bulununca otomatik başlayacak.</p><div class="ybArenaSearchLine"><i></i><i></i><i></i></div><button class="btn ghost" data-arena-cancel>Vazgeç</button></section>`);$('[data-arena-cancel]')?.addEventListener('click',()=>{cleanup();hub()});let tries=0;const attempt=async()=>{tries++;const q=await sb.from('arena_matches').select('*').eq('mode',mode).eq('status','waiting').neq('created_by',user.id).order('created_at',{ascending:true}).limit(1);const candidate=q.data?.[0];if(candidate){const j=await sb.rpc('arena_join_match',{p_code:candidate.code});if(!j.error){match=j.data;await loadMatchPlayers();renderArenaGame();subscribe();return}}if(tries===1){const c=await sb.rpc('arena_create_match',{p_mode:mode,p_topic:null,p_question_count:10});if(c.error){toast(c.error.message,'error');hub();return}match=c.data;await loadMatchPlayers();showWaitingMatch();subscribe()}};await attempt()}
function showWaitingMatch(){shell(`<section class="ybArenaWait"><div class="ybArenaPulse">🛡️</div><span class="ybArenaKicker">ODA HAZIR</span><h1>Rakibini bekliyoruz.</h1><p>Bu kodu arkadaşına gönder veya eşleşmenin tamamlanmasını bekle.</p><div class="ybArenaCode">${esc(match.code)}</div><button class="btn primary" data-arena-copy>📋 Kodu Kopyala</button><button class="btn ghost" data-arena-cancel>İptal</button><div class="ybArenaHint">Oyuncu geldiğinde oyun otomatik başlar.</div></section>`);$('[data-arena-copy]')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(match.code);toast('Arena kodu kopyalandı.')}catch{toast(match.code)}});$('[data-arena-cancel]')?.addEventListener('click',()=>{cleanup();hub()})}
function subscribe(){if(channel)sb.removeChannel(channel);channel=sb.channel('yb-arena-'+match.id).on('postgres_changes',{event:'UPDATE',schema:'public',table:'arena_matches',filter:'id=eq.'+match.id},p=>onMatch(p.new)).on('postgres_changes',{event:'INSERT',schema:'public',table:'arena_players',filter:'match_id=eq.'+match.id},async()=>{await loadMatchPlayers();if(match?.status==='waiting'&&opponent)showWaitingMatch()}).subscribe();poll=setInterval(async()=>{const r=await sb.from('arena_matches').select('*').eq('id',match.id).maybeSingle();if(r.data)onMatch(r.data)},1500)}
function onMatch(m){match=m;if(m.status==='waiting'){if(opponent&&!$('.ybArenaQuestion',view())){renderArenaGame()}return}if(m.status==='active'){loadMatchPlayers().then(()=>{if(!view()?.querySelector('.ybArenaQuestion'))renderArenaGame();else updateScore()})}if(m.status==='finished')finishScreen()}
function updateScore(){const a=$('#ybArenaMeScore'),b=$('#ybArenaOppScore');if(a)a.textContent=String(me?.score||0);if(b)b.textContent=String(opponent?.score||0);const qn=$('#ybArenaQNum');if(qn)qn.textContent=`Tur ${Math.min(match.current_question+1,match.question_count)} / ${match.question_count}`}
function renderArenaGame(){questions=buildQuestions();answered=false;questionStarted=Date.now();const item=questions[Math.min(match.current_question,questions.length-1)]||questions[0];if(!item)return;const my=me||{},op=opponent||{};shell(`<section class="ybArenaTop"><div><span class="ybArenaKicker">${match.mode==='speed'?'HIZ ARENASI':match.mode==='chain'?'BİLGİ ZİNCİRİ':'KLASİK DÜELLO'}</span><h1>Canlı Düello</h1></div><div class="ybArenaRound" id="ybArenaQNum">Tur ${match.current_question+1} / ${match.question_count}</div></section><section class="ybArenaScore"><div class="ybArenaPlayer me"><span>🧑‍💻</span><div><b>${esc(my.display_name||name())}</b><small>Sen • <strong id="ybArenaMeScore">${my.score||0}</strong> puan</small></div></div><div class="ybArenaVS">VS</div><div class="ybArenaPlayer"><span>⚔️</span><div><b>${esc(op.display_name||'Rakip')}</b><small>Rakip • <strong id="ybArenaOppScore">${op.score||0}</strong> puan</small></div></div></section><section class="ybArenaQuestion"><div class="ybArenaQuestionMeta"><span>⏱ ${match.mode==='speed'?'15':'25'} sn</span><span>${esc(item.topic||'Genel')}</span></div><h2>${esc(item.q)}</h2><div class="ybArenaOptions">${item.displayOpts.map((o,i)=>`<button data-arena-answer="${o.i}"><b>${String.fromCharCode(65+i)}</b><span>${esc(o.v)}</span></button>`).join('')}</div><div class="ybArenaLive" id="ybArenaLive">Rakibin cevabı bekleniyor…</div></section>`);updateScore();startTimer(match.mode==='speed'?15:25,item)}
function startTimer(seconds,item){if(timer)clearInterval(timer);let left=seconds;const e=$('.ybArenaQuestionMeta span');if(e)e.textContent='⏱ '+left+' sn';timer=setInterval(()=>{left--;if(e)e.textContent='⏱ '+left+' sn';if(left<=0){clearInterval(timer);timer=null;if(!answered)submit(item,-1,false,seconds*1000)}},1000);$$('[data-arena-answer]').forEach(b=>b.onclick=()=>{if(answered)return;const idx=Number(b.dataset.arenaAnswer);submit(item,idx,idx===item.a,Date.now()-questionStarted)})}
async function submit(item,answerIndex,ok,responseMs){if(answered)return;answered=true;if(timer){clearInterval(timer);timer=null}$$('[data-arena-answer]').forEach(b=>b.disabled=true);const points=ok?100+(match.mode==='speed'?Math.max(0,Math.round((12000-Math.min(responseMs,12000))/500)):0):0;const playerId=me?.id;if(!playerId){toast('Oyuncu kaydı bulunamadı.','error');return}const r=await sb.rpc('arena_submit_answer',{p_match_id:match.id,p_player_id:playerId,p_question_index:match.current_question,p_answer_index:answerIndex,p_is_correct:ok,p_response_ms:responseMs,p_points:points});if(r.error){toast(r.error.message,'error');return}match=r.data;await loadMatchPlayers();const live=$('#ybArenaLive');if(live)live.textContent=ok?'✓ Doğru! Rakibin hamlesi bekleniyor…':'✕ Yanlış. Rakibin hamlesi bekleniyor…';if(match.status==='finished')finishScreen()}
async function finishScreen(){cleanup();await loadMatchPlayers();const myScore=me?.score||0,opScore=opponent?.score||0;let result='Berabere',emoji='🤝';if(myScore>opScore){result='Zafer!';emoji='🏆'}else if(myScore<opScore){result='Bu tur rakibin.';emoji='⚔️'}let rating=null;if(sb&&user){const r=await sb.from('arena_ratings').select('*').eq('user_id',user.id).maybeSingle();rating=r.data}const mode=match?.mode||'duel';shell(`<section class="ybArenaResult"><div class="ybArenaResultEmoji">${emoji}</div><span class="ybArenaKicker">ARENA SONUCU</span><h1>${result}</h1><div class="ybArenaFinal"><div><small>${esc(me?.display_name||name())}</small><b>${myScore}</b></div><strong>—</strong><div><small>${esc(opponent?.display_name||'Rakip')}</small><b>${opScore}</b></div></div><div class="ybArenaReward"><span>🏅 ${rating?.rating||1000} RP</span><span>🔥 ${rating?.best_streak||0} en iyi seri</span></div><div class="ybArenaResultActions"><button class="btn primary" data-arena-rematch>Tekrar Oyna</button><button class="btn secondary" data-arena-home>Arena Ana Sayfa</button></div></section>`);$('[data-arena-home]')?.addEventListener('click',hub);$('[data-arena-rematch]')?.addEventListener('click',()=>matchmake(mode))}
window.YBArena={open:async()=>{goEvents();setTimeout(async()=>{user=await auth();if(user)hub()},0)},hub};
})();
