/* Yurdunu Bil 21.7.1 — atlas category/legend hotfix */
(()=>{
'use strict';
const norm=v=>String(v||'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c').trim();
const DATA=window.PROVINCE_DATA||[]; const get=n=>DATA.find(p=>norm(p.name)===norm(n))||null; const has=v=>!!v&&v!=='—'&&v!=='Belirtilmemiş';
const colors={region:{marmara:'#4c8dff',ege:'#a77bff',akdeniz:'#ff876f',karadeniz:'#35c9ad',ic:'#f0b84d',dogu:'#7b8dff',guney:'#d86f9d'},climate:{akdeniz:'#ef8a68',karadeniz:'#35c9ad',karasal:'#8c82ef',gecis:'#d0ad58'},agriculture:{strong:'#35c7a4',data:'#347fb5',none:'#253f59'},mountains:{yes:'#8d76e8',no:'#27455f'},plains:{yes:'#55c982',no:'#27455f'},water:{yes:'#36bce8',no:'#27455f'},mining:{yes:'#d39a4d',no:'#27455f'}};
let mode='default';
function modeFill(name){const d=get(name);if(!d)return'#2b73ad';if(mode==='region'){const r=norm(d.region);if(r.includes('marmara'))return colors.region.marmara;if(r.includes('ege'))return colors.region.ege;if(r.includes('akdeniz'))return colors.region.akdeniz;if(r.includes('karadeniz'))return colors.region.karadeniz;if(r.includes('dogu'))return colors.region.dogu;if(r.includes('guney'))return colors.region.guney;return colors.region.ic}if(mode==='climate'){const s=norm(d.climate);if(s.includes('akdeniz'))return colors.climate.akdeniz;if(s.includes('karadeniz'))return colors.climate.karadeniz;if(s.includes('karasal'))return colors.climate.karasal;if(s.includes('gecis'))return colors.climate.gecis;return'#4f82c6'}if(mode==='agriculture'){const s=norm(d.agriculture);return /cay|findik|zeytin|pamuk|uzum|kayisi|narenciye|misir|bugday|arpa|seker/.test(s)?colors.agriculture.strong:(has(d.agriculture)?colors.agriculture.data:colors.agriculture.none)}if(mode==='mountains')return has(d.mountains)?colors.mountains.yes:colors.mountains.no;if(mode==='plains')return has(d.plains)?colors.plains.yes:colors.plains.no;if(mode==='water')return has(d.lakes)||has(d.rivers)?colors.water.yes:colors.water.no;if(mode==='mining')return has(d.mining)?colors.mining.yes:colors.mining.no;return null}
function legend(){const maps={default:[['#2ec9a4','Keşfedilen il'],['#54d8ff','Seçili il']],region:[['#4c8dff','Marmara'],['#a77bff','Ege'],['#ff876f','Akdeniz'],['#35c9ad','Karadeniz'],['#f0b84d','İç Anadolu'],['#7b8dff','Doğu Anadolu'],['#d86f9d','Güneydoğu Anadolu']],climate:[['#ef8a68','Akdeniz'],['#35c9ad','Karadeniz'],['#8c82ef','Karasal'],['#d0ad58','Geçiş']],agriculture:[['#35c7a4','Öne çıkan tarım'],['#347fb5','Tarım verisi'],['#253f59','Belirgin veri yok']],mountains:[['#8d76e8','Dağ bilgisi var'],['#27455f','Belirgin veri yok']],plains:[['#55c982','Ova bilgisi var'],['#27455f','Belirgin veri yok']],water:[['#36bce8','Göl / akarsu var'],['#27455f','Belirgin veri yok']],mining:[['#d39a4d','Maden / kaynak var'],['#27455f','Belirgin veri yok']]};return maps[mode]||maps.default}
function apply(){document.querySelectorAll('.atlas-svg .province-shape').forEach(x=>{const d=modeFill(x.dataset.province);if(d)x.style.fill=d;if(x.classList.contains('selected'))x.style.fill='url(#selectedProvinceGradient)'});document.querySelectorAll('.map-legend').forEach(box=>{let root=box.querySelector('[data-hotfix-legend]');if(!root){root=document.createElement('div');root.dataset.hotfixLegend='1';box.innerHTML='<b>HARİTA LEJANTI</b>';box.appendChild(root)}root.innerHTML=legend().map(([c,t])=>`<div class="legend-row"><i class="legend-dot" style="background:${c}"></i>${t}</div>`).join('')})}
function injectTabs(){document.querySelectorAll('.map-tabs').forEach(w=>{if(w.dataset.hotfix==='1')return;w.dataset.hotfix='1';w.innerHTML='';[['default','Standart'],['region','Bölgeler'],['climate','İklim'],['agriculture','Tarım'],['mountains','Dağlar'],['plains','Ovalar'],['water','Su'],['mining','Maden']].forEach(([m,t],i)=>{const b=document.createElement('button');b.className='map-tab'+(i===0?' active':'');b.dataset.hotfixMode=m;b.textContent=t;b.onclick=()=>{mode=m;w.querySelectorAll('.map-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');setTimeout(apply,40)};w.appendChild(b)})})}
function boot(){injectTabs();apply();const root=document.querySelector('#view-dashboard');if(root)new MutationObserver(()=>{injectTabs();setTimeout(apply,20)}).observe(root,{childList:true,subtree:true});document.addEventListener('click',e=>{if(e.target.closest('.map-tab'))setTimeout(apply,50)});setInterval(()=>{if(document.querySelector('.atlas-svg')){injectTabs();apply()}},1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
