/* Yurdunu Bil 27 — interactive atlas + live data controls */
(() => {
  'use strict';
  const ROOTS=['dash-svg','map-svg'], maps=new WeakMap();
  let liveIndex=0;
  const LIVE=[
    {icon:'👥',label:'Türkiye nüfusu',value:'86.092.168',note:'TÜİK ADNKS 2025 • 31 Aralık 2025'},
    {icon:'🏙️',label:'En kalabalık il',value:'İstanbul',note:'2025 nüfus verisi'},
    {icon:'👤',label:'En az nüfuslu il',value:'Bayburt',note:'2025 nüfus verisi'},
    {icon:'📐',label:'En büyük yüz ölçümü',value:'Konya',note:'40.838 km²'},
    {icon:'◻️',label:'En küçük yüz ölçümü',value:'Yalova',note:'798 km²'},
    {icon:'🌾',label:'Öne çıkan tarım',value:'Fındık',note:'Doğu Karadeniz kıyı kuşağında öne çıkar'}
  ];
  const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
  const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>[...r.querySelectorAll(s)];
  function mapState(svg){let s=maps.get(svg);if(!s){s={x:0,y:0,zoom:1,pointer:false,startX:0,startY:0,baseX:0,baseY:0,moved:false,suppress:false};maps.set(svg,s)}return s}
  function applyMap(svg){const s=mapState(svg);svg.style.transform=`translate3d(${s.x}px,${s.y}px,0) scale(${s.zoom})`;svg.classList.toggle('atlas-panning',s.pointer);const n=svg.closest('.atlas-shell')?.querySelector('.atlas-reset-note');if(n)n.textContent=`${Math.round(s.zoom*100)}%`}
  function resetMap(svg){const s=mapState(svg);s.x=0;s.y=0;s.zoom=1;s.pointer=false;s.moved=false;applyMap(svg)}
  function pan(svg,dx,dy){const s=mapState(svg);s.x=clamp(s.x+dx,-300,300);s.y=clamp(s.y+dy,-180,180);applyMap(svg)}
  function zoom(svg,d){const s=mapState(svg);s.zoom=clamp(s.zoom+d,.75,2.4);applyMap(svg)}
  function addMapControls(svg){const shell=svg.closest('.atlas-shell');if(!shell||shell.querySelector('.atlas-nav'))return;const n=document.createElement('div');n.className='atlas-nav';n.innerHTML='<button type="button" data-map-left aria-label="Sola kaydır">‹</button><button type="button" data-map-zoom-out aria-label="Uzaklaştır">−</button><button type="button" class="atlas-reset" data-map-reset aria-label="Sıfırla">⌂</button><button type="button" data-map-zoom-in aria-label="Yakınlaştır">+</button><button type="button" data-map-right aria-label="Sağa kaydır">›</button><span class="atlas-reset-note">100%</span>';shell.appendChild(n);const h=document.createElement('div');h.className='atlas-gesture-hint';h.textContent='Sürükle • kaydır • yakınlaştır';shell.appendChild(h);n.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.mapLeft)pan(svg,-90,0);else if(b.dataset.mapRight)pan(svg,90,0);else if(b.dataset.mapZoomIn)zoom(svg,.18);else if(b.dataset.mapZoomOut)zoom(svg,-.18);else if(b.dataset.mapReset)resetMap(svg)})}
  function bindMap(svg){if(svg.dataset.v27==='1'){addMapControls(svg);return}svg.dataset.v27='1';addMapControls(svg);const s=mapState(svg);svg.addEventListener('wheel',e=>{e.preventDefault();zoom(svg,e.deltaY<0?.12:-.12)},{passive:false});svg.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;s.pointer=true;s.moved=false;s.startX=e.clientX;s.startY=e.clientY;s.baseX=s.x;s.baseY=s.y;try{svg.setPointerCapture(e.pointerId)}catch{};applyMap(svg)});svg.addEventListener('pointermove',e=>{if(!s.pointer)return;const dx=e.clientX-s.startX,dy=e.clientY-s.startY;if(Math.abs(dx)+Math.abs(dy)>6)s.moved=true;if(!s.moved)return;s.x=clamp(s.baseX+dx,-300,300);s.y=clamp(s.baseY+dy,-180,180);applyMap(svg);e.preventDefault()},{passive:false});const end=e=>{if(!s.pointer)return;s.pointer=false;s.suppress=s.moved;try{svg.releasePointerCapture(e.pointerId)}catch{};applyMap(svg);if(s.suppress)setTimeout(()=>s.suppress=false,120)};svg.addEventListener('pointerup',end);svg.addEventListener('pointercancel',end);svg.addEventListener('dblclick',()=>resetMap(svg));svg.addEventListener('click',e=>{if(s.suppress){e.preventDefault();e.stopImmediatePropagation();s.suppress=false}},true)}
  function enhanceMaps(){ROOTS.forEach(id=>{const svg=document.getElementById(id);if(svg)bindMap(svg)})}
  function syncLiveIndexFromMarkup(el){const label=el.querySelector('.live-main small')?.textContent?.trim();const i=LIVE.findIndex(x=>x.label===label);if(i>=0)liveIndex=i}
  function renderLive(el){const e=LIVE[liveIndex];const root=el.querySelector('.live-main');if(!root)return;root.innerHTML=`<span class="live-icon">${e.icon}</span><div><small>${e.label}</small><strong>${e.value}</strong><p>${e.note}</p></div>`;qa('.live-dots i',el).forEach((d,i)=>d.classList.toggle('active',i===liveIndex));}
  function setLiveIndex(i){liveIndex=(i+LIVE.length)%LIVE.length;const el=q('#live-stats');if(!el)return;renderLive(el);const root=el.querySelector('.live-main');root?.classList.remove('live-swap');requestAnimationFrame(()=>root?.classList.add('live-swap'))}
  function bindLive(){const el=q('#live-stats');if(!el||el.dataset.v27Live==='1')return;syncLiveIndexFromMarkup(el);el.dataset.v27Live='1';const head=el.querySelector('.live-head');if(head){const old=head.querySelector('b');if(old)old.style.display='none';const r=document.createElement('button');r.type='button';r.className='live-refresh';r.dataset.atlasRefresh='1';r.textContent='↻ Yenile';head.appendChild(r)}const wrap=document.createElement('div');wrap.className='live-switcher';wrap.innerHTML='<button type="button" data-live-prev aria-label="Önceki veri">‹</button><div class="live-track"></div><button type="button" data-live-next aria-label="Sonraki veri">›</button>';const main=el.querySelector('.live-main');if(main){const track=wrap.querySelector('.live-track');main.parentNode.insertBefore(wrap,main);track.appendChild(main)}const dots=el.querySelector('.live-dots');if(dots)qa('i',dots).forEach((d,i)=>d.addEventListener('click',()=>setLiveIndex(i)));el.addEventListener('click',e=>{const b=e.target.closest('[data-live-prev],[data-live-next],[data-atlas-refresh]');if(!b)return;e.preventDefault();if(b.dataset.livePrev)setLiveIndex(liveIndex-1);else if(b.dataset.liveNext)setLiveIndex(liveIndex+1);else hardRefresh()});let sx=0,sy=0,drag=false;el.addEventListener('touchstart',e=>{const t=e.touches[0];sx=t.clientX;sy=t.clientY;drag=true},{passive:true});el.addEventListener('touchend',e=>{if(!drag)return;drag=false;const t=e.changedTouches[0],dx=t.clientX-sx,dy=t.clientY-sy;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)){setLiveIndex(liveIndex+(dx<0?1:-1));e.preventDefault()}},{passive:false});renderLive(el)}
  function hardRefresh(){try{sessionStorage.setItem('yb_reload_v27',String(Date.now()))}catch{};location.reload()}
  function patchRefreshButtons(){qa('button,a').forEach(b=>{if(b.dataset.v27Refresh==='1')return;const t=(b.textContent||'').trim().toLocaleLowerCase('tr-TR');if(t.includes('yenile')||t.includes('refresh')){b.dataset.v27Refresh='1';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();hardRefresh()},true)}})}
  let obTimer=0;const observer=new MutationObserver(()=>{clearTimeout(obTimer);obTimer=setTimeout(()=>{enhanceMaps();bindLive();patchRefreshButtons()},100)});
  function start(){enhanceMaps();bindLive();patchRefreshButtons();observer.observe(document.body,{subtree:true,childList:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
