/* Yurdunu Bil — Atlas interaction core v29
 * Comfortable pan from the whole map, click-to-select, pinch/wheel zoom,
 * preserves state, and keeps arrow semantics intuitive.
 */
(()=>{
'use strict';
const ROOTS=['dash-svg','map-svg'],mapStates=new Map(),pointers=new Map();let liveIndex=0,liveTimer=null;
const LIVE=[{icon:'👥',label:'Türkiye nüfusu',value:'86.092.168',note:'TÜİK ADNKS 2025 • 31 Aralık 2025'},{icon:'🏙️',label:'İstanbul nüfusu',value:'15.754.053',note:'TÜİK ADNKS 2025'},{icon:'🏛️',label:'Ankara nüfusu',value:'5.910.320',note:'TÜİK ADNKS 2025'},{icon:'🌊',label:'İzmir nüfusu',value:'4.504.185',note:'TÜİK ADNKS 2025'},{icon:'🏭',label:'Bursa nüfusu',value:'3.263.011',note:'TÜİK ADNKS 2025'},{icon:'🌴',label:'Antalya nüfusu',value:'2.777.677',note:'TÜİK ADNKS 2025'},{icon:'📉',label:'Nüfusu azalan il sayısı',value:'33 il',note:'2025’te bir önceki yıla göre azalış'},{icon:'🏙️',label:'İl/ilçe merkezlerinde yaşayanlar',value:'%93,6',note:'TÜİK ADNKS 2025'},{icon:'🏙️',label:'Yoğun kent nüfusu',value:'%67,5',note:'TÜİK kent-kır sınıflaması, 2025'},{icon:'📐',label:'En büyük yüz ölçümü',value:'Konya',note:'40.838 km²'},{icon:'◻️',label:'En küçük yüz ölçümü',value:'Yalova',note:'798 km²'}];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
function state(svg){const k=svg.id||'map';if(!mapStates.has(k))mapStates.set(k,{x:0,y:0,zoom:1,dragging:false,moved:false,startX:0,startY:0,baseX:0,baseY:0,suppress:false,pinchDistance:0,pinchZoom:1});return mapStates.get(k)}
function limits(svg){const r=svg.getBoundingClientRect(),w=Math.max(280,r.width||900),h=Math.max(220,r.height||500),z=state(svg).zoom;return{x:Math.min(420,120+Math.max(90,w*Math.max(z-1,.06)*.68)),y:Math.min(250,75+Math.max(60,h*Math.max(z-1,.06)*.68))}}
function apply(svg){const s=state(svg),b=limits(svg);s.x=clamp(s.x,-b.x,b.x);s.y=clamp(s.y,-b.y,b.y);s.zoom=clamp(s.zoom,.82,2.35);svg.style.transform=`translate3d(${s.x}px,${s.y}px,0) scale(${s.zoom})`;svg.classList.toggle('atlas-panning',s.dragging);const n=svg.closest('.atlas-shell')?.querySelector('.atlas-reset-note');if(n)n.textContent=`${Math.round(s.zoom*100)}%`}
function pan(svg,dx,dy){const s=state(svg);s.x+=dx;s.y+=dy;apply(svg)}
function zoom(svg,d,cx=null,cy=null){const s=state(svg),old=s.zoom,next=clamp(old+d,.82,2.35);if(next===old)return;if(cx!=null&&cy!=null){const r=svg.getBoundingClientRect(),ox=cx-(r.left+r.width/2),oy=cy-(r.top+r.height/2),ratio=next/old-1;s.x-=ox*ratio;s.y-=oy*ratio}s.zoom=next;apply(svg)}
function reset(svg){const s=state(svg);s.x=0;s.y=0;s.zoom=1;s.dragging=false;s.moved=false;s.suppress=false;s.pinchDistance=0;s.pinchZoom=1;apply(svg)}
function addControls(svg){const shell=svg.closest('.atlas-shell');if(!shell||shell.querySelector('.atlas-nav'))return;const n=document.createElement('div');n.className='atlas-nav';n.innerHTML='<button type="button" data-map-left aria-label="Sola git">‹</button><button type="button" data-map-zoom-out aria-label="Uzaklaştır">−</button><button type="button" class="atlas-reset" data-map-reset aria-label="Haritayı sıfırla">⌂</button><button type="button" data-map-zoom-in aria-label="Yakınlaştır">+</button><button type="button" data-map-right aria-label="Sağa git">›</button><span class="atlas-reset-note">100%</span>';shell.appendChild(n);const hint=document.createElement('div');hint.className='atlas-gesture-hint';hint.textContent='Haritanın her yerinde sürükle • pinch / tekerlek ile yakınlaştır';shell.appendChild(hint);n.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;e.preventDefault();e.stopPropagation();if('mapLeft'in b.dataset)pan(svg,90,0);else if('mapRight'in b.dataset)pan(svg,-90,0);else if('mapZoomIn'in b.dataset)zoom(svg,.18);else if('mapZoomOut'in b.dataset)zoom(svg,-.18);else if('mapReset'in b.dataset)reset(svg)})}
function distance(){const a=[...pointers.values()];return a.length<2?0:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)}
function bind(svg){if(!svg)return;if(svg.dataset.atlasV29==='1'){addControls(svg);apply(svg);return}svg.dataset.atlasV29='1';addControls(svg);apply(svg);svg.addEventListener('wheel',e=>{e.preventDefault();zoom(svg,e.deltaY<0?.13:-.13,e.clientX,e.clientY)},{passive:false});svg.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});try{svg.setPointerCapture(e.pointerId)}catch{}const s=state(svg);if(pointers.size>=2){s.pinchDistance=distance();s.pinchZoom=s.zoom;s.dragging=false;s.moved=true;s.suppress=true;return}s.dragging=true;s.moved=false;s.suppress=false;s.startX=e.clientX;s.startY=e.clientY;s.baseX=s.x;s.baseY=s.y;apply(svg)});svg.addEventListener('pointermove',e=>{if(pointers.has(e.pointerId))pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const s=state(svg);if(pointers.size>=2){const d=distance();if(!d||!s.pinchDistance)return;s.zoom=clamp(s.pinchZoom*d/s.pinchDistance,.82,2.35);apply(svg);e.preventDefault();return}if(!s.dragging)return;const dx=e.clientX-s.startX,dy=e.clientY-s.startY;if(Math.abs(dx)+Math.abs(dy)>7){s.moved=true;s.suppress=true}s.x=s.moved?clamp(s.baseX+dx,-420,420):s.x;s.y=s.moved?clamp(s.baseY+dy,-250,250):s.y;if(s.moved){apply(svg);e.preventDefault()}},{passive:false});const end=e=>{const s=state(svg);pointers.delete(e.pointerId);try{svg.releasePointerCapture(e.pointerId)}catch{}if(pointers.size<2)s.pinchDistance=0;if(!pointers.size){s.dragging=false;apply(svg);if(s.suppress)setTimeout(()=>s.suppress=false,90)}};svg.addEventListener('pointerup',end);svg.addEventListener('pointercancel',end);svg.addEventListener('click',e=>{const s=state(svg);if(s.suppress){e.preventDefault();e.stopImmediatePropagation();s.suppress=false}},true)}
function enhance(){ROOTS.forEach(id=>{const s=document.getElementById(id);if(s)bind(s)})}
function renderLive(el){if(!el)return;const x=LIVE[liveIndex%LIVE.length],m=el.querySelector('.live-main');if(!m)return;m.innerHTML=`<span class="live-icon">${x.icon}</span><div><small>${x.label}</small><strong>${x.value}</strong><p>${x.note}</p></div>`;$$('.live-dots i',el).forEach((d,i)=>d.classList.toggle('active',i===liveIndex%LIVE.length));m.classList.remove('live-swap');requestAnimationFrame(()=>m.classList.add('live-swap'))}
function bindLive(){const el=$('#live-stats');if(!el)return;if(el.dataset.atlasLive29==='1')return;el.dataset.atlasLive29='1';const h=el.querySelector('.live-head');if(h&&!h.querySelector('[data-atlas-refresh]')){const r=document.createElement('button');r.type='button';r.className='live-refresh';r.dataset.atlasRefresh='1';r.textContent='↻ Yenile';h.appendChild(r)}const m=el.querySelector('.live-main');if(m&&!el.querySelector('.live-switcher')){const w=document.createElement('div');w.className='live-switcher';w.innerHTML='<button type="button" data-live-prev aria-label="Önceki veri">‹</button><div class="live-track"></div><button type="button" data-live-next aria-label="Sonraki veri">›</button>';m.parentNode.insertBefore(w,m);w.querySelector('.live-track').appendChild(m)}el.addEventListener('click',e=>{const b=e.target.closest('[data-live-prev],[data-live-next],[data-atlas-refresh]');if(!b)return;e.preventDefault();e.stopPropagation();if(b.dataset.livePrev!==undefined)liveIndex=(liveIndex-1+LIVE.length)%LIVE.length;else liveIndex=(liveIndex+1)%LIVE.length;renderLive(el)});let sx=0,sy=0;el.addEventListener('touchstart',e=>{const t=e.touches[0];if(t){sx=t.clientX;sy=t.clientY}},{passive:true});el.addEventListener('touchend',e=>{const t=e.changedTouches[0];if(!t)return;const dx=t.clientX-sx,dy=t.clientY-sy;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)){liveIndex=(liveIndex+(dx<0?1:-1)+LIVE.length)%LIVE.length;renderLive(el);e.preventDefault()}},{passive:false});renderLive(el)}
function start(){enhance();bindLive();if(liveTimer)clearInterval(liveTimer);liveTimer=setInterval(()=>{const el=$('#live-stats');if(el){liveIndex=(liveIndex+1)%LIVE.length;renderLive(el)}},180000)}
let ob=0;new MutationObserver(()=>{clearTimeout(ob);ob=setTimeout(()=>{enhance();bindLive()},90)}).observe(document.body,{subtree:true,childList:true});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
