window.YURDUNUBIL_CONFIG=window.YURDUNUBIL_CONFIG||{};
YURDUNUBIL_CONFIG.APP_VERSION='63.1.0';
YURDUNUBIL_CONFIG.SUPABASE_URL='https://rdgefzwvfqvzmpfoiprj.supabase.co';
YURDUNUBIL_CONFIG.SUPABASE_PUBLISHABLE_KEY='sb_publishable_LjA0E5FY6t6ID0YMwjJpxA_vCRNCuY7';
