/* Yurdunu Bil 24.1 — visual/data enhancement */
(()=>{'use strict';
const F=window.GEO_FEATURES||{},POP=window.POPULATION_2025||{};const NS='http://www.w3.org/2000/svg';
const norm=s=>String(s||'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c');
const bounds=svg=>{let a=[Infinity,Infinity,-Infinity,-Infinity];svg.querySelectorAll('.province-shape').forEach(p=>{for(const m of (p.getAttribute('d')||'').matchAll(/(-?\d+(?:\.\d+)?),(-?\d+(?:\.\d+)?)/g)){const x=+m[1],y=+m[2];a[0]=Math.min(a[0],x);a[1]=Math.min(a[1],y);a[2]=Math.max(a[2],x);a[3]=Math.max(a[3],y)}});return{minX:a[0],minY:a[1],maxX:a[2],maxY:a[3]}};
const P=(lon,lat,b)=>[((lon-b.minX)/(b.maxX-b.minX))*930+35,((b.maxY-lat)/(b.maxY-b.minY))*430+45];
function layer(svg,mode){if(svg.querySelector('.enhanced-features.'+mode))return;svg.querySelector('.enhanced-features')?.remove();if(!['water','mountains','plains','mining'].includes(mode))return;const g=document.createElementNS(NS,'g');g.classList.add('enhanced-features',mode);const b=bounds(svg);const text=(x,y,s,c)=>{const t=document.createElementNS(NS,'text');t.setAttribute('x',x);t.setAttribute('y',y);t.textContent=s;t.setAttribute('class','enh-label '+c);g.appendChild(t)};
if(mode==='water'){(F.rivers||[]).forEach(r=>{const p=document.createElementNS(NS,'path');p.setAttribute('class','enh-river');p.setAttribute('d',r.points.map(([lat,lon],i)=>{const[x,y]=P(lon,lat,b);return(i?'L':'M')+x.toFixed(1)+','+y.toFixed(1)}).join(' '));g.appendChild(p)});(F.lakes||[]).forEach(l=>{const[x,y]=P(l.lon,l.lat,b),e=document.createElementNS(NS,'ellipse');e.setAttribute('cx',x);e.setAttribute('cy',y);e.setAttribute('rx',l.rx);e.setAttribute('ry',l.ry);e.setAttribute('class','enh-lake');g.appendChild(e);text(x,y+3,l.name,'water-text')})}
else if(mode==='mountains')(F.mountains||[]).forEach(m=>{const[x,y]=P(m.lon,m.lat,b);text(x,y,'▲ '+m.name,'mountain-text')});
else if(mode==='plains')(F.plains||[]).forEach(p=>{const[x,y]=P(p.lon,p.lat,b),e=document.createElementNS(NS,'ellipse');e.setAttribute('cx',x);e.setAttribute('cy',y);e.setAttribute('rx',p.rx);e.setAttribute('ry',p.ry);e.setAttribute('class','enh-plain');g.appendChild(e);text(x,y+3,p.name,'plain-text')});
else(F.mines||[]).forEach(m=>{const[x,y]=P(m.lon,m.lat,b),c=document.createElementNS(NS,'circle');c.setAttribute('cx',x);c.setAttribute('cy',y);c.setAttribute('r',6);c.setAttribute('class','enh-mine');g.appendChild(c);text(x+8,y+3,m.name,'mine-text')});svg.appendChild(g)}
function patch(){document.querySelectorAll('.atlas-svg').forEach(svg=>{const a=svg.closest('.atlas-shell')?.querySelector('.mode-tabs button.active');layer(svg,a?.dataset.mode||'default')});document.querySelectorAll('.province-panel').forEach(panel=>{const title=panel.querySelector('.province-top h2'),name=title?.textContent.trim(),row=[...panel.querySelectorAll('.geo-grid>div')].find(x=>norm(x.textContent).includes('2025 nufusu'));if(row&&POP[name])row.querySelector('b').textContent=POP[name]});document.querySelectorAll('#nav-discovered').forEach(x=>x.remove());document.querySelectorAll('.toast').forEach(x=>{if(norm(x.textContent).includes('kesfedildi'))x.remove()})}
let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(patch,40)}).observe(document.body,{subtree:true,childList:true});document.addEventListener('click',e=>{if(e.target.closest('.mode-tabs button'))setTimeout(patch,60)});patch();})();
