/* Yurdunu Bil — library.js: kütüphane modülleri birleşik dosyası */

/* ── v75-library-study.js ── */
/* Yurdunu Bil 75 â€” expanded study modules for the library */
(()=>{'use strict';
if(window.__YB75_LIBRARY__)return;window.__YB75_LIBRARY__=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const modules=[
{id:'m01',topic:'konum',icon:'ğŸ§­',title:'Matematik Konum',tag:'TEMEL',mins:8,summary:'Enlem ve boylamÄ±n TÃ¼rkiye Ã¼zerindeki sonuÃ§larÄ±nÄ± netleÅŸtir.',points:['TÃ¼rkiye 36Â°-42Â° kuzey paralelleri ile 26Â°-45Â° doÄŸu meridyenleri arasÄ±ndadÄ±r.','Enlem; gÃ¼neÅŸ Ä±ÅŸÄ±nlarÄ±nÄ±n geliÅŸ aÃ§Ä±sÄ±, sÄ±caklÄ±k ve gece-gÃ¼ndÃ¼z sÃ¼re farklarÄ±nÄ± etkiler.','Boylam; yerel saat ve gÃ¼neÅŸin doÄŸuÅŸ-batÄ±ÅŸ zamanlarÄ±nda fark oluÅŸturur.'],memory:'Enlem = sÄ±caklÄ±k + gÃ¶lge + gece-gÃ¼ndÃ¼z. Boylam = saat.'},
{id:'m02',topic:'konum',icon:'ğŸ•°ï¸',title:'Yerel Saat ve Boylam',tag:'YÃœKSEK GETÄ°RÄ°',mins:7,summary:'DoÄŸu-batÄ± yÃ¶nlÃ¼ saat sorularÄ±nÄ± tek mantÄ±kla Ã§Ã¶z.',points:['DoÄŸuya gidildikÃ§e yerel saat ilerler; batÄ±ya gidildikÃ§e geri kalÄ±r.','1Â° boylam farkÄ± 4 dakikalÄ±k yerel saat farkÄ± oluÅŸturur.','GÃ¼neÅŸ doÄŸuda daha erken doÄŸar ve daha erken batar.'],memory:'DoÄŸu = saat ileri.'},
{id:'m03',topic:'konum',icon:'ğŸŒ',title:'Ã–zel Konum SonuÃ§larÄ±',tag:'YÃœKSEK GETÄ°RÄ°',mins:9,summary:'TÃ¼rkiyeâ€™nin kÄ±talar, denizler ve ulaÅŸÄ±m aÄŸlarÄ± arasÄ±ndaki konumunu Ã¶ÄŸren.',points:['TÃ¼rkiye Asya ile Avrupa arasÄ±nda geÃ§iÅŸ alanÄ±dÄ±r.','BoÄŸazlar Karadenizâ€™i Akdeniz Ã¼zerinden dÃ¼nya denizlerine baÄŸlar.','UlaÅŸÄ±m, ticaret ve enerji geÃ§iÅŸlerinde kÃ¶prÃ¼ konumunun etkisi gÃ¶rÃ¼lÃ¼r.'],memory:'Ã–zel konum = Ã§evresindeki Ã¼lkeler, denizler, yollar ve ekonomik baÄŸlantÄ±lar.'},
{id:'m04',topic:'konum',icon:'â˜€ï¸',title:'Enlem Etkisi ve GÃ¼neÅŸ',tag:'TEMEL',mins:8,summary:'Enleme baÄŸlÄ± sÄ±caklÄ±k ve gÃ¼neÅŸ aÃ§Ä±sÄ± sorularÄ±nÄ± ayÄ±rt et.',points:['GÃ¼neyden kuzeye gidildikÃ§e gÃ¼neÅŸ Ä±ÅŸÄ±nlarÄ±nÄ±n geliÅŸ aÃ§Ä±sÄ± kÃ¼Ã§Ã¼lÃ¼r.','Genel olarak sÄ±caklÄ±k gÃ¼neyden kuzeye azalÄ±r; yÃ¼kselti bu iliÅŸkiyi deÄŸiÅŸtirebilir.','Gece-gÃ¼ndÃ¼z sÃ¼re farkÄ± kutuplara doÄŸru artar.'],memory:'Kuzeye = daha eÄŸik gÃ¼neÅŸ, daha dÃ¼ÅŸÃ¼k ortalama sÄ±caklÄ±k.'},
{id:'m05',topic:'iklim',icon:'ğŸŒ¦ï¸',title:'TÃ¼rkiyeâ€™de Ä°klim Tipleri',tag:'YÃœKSEK GETÄ°RÄ°',mins:10,summary:'Karadeniz, Akdeniz ve karasal iklimi ayÄ±rt et.',points:['Karadeniz: yÄ±l boyunca yaÄŸÄ±ÅŸlÄ± ve ormanlÄ±ktÄ±r.','Akdeniz: yaz sÄ±cak-kurak, kÄ±ÅŸ Ä±lÄ±k-yaÄŸÄ±ÅŸlÄ±dÄ±r; maki yaygÄ±ndÄ±r.','Karasal alanlarda yÄ±llÄ±k sÄ±caklÄ±k farkÄ± daha yÃ¼ksektir.'],memory:'Yaz kuraklÄ±ÄŸÄ± â†’ Akdeniz. Her mevsim yaÄŸÄ±ÅŸ â†’ Karadeniz. Sert kÄ±ÅŸ â†’ karasal.'},
{id:'m06',topic:'iklim',icon:'ğŸŒ²',title:'Bitki Ã–rtÃ¼sÃ¼ EÅŸleÅŸtirmeleri',tag:'TEMEL',mins:8,summary:'Ä°klim ile doÄŸal bitki Ã¶rtÃ¼sÃ¼nÃ¼ eÅŸleÅŸtirmeyi Ã¶ÄŸren.',points:['Karadenizâ€™de ormanlar geniÅŸ alan kaplar.','Akdeniz kÄ±yÄ±larÄ±nda maki ve kÄ±zÄ±lÃ§am topluluklarÄ± gÃ¶rÃ¼lÃ¼r.','Ä°Ã§ Anadoluâ€™da step/bozkÄ±r yaygÄ±ndÄ±r.'],memory:'Nem arttÄ±kÃ§a orman; yaz kuraklÄ±ÄŸÄ± arttÄ±kÃ§a maki; yarÄ± kurak alanlarda bozkÄ±r.'},
{id:'m07',topic:'iklim',icon:'â„ï¸',title:'YÃ¼kselti ve SÄ±caklÄ±k',tag:'SINAV TUZAÄI',mins:7,summary:'AynÄ± enlemde neden farklÄ± sÄ±caklÄ±k gÃ¶rÃ¼ldÃ¼ÄŸÃ¼nÃ¼ Ã§Ã¶z.',points:['YÃ¼kselti arttÄ±kÃ§a sÄ±caklÄ±k genel olarak azalÄ±r.','DoÄŸu Anadoluâ€™nun yÃ¼kseltisi yÃ¼ksek olduÄŸu iÃ§in kÄ±ÅŸlar daha serttir.','Enlem tek baÅŸÄ±na sÄ±caklÄ±ÄŸÄ± aÃ§Ä±klamaz; yÃ¼kselti ve denizellik de dÃ¼ÅŸÃ¼nÃ¼lmelidir.'],memory:'AynÄ± enlem + farklÄ± yÃ¼kselti = farklÄ± sÄ±caklÄ±k.'},
{id:'m08',topic:'iklim',icon:'â˜”',title:'YaÄŸÄ±ÅŸ Rejimi ve Denizellik',tag:'ORTA',mins:9,summary:'KÄ±yÄ±-iÃ§ kesim farkÄ±nÄ± yaÄŸÄ±ÅŸ ve sÄ±caklÄ±k Ã¼zerinden kur.',points:['Denizler kÄ±yÄ±larda sÄ±caklÄ±k farkÄ±nÄ± azaltÄ±r.','Ä°Ã§ kesimlerde karasallÄ±k nedeniyle yÄ±llÄ±k sÄ±caklÄ±k farkÄ± bÃ¼yÃ¼r.','DaÄŸlarÄ±n kÄ±yÄ±ya paralel uzanmasÄ± bazÄ± kÄ±yÄ±larda deniz etkisinin iÃ§eri sokulmasÄ±nÄ± sÄ±nÄ±rlar.'],memory:'Deniz = tampon. DaÄŸ = engel.'},
{id:'m09',topic:'yerseki',icon:'â›°ï¸',title:'KÄ±rÄ±k ve KÄ±vrÄ±m DaÄŸlarÄ±',tag:'YÃœKSEK GETÄ°RÄ°',mins:9,summary:'TÃ¼rkiyeâ€™deki daÄŸ sÄ±ralarÄ±nÄ±n uzanÄ±ÅŸÄ±nÄ± ve etkilerini Ã¶ÄŸren.',points:['Kuzey Anadolu DaÄŸlarÄ± Karadeniz kÄ±yÄ±larÄ±na paralel uzanÄ±r.','Toroslar Akdeniz kÄ±yÄ± kuÅŸaÄŸÄ±na paralel uzanÄ±r.','KÄ±yÄ±ya paralel daÄŸlar deniz etkisinin iÃ§ kesimlere ulaÅŸmasÄ±nÄ± zorlaÅŸtÄ±rabilir.'],memory:'Karadeniz â†’ Kuzey Anadolu. Akdeniz â†’ Toroslar.'},
{id:'m10',topic:'yerseki',icon:'ğŸ”ï¸',title:'Ovalar ve Platolar',tag:'TEMEL',mins:10,summary:'KÄ±yÄ± ve iÃ§ ovalarÄ±, platolarÄ± Ã¶rnekleriyle ayÄ±r.',points:['Ã‡ukurova ve Bafra kÄ±yÄ± ovalarÄ±na Ã¶rnektir.','Konya ve Erzurum-Pasinler iÃ§ ovalara Ã¶rnektir.','Bozok, Cihanbeyli, Teke ve Erzurum-Kars Ã¶nemli plato Ã¶rnekleridir.'],memory:'Ova = taban dÃ¼zlÃ¼ÄŸÃ¼. Plato = akarsularla yarÄ±lmÄ±ÅŸ yÃ¼ksek dÃ¼zlÃ¼k.'},
{id:'m11',topic:'yerseki',icon:'ğŸŒ‹',title:'Volkanik ve Karstik Åekiller',tag:'SINAV TUZAÄI',mins:8,summary:'OluÅŸum sÃ¼recinden yer ÅŸeklinin tÃ¼rÃ¼nÃ¼ Ã§Ä±kar.',points:['Volkanizma; volkan konileri ve lavlarla iliÅŸkili yÃ¼zey ÅŸekilleri oluÅŸturur.','Kalker gibi Ã§Ã¶zÃ¼nebilen kayaÃ§larda karstik ÅŸekiller geliÅŸir.','Obruk, dolin ve maÄŸara karstik sÃ¼reÃ§lerle iliÅŸkilidir.'],memory:'Volkan = magma. Karst = Ã§Ã¶zÃ¼nme.'},
{id:'m12',topic:'yerseki',icon:'ğŸ“',title:'Faylar ve Depremsellik',tag:'YÃœKSEK GETÄ°RÄ°',mins:7,summary:'TÃ¼rkiyeâ€™de aktif fay kuÅŸaklarÄ±nÄ± ve sonuÃ§larÄ±nÄ± kavra.',points:['Kuzey Anadolu ve DoÄŸu Anadolu fay kuÅŸaklarÄ± Ã¶nemli tektonik yapÄ±lardÄ±r.','Fay hatlarÄ± boyunca deprem riski yÃ¼kselir.','Tektonik hareketler graben, horst ve kÄ±rÄ±klÄ± yapÄ±larÄ±n geliÅŸmesinde rol oynar.'],memory:'Fay = kÄ±rÄ±k = deprem riski.'},
{id:'m13',topic:'su',icon:'ğŸŒŠ',title:'AkarsularÄ±n Genel Ã–zellikleri',tag:'TEMEL',mins:9,summary:'Akarsu rejimi, debi ve akÄ±ÅŸ Ã¶zelliklerini yorumla.',points:['TÃ¼rkiye akarsularÄ±nÄ±n rejimleri Ã§oÄŸunlukla dÃ¼zensizdir.','Karadenizâ€™de kÄ±sa boylu ve eÄŸimli arazide hÄ±zlÄ± akÄ±ÅŸlÄ± akarsular gÃ¶rÃ¼lÃ¼r.','Kurak ve yarÄ± kurak iÃ§ kesimlerde su miktarÄ± mevsime daha baÄŸlÄ±dÄ±r.'],memory:'Rejim = yÄ±l iÃ§indeki su deÄŸiÅŸimi.'},
{id:'m14',topic:'su',icon:'ğŸ’§',title:'GÃ¶llerin OluÅŸumlarÄ±',tag:'YÃœKSEK GETÄ°RÄ°',mins:10,summary:'GÃ¶l tÃ¼rlerini oluÅŸum ÅŸekilleriyle eÅŸleÅŸtir.',points:['Tektonik gÃ¶ller fay ve Ã§Ã¶kÃ¼ntÃ¼lerle iliÅŸkilidir.','Volkanik gÃ¶ller krater veya volkanik faaliyetlerle oluÅŸabilir.','Set gÃ¶lleri heyelan, alÃ¼vyon veya lav setleriyle oluÅŸabilir.'],memory:'Fay = tektonik. Krater = volkanik. Set = engellenmiÅŸ akÄ±ÅŸ.'},
{id:'m15',topic:'su',icon:'ğŸï¸',title:'GAP ve FÄ±rat-Dicle HavzasÄ±',tag:'YÃœKSEK GETÄ°RÄ°',mins:9,summary:'Su kaynaklarÄ±nÄ±n enerji ve tarÄ±mdaki rolÃ¼nÃ¼ Ã¶ÄŸren.',points:['FÄ±rat ve Dicle havzasÄ± bÃ¼yÃ¼k su ve hidroelektrik potansiyeline sahiptir.','GAP; sulama, enerji ve tarÄ±msal Ã¼retimi birlikte etkiler.','Barajlar akÄ±ÅŸÄ±n dÃ¼zenlenmesi ve enerji Ã¼retiminde Ã¶nemlidir.'],memory:'FÄ±rat-Dicle = su + enerji + sulama.'},
{id:'m16',topic:'su',icon:'ğŸ§‚',title:'Van GÃ¶lÃ¼ ve KapalÄ± Havzalar',tag:'ORTA',mins:7,summary:'GÃ¶llerde dÄ±ÅŸa akÄ±ÅŸ ve tuzluluk gibi Ã¶zellikleri karÅŸÄ±laÅŸtÄ±r.',points:['Van GÃ¶lÃ¼ TÃ¼rkiyeâ€™nin en bÃ¼yÃ¼k gÃ¶lÃ¼dÃ¼r.','KapalÄ± havzalarda sular denize ulaÅŸmadan gÃ¶l veya Ã§anaklarda toplanabilir.','BuharlaÅŸma ve akarsu giriÅŸleri gÃ¶l suyu Ã¶zelliklerini etkiler.'],memory:'KapalÄ± havza = denize Ã§Ä±kÄ±ÅŸ yok.'},
{id:'m17',topic:'nufus',icon:'ğŸ‘¥',title:'NÃ¼fus DaÄŸÄ±lÄ±ÅŸÄ±nÄ± Belirleyen FaktÃ¶rler',tag:'YÃœKSEK GETÄ°RÄ°',mins:9,summary:'NÃ¼fusun neden bazÄ± alanlarda yoÄŸunlaÅŸtÄ±ÄŸÄ±nÄ± sistematik Ã§Ã¶z.',points:['Ä°klim, yer ÅŸekilleri, su kaynaklarÄ± ve toprak Ã¶zellikleri doÄŸal etkenlerdir.','Sanayi, ulaÅŸÄ±m, ticaret ve hizmetler beÅŸerÃ®-ekonomik etkenlerdir.','Marmara ve bÃ¼yÃ¼k ova/ÅŸehir Ã§evreleri yoÄŸun nÃ¼fuslu alanlardÄ±r.'],memory:'NÃ¼fus = doÄŸal ÅŸartlar + ekonomik fÄ±rsat.'},
{id:'m18',topic:'nufus',icon:'ğŸ™ï¸',title:'Ä°Ã§ GÃ¶Ã§ ve KentleÅŸme',tag:'ORTA',mins:8,summary:'TÃ¼rkiyeâ€™de gÃ¶Ã§ yÃ¶nÃ¼nÃ¼ ve sonuÃ§larÄ±nÄ± yorumla.',points:['Ä°Ã§ gÃ¶Ã§te kÄ±rdan kente ve doÄŸudan batÄ±ya yÃ¶nelim sÄ±k gÃ¶rÃ¼lÃ¼r.','Sanayi ve hizmet sektÃ¶rÃ¼nÃ¼n gÃ¼Ã§lÃ¼ olduÄŸu merkezler gÃ¶Ã§ Ã§eker.','GÃ¶Ã§; konut, ulaÅŸÄ±m ve altyapÄ± talebini artÄ±rabilir.'],memory:'GÃ¶Ã§Ã¼n Ã§ekim merkezi = iÅŸ + eÄŸitim + hizmet.'},
{id:'m19',topic:'nufus',icon:'ğŸ“Š',title:'NÃ¼fus YoÄŸunluÄŸu SorularÄ±',tag:'SINAV TAKTÄ°ÄÄ°',mins:7,summary:'YoÄŸunluk ile toplam nÃ¼fus arasÄ±ndaki farkÄ± netleÅŸtir.',points:['NÃ¼fus yoÄŸunluÄŸu, nÃ¼fusun yÃ¼zÃ¶lÃ§Ã¼mÃ¼ne oranÄ±dÄ±r.','Toplam nÃ¼fusu fazla olan bir alanÄ±n yoÄŸunluÄŸu mutlaka en yÃ¼ksek olmak zorunda deÄŸildir.','Dar alan + kalabalÄ±k nÃ¼fus, yÃ¼ksek yoÄŸunluk yaratabilir.'],memory:'YoÄŸunluk = kiÅŸi / alan.'},
{id:'m20',topic:'nufus',icon:'ğŸ“',title:'YerleÅŸme Tipleri',tag:'TEMEL',mins:8,summary:'KÄ±r ve ÅŸehir yerleÅŸmelerini ekonomik faaliyetlerle iliÅŸkilendir.',points:['Åehir yerleÅŸmelerinde sanayi ve hizmet faaliyetleri aÄŸÄ±rlÄ±k kazanÄ±r.','KÄ±rsal yerleÅŸmelerde tarÄ±m ve hayvancÄ±lÄ±ÄŸÄ±n payÄ± daha yÃ¼ksektir.','DaÄŸÄ±nÄ±k ve toplu yerleÅŸme; iklim, su ve arazi yapÄ±sÄ±yla iliÅŸkilidir.'],memory:'Su + arazi + geÃ§im = yerleÅŸme biÃ§imi.'},
{id:'m21',topic:'tarim',icon:'ğŸŒ¾',title:'TarÄ±m ÃœrÃ¼nleri ve BÃ¶lgesel DaÄŸÄ±lÄ±ÅŸ',tag:'YÃœKSEK GETÄ°RÄ°',mins:10,summary:'ÃœrÃ¼n ile iklim/alan eÅŸleÅŸtirmelerini hÄ±zlandÄ±r.',points:['FÄ±ndÄ±k DoÄŸu Karadeniz kÄ±yÄ± kuÅŸaÄŸÄ±nda yoÄŸunlaÅŸÄ±r.','Ã‡ay DoÄŸu Karadenizâ€™de yetiÅŸir.','Zeytin Ege ve Akdeniz kÄ±yÄ±larÄ±nda yaygÄ±ndÄ±r.','Pamuk; Ã‡ukurova, Ege ve GAP sonrasÄ± GÃ¼neydoÄŸuâ€™da Ã¶nemlidir.'],memory:'ÃœrÃ¼nÃ¼ tek baÅŸÄ±na deÄŸil, istediÄŸi iklimle birlikte ezberle.'},
{id:'m22',topic:'tarim',icon:'ğŸµ',title:'Ã‡ay, FÄ±ndÄ±k ve Zeytin',tag:'EZBER DEÄERÄ° YÃœKSEK',mins:7,summary:'SÄ±k sorulan Ã¼rÃ¼n-bÃ¶lge Ã¼Ã§lÃ¼lerini kalÄ±cÄ±laÅŸtÄ±r.',points:['Ã‡ay â†’ DoÄŸu Karadeniz.','FÄ±ndÄ±k â†’ Karadeniz kÄ±yÄ±larÄ±.','Zeytin â†’ Ege ve Akdeniz kÄ±yÄ±larÄ±.'],memory:'Ã‡ay = yaÄŸÄ±ÅŸ. FÄ±ndÄ±k = nemli kÄ±yÄ±. Zeytin = Akdeniz iklimi.'},
{id:'m23',topic:'tarim',icon:'ğŸ‘',title:'HayvancÄ±lÄ±k TÃ¼rleri',tag:'TEMEL',mins:8,summary:'KÃ¼Ã§Ã¼kbaÅŸ ve bÃ¼yÃ¼kbaÅŸ hayvancÄ±lÄ±ÄŸÄ± coÄŸrafyayla baÄŸla.',points:['KÃ¼Ã§Ã¼kbaÅŸ hayvancÄ±lÄ±k kurak ve engebeli alanlarda daha elveriÅŸlidir.','BÃ¼yÃ¼kbaÅŸ hayvancÄ±lÄ±k Ã§ayÄ±r ve mera olanaklarÄ±nÄ±n gÃ¼Ã§lÃ¼ olduÄŸu alanlarda geliÅŸir.','DoÄŸu Anadolu yÃ¼ksek platolarÄ± bÃ¼yÃ¼kbaÅŸ hayvancÄ±lÄ±k aÃ§Ä±sÄ±ndan Ã¶nemlidir.'],memory:'Kuru-bozkÄ±r = kÃ¼Ã§Ã¼kbaÅŸ; serin-Ã§ayÄ±rlÄ±k = bÃ¼yÃ¼kbaÅŸ.'},
{id:'m24',topic:'tarim',icon:'ğŸŒ³',title:'Orman ve OrmancÄ±lÄ±k',tag:'ORTA',mins:7,summary:'OrmanlarÄ±n iklim ve ekonomik Ã¶nemini kavra.',points:['Karadeniz ve Akdeniz kÄ±yÄ± kuÅŸaklarÄ± orman varlÄ±ÄŸÄ± bakÄ±mÄ±ndan zengindir.','Orman Ã¼rÃ¼nleri, kereste ve sel/erozyon kontrolÃ¼ aÃ§Ä±sÄ±ndan Ã¶nemlidir.','YÃ¼kselti ve nem koÅŸullarÄ± ormanlarÄ±n daÄŸÄ±lÄ±ÅŸÄ±nÄ± etkiler.'],memory:'Nem + uygun sÄ±caklÄ±k = orman.'},
{id:'m25',topic:'sanayi',icon:'â›ï¸',title:'Madenler ve Ã–nemli Yataklar',tag:'YÃœKSEK GETÄ°RÄ°',mins:10,summary:'Maden sorularÄ±nda kaynak-yer eÅŸleÅŸtirmesini gÃ¼Ã§lendir.',points:['Bor; KÃ¼tahya, EskiÅŸehir ve BalÄ±kesir Ã§evresinde Ã¶nemlidir.','TaÅŸ kÃ¶mÃ¼rÃ¼ Zonguldak havzasÄ±nda Ã§Ä±karÄ±lÄ±r.','Demir iÃ§in Sivas-DivriÄŸi, bakÄ±r iÃ§in ElazÄ±ÄŸ-Ergani Ã¶nemli Ã¶rneklerdir.'],memory:'Maden sorusu = maden + merkez + kullanÄ±m alanÄ± Ã¼Ã§lÃ¼sÃ¼.'},
{id:'m26',topic:'sanayi',icon:'ğŸ­',title:'Sanayinin DaÄŸÄ±lÄ±ÅŸÄ±nÄ± Etkileyen FaktÃ¶rler',tag:'ORTA',mins:9,summary:'Sanayi neden belirli merkezlerde toplanÄ±r?',points:['Pazar, ulaÅŸÄ±m, enerji ve iÅŸ gÃ¼cÃ¼ sanayinin daÄŸÄ±lÄ±ÅŸÄ±nda Ã¶nemlidir.','Marmara BÃ¶lgesi sanayi Ã¼retiminde gÃ¼Ã§lÃ¼ bir merkezdir.','Liman kentleri ve ulaÅŸÄ±m koridorlarÄ± sanayi iÃ§in avantaj saÄŸlayabilir.'],memory:'Sanayi = pazar + ulaÅŸÄ±m + enerji + iÅŸ gÃ¼cÃ¼.'},
{id:'m27',topic:'sanayi',icon:'âš¡',title:'Enerji KaynaklarÄ±',tag:'YÃœKSEK GETÄ°RÄ°',mins:9,summary:'Hidroelektrik, jeotermal ve diÄŸer enerji tÃ¼rlerini ayÄ±r.',points:['FÄ±rat-Dicle havzasÄ± hidroelektrik potansiyeli ile Ã¶ne Ã§Ä±kar.','BatÄ± Anadolu jeotermal kaynaklarÄ± bakÄ±mÄ±ndan zengindir.','Enerji tÃ¼rÃ¼nÃ¼n daÄŸÄ±lÄ±ÅŸÄ± jeolojik ve topografik koÅŸullarla iliÅŸkilidir.'],memory:'HES = yÃ¼kselti + akarsu. Jeotermal = genÃ§/aktif tektonizma.'},
{id:'m28',topic:'sanayi',icon:'ğŸšš',title:'UlaÅŸÄ±m ve Ekonomik Konum',tag:'ORTA',mins:8,summary:'UlaÅŸÄ±m aÄŸÄ±nÄ±n Ã¼retim ve ticaret Ã¼zerindeki etkisini Ã¶ÄŸren.',points:['DoÄŸal engeller ve yÃ¼kselti ulaÅŸÄ±m maliyetini artÄ±rabilir.','BoÄŸazlar ve ana kara baÄŸlantÄ±larÄ± TÃ¼rkiyeâ€™nin stratejik ulaÅŸÄ±m konumunu gÃ¼Ã§lendirir.','Limanlar dÄ±ÅŸ ticaret ve taÅŸÄ±mada kritik dÃ¼ÄŸÃ¼m noktalarÄ±dÄ±r.'],memory:'UlaÅŸÄ±m = mesafe + relief + baÄŸlantÄ±.'},
{id:'m29',topic:'bolgeler',icon:'ğŸ—ºï¸',title:'7 CoÄŸrafi BÃ¶lgeyi AyÄ±rt Et',tag:'TEMEL',mins:10,summary:'BÃ¶lgeleri tek tek ezberlemek yerine ayÄ±rt edici Ã¶zelliklerle Ã¶ÄŸren.',points:['Marmara â†’ sanayi ve geÃ§iÅŸ Ã¶zelliÄŸi.','Ege â†’ graben ovalarÄ±, zeytin ve turizm.','Akdeniz â†’ kÄ±yÄ± turizmi, sera tarÄ±mÄ±, Toroslar.','Karadeniz â†’ orman, yaÄŸÄ±ÅŸ ve Ã§ay-fÄ±ndÄ±k.'],memory:'Her bÃ¶lgeye 3 ayÄ±rt edici kelime ver; soru kÃ¶kÃ¼nde bunlarÄ± ara.'},
{id:'m30',topic:'bolgeler',icon:'ğŸœï¸',title:'Ä°Ã§ ve DoÄŸu Anadolu KarÅŸÄ±laÅŸtÄ±rmasÄ±',tag:'SINAV TAKTÄ°ÄÄ°',mins:9,summary:'Karasal iklim ve yÃ¼kselti iliÅŸkisini iki bÃ¶lge Ã¼zerinden karÅŸÄ±laÅŸtÄ±r.',points:['Ä°Ã§ Anadolu daha kurak ve bozkÄ±r karakterlidir.','DoÄŸu Anadoluâ€™da yÃ¼kselti daha fazla, kÄ±ÅŸ koÅŸullarÄ± daha serttir.','TarÄ±m ve yerleÅŸme Ã¼zerinde yaÄŸÄ±ÅŸ ve yÃ¼kselti belirleyicidir.'],memory:'DoÄŸu Anadolu = daha yÃ¼ksek + daha sert.'},
{id:'m31',topic:'bolgeler',icon:'ğŸ–ï¸',title:'Turizm TÃ¼rleri',tag:'YÃœKSEK GETÄ°RÄ°',mins:8,summary:'Turizm tÃ¼rlerini coÄŸrafi Ã¶zelliklerle eÅŸleÅŸtir.',points:['Akdeniz ve Ege kÄ±yÄ±larÄ±nda deniz turizmi Ã¶ne Ã§Ä±kar.','Karadenizâ€™de yayla turizmi Ã¶nemlidir.','Kapadokya ve Pamukkale doÄŸal/kÃ¼ltÃ¼rel Ã§ekicilikleriyle Ã¶ne Ã§Ä±kar.'],memory:'Turizm tÃ¼rÃ¼nÃ¼ yerin doÄŸal/kÃ¼ltÃ¼rel Ã¶zelliÄŸinden Ã§Ä±kar.'},
{id:'m32',topic:'bolgeler',icon:'ğŸ”',title:'BÃ¶lge KarÅŸÄ±laÅŸtÄ±rmalÄ± Sorular',tag:'YÃœKSEK GETÄ°RÄ°',mins:10,summary:'â€œHangisi daha fazla?â€ sorularÄ±nda Ã¶lÃ§Ã¼t tablosu kullan.',points:['SÄ±caklÄ±k, yaÄŸÄ±ÅŸ, nÃ¼fus, yÃ¼kselti ve tarÄ±m Ã¼rÃ¼nleri ayrÄ± ayrÄ± dÃ¼ÅŸÃ¼nÃ¼lmelidir.','Tek bir Ã¶zelliÄŸi bÃ¼tÃ¼n bÃ¶lgeye genellemeden Ã¶nce soru kÃ¶kÃ¼nÃ¼ dikkatle oku.','KarÅŸÄ±laÅŸtÄ±rmada Ã¶nce ortak zemin, sonra ayÄ±rt edici Ã¶zellik aranÄ±r.'],memory:'Ã–nce Ã¶lÃ§Ã¼tÃ¼ bul, sonra bÃ¶lgeleri karÅŸÄ±laÅŸtÄ±r.'}
];
window.YB75_STUDY_MODULES=modules;
function moduleCard(m){return `<article class="study-module" data-study-id="${m.id}" data-topic="${m.topic}" data-tag="${m.tag.toLowerCase('tr-TR')}"><div class="study-module-top"><span class="study-module-icon">${m.icon}</span><span class="study-module-tag">${esc(m.tag)}</span><span class="study-module-time">â± ${m.mins} dk</span></div><h3>${esc(m.title)}</h3><p>${esc(m.summary)}</p><div class="study-points-preview">${m.points.slice(0,2).map(x=>`<span>âœ“ ${esc(x)}</span>`).join('')}</div><button class="study-open" type="button">Ã‡alÄ±ÅŸmaya baÅŸla â†’</button></article>`}
function inject(){const v=$('#view-library');if(!v||!v.classList.contains('active')||$('.study-zone',v))return;const grid=$('.library-note-grid',v);if(!grid)return;const zone=document.createElement('section');zone.className='study-zone';zone.innerHTML=`<div class="study-zone-head"><div><span class="eyebrow">DERÄ°NLEÅTÄ°RÄ°LMÄ°Å Ã‡ALIÅMA</span><h2>Konuyu parÃ§ala, gerÃ§ekten Ã¶ÄŸren.</h2><p>8 ana Ã¼nitenin altÄ±na ${modules.length} kÄ±sa Ã§alÄ±ÅŸma modÃ¼lÃ¼ ekledik. Her modÃ¼l: Ã¶zet + kilit bilgiler + sÄ±nav hafÄ±zasÄ±.</p></div><div class="study-zone-stat"><b>${modules.length}</b><span>Ã§alÄ±ÅŸma modÃ¼lÃ¼</span></div></div><div class="study-filter"><input id="study-search" type="search" placeholder="Alt konu, kavram veya baÅŸlÄ±k ara..."><div class="study-pills"><button class="active" data-study-filter="all">TÃ¼mÃ¼</button><button data-study-filter="konum">Konum</button><button data-study-filter="iklim">Ä°klim</button><button data-study-filter="yerseki">YerÅŸekilleri</button><button data-study-filter="su">Sular</button><button data-study-filter="nufus">NÃ¼fus</button><button data-study-filter="tarim">TarÄ±m</button><button data-study-filter="sanayi">Maden & Sanayi</button><button data-study-filter="bolgeler">BÃ¶lgeler</button></div></div><div class="study-module-grid">${modules.map(moduleCard).join('')}</div>`;grid.parentNode.insertBefore(zone,grid.nextSibling);bind(zone)}
function bind(zone){$$('[data-study-filter]',zone).forEach(b=>b.onclick=()=>filter(zone,b.dataset.studyFilter));$('#study-search',zone)?.addEventListener('input',e=>filter(zone,'search',e.target.value));$$('.study-open',zone).forEach(b=>b.onclick=()=>open($(b.closest('.study-module')).dataset.studyId));}
function filter(zone,mode,value=''){const cards=$$('.study-module',zone);if(mode!=='search')$$('[data-study-filter]',zone).forEach(x=>x.classList.toggle('active',x.dataset.studyFilter===mode));const q=mode==='search'?String(value).toLocaleLowerCase('tr-TR').trim():'';const active=$('.study-pills .active',zone)?.dataset.studyFilter||'all';cards.forEach(c=>{const okTopic=active==='all'||c.dataset.topic===active;const okSearch=!q||String(c.textContent).toLocaleLowerCase('tr-TR').includes(q);c.hidden=!(okTopic&&okSearch)});}
function open(id){const m=modules.find(x=>x.id===id);if(!m)return;let modal=$('#yb75-study-modal');if(!modal){modal=document.createElement('div');modal.id='yb75-study-modal';document.body.appendChild(modal)}modal.innerHTML=`<div class="study-modal-backdrop" data-study-close></div><section class="study-modal-card" role="dialog" aria-modal="true"><button class="study-modal-close" type="button" data-study-close>Ã—</button><div class="study-modal-kicker">${m.icon} ${esc(m.tag)} â€¢ ${m.mins} DK</div><h2>${esc(m.title)}</h2><p class="study-modal-summary">${esc(m.summary)}</p><h3>Kilit bilgiler</h3><div class="study-modal-points">${m.points.map((x,i)=>`<div><b>${String(i+1).padStart(2,'0')}</b><span>${esc(x)}</span></div>`).join('')}</div><div class="study-memory"><span>ğŸ§  SINAV HAFIZASI</span><b>${esc(m.memory)}</b></div><div class="study-modal-actions"><button class="btn secondary" data-study-close>Kapat</button><button class="btn primary" data-study-events>âš¡ Sorularla pekiÅŸtir</button></div></section>`;modal.querySelectorAll('[data-study-close]').forEach(x=>x.onclick=close);modal.querySelector('[data-study-events]')?.addEventListener('click',()=>{close();document.querySelector('.nav-item[data-view="events"]')?.click()});requestAnimationFrame(()=>modal.classList.add('show'));}
function close(){const m=$('#yb75-study-modal');if(m){m.classList.remove('show');setTimeout(()=>m.remove(),180)}}
let t=null;function schedule(){clearTimeout(t);t=setTimeout(inject,80)}
document.addEventListener('yb:navigate',e=>{if(e.detail?.view==='library')setTimeout(inject,80)});new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});window.addEventListener('load',()=>setTimeout(inject,120));setTimeout(inject,350);
})();


/* ── v76-review.js ── */
/* Yurdunu Bil 76 â€” active recall mini test */
(()=>{'use strict';
if(window.__YB76_REVIEW__)return;window.__YB76_REVIEW__=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const key='yb_review_76';let quiz=null;
function saved(){try{return JSON.parse(localStorage.getItem(key)||'{"done":{},"xp":0,"streak":0}')}catch{return {done:{},xp:0,streak:0}}}
function persist(x){try{localStorage.setItem(key,JSON.stringify(x))}catch{}}
function topicFromModule(el){return el?.dataset.topic||el?.closest('[data-topic]')?.dataset.topic||el?.closest('.study-module')?.dataset.topic||''}
function injectLaunch(){
  $$('.study-module').forEach(m=>{
    if(m.querySelector('.review-launch'))return;
    const topic=m.dataset.topic||''; if(!topic)return;
    const b=document.createElement('div');b.className='review-launch';b.innerHTML=`<div class="review-launch-copy"><span>AKTÄ°F HATIRLAMA</span><b>5 soruyla pekiÅŸtir</b><small>Notu okuduktan hemen sonra mini test yap.</small></div><button class="review-launch-btn" type="button" data-review-topic="${esc(topic)}">BaÅŸla â†’</button>`;
    const open=m.querySelector('.study-open');(open||m).appendChild(b);
  });
}
function mountModal(){
  if($('#yb76-review-modal'))return;
  const d=document.createElement('div');d.id='yb76-review-modal';d.innerHTML=`<div class="review-backdrop"></div><section class="review-card" role="dialog" aria-modal="true" aria-labelledby="yb76-title"><div class="review-head"><div><span class="review-kicker">AKTÄ°F HATIRLAMA</span><h2 id="yb76-title">Mini tekrar</h2></div><button class="review-close" type="button" data-review-close>Ã—</button></div><div class="review-progress"><i></i></div><div id="yb76-body"></div></section>`;document.body.appendChild(d);
}
function topicQuestions(topic){
 const bank=Array.isArray(window.QUESTION_BANK)?window.QUESTION_BANK:[];
 const pool=bank.filter(q=>String(q.topic||'')===String(topic));
 if(pool.length>=5)return shuffle(pool).slice(0,5);
 return shuffle(bank).slice(0,5);
}
function shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function topicTitle(topic){const t=(window.TOPICS||[]).find(x=>String(x.id)===String(topic));return t?.title||'Konu TekrarÄ±'}
function open(topic){
 mountModal();quiz={topic,items:topicQuestions(topic),i:0,correct:0,answered:false};$('#yb76-review-modal').classList.add('show');document.body.classList.add('yb76-review-open');render();
}
function close(){const m=$('#yb76-review-modal');if(m)m.classList.remove('show');document.body.classList.remove('yb76-review-open');quiz=null}
function render(){
 if(!quiz)return;const q=quiz.items[quiz.i],body=$('#yb76-body'),bar=$('.review-progress i');if(!q||!body)return;
 if(bar)bar.style.width=`${Math.round((quiz.i/quiz.items.length)*100)}%`;
 body.innerHTML=`<div class="review-question"><small>Soru ${quiz.i+1} / ${quiz.items.length}</small><h3>${esc(q.q)}</h3><div class="review-options">${(q.options||[]).map((o,i)=>`<button type="button" class="review-option" data-review-answer="${i}">${esc(o)}</button>`).join('')}</div><div class="review-feedback" id="yb76-feedback"></div><button class="btn primary review-next hidden" type="button" id="yb76-next">Sonraki soru â†’</button></div>`;
 $$('.review-option',body).forEach(b=>b.addEventListener('click',()=>answer(Number(b.dataset.reviewAnswer))));
 $('#yb76-next')?.addEventListener('click',next);
}
function answer(i){if(!quiz||quiz.answered)return;quiz.answered=true;const q=quiz.items[quiz.i],ok=i===Number(q.answer);if(ok)quiz.correct++;$$('.review-option').forEach((b,n)=>{b.disabled=true;if(n===Number(q.answer))b.classList.add('correct');if(n===i&&!ok)b.classList.add('wrong')});const f=$('#yb76-feedback');if(f){f.className='review-feedback '+(ok?'good':'bad');f.textContent=ok?`âœ“ DoÄŸru! ${q.explain||'Bu bilgiyi doÄŸru hatÄ±rladÄ±n.'}`:`âœ• YanlÄ±ÅŸ. ${q.explain||'DoÄŸru seÃ§eneÄŸi tekrar et.'}`};$('#yb76-next')?.classList.remove('hidden')}
function next(){if(!quiz)return;if(quiz.i<quiz.items.length-1){quiz.i++;quiz.answered=false;render()}else finish()}
function finish(){
 const s=saved(),prev=s.done?.[quiz.topic]||0,pct=Math.round((quiz.correct/quiz.items.length)*100),xpGain=quiz.correct*10;
 const out={...s,done:{...(s.done||{}),[quiz.topic]:Math.max(prev,pct)},xp:(s.xp||0)+xpGain,streak:(quiz.correct===quiz.items.length?(s.streak||0)+1:0)};persist(out);
 const bar=$('.review-progress i');if(bar)bar.style.width='100%';
 const title=quiz.correct===5?'ğŸ”¥ MÃ¼kemmel!':quiz.correct>=4?'ğŸ’ª Ã‡ok iyi!':quiz.correct>=3?'ğŸ¯ Ä°yi gidiyor!':'ğŸ” Bir tekrar daha iyi olur.';
 $('#yb76-body').innerHTML=`<div class="review-finish"><h3>${title}</h3><p>${esc(topicTitle(quiz.topic))} mini tekrarÄ±nÄ± tamamladÄ±n. YanlÄ±ÅŸlarÄ±nÄ± ÅŸimdi yeniden okuyup hemen bir oyunla pekiÅŸtirebilirsin.</p><div class="review-score"><div><b>${quiz.correct}/5</b><span>doÄŸru</span></div><div><b>%${pct}</b><span>baÅŸarÄ±</span></div><div><b>+${xpGain} XP</b><span>kazanÄ±ldÄ±</span></div></div><button class="btn primary review-next" type="button" id="yb76-finish-close">Kapat</button></div>`;
 $('#yb76-finish-close').onclick=close;
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-review-topic]');if(b)open(b.dataset.reviewTopic)});
document.addEventListener('click',e=>{if(e.target.matches('[data-review-close],.review-backdrop'))close()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#yb76-review-modal')?.classList.contains('show'))close()});
let t=null;function schedule(){clearTimeout(t);t=setTimeout(injectLaunch,80)}
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});
document.addEventListener('yb:navigate',e=>{if(e.detail?.view==='library')setTimeout(injectLaunch,120)});
window.addEventListener('load',()=>{mountModal();setTimeout(injectLaunch,150)});
})();


/* ── v84-library-expansion.js ── */
/* Yurdunu Bil 84 â€” richer library modules */
(()=>{'use strict';if(window.__YB84_LIBRARY__)return;window.__YB84_LIBRARY__=true;
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const extras=[
{id:'x01',topic:'konum',icon:'ğŸ§®',title:'Koordinat ve TÃ¼rkiye',tag:'TEMEL',mins:8,summary:'Paralel-meridyen mantÄ±ÄŸÄ±nÄ± koordinat sorularÄ±na uygula.',points:['Paraleller enlem, meridyenler boylam bilgisini verir.','TÃ¼rkiye kuzey ve doÄŸu yarÄ±m kÃ¼relerde yer alÄ±r.'],memory:'Enlem = kuzey-gÃ¼ney; boylam = doÄŸu-batÄ±.'},
{id:'x02',topic:'konum',icon:'ğŸŒ“',title:'Yerel Saat SorularÄ±',tag:'SORU TÄ°PÄ°',mins:9,summary:'DoÄŸu-batÄ± karÅŸÄ±laÅŸtÄ±rmalarÄ±nda saat farkÄ±nÄ± hÄ±zlÄ± Ã§Ã¶z.',points:['DoÄŸuya gidildikÃ§e yerel saat ilerler.','1Â° boylam 4 dakika yerel saat farkÄ± oluÅŸturur.'],memory:'DoÄŸu ileri, batÄ± geri.'},
{id:'x03',topic:'iklim',icon:'ğŸŒ¡ï¸',title:'SÄ±caklÄ±k DaÄŸÄ±lÄ±ÅŸÄ±nÄ± Etkileyenler',tag:'YÃœKSEK GETÄ°RÄ°',mins:10,summary:'Enlem, yÃ¼kselti, denizellik ve bakÄ±yÄ± birlikte yorumla.',points:['YÃ¼kselti arttÄ±kÃ§a sÄ±caklÄ±k genel olarak azalÄ±r.','Denizler yÄ±llÄ±k sÄ±caklÄ±k farkÄ±nÄ± azaltÄ±r.'],memory:'Tek sebebe takÄ±lma: enlem + yÃ¼kselti + denizellik + bakÄ±.'},
{id:'x04',topic:'iklim',icon:'ğŸŒ§ï¸',title:'YaÄŸÄ±ÅŸ Tipleri',tag:'ORTA',mins:9,summary:'Orografik, cephe ve konveksiyonel yaÄŸÄ±ÅŸÄ± ayÄ±rt et.',points:['DaÄŸ yamacÄ±nda yÃ¼kselen nemli hava orografik yaÄŸÄ±ÅŸ oluÅŸturabilir.','IsÄ±nan havanÄ±n yÃ¼kselmesi konveksiyonel yaÄŸÄ±ÅŸÄ± destekler.'],memory:'DaÄŸ = orografik; Ä±sÄ±nma-yÃ¼kselme = konveksiyonel.'},
{id:'x05',topic:'yerseki',icon:'ğŸª¨',title:'AÅŸÄ±nÄ±m ve Birikim',tag:'TEMEL',mins:10,summary:'Akarsu ve dalga ÅŸekillerini oluÅŸum sÃ¼reciyle eÅŸleÅŸtir.',points:['Delta alÃ¼vyon birikimiyle oluÅŸur.','Falez dalga aÅŸÄ±ndÄ±rmasÄ±yla oluÅŸabilir.'],memory:'TaÅŸÄ±yan ve biriktiren sÃ¼reÃ§leri ters dÃ¼ÅŸÃ¼nme.'},
{id:'x06',topic:'yerseki',icon:'ğŸï¸',title:'Karstik Åekiller',tag:'SINAV TUZAÄI',mins:8,summary:'Kalkerli arazilerde oluÅŸan temel karstik ÅŸekilleri Ã¶ÄŸren.',points:['Dolin, uvala ve polye Ã§Ã¶zÃ¼nme sÃ¼reÃ§leriyle iliÅŸkilidir.','Obruk yer altÄ± boÅŸluklarÄ±nÄ±n Ã§Ã¶kmesiyle geliÅŸebilir.'],memory:'Karst = Ã§Ã¶zÃ¼nen kayaÃ§ + su.'},
{id:'x07',topic:'su',icon:'âš¡',title:'Akarsu ve Enerji',tag:'YÃœKSEK GETÄ°RÄ°',mins:8,summary:'EÄŸim ve akÄ±mÄ±n hidroelektrik potansiyelle iliÅŸkisini kur.',points:['EÄŸim ve su miktarÄ± arttÄ±kÃ§a enerji potansiyeli yÃ¼kselir.','DaÄŸlÄ±k alanlar bu aÃ§Ä±dan elveriÅŸli olabilir.'],memory:'HES iÃ§in su + eÄŸim Ã¶nemlidir.'},
{id:'x08',topic:'su',icon:'ğŸï¸',title:'GÃ¶l ve Havza SorularÄ±',tag:'ORTA',mins:8,summary:'AÃ§Ä±k-kapalÄ± havza ayrÄ±mÄ±nÄ± Ã¶rneklerle pekiÅŸtir.',points:['AÃ§Ä±k havzada sular bir akarsu yoluyla denize ulaÅŸabilir.','KapalÄ± havzada dÄ±ÅŸa akÄ±ÅŸ yoktur.'],memory:'Denize Ã§Ä±kÄ±ÅŸ varsa aÃ§Ä±k havza.'},
{id:'x09',topic:'nufus',icon:'ğŸ§‘â€ğŸ¤â€ğŸ§‘',title:'NÃ¼fusun DaÄŸÄ±lÄ±ÅŸÄ±nda DoÄŸal Etkenler',tag:'TEMEL',mins:9,summary:'Ä°klim, su, toprak ve yer ÅŸekillerini nÃ¼fusla baÄŸla.',points:['ElveriÅŸli iklim ve dÃ¼z araziler yerleÅŸmeyi kolaylaÅŸtÄ±rÄ±r.','Su kaynaklarÄ± yerleÅŸmelerin konumunu etkiler.'],memory:'YaÅŸanabilirlik = doÄŸal koÅŸullarÄ±n bileÅŸkesi.'},
{id:'x10',topic:'nufus',icon:'ğŸš†',title:'GÃ¶Ã§ Nedenleri ve SonuÃ§larÄ±',tag:'YÃœKSEK GETÄ°RÄ°',mins:9,summary:'Ä°tici ve Ã§ekici faktÃ¶rleri soru kÃ¶kÃ¼nde ayÄ±r.',points:['Ä°ÅŸsizlik itici, iÅŸ olanaklarÄ± Ã§ekici faktÃ¶r olabilir.','GÃ¶Ã§ alan merkezlerde altyapÄ± talebi artabilir.'],memory:'Ä°tici = gÃ¶nderen; Ã§ekici = alan.'},
{id:'x11',topic:'tarim',icon:'ğŸŒ±',title:'TarÄ±mÄ± Etkileyen DoÄŸal KoÅŸullar',tag:'TEMEL',mins:9,summary:'Ä°klim, toprak ve suyu Ã¼rÃ¼n seÃ§imiyle iliÅŸkilendir.',points:['Don riski Ã¼rÃ¼n desenini sÄ±nÄ±rlar.','Sulama kurak alanlarda Ã¼retimi artÄ±rabilir.'],memory:'ÃœrÃ¼n = iklim + toprak + su.'},
{id:'x12',topic:'tarim',icon:'ğŸ­',title:'TarÄ±m-Sanayi Ä°liÅŸkisi',tag:'ORTA',mins:8,summary:'Hammaddenin sanayiye dÃ¶nÃ¼ÅŸÃ¼mÃ¼nÃ¼ Ã¶rneklerle yorumla.',points:['Åeker pancarÄ± ÅŸeker sanayisinin hammaddesidir.','AyÃ§iÃ§eÄŸi yaÄŸ sanayisinde kullanÄ±lÄ±r.'],memory:'TarÄ±m Ã¼rÃ¼nÃ¼ â†’ iÅŸleme tesisi â†’ katma deÄŸer.'},
{id:'x13',topic:'maden',icon:'â›ï¸',title:'Maden-YerleÅŸme-Sanayi',tag:'YÃœKSEK GETÄ°RÄ°',mins:9,summary:'Madenin sanayi ve yerleÅŸme Ã¼zerindeki etkisini Ã§Ã¶z.',points:['Maden Ã§Ä±karÄ±lan yerlerde istihdam artabilir.','UlaÅŸÄ±m ve enerji olanaklarÄ± sanayinin geliÅŸimini etkiler.'],memory:'Maden tek baÅŸÄ±na yetmez: enerji + ulaÅŸÄ±m + pazar.'},
{id:'x14',topic:'maden',icon:'â˜€ï¸',title:'Yenilenebilir Enerji',tag:'TEMEL',mins:8,summary:'GÃ¼neÅŸ, rÃ¼zgÃ¢r, jeotermal ve hidroelektriÄŸi ayÄ±rt et.',points:['Jeotermal kaynaklar fay hatlarÄ±yla iliÅŸkili alanlarda yaygÄ±ndÄ±r.','GÃ¼neÅŸlenme koÅŸullarÄ± gÃ¼neÅŸ enerjisi potansiyelini etkiler.'],memory:'KaynaÄŸÄ±n doÄŸal koÅŸulunu ara.'},
{id:'x15',topic:'bolgeler',icon:'ğŸ—ºï¸',title:'BÃ¶lge KarÅŸÄ±laÅŸtÄ±rma',tag:'YÃœKSEK GETÄ°RÄ°',mins:10,summary:'Ä°ki bÃ¶lgeyi iklim, tarÄ±m, nÃ¼fus ve sanayi aÃ§Ä±sÄ±ndan kÄ±yasla.',points:['Marmara sanayi ve nÃ¼fusta Ã¶ne Ã§Ä±kar.','DoÄŸu Anadolu yÃ¼kselti ve hayvancÄ±lÄ±kta belirgindir.'],memory:'KarÅŸÄ±laÅŸtÄ±rmada tek Ã¶zellik deÄŸil, ortak tabloyu dÃ¼ÅŸÃ¼n.'},
{id:'x16',topic:'bolgeler',icon:'ğŸ›ï¸',title:'Turizm TÃ¼rleri ve AlanlarÄ±',tag:'ORTA',mins:9,summary:'Deniz, kÃ¼ltÃ¼r, kÄ±ÅŸ ve doÄŸa turizmini yerle eÅŸleÅŸtir.',points:['Akdeniz ve Ege kÄ±yÄ±larÄ± deniz turizmiyle Ã¶ne Ã§Ä±kar.','DaÄŸlÄ±k ve karlÄ± alanlar kÄ±ÅŸ turizmine elveriÅŸlidir.'],memory:'Turizm tÃ¼rÃ¼ = doÄŸal/kÃ¼ltÃ¼rel Ã§ekicilik.'}
];
function card(m){return `<article class="study-module yb84-extra-module" data-topic="${esc(m.topic)}" data-x84="1" data-x84-id="${m.id}"><div class="study-module-top"><div class="study-module-icon">${m.icon}</div><span class="study-module-tag">${esc(m.tag)}</span><span class="study-module-time">â—· ${m.mins} dk</span></div><h3>${esc(m.title)}</h3><p>${esc(m.summary)}</p><div class="study-points-preview">${m.points.map(x=>`<span>âœ“ ${esc(x)}</span>`).join('')}</div><button class="study-open yb84-open" type="button">Ã‡alÄ±ÅŸmaya baÅŸla â†’</button><div class="review-launch"><div class="review-launch-copy"><span>AKTÄ°F HATIRLAMA</span><b>5 soruyla pekiÅŸtir</b><small>Notu okuduktan sonra mini test yap.</small></div><button class="review-launch-btn" type="button" data-review-topic="${esc(m.topic)}">BaÅŸla â†’</button></div></article>`}
function mount(){const grid=$('.study-module-grid');if(!grid||grid.querySelector('[data-x84]'))return;grid.insertAdjacentHTML('beforeend',extras.map(card).join(''));updateCount();}
function updateCount(){const zone=$('.study-zone');if(!zone)return;const b=$('.study-zone-stat b',zone);if(b)b.textContent=String(32+extras.length);const p=$('.study-zone-head p',zone);if(p)p.textContent=`8 ana Ã¼nitenin altÄ±nda ${32+extras.length} kÄ±sa Ã§alÄ±ÅŸma modÃ¼lÃ¼ var. Her modÃ¼l: Ã¶zet + kilit bilgiler + sÄ±nav hafÄ±zasÄ±.`}
function openModule(id){const m=extras.find(x=>x.id===id);if(!m)return;let modal=$('#yb84-module-modal');if(!modal){modal=document.createElement('div');modal.id='yb84-module-modal';document.body.appendChild(modal)}modal.className='show';modal.innerHTML=`<div class="yb84-backdrop"></div><section class="yb84-card"><button class="yb84-close" type="button">Ã—</button><span class="yb84-kicker">${esc(m.tag)} â€¢ ${m.mins} DK</span><div class="yb84-title-row"><span>${m.icon}</span><div><h2>${esc(m.title)}</h2><p>${esc(m.summary)}</p></div></div><div class="yb84-points"><h3>Kilit bilgiler</h3>${m.points.map((x,i)=>`<div><b>${String(i+1).padStart(2,'0')}</b><span>${esc(x)}</span></div>`).join('')}</div><div class="yb84-memory"><span>SINAV HAFIZASI</span><b>${esc(m.memory)}</b></div><button class="btn primary yb84-review" data-review-topic="${esc(m.topic)}">5 soruyla pekiÅŸtir â†’</button></section></div>`;$('.yb84-backdrop',modal).onclick=closeModule;$('.yb84-close',modal).onclick=closeModule;$('.yb84-review',modal).onclick=e=>{closeModule();setTimeout(()=>{const ev=new MouseEvent('click',{bubbles:true});e.currentTarget.dispatchEvent(ev)},0)};}
function closeModule(){const m=$('#yb84-module-modal');if(m)m.classList.remove('show')}
document.addEventListener('click',e=>{const b=e.target.closest('.yb84-open');if(!b)return;const id=b.closest('[data-x84-id]')?.dataset.x84Id;if(id)openModule(id)});
document.addEventListener('yb:navigate',e=>{if(e.detail?.view==='library')setTimeout(mount,180)});window.addEventListener('load',()=>setTimeout(mount,600));new MutationObserver(()=>setTimeout(mount,100)).observe(document.body,{childList:true,subtree:true});
window.YB84Library={count:()=>32+extras.length};
})();


/* ── v87-library-deepening.js ── */
/* Yurdunu Bil 87 â€” deeper library modules */
(()=>{'use strict';if(window.__YB87_LIBRARY__)return;window.__YB87_LIBRARY__=true;const $=(s,r=document)=>r.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const extras=[
['z01','konum','ğŸ§­','Paralel SorularÄ±','SINAV TÄ°PÄ°',8,'Enlem karÅŸÄ±laÅŸtÄ±rmalarÄ±nÄ± tablo gibi Ã§Ã¶z.',['Paralel deÄŸerleri kuzeye gittikÃ§e bÃ¼yÃ¼r.','AynÄ± paralelde yer alan noktalarÄ±n enlemleri aynÄ±dÄ±r.'],'Paralel = enlem.'],
['z02','konum','ğŸ•“','Meridyen SorularÄ±','YÃœKSEK GETÄ°RÄ°',8,'Boylam farkÄ±nÄ± yerel saatle eÅŸleÅŸtir.',['Meridyenler kutuplarda birleÅŸir.','AynÄ± meridyen Ã¼zerinde yerel saat aynÄ±dÄ±r.'],'Meridyen = boylam = saat.'],
['z03','konum','ğŸ§©','Matematik mi Ã–zel mi?','SINAV TUZAÄI',7,'Bir sonuÃ§ cÃ¼mlesinin hangi konumdan Ã§Ä±ktÄ±ÄŸÄ±nÄ± ayÄ±r.',['Enlem-boylam sonuÃ§larÄ± matematik konumdur.','BoÄŸazlar ve kÄ±talar arasÄ± geÃ§iÅŸ Ã¶zel konumla iliÅŸkilidir.'],'Koordinat = matematik; Ã§evresel avantaj = Ã¶zel.'],
['z04','iklim','â˜€ï¸','BakÄ± ve GÃ¼neÅŸlenme','SINAV TÄ°PÄ°',8,'Kuzey yarÄ±m kÃ¼rede bakÄ± yÃ¶nÃ¼nÃ¼ yorumla.',['GÃ¼neye bakan yamaÃ§lar genel olarak daha fazla gÃ¼neÅŸ alÄ±r.','BakÄ± sÄ±caklÄ±k ve tarÄ±msal Ã¼rÃ¼nlerin olgunlaÅŸmasÄ±nÄ± etkileyebilir.'],'BakÄ± = gÃ¼neÅŸe dÃ¶nÃ¼klÃ¼k.'],
['z05','iklim','ğŸ’¦','Nem ve BuharlaÅŸma','ORTA',8,'Nemlilik ile buharlaÅŸma iliÅŸkisini kavra.',['Nem arttÄ±kÃ§a gerÃ§ek ve maksimum nem arasÄ±ndaki fark deÄŸiÅŸir.','Kurak alanlarda potansiyel buharlaÅŸma yÃ¼ksektir.'],'KuraklÄ±k = yÃ¼ksek buharlaÅŸma baskÄ±sÄ±.'],
['z06','iklim','ğŸŒ¬ï¸','RÃ¼zgÃ¢r ve BasÄ±nÃ§','TEMEL',7,'BasÄ±nÃ§ farkÄ±ndan rÃ¼zgÃ¢r yÃ¶nÃ¼nÃ¼ Ã§Ä±kar.',['RÃ¼zgÃ¢r yÃ¼ksek basÄ±nÃ§tan alÃ§ak basÄ±nca doÄŸru eser.','BasÄ±nÃ§ farkÄ± arttÄ±kÃ§a rÃ¼zgÃ¢r hÄ±zÄ± artabilir.'],'RÃ¼zgÃ¢r = basÄ±nÃ§ farkÄ±.'],
['z07','yerseki','ğŸ”ï¸','DaÄŸlarÄ±n UzanÄ±ÅŸÄ±','YÃœKSEK GETÄ°RÄ°',8,'DaÄŸlarÄ±n uzanÄ±ÅŸÄ±nÄ±n iklim ve ulaÅŸÄ±m etkisini Ã§Ã¶z.',['KÄ±yÄ±ya paralel daÄŸlar deniz etkisinin iÃ§eri girmesini sÄ±nÄ±rlar.','KÄ±yÄ±ya dik uzanÄ±ÅŸ ulaÅŸÄ±mÄ± bazÄ± kesimlerde kolaylaÅŸtÄ±rabilir.'],'UzanÄ±ÅŸ = iklim + ulaÅŸÄ±m.'],
['z08','yerseki','ğŸª¨','Toprak Erozyonu','YÃœKSEK GETÄ°RÄ°',9,'Erozyonun neden ve sonuÃ§larÄ±nÄ± baÄŸla.',['Bitki Ã¶rtÃ¼sÃ¼nÃ¼n zayÄ±f olduÄŸu eÄŸimli alanlarda erozyon artabilir.','AÄŸaÃ§landÄ±rma ve teraslama erozyonu azaltabilir.'],'EÄŸim + Ã§Ä±plak yÃ¼zey = erozyon.'],
['z09','su','ğŸŒ§ï¸','Su Rejimi Yorumlama','SINAV TÄ°PÄ°',8,'Akarsu grafiÄŸinden mevsimsel yaÄŸÄ±ÅŸ ipucu Ã§Ä±kar.',['AkÄ±mÄ±n yÄ±l iÃ§indeki deÄŸiÅŸimi rejimi gÃ¶sterir.','Kar erimeleri ilkbahar-yaz dÃ¶neminde akÄ±mÄ± artÄ±rabilir.'],'Grafikte pik mevsimi yakala.'],
['z10','su','ğŸ—ï¸','BarajlarÄ±n SonuÃ§larÄ±','ORTA',8,'BarajÄ±n enerji, sulama ve ulaÅŸÄ±m etkilerini birlikte deÄŸerlendir.',['Barajlar hidroelektrik enerji Ã¼retimini destekleyebilir.','Sulama alanÄ±nÄ± geniÅŸletebilir; ancak bazÄ± doÄŸal sistemleri deÄŸiÅŸtirebilir.'],'Baraj = enerji + sulama + su yÃ¶netimi.'],
['z11','nufus','ğŸ§®','Aritmetik NÃ¼fus YoÄŸunluÄŸu','TEMEL',7,'YoÄŸunluk hesaplamasÄ±nÄ± soru iÃ§inde hÄ±zlÄ± uygula.',['Aritmetik yoÄŸunluk toplam nÃ¼fusun yÃ¼zÃ¶lÃ§Ã¼mÃ¼ne oranÄ±dÄ±r.','YÃ¼zÃ¶lÃ§Ã¼mÃ¼ bÃ¼yÃ¼dÃ¼kÃ§e aynÄ± nÃ¼fus daha dÃ¼ÅŸÃ¼k yoÄŸunluk verir.'],'KiÅŸi / kmÂ².'],
['z12','nufus','ğŸ‘¨â€ğŸ‘©â€ğŸ‘§','NÃ¼fusun YapÄ±sÄ±','ORTA',9,'YaÅŸ ve cinsiyet yapÄ±sÄ±nÄ±n ekonomik sonuÃ§larÄ±nÄ± yorumla.',['GenÃ§ nÃ¼fus oranÄ± yÃ¼ksek alanlarda eÄŸitim ve istihdam ihtiyacÄ± artabilir.','YaÅŸlÄ± nÃ¼fus oranÄ± yÃ¼kseldikÃ§e saÄŸlÄ±k ve sosyal hizmet ihtiyacÄ± artabilir.'],'NÃ¼fus piramidi = gelecek planÄ±.'],
['z13','tarim','ğŸšœ','TarÄ±mda Verimlilik','YÃœKSEK GETÄ°RÄ°',9,'Ãœretim miktarÄ± ile verim arasÄ±ndaki farkÄ± ayÄ±r.',['Verim birim alandan alÄ±nan Ã¼rÃ¼n miktarÄ±yla ilgilidir.','Sulama, gÃ¼breleme ve tohum Ä±slahÄ± verimi artÄ±rabilir.'],'Verim = birim alan Ã§Ä±ktÄ±sÄ±.'],
['z14','tarim','ğŸŒ½','ÃœrÃ¼n-Ä°klim EÅŸleÅŸtirme','SINAV TÄ°PÄ°',8,'ÃœrÃ¼nÃ¼ Ã¶zelliklerinden yakala.',['Ã‡ay nemli ve yaÄŸÄ±ÅŸlÄ± koÅŸullarÄ± ister.','Zeytin Ä±lÄ±k kÄ±ÅŸ koÅŸullarÄ±nÄ± sever.'],'Ã–nce Ã¼rÃ¼nÃ¼n istediÄŸi iklimi dÃ¼ÅŸÃ¼n.'],
['z15','maden','âš™ï¸','Sanayi KuruluÅŸ FaktÃ¶rleri','YÃœKSEK GETÄ°RÄ°',10,'Hammadde, enerji, ulaÅŸÄ±m, pazar ve iÅŸ gÃ¼cÃ¼nÃ¼ birlikte deÄŸerlendir.',['Sanayinin kuruluÅŸunda tek bir faktÃ¶r belirleyici deÄŸildir.','AÄŸÄ±r sanayide hammadde ve enerji maliyetleri Ã¶nem kazanabilir.'],'Sanayi = hammadde + enerji + ulaÅŸÄ±m + pazar + iÅŸ gÃ¼cÃ¼.'],
['z16','bolgeler','ğŸ“','BÃ¶lgesel Ekonomik Ã–zet','YÃœKSEK GETÄ°RÄ°',10,'BÃ¶lgeyi tek ezber yerine faaliyet deseniyle tanÄ±.',['Marmara sanayi, ticaret ve nÃ¼fus yoÄŸunluÄŸunda Ã¶ne Ã§Ä±kar.','DoÄŸu Anadolu yÃ¼ksek yÃ¼kselti ve hayvancÄ±lÄ±k Ã¶zellikleriyle ayrÄ±lÄ±r.'],'BÃ¶lgeyi 3 ana ipucuyla tanÄ±.']
];
function card(m){return `<article class="study-module yb87-module" data-topic="${m[1]}" data-z87="1"><div class="study-module-top"><div class="study-module-icon">${m[2]}</div><span class="study-module-tag">${esc(m[4])}</span><span class="study-module-time">â—· ${m[5]} dk</span></div><h3>${esc(m[3])}</h3><p>${esc(m[6])}</p><div class="study-points-preview">${m[7].map(x=>`<span>âœ“ ${esc(x)}</span>`).join('')}</div><button class="study-open yb87-open" type="button" data-z87-id="${m[0]}">Ã‡alÄ±ÅŸmaya baÅŸla â†’</button><div class="review-launch"><div class="review-launch-copy"><span>AKTÄ°F HATIRLAMA</span><b>5 soruyla pekiÅŸtir</b><small>Notu okuduktan sonra mini test yap.</small></div><button class="review-launch-btn" type="button" data-review-topic="${esc(m[1])}">BaÅŸla â†’</button></div></article>`}
function mount(){const grid=$('.study-module-grid');if(!grid||grid.querySelector('[data-z87]'))return;grid.insertAdjacentHTML('beforeend',extras.map(card).join(''));const st=$('.study-zone-stat b');if(st)st.textContent=String(48+extras.length);const p=$('.study-zone-head p');if(p)p.textContent=`8 ana Ã¼nitenin altÄ±nda ${48+extras.length} kÄ±sa Ã§alÄ±ÅŸma modÃ¼lÃ¼ var. Her modÃ¼l: Ã¶zet + kilit bilgiler + sÄ±nav hafÄ±zasÄ±.`}
function open(id){const m=extras.find(x=>x[0]===id);if(!m)return;let root=$('#yb87-module-modal');if(!root){root=document.createElement('div');root.id='yb87-module-modal';document.body.appendChild(root)}root.className='show';root.innerHTML=`<div class="yb87-backdrop"></div><section class="yb87-modal"><button type="button" class="yb87-close">Ã—</button><span class="yb87-kicker">${esc(m[4])} â€¢ ${m[5]} DK</span><div class="yb87-title"><span>${m[2]}</span><div><h2>${esc(m[3])}</h2><p>${esc(m[6])}</p></div></div><h3>Kilit bilgiler</h3><div class="yb87-list">${m[7].map((x,i)=>`<div><b>${String(i+1).padStart(2,'0')}</b><span>${esc(x)}</span></div>`).join('')}</div><div class="yb87-memory"><span>SINAV HAFIZASI</span><b>${esc(m[8])}</b></div><button class="btn primary" data-review-topic="${esc(m[1])}">5 soruyla pekiÅŸtir â†’</button></section></div>`;$('.yb87-backdrop',root).onclick=close;$('.yb87-close',root).onclick=close;root.querySelector('[data-review-topic]').onclick=()=>{close();document.querySelector(`[data-review-topic="${CSS.escape(m[1])}"]`)?.click()}}
function close(){const x=$('#yb87-module-modal');if(x)x.classList.remove('show')}
document.addEventListener('click',e=>{const b=e.target.closest('.yb87-open');if(b)open(b.dataset.z87Id)});
document.addEventListener('yb:navigate',e=>{if(e.detail?.view==='library')setTimeout(mount,150)});window.addEventListener('load',()=>setTimeout(mount,500));
})();


/* ── v88-question-center.js ── */
/* Yurdunu Bil 88 â€” adaptive question center */
(()=>{'use strict';
if(window.__YB88_QUESTION_CENTER__)return;window.__YB88_QUESTION_CENTER__=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const topics={konum:'CoÄŸrafi Konum',iklim:'Ä°klim ve Bitki Ã–rtÃ¼sÃ¼',yerseki:'YerÅŸekilleri',su:'Su KaynaklarÄ±',nufus:'NÃ¼fus ve YerleÅŸme',tarim:'TarÄ±m ve HayvancÄ±lÄ±k',maden:'Madenler ve Enerji',bolgeler:'BÃ¶lgeler ve Turizm'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function bank(){return Array.isArray(window.QUESTION_BANK)?window.QUESTION_BANK.filter(x=>x&&x.q&&Array.isArray(x.options)):[]}
function read(){try{return JSON.parse(localStorage.getItem('yb88_question_center')||'{}')}catch{return {wrong:[],bookmarks:[],attempts:0,correct:0}}}
function write(x){try{localStorage.setItem('yb88_question_center',JSON.stringify(x))}catch{}}
function render(){const v=$('#view-library');if(!v||!v.classList.contains('active')||$('.yb88-question-center',v))return;const b=bank(),s=read();v.insertAdjacentHTML('afterbegin',`<section class="yb88-question-center"><div class="yb88-qc-head"><div><span>YENÄ° â€¢ SORU MERKEZÄ°</span><h2>Soru bankasÄ±nÄ± istediÄŸin gibi Ã§alÄ±ÅŸ.</h2><p>${b.length} soruyu konu, alt konu ve zorluk Ã¼zerinden filtrele. YanlÄ±ÅŸlarÄ±n otomatik olarak tekrar listesine alÄ±nÄ±r.</p></div><div class="yb88-qc-stats"><div><b class="yb88-count">${b.length}</b><span>SORU</span></div><div><b>${s.wrong?.length||0}</b><span>YANLIÅ</span></div><div><b>${s.bookmarks?.length||0}</b><span>KAYITLI</span></div></div></div><div class="yb88-qc-controls"><label><span>Konu</span><select id="yb88-topic"><option value="all">TÃ¼m konular</option>${Object.entries(topics).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label><span>Zorluk</span><select id="yb88-diff"><option value="all">TÃ¼m seviyeler</option><option value="kolay">Kolay</option><option value="orta">Orta</option><option value="zor">Zor</option></select></label><label class="yb88-qc-search"><span>Ara</span><input id="yb88-search" placeholder="Kavram veya soru ara..."></label><button class="btn primary" id="yb88-start-quick" type="button">10 Soruluk Test â†’</button><button class="btn secondary" id="yb88-start-wrong" type="button">YanlÄ±ÅŸlarÄ±mÄ± Ã‡Ã¶z</button></div><div class="yb88-qc-note"><span>ğŸ§ </span><b>AkÄ±llÄ± tekrar:</b><span>YanlÄ±ÅŸ yaptÄ±ÄŸÄ±n sorular bir sonraki tekrarÄ±nda Ã¶ncelik kazanÄ±r.</span></div></section>`);bind();}
function filtered(mode='all'){const b=bank();const t=$('#yb88-topic')?.value||'all',d=$('#yb88-diff')?.value||'all',term=($('#yb88-search')?.value||'').trim().toLocaleLowerCase('tr-TR');let out=b.filter(q=>(t==='all'||q.topic===t)&&(d==='all'||q.difficulty===d)&&(!term||`${q.q} ${(q.subtopic||'')} ${q.options.join(' ')}`.toLocaleLowerCase('tr-TR').includes(term)));if(mode==='wrong'){const s=read(),set=new Set(s.wrong||[]);out=out.filter(q=>set.has(q.id))}return out;}
function openQuiz(list,title){if(!list.length){toast('Bu filtrede soru bulunamadÄ±.');return}let pool=list.slice();for(let i=pool.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]]}pool=pool.slice(0,Math.min(10,pool.length));let i=0,score=0,answered=false;let root=$('#yb88-quiz');if(!root){root=document.createElement('div');root.id='yb88-quiz';document.body.appendChild(root)}const state=read();root.className='show';const draw=()=>{if(i>=pool.length){state.attempts=Number(state.attempts||0)+1;write(state);root.innerHTML=`<div class="yb88-q-backdrop"></div><section class="yb88-q-modal yb88-result"><span class="yb88-kicker">TEST TAMAMLANDI</span><div class="yb88-result-score"><b>${score}/${pool.length}</b><span>doÄŸru</span></div><h2>${score>=8?'Ã‡ok iyi! ğŸ”¥':score>=5?'GÃ¼zel gidiyor. ğŸ’ª':'Bir tekrar turu daha iyi olur.'}</h2><p>${score>=8?'Konunun mantÄ±ÄŸÄ±nÄ± yakalamÄ±ÅŸsÄ±n.':score>=5?'YanlÄ±ÅŸlarÄ±nÄ± tekrar et ve bir tur daha dene.':'YanlÄ±ÅŸlarÄ±nÄ± listeye aldÄ±k; bir sonraki turda onlarÄ± Ã¶nceliklendirebilirsin.'}</p><div class="yb88-q-actions"><button class="btn primary" data-q-retry>Tekrar Ã‡Ã¶z</button><button class="btn secondary" data-q-close>Kapat</button></div></section>`;root.querySelector('[data-q-retry]').onclick=()=>openQuiz(pool,title);root.querySelector('[data-q-close]').onclick=close;return}const q=pool[i];answered=false;root.innerHTML=`<div class="yb88-q-backdrop"></div><section class="yb88-q-modal"><button class="yb88-q-close" type="button">Ã—</button><div class="yb88-q-top"><span>${i+1}/${pool.length}</span><span>${esc(topics[q.topic]||q.topic||'CoÄŸrafya')} Â· ${esc(q.difficulty||'orta')}</span></div><div class="yb88-q-progress"><i style="width:${(i/pool.length)*100}%"></i></div><span class="yb88-q-sub">${esc(q.subtopic||'Soru')}</span><h2>${esc(q.q)}</h2><div class="yb88-options">${q.options.map((o,n)=>`<button type="button" data-answer="${n}">${String.fromCharCode(65+n)} <span>${esc(o)}</span></button>`).join('')}</div><div class="yb88-feedback" hidden></div><button class="btn primary yb88-next" type="button" disabled>Sonraki soru â†’</button></section>`;root.querySelector('.yb88-q-close').onclick=close;$$('[data-answer]',root).forEach(btn=>btn.onclick=()=>answer(q,Number(btn.dataset.answer),root));root.querySelector('.yb88-next').onclick=()=>{i++;draw()};};
function answer(q,n,root){if(answered)return;answered=true;const s=read(),correct=n===Number(q.answer),wrong=new Set(s.wrong||[]);if(correct){score++;s.correct=Number(s.correct||0)+1;wrong.delete(q.id)}else wrong.add(q.id);s.wrong=[...wrong];write(s);$$('[data-answer]',root).forEach(b=>{b.disabled=true;const x=Number(b.dataset.answer);b.classList.toggle('correct',x===Number(q.answer));b.classList.toggle('wrong',x===n&&!correct)});const fb=$('.yb88-feedback',root);fb.hidden=false;fb.innerHTML=correct?`<b>DoÄŸru! âœ“</b><span>${esc(q.explain||'GÃ¼zel.')}</span>`:`<b>YanlÄ±ÅŸ.</b><span>${esc(q.explain||'DoÄŸru cevabÄ± tekrar incele.')}</span>`;root.querySelector('.yb88-next').disabled=false}
function close(){const x=$('#yb88-quiz');if(x)x.classList.remove('show')}
function toast(msg){let t=$('#toast-root');if(!t)return;const x=document.createElement('div');x.className='toast';x.textContent=msg;t.appendChild(x);setTimeout(()=>x.remove(),2400)}
function bind(){['yb88-topic','yb88-diff','yb88-search'].forEach(id=>$('#'+id)?.addEventListener(id==='yb88-search'?'input':'change',()=>{const n=$('.yb88-qc-note');if(n)n.dataset.filtered=String(filtered().length)}));$('#yb88-start-quick')?.addEventListener('click',()=>openQuiz(filtered(),'HÄ±zlÄ± Test'));$('#yb88-start-wrong')?.addEventListener('click',()=>openQuiz(filtered('wrong'),'YanlÄ±ÅŸlarÄ±m'));}
document.addEventListener('yb:navigate',e=>{if(e.detail?.view==='library')setTimeout(render,100)});window.addEventListener('load',()=>setTimeout(render,500));
window.YB88QuestionCenter={openQuiz:(mode='all')=>{
  if(Array.isArray(mode)){openQuiz(mode,'Konu Testi');return}
  openQuiz(mode==='wrong'?filtered('wrong'):filtered(),mode==='wrong'?'YanlÄ±ÅŸlarÄ±m':'HÄ±zlÄ± Test')
}};
})();

