/* Yurdunu Bil — Notifications v2: bildirim merkezi + canlı olaylar */
(()=>{
'use strict';
if(window.__YB_NOTIF__)return;window.__YB_NOTIF__=true;
const KEY='yb_notifications_v2';let sb=null,uid=null,channel=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return {items:Array.isArray(x.items)?x.items:[],unread:Number(x.unread)||0}}catch{return {items:[],unread:0}}}
function write(x){try{localStorage.setItem(KEY,JSON.stringify(x))}catch{}}
function showToast(n){let c=document.getElementById('yb-notif-container');if(!c){c=document.createElement('div');c.id='yb-notif-container';document.body.appendChild(c)}const e=document.createElement('div');e.className=`yb-notif yb-notif-${n.type||'info'} yb-notif-show`;e.innerHTML=`<div class="yb-notif-icon">${esc(n.icon||'🔔')}</div><div class="yb-notif-body"><b>${esc(n.title)}</b><span>${esc(n.body)}</span></div><button class="yb-notif-close" type="button">×</button>`;c.appendChild(e);e.querySelector('button').onclick=()=>e.remove();setTimeout(()=>e.remove(),7000)}
function add(n,toast=true){const d=read(),item={id:n.id||crypto.randomUUID?.()||String(Date.now()),title:n.title||'Yurdunu Bil',body:n.body||'',icon:n.icon||'🔔',type:n.type||'info',createdAt:new Date().toISOString(),read:false};d.items=[item,...d.items].slice(0,50);d.unread++;write(d);updateBadge();if(toast)showToast(item);return item}
function updateBadge(){const d=read();document.querySelectorAll('[data-yb-notif-badge]').forEach(e=>{e.textContent=d.unread>99?'99+':String(d.unread);e.hidden=d.unread<1})}
function openCenter(){let old=document.getElementById('yb-notif-center');if(old){old.remove();return}const w=document.createElement('div');w.id='yb-notif-center';const d=read();w.innerHTML=`<div class="yb-notif-center-backdrop"></div><section class="yb-notif-center-card"><header><div><span class="eyebrow">🔔 BİLDİRİMLER</span><h2>Bildirim Merkezi</h2></div><button id="yb-notif-close" class="icon-btn">×</button></header><div class="yb-notif-center-actions"><button class="btn ghost" id="yb-notif-read">Tümünü okundu işaretle</button><button class="btn ghost" id="yb-notif-clear">Temizle</button></div><div class="yb-notif-center-list">${d.items.length?d.items.map(x=>`<article class="yb-notif-center-item ${x.read?'':'unread'}"><span>${esc(x.icon)}</span><div><b>${esc(x.title)}</b><p>${esc(x.body)}</p><small>${new Date(x.createdAt).toLocaleString('tr-TR')}</small></div></article>`).join(''):'<div class="yb-notif-empty">Henüz bildirimin yok. Yeni bir Arena daveti, başarı veya önemli gelişme olduğunda burada görünecek.</div>'}</div></section>`;document.body.appendChild(w);w.querySelector('#yb-notif-close').onclick=()=>w.remove();w.querySelector('.yb-notif-center-backdrop').onclick=()=>w.remove();w.querySelector('#yb-notif-read').onclick=()=>{const x=read();x.items=x.items.map(i=>({...i,read:true}));x.unread=0;write(x);updateBadge();openCenter()};w.querySelector('#yb-notif-clear').onclick=()=>{write({items:[],unread:0});updateBadge();openCenter()}}
async function initRealtime(){try{const cfg=window.YURDUNUBIL_CONFIG||{};if(!cfg.SUPABASE_URL||!cfg.SUPABASE_PUBLISHABLE_KEY||!window.supabase)return;sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);const {data}=await sb.auth.getSession();uid=data?.session?.user?.id;if(!uid)return;channel=sb.channel('yb-user-notifications-'+uid).on('postgres_changes',{event:'INSERT',schema:'public',table:'arena_invites',filter:`invitee_id=eq.${uid}`},p=>add({title:'⚔️ Arena daveti',body:`${p.new.inviter_name||'Bir kullanıcı'} seni Arena'ya çağırdı.`,icon:'⚔️',type:'arena'})).on('postgres_changes',{event:'INSERT',schema:'public',table:'friend_requests',filter:`target_id=eq.${uid}`},p=>add({title:'👥 Yeni arkadaşlık isteği',body:`${p.new.sender_name||'Bir kullanıcı'} sana arkadaşlık isteği gönderdi.`,icon:'👥',type:'friend'})).subscribe()}catch(e){console.warn('notification realtime',e)}}
function requestPush(){if(!('Notification' in window)||Notification.permission!=='default')return Promise.resolve(Notification.permission==='granted');return Notification.requestPermission().then(x=>x==='granted').catch(()=>false)}
function pushNotif(title,body){if(Notification?.permission==='granted')try{new Notification(title,{body,icon:'/icon-192.svg'})}catch{}}
window.addEventListener('yb:game-complete',e=>{const x=e.detail||{};if(Number(x.correct)>=Math.ceil(Number(x.total||0)*.8))add({title:'🏆 Harika sonuç!',body:`${x.mode||'Oyun'}: ${x.correct}/${x.total} doğru · ${x.score||0} puan`,icon:'🏆',type:'success'})});
window.addEventListener('yb:onboarding-done',()=>setTimeout(requestPush,400));window.addEventListener('load',()=>{updateBadge();setTimeout(initRealtime,1800)});window.addEventListener('yb:profile-set',()=>{setTimeout(initRealtime,200)});
window.YBNotif={show:(o)=>add(o,true),add,dismiss:e=>e?.remove?.(),openCenter,requestPush,pushNotif,arenaInvite:(name,code)=>add({title:'⚔️ Arena daveti',body:`${name||'Bir kullanıcı'} seni düelloya çağırıyor. Oda: ${code||'—'}`,icon:'⚔️',type:'arena'}),friendRequest:name=>add({title:'👥 Arkadaşlık isteği',body:`${name||'Bir kullanıcı'} sana istek gönderdi.`,icon:'👥',type:'friend'})};
})();