/* Yurdunu Bil — Onboarding v2: kalıcı profil */
(()=>{
'use strict';
if(window.__YB_ONBOARDING__)return;window.__YB_ONBOARDING__=true;
const STORAGE_KEY='yb_onboarding_done',PROFILE_KEY='yb_profile_v1';
const AVATARS=[{id:'harita',emoji:'🗺️',label:'Haritacı'},{id:'pusola',emoji:'🧭',label:'Pusulacı'},{id:'dag',emoji:'⛰️',label:'Dağcı'},{id:'su',emoji:'💧',label:'Su Bilgini'},{id:'kitap',emoji:'📚',label:'Kitap Kurdu'},{id:'yildiz',emoji:'⭐',label:'Yıldız Aday'},{id:'roket',emoji:'🚀',label:'Roketçi'},{id:'kalkan',emoji:'🛡️',label:'Şampiyon'},{id:'lens',emoji:'🔍',label:'Araştırmacı'},{id:'kupa',emoji:'🏆',label:'Kupacı'},{id:'fener',emoji:'🔦',label:'Kaşif'},{id:'bey',emoji:'♟️',label:'Stratejist'}];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function getProfile(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'{}')}catch{return {}}}
function saveProfile(p){try{localStorage.setItem(PROFILE_KEY,JSON.stringify(p))}catch{}}
function applyProfile(p){if(!p?.username)return;saveProfile(p);localStorage.setItem(STORAGE_KEY,'1');const s=window.YURDUNUBIL_STATE;if(s){s.profile=s.profile||{};s.profile.displayName=p.username;s.profile.avatarEmoji=p.avatarEmoji;s.profile.avatarId=p.avatarId;try{localStorage.setItem('yb_state_70',JSON.stringify(s))}catch{}}window.dispatchEvent(new CustomEvent('yb:profile-set',{detail:p}));}
async function hydrateFromSupabase(){try{const cfg=window.YURDUNUBIL_CONFIG||{};if(!cfg.SUPABASE_URL||!cfg.SUPABASE_PUBLISHABLE_KEY||!window.supabase)return false;const sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);const {data}=await sb.auth.getSession();const uid=data?.session?.user?.id;if(!uid)return false;const {data:p,error}=await sb.from('profiles').select('id,display_name,avatar_id,avatar_emoji').eq('id',uid).maybeSingle();if(error||!p?.display_name)return false;const av=AVATARS.find(a=>a.id===p.avatar_id);applyProfile({username:p.display_name,avatarId:p.avatar_id||av?.id||'pusola',avatarEmoji:p.avatar_emoji||av?.emoji||'🧭',avatarLabel:av?.label||'Pusulacı',updatedAt:new Date().toISOString()});return true}catch(e){console.warn('profile hydrate',e);return false}}
function needsOnboarding(){const p=getProfile();return !p.username||!p.avatarId}
function open(){if(!needsOnboarding())return;const old=document.getElementById('yb-onboarding');if(old)return;const w=document.createElement('div');w.id='yb-onboarding';w.innerHTML=`<div class="yb-ob-backdrop"></div><section class="yb-ob-card" role="dialog" aria-modal="true"><div class="yb-ob-step" id="yb-ob-step1"><div class="yb-ob-logo">⌖</div><span class="eyebrow">YURDUNU BİL'E HOŞ GELDİN</span><h2>Sana nasıl seslenelim?</h2><p>Arena ve sıralamada görünecek kullanıcı adını seç.</p><div class="yb-ob-name-wrap"><input id="yb-ob-name" type="text" maxlength="20" placeholder="Kullanıcı adın (maks 20 karakter)" autocomplete="off"><span class="yb-ob-name-count" id="yb-ob-name-count">0/20</span></div><div id="yb-ob-name-err" class="yb-ob-err"></div><button class="btn primary yb-ob-next" id="yb-ob-to-avatar">Avatarımı Seç →</button></div><div class="yb-ob-step hidden" id="yb-ob-step2"><span class="eyebrow">2. ADIM</span><h2>Avatarını seç.</h2><p>Profilinde ve Arena'da görünecek.</p><div class="yb-ob-avatar-grid" id="yb-ob-avatar-grid">${AVATARS.map(a=>`<button type="button" class="yb-ob-av-btn" data-av="${a.id}"><span class="yb-ob-av-emoji">${a.emoji}</span><small>${a.label}</small></button>`).join('')}</div><div class="yb-ob-step2-actions"><button class="btn ghost" id="yb-ob-back">← Geri</button><button class="btn primary" id="yb-ob-finish" disabled>Başlayalım! 🚀</button></div></div></section>`;document.body.appendChild(w);requestAnimationFrame(()=>w.classList.add('yb-ob-visible'));let av=null;const name=w.querySelector('#yb-ob-name');name?.addEventListener('input',()=>w.querySelector('#yb-ob-name-count').textContent=`${name.value.length}/20`);w.querySelector('#yb-ob-to-avatar').onclick=()=>{if(name.value.trim().length<2){w.querySelector('#yb-ob-name-err').textContent='En az 2 karakter yazmalısın.';return}w.querySelector('#yb-ob-step1').classList.add('hidden');w.querySelector('#yb-ob-step2').classList.remove('hidden')};w.querySelector('#yb-ob-back').onclick=()=>{w.querySelector('#yb-ob-step2').classList.add('hidden');w.querySelector('#yb-ob-step1').classList.remove('hidden')};w.querySelectorAll('.yb-ob-av-btn').forEach(b=>b.onclick=()=>{w.querySelectorAll('.yb-ob-av-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');av=b.dataset.av;w.querySelector('#yb-ob-finish').disabled=false});w.querySelector('#yb-ob-finish').onclick=async()=>{const a=AVATARS.find(x=>x.id===av)||AVATARS[0],p={username:name.value.trim(),avatarId:a.id,avatarEmoji:a.emoji,avatarLabel:a.label,createdAt:new Date().toISOString()};applyProfile(p);await saveSupabase(p);w.classList.remove('yb-ob-visible');setTimeout(()=>w.remove(),350);window.dispatchEvent(new CustomEvent('yb:onboarding-done'))};}
async function saveSupabase(p){try{const cfg=window.YURDUNUBIL_CONFIG||{};if(!cfg.SUPABASE_URL||!cfg.SUPABASE_PUBLISHABLE_KEY||!window.supabase)return;const sb=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);const {data}=await sb.auth.getSession();const uid=data?.session?.user?.id;if(!uid)return;await sb.from('profiles').upsert({id:uid,display_name:p.username,avatar_id:p.avatarId,avatar_emoji:p.avatarEmoji},{onConflict:'id'})}catch(e){console.warn('profile save',e)}}
window.YBOnboarding={open,getProfile,getAvatarEmoji:()=>getProfile().avatarEmoji||'🧭',getUsername:()=>getProfile().username||window.YURDUNUBIL_STATE?.profile?.displayName||'Öğrenci',hydrateFromSupabase,reset:()=>{localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(PROFILE_KEY)}};
window.addEventListener('yb:app-ready',()=>setTimeout(open,700));window.addEventListener('load',async()=>{await hydrateFromSupabase();if(document.getElementById('app-shell')&&!document.getElementById('app-shell').classList.contains('hidden'))setTimeout(open,700)});
})();