/* Yurdunu Bil 39 — navigation resilience; Leaflet is the only atlas */
(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s);
function dashboard(){const v=$('#view-dashboard');if(!v||v.querySelector('.v30-start'))return;const live=$('#live-stats');if(live)live.style.display='none';const lower=$('.dashboard-lower',v);if(!lower)return;const q=(window.QUESTION_BANK||[]).length;lower.innerHTML=`<section class="surface v30-start"><div><span class="eyebrow">KPSS COĞRAFYA • HIZLI BAŞLANGIÇ</span><h2>Önce yurdu tanı, sonra soruya dön.</h2><p>Haritada gördüğün bilgiyi kısa notla pekiştir ve hemen KPSS tipi soruyla ölç.</p></div><div class="v30-start-grid"><button data-view="map"><b>🗺️ Türkiye Atlasını aç</b><small>Tek harita • Leaflet + gerçek kıyı, göl ve akarsu altlığı + KPSS katmanları</small></button><button data-view="topics"><b>📚 Konu çalış</b><small>KPSS odaklı kısa anlatımlar ve görsel tekrar</small></button><button data-view="provinceStudy"><b>📍 İlleri tanı</b><small>81 ilin coğrafya özelliklerini tek kartta incele</small></button><button data-view="quiz"><b>🎯 Test çöz</b><small>${q} soruluk havuzdan kendi testini oluştur</small></button></div></section>`}
function settings(){const v=$('#view-settings');if(!v||v.querySelector('.v30-settings-grid'))return;let p={};try{p=JSON.parse(localStorage.getItem('yb_state_25')||'{}').profile||{}}catch{}const name=p.displayName||'KPSS Öğrencisi',light=document.body.classList.contains('light'),labels=localStorage.getItem('yb30_labels')!=='0',compact=localStorage.getItem('yb30_compact')==='1',q=(window.QUESTION_BANK||[]).length;v.innerHTML=`<div class="page-title"><div><span class="eyebrow">YURDUNU BİL • 39.0.0</span><h1>Ayarlar</h1><p>Çalışma deneyimini sadeleştir, tek atlası kendine göre kullan.</p></div></div><div class="v30-settings-grid"><section class="surface v30-profile"><div class="v30-profile-top"><div class="avatar big">${String(name).slice(0,1).toLocaleUpperCase('tr-TR')}</div><div><h2>${name}</h2><p>İlerleme, favoriler ve test sonuçları cihazında saklanır.</p></div></div><div class="v30-info-row"><span>📚 Soru bankası</span><b>${q} özgün soru</b></div><div class="v30-info-row"><span>📍 İl atlası</span><b>81 il</b></div><div class="v30-info-row"><span>🗺️ Harita</span><b>1 Leaflet atlas • 8 katman</b></div></section><section class="surface v30-settings-card"><div class="v30-setting"><div><b>Görünüm</b><small>${light?'Aydınlık tema':'Koyu tema'}</small></div><button class="btn secondary" data-v30-theme>${light?'☾ Koyu tema':'☀ Aydınlık tema'}</button></div><div class="v30-setting"><div><b>İl isimleri</b><small>Haritada 81 il adını göster</small></div><label class="v30-switch"><input data-v30-labels type="checkbox" ${labels?'checked':''}><span></span></label></div><div class="v30-setting"><div><b>Sade görünüm</b><small>Gereksiz dekoratif alanları azalt</small></div><label class="v30-switch"><input data-v30-compact type="checkbox" ${compact?'checked':''}><span></span></label></div><div class="v30-setting danger-line"><div><b>Yerel verileri temizle</b><small>Test geçmişi, favoriler ve yerel tercihler silinir.</small></div><button class="btn danger-btn" data-v30-reset>Temizle</button></div></section></div><section class="surface v30-about"><span class="eyebrow">NE VAR?</span><h2>KPSS için gerekenler tek yerde.</h2><div class="v30-about-grid"><div><b>🗺️ Tek Atlas</b><p>81 il + gerçek kıyı/göl/akarsu altlığı + çalışma katmanları.</p></div><div><b>🧠 Öğrenme</b><p>Kısa konu anlatımı, görsel tekrar ve il bazlı çalışma.</p></div><div><b>🎯 Ölçme</b><p>Kolay, orta ve zor seviyelerde ${q} soruluk havuz.</p></div></div></section>`;
$('[data-v30-theme]',v).onclick=()=>{const isLight=document.body.classList.toggle('light');let raw={};try{raw=JSON.parse(localStorage.getItem('yb_state_25')||'{}')}catch{}raw.theme=isLight?'light':'dark';localStorage.setItem('yb_state_25',JSON.stringify(raw));settings()};
$('[data-v30-labels]',v).onchange=e=>{localStorage.setItem('yb30_labels',e.target.checked?'1':'0');document.body.classList.toggle('hide-map-labels',!e.target.checked)};
$('[data-v30-compact]',v).onchange=e=>{localStorage.setItem('yb30_compact',e.target.checked?'1':'0');document.body.classList.toggle('v30-compact',e.target.checked)};
$('[data-v30-reset]',v).onclick=()=>{if(confirm('Yerel test geçmişi ve favoriler silinsin mi?')){localStorage.removeItem('yb_state_25');localStorage.removeItem('yb30_labels');localStorage.removeItem('yb30_compact');localStorage.removeItem('yb_province_study_v31');localStorage.removeItem('yb_last_seen_version');localStorage.removeItem('yb_update_dismissed');location.reload()}}}
function refresh(){dashboard();settings()}
new MutationObserver(()=>setTimeout(refresh,80)).observe(document.body,{subtree:true,childList:true});
refresh();
})();
