/* Yurdunu Bil 30 — KPSS-focused UX, map layers, settings and consistency patch */
(()=>{
'use strict';
const VERSION='30.0.0',QCOUNT=(window.QUESTION_BANK||[]).length||120;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c').trim();
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const FEATURES=window.GEO_FEATURES||{};
const PLATEAUS=FEATURES.plateaus||[
{name:'Erzurum–Kars Platosu',lat:40.05,lon:41.4},{name:'Haymana Platosu',lat:39.2,lon:32.7},{name:'Cihanbeyli Platosu',lat:38.55,lon:32.6},{name:'Obruk Platosu',lat:37.75,lon:33.3},{name:'Bozok Platosu',lat:39.7,lon:35.1},{name:'Taşeli Platosu',lat:36.65,lon:33.0},{name:'Teke Platosu',lat:36.9,lon:29.6},{name:'Gaziantep Platosu',lat:37.0,lon:37.0},{name:'Şanlıurfa Platosu',lat:37.2,lon:39.0},{name:'Ardahan Platosu',lat:41.1,lon:42.8},{name:'Çatalca–Kocaeli Platosu',lat:41.0,lon:29.8},{name:'Perşembe Platosu',lat:41.1,lon:37.8}
];
const MODES=[['default','Standart'],['region','Bölgeler'],['climate','İklim'],['agriculture','Tarım'],['mountains','Dağlar'],['plains','Ovalar'],['plateaus','Platolar'],['lakes','Göller'],['rivers','Nehirler'],['mining','Madenler']];
function geo(){return window.GEO_FEATURES||FEATURES}
function bounds(fs){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const f of fs||[])coords(f.geometry,c=>{minX=Math.min(minX,c[0]);maxX=Math.max(maxX,c[0]);minY=Math.min(minY,c[1]);maxY=Math.max(maxY,c[1])});return{minX,minY,maxX,maxY}}
function coords(g,cb){if(!g)return;if(g.type==='Polygon')g.coordinates.flat().forEach(cb);else if(g.type==='MultiPolygon')g.coordinates.flat(2).forEach(cb)}
function projectFactory(b){const s=Math.min(860/(b.maxX-b.minX||1),390/(b.maxY-b.minY||1));return(lon,lat)=>[70+(lon-b.minX)*s,465-(lat-b.minY)*s]}
function layerColor(p,m){const r=p?.region||'';if(m==='region')return({Marmara:'#5d8fe5',Ege:'#68b96e',Akdeniz:'#e09b55','İç Anadolu':'#d5a64a',Karadeniz:'#4dc1a4','Doğu Anadolu':'#8c78d9','Güneydoğu Anadolu':'#c66e73'})[r]||'#4d87d9';if(m==='climate'){const n=norm(p?.climate);if(n.includes('akdeniz'))return'#e28c60';if(n.includes('karadeniz'))return'#45bda7';if(n.includes('karasal')||n.includes('sert'))return'#8b7ddd';return'#c9a85f'}if(m==='agriculture')return p?.agriculture?'#38c89a':'#395f73';if(m==='mountains')return /dağ|toros|kaçkar|koroğlu|uludağ|ağrı/i.test((p?.terrain||'')+' '+(p?.mountains||''))?'#b48756':'#426c83';if(m==='plains')return /ova|düzlük|graben/i.test((p?.plains||'')+' '+(p?.terrain||''))?'#e5bd54':'#496579';if(m==='plateaus')return /plato|yayla/i.test((p?.terrain||'')+' '+(p?.plains||''))?'#b98a61':'#496579';if(m==='lakes')return p?.lakes?'#3a8fc1':'#405f73';if(m==='rivers')return p?.rivers?'#397da7':'#405f73';if(m==='mining')return p?.mining?'#d27d51':'#455e70';return p?.color||'#4d87d9'}
function makeSvgLayer(svg,cls){svg.querySelectorAll('.v30-feature-layer').forEach(x=>x.remove());const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('class','v30-feature-layer '+cls);return g}
function featureText(g,x,y,label,cls){const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('x',x);t.setAttribute('y',y);t.setAttribute('class','v30-feature-label '+cls);t.textContent=label;g.appendChild(t)}
function drawFeatures(svg,mode){if(!['mountains','plains','plateaus','lakes','rivers','mining'].includes(mode))return;const f=geo(),fs=window.__YB30_GEO?.features||[];if(!fs.length)return;const b=bounds(fs),p=projectFactory(b),g=makeSvgLayer(svg,mode),add=(x,y)=>{const e=document.createElementNS('http://www.w3.org/2000/svg','circle');e.setAttribute('cx',x);e.setAttribute('cy',y);e.setAttribute('r','4');e.setAttribute('class','v30-dot');g.appendChild(e)};
if(mode==='rivers'){(f.rivers||[]).forEach(r=>{const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('class','v30-river');path.setAttribute('d',(r.points||[]).map(([lat,lon],i)=>{const[x,y]=p(lon,lat);return(i?'L':'M')+x.toFixed(1)+','+y.toFixed(1)}).join(' '));g.appendChild(path);const z=r.points?.[Math.floor((r.points.length-1)/2)];if(z){const[x,y]=p(z[1],z[0]);featureText(g,x+5,y-4,r.name,'river')}})}
if(mode==='lakes'){(f.lakes||[]).forEach(l=>{const[x,y]=p(l.lon,l.lat),e=document.createElementNS('http://www.w3.org/2000/svg','ellipse');e.setAttribute('cx',x);e.setAttribute('cy',y);e.setAttribute('rx',Math.min(l.rx||8,34));e.setAttribute('ry',Math.min(l.ry||5,18));e.setAttribute('class','v30-lake');g.appendChild(e);featureText(g,x+5,y-4,l.name,'lake')})}
if(mode==='mountains'){(f.mountains||[]).forEach(x=>{const[a,b1]=p(x.lon,x.lat);add(a,b1);featureText(g,a+6,b1-5,'▲ '+x.name,'mountain')})}
if(mode==='plains'){(f.plains||[]).forEach(x=>{const[a,b1]=p(x.lon,x.lat),e=document.createElementNS('http://www.w3.org/2000/svg','ellipse');e.setAttribute('cx',a);e.setAttribute('cy',b1);e.setAttribute('rx',Math.min(x.rx||12,55));e.setAttribute('ry',Math.min(x.ry||6,20));e.setAttribute('class','v30-plain');g.appendChild(e);featureText(g,a+5,b1-4,x.name,'plain')})}
if(mode==='plateaus'){PLATEAUS.forEach(x=>{const[a,b1]=p(x.lon,x.lat);add(a,b1);featureText(g,a+6,b1-5,'◆ '+x.name,'plateau')})}
if(mode==='mining'){(f.mines||[]).forEach(x=>{const[a,b1]=p(x.lon,x.lat);const e=document.createElementNS('http://www.w3.org/2000/svg','circle');e.setAttribute('cx',a);e.setAttribute('cy',b1);e.setAttribute('r','5');e.setAttribute('class','v30-mine');g.appendChild(e);featureText(g,a+7,b1-4,x.name,'mine')})}
svg.appendChild(g)}
function applyMap(shell,mode){const svg=$('.atlas-svg',shell);if(!svg)return;const data=window.PROVINCE_DATA||[];svg.querySelectorAll('.province-shape').forEach(s=>{const p=data.find(x=>norm(x.name)===norm(s.dataset.province));s.style.setProperty('--fill',layerColor(p,mode));s.classList.toggle('v30-focus',mode!=='default')});drawFeatures(svg,mode)}
function installMap(shell){const tabs=$('.mode-tabs',shell);if(!tabs)return;tabs.innerHTML=MODES.map(([id,label])=>`<button type="button" data-v30-mode="${id}">${label}</button>`).join('');const setMode=id=>{tabs.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.v30Mode===id));shell.dataset.v30Mode=id;applyMap(shell,id);updateHint(shell,id)};tabs.querySelectorAll('button').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();setMode(b.dataset.v30Mode)});setMode(shell.dataset.v30Mode||'default')}
function updateHint(shell,m){const h=$('.atlas-gesture-hint',shell);const map={default:'İle tıkla → KPSS özeti',region:'Bölge dağılışını karşılaştır',climate:'İklim tiplerini karşılaştır',agriculture:'Tarım alanlarını karşılaştır',mountains:'Dağları ve adlarını gör',plains:'Ovaları oluşumlarıyla çalış',plateaus:'Başlıca platoları gör',lakes:'Gölleri adlarıyla çalış',rivers:'Akarsuları ve yönlerini izle',mining:'Maden merkezlerini gör'};if(h)h.textContent=map[m]||map.default}
async function loadGeo(){if(window.__YB30_GEO)return;try{const r=await fetch('data/provinces.geojson',{cache:'no-store'});if(r.ok)window.__YB30_GEO=await r.json()}catch(e){console.warn('YB30 geo',e)}}
function quickDashboard(){const v=$('#view-dashboard');if(!v||v.dataset.v30Dashboard==='1')return;v.dataset.v30Dashboard='1';const live=$('#live-stats');if(live)live.style.display='none';const lower=$('.dashboard-lower',v);if(lower)lower.innerHTML=`<section class="surface v30-start"><div><span class="eyebrow">KPSS COĞRAFYA • HIZLI BAŞLANGIÇ</span><h2>Önce yurdu tanı, sonra soruya dön.</h2><p>Haritada gördüğün bilgiyi kısa notla pekiştir ve hemen KPSS tipi soruyla ölç.</p></div><div class="v30-start-grid"><button data-view="map"><b>🗺️ Haritayı keşfet</b><small>Dağ, ova, plato, göl, nehir ve maden katmanları</small></button><button data-view="topics"><b>📚 Konu çalış</b><small>KPSS odaklı kısa anlatımlar ve görsel tekrar</small></button><button data-view="provinceStudy"><b>📍 İlleri tanı</b><small>81 ilin coğrafya özelliklerini tek kartta incele</small></button><button data-view="quiz"><b>🎯 Test çöz</b><small>${QCOUNT} soruluk havuzdan kendi testini oluştur</small></button></div></section>`}
function consistency(){const walk=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=walk.nextNode()){if(!n.parentElement.closest('script,style'))n.nodeValue=n.nodeValue.replace(/120\+/g,`${QCOUNT}+`).replace(/120 soru havuzu/g,`${QCOUNT} soru havuzu`).replace(/120 soru/g,`${QCOUNT} soru`)}}
function settings(){const v=$('#view-settings');if(!v||v.dataset.v30==='1')return;v.dataset.v30='1';const light=document.body.classList.contains('light'),labels=localStorage.getItem('yb30_labels')!=='0',compact=localStorage.getItem('yb30_compact')==='1';let profile={};try{profile=JSON.parse(localStorage.getItem('yb_state_25')||'{}').profile||{}}catch{};const name=profile.displayName||'KPSS Öğrencisi';v.innerHTML=`<div class="page-title"><div><span class="eyebrow">YURDUNU BİL • ${VERSION}</span><h1>Ayarlar</h1><p>Çalışma deneyimini sadeleştir, haritayı kendine göre kullan.</p></div></div><div class="v30-settings-grid"><section class="surface v30-profile"><div class="v30-profile-top"><div class="avatar big">${esc(name.slice(0,1).toLocaleUpperCase('tr-TR'))}</div><div><h2>${esc(name)}</h2><p>İlerleme, favoriler ve test sonuçları cihazında saklanır.</p></div></div><div class="v30-info-row"><span>📚 Soru bankası</span><b>${QCOUNT} özgün soru</b></div><div class="v30-info-row"><span>📍 İl atlası</span><b>81 il</b></div><div class="v30-info-row"><span>🗺️ Harita katmanı</span><b>10 çalışma modu</b></div></section><section class="surface v30-settings-card"><div class="v30-setting"><div><b>Görünüm</b><small>${light?'Aydınlık tema':'Koyu tema'}</small></div><button class="btn secondary" id="v30-theme">${light?'☾ Koyu tema':'☀ Aydınlık tema'}</button></div><div class="v30-setting"><div><b>İl isimleri</b><small>Haritada 81 il adını göster</small></div><label class="v30-switch"><input id="v30-labels" type="checkbox" ${labels?'checked':''}><span></span></label></div><div class="v30-setting"><div><b>Sade görünüm</b><small>Gereksiz dekoratif alanları azalt</small></div><label class="v30-switch"><input id="v30-compact" type="checkbox" ${compact?'checked':''}><span></span></label></div><div class="v30-setting danger-line"><div><b>Yerel verileri temizle</b><small>Test geçmişi, favoriler ve yerel tercihler silinir.</small></div><button class="btn danger-btn" id="v30-reset">Temizle</button></div></section></div><section class="surface v30-about"><span class="eyebrow">NE VAR?</span><h2>KPSS için gerekenler tek yerde.</h2><div class="v30-about-grid"><div><b>🗺️ Atlas</b><p>81 il + dağ, ova, plato, göl, nehir ve maden katmanları.</p></div><div><b>🧠 Öğrenme</b><p>Kısa konu anlatımı, görsel tekrar ve il bazlı çalışma.</p></div><div><b>🎯 Ölçme</b><p>Kolay, orta ve zor seviyelerde ${QCOUNT} soruluk havuz.</p></div></div></section>`;
$('#v30-theme').onclick=()=>{const isLight=document.body.classList.toggle('light');let raw={};try{raw=JSON.parse(localStorage.getItem('yb_state_25')||'{}')}catch{}raw.theme=isLight?'light':'dark';localStorage.setItem('yb_state_25',JSON.stringify(raw));localStorage.setItem('yb_theme',isLight?'light':'dark');v.dataset.v30='';settings()};
$('#v30-labels').onchange=e=>{localStorage.setItem('yb30_labels',e.target.checked?'1':'0');document.body.classList.toggle('hide-map-labels',!e.target.checked)};
$('#v30-compact').onchange=e=>{localStorage.setItem('yb30_compact',e.target.checked?'1':'0');document.body.classList.toggle('v30-compact',e.target.checked)};
$('#v30-reset').onclick=()=>{if(confirm('Yerel test geçmişi ve favoriler silinsin mi?')){localStorage.removeItem('yb_state_25');localStorage.removeItem('yb30_labels');localStorage.removeItem('yb30_compact');location.reload()}};
}
function enhance(){quickDashboard();settings();consistency();document.querySelectorAll('.atlas-shell').forEach(installMap);document.body.classList.toggle('hide-map-labels',localStorage.getItem('yb30_labels')==='0');document.body.classList.toggle('v30-compact',localStorage.getItem('yb30_compact')==='1');$$('.setup-badge').forEach(x=>x.textContent=`${QCOUNT} soru havuzu`);$$('.atlas-shell').forEach(s=>{if(window.__YB30_GEO)applyMap(s,s.dataset.v30Mode||'default')})}
let timer=0;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(enhance,80)}).observe(document.body,{subtree:true,childList:true});
loadGeo().then(enhance);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance,{once:true});else enhance();
})();
