/* Yurdunu Bil v34.1 — sürüm bildirimi + 2026 KPSS Ön Lisans geri sayımı */
(()=>{
'use strict';
const VERSION='34.1.0';
const EXAM_DATE=new Date('2026-10-04T10:15:00+03:00');
const $=(s,r=document)=>r.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function remaining(){const ms=EXAM_DATE-Date.now();if(ms<=0)return{days:0,hours:0,minutes:0,past:true};const s=Math.floor(ms/1000);return{days:Math.floor(s/86400),hours:Math.floor(s%86400/3600),minutes:Math.floor(s%3600/60),past:false}}
function countdownHTML(){const r=remaining();return `<div class="yb32-countdown"><span>🎯</span><div><strong>${r.past?'Sınav günü geldi':'KPSS Ön Lisans 2026'}</strong><small>04 Ekim 2026 • 10:15</small></div></div><div class="yb32-countdown-grid"><div><span>${r.days}</span><small>gün</small></div><div><span>${r.hours}</span><small>saat</small></div><div><span>${r.minutes}</span><small>dakika</small></div></div>`}
function installTopbar(){const top=$('.top-actions');if(!top||top.querySelector('.yb32-version-badge'))return;const b=document.createElement('span');b.className='yb32-version-badge';b.innerHTML='<i class="yb32-version-dot"></i> v'+VERSION;top.insertBefore(b,top.firstChild)}
function installDashboard(){const v=$('#view-dashboard');if(!v||v.querySelector('.yb32-exam-card'))return;const target=v.querySelector('.dashboard-intro');if(!target)return;const card=document.createElement('section');card.className='surface yb32-exam-card';card.innerHTML='<span class="eyebrow">2026 KPSS ÖN LİSANS</span><h2>Sınava kalan süre</h2><div data-yb32-countdown></div>';target.insertAdjacentElement('afterend',card);renderCountdown()}
function renderCountdown(){document.querySelectorAll('[data-yb32-countdown]').forEach(e=>e.innerHTML=countdownHTML())}
function patchSettings(){const v=$('#view-settings');if(!v)return;const title=v.querySelector('.v30-settings-card');if(!title||v.querySelector('.yb32-settings-version'))return;const box=document.createElement('div');box.className='yb32-settings-version';box.innerHTML='<div><b>Yurdunu Bil sürümü</b><small>Son sürüm: '+VERSION+' • Güncellemeler otomatik kontrol edilir.</small></div><b>v'+VERSION+'</b>';title.appendChild(box);const about=v.querySelector('.v30-about');if(about&&!about.querySelector('.yb32-settings-exam')){const x=document.createElement('div');x.className='yb32-settings-exam';x.innerHTML='<span class="eyebrow">SINAV SAYACI</span><div data-yb32-countdown></div>';about.appendChild(x);renderCountdown()}}
function showNotice(version,message,title='Yurdunu Bil güncellendi'){if(document.querySelector('.yb32-update'))return;const n=document.createElement('aside');n.className='yb32-update';n.setAttribute('role','status');n.innerHTML='<h3>🎉 '+esc(title)+'</h3><p>'+esc(message)+' Güncel sürümü kullanmak için lütfen siteyi yenileyin.</p><div class="yb32-update-actions"><button class="primary" data-yb32-reload>Siteyi yenile</button><button class="ghost" data-yb32-dismiss>Daha sonra</button></div>';document.body.appendChild(n);const key='yb_last_seen_version';n.querySelector('[data-yb32-reload]').onclick=()=>{localStorage.setItem(key,version);location.reload()};n.querySelector('[data-yb32-dismiss]').onclick=()=>{localStorage.setItem(key,version);n.remove()}}
function checkRemoteVersion(){fetch('yb-release.json?v='+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.json():null).then(data=>{if(!data)return;const remote=String(data.version||VERSION),key='yb_last_seen_version',seen=localStorage.getItem(key);if(!seen){if(localStorage.getItem('yb_state_25'))showNotice(VERSION,'Yeni özellikler ve düzeltmeler yayında.');localStorage.setItem(key,VERSION);return}if(remote!==VERSION&&remote!==seen)showNotice(remote,data.message||'Yeni özellikler ve düzeltmeler yayında.','Yeni sürüm hazır')}).catch(()=>{})}
function loop(){renderCountdown();setTimeout(loop,1000)}
function start(){installTopbar();installDashboard();patchSettings();const key='yb_last_seen_version',seen=localStorage.getItem(key);if(seen&&seen!==VERSION)showNotice(VERSION,'Mobil kullanım ve sayfa düzeni için kritik düzeltmeler yayında.');else if(!seen&&!localStorage.getItem('yb_state_25'))localStorage.setItem(key,VERSION);checkRemoteVersion();setInterval(checkRemoteVersion,1800000);loop();new MutationObserver(()=>{installTopbar();installDashboard();patchSettings()}).observe(document.body,{subtree:true,childList:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
