/* Yurdunu Bil v32 — sürüm bildirimi + 2026 KPSS Ön Lisans geri sayımı */
(()=>{
'use strict';
const VERSION='32.0.0';
const EXAM_DATE=new Date('2026-10-04T10:15:00+03:00');
const $=(s,r=document)=>r.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function remaining(){const ms=EXAM_DATE-Date.now();if(ms<=0)return{days:0,hours:0,minutes:0,seconds:0,past:true};const s=Math.floor(ms/1000);return{days:Math.floor(s/86400),hours:Math.floor(s%86400/3600),minutes:Math.floor(s%3600/60),seconds:s%60,past:false}}
function countdownHTML(){const r=remaining();return `<div class="yb32-countdown"><span>🎯</span><div><strong>${r.past?'Sınav günü geldi':'KPSS Ön Lisans 2026'}</strong><small>04 Ekim 2026 • 10:15</small></div></div><div class="yb32-countdown-grid"><div><span>${r.days}</span><small>gün</small></div><div><span>${r.hours}</span><small>saat</small></div><div><span>${r.minutes}</span><small>dakika</small></div></div>`}
function installTopbar(){const top=$('.top-actions');if(!top||top.querySelector('.yb32-version-badge'))return;const b=document.createElement('span');b.className='yb32-version-badge';b.innerHTML='<i class="yb32-version-dot"></i> v'+VERSION;top.insertBefore(b,top.firstChild)}
function installDashboard(){const v=$('#view-dashboard');if(!v||v.querySelector('.yb32-exam-card'))return;const target=v.querySelector('.dashboard-intro');if(!target)return;const card=document.createElement('section');card.className='surface yb32-exam-card';card.innerHTML='<span class="eyebrow">2026 KPSS ÖN LİSANS</span><h2>Sınava kalan süre</h2><div data-yb32-countdown></div>';target.insertAdjacentElement('afterend',card);renderCountdown()}
function renderCountdown(){document.querySelectorAll('[data-yb32-countdown]').forEach(e=>e.innerHTML=countdownHTML())}
function patchSettings(){const v=$('#view-settings');if(!v)return;const title=v.querySelector('.v30-settings-card');if(!title||v.querySelector('.yb32-settings-version'))return;const box=document.createElement('div');box.className='yb32-settings-version';box.innerHTML='<div><b>Yurdunu Bil sürümü</b><small>Son sürüm: '+VERSION+' • Güncellemeler otomatik kontrol edilir.</small></div><b>v'+VERSION+'</b>';title.appendChild(box);const about=v.querySelector('.v30-about');if(about&&!about.querySelector('.yb32-settings-exam')){const x=document.createElement('div');x.className='yb32-settings-exam';x.innerHTML='<div class="yb32-countdown-grid" data-yb32-countdown></div>';about.appendChild(x);renderCountdown()}}
function notifyUpdate(){const key='yb_last_seen_version';const seen=localStorage.getItem(key);if(!seen){localStorage.setItem(key,VERSION);return}if(seen===VERSION)return;if(document.querySelector('.yb32-update'))return;const n=document.createElement('aside');n.className='yb32-update';n.setAttribute('role','status');n.innerHTML='<h3>🎉 Yurdunu Bil güncellendi</h3><p>Yeni özellikler ve düzeltmeler yayında. Güncel sürümü kullanmak için lütfen siteyi yenileyin.</p><div class="yb32-update-actions"><button class="primary" data-yb32-reload>Siteyi yenile</button><button class="ghost" data-yb32-dismiss>Daha sonra</button></div>';document.body.appendChild(n);n.querySelector('[data-yb32-reload]').onclick=()=>{localStorage.setItem(key,VERSION);location.reload()};n.querySelector('[data-yb32-dismiss]').onclick=()=>{localStorage.setItem(key,VERSION);n.remove()}}
async function checkRemoteVersion(){try{const r=await fetch('version.json?v='+Date.now(),{cache:'no-store'});if(!r.ok)return;const data=await r.json();const remote=String(data.version||VERSION);const key='yb_last_seen_version';const seen=localStorage.getItem(key);if(seen&&remote!==VERSION&&remote!==seen){const n=document.createElement('aside');n.className='yb32-update';n.innerHTML='<h3>🚀 Yeni sürüm hazır</h3><p>'+esc(data.message||'Yeni özellikler ve iyileştirmeler yayında.')+' Güncel sürümü kullanmak için lütfen siteyi yenileyin.</p><div class="yb32-update-actions"><button class="primary" data-yb32-reload>Siteyi yenile</button><button class="ghost" data-yb32-dismiss>Daha sonra</button></div>';document.body.appendChild(n);n.querySelector('[data-yb32-reload]').onclick=()=>{localStorage.setItem(key,remote);location.reload()};n.querySelector('[data-yb32-dismiss]').onclick=()=>{localStorage.setItem(key,remote);n.remove()}}}catch(e){console.debug('YB update check',e)}}
function loop(){renderCountdown();setTimeout(loop,1000)}
function start(){installTopbar();installDashboard();patchSettings();notifyUpdate();checkRemoteVersion();loop();new MutationObserver(()=>{installTopbar();installDashboard();patchSettings()}).observe(document.body,{subtree:true,childList:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
