/* Yurdunu Bil 41 — canonical atlas, no duplicate maps, resilient SVG renderer */
(()=>{
'use strict';
if(window.__YB41_ATLAS)return; window.__YB41_ATLAS=1;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const DATA=Array.isArray(window.PROVINCE_DATA)?window.PROVINCE_DATA:[];
const FEATURES=window.GEO_FEATURES||{};
const FACTS=window.PROVINCE_FACTS_25||{};
const POP=window.POPULATION_2025||{};
const NS='http://www.w3.org/2000/svg';
const MODES=[['standard','Standart','81 il'],['region','Bölgeler','7 bölge'],['climate','İklim','iklim tipleri'],['agriculture','Tarım','ürünler'],['landform','Yer Şekilleri','ova • dağ • plato'],['water','Sular','akarsu • göl'],['mining','Maden','kaynaklar'],['population','Nüfus','2025']];
const EXTRA={
 rivers:[['Murat',[39.2,42.5,38.9,41.8,38.7,40.9,38.5,40.0,38.3,39.4]],['Zap Suyu',[37.5,44.2,37.3,44.0,37.0,43.5,36.9,43.1]],['Kelkit',[40.1,39.8,40.0,38.9,39.9,38.2,40.0,37.5]],['Susurluk',[40.0,28.1,39.9,28.7,39.8,29.2,39.7,29.7]],['Bakırçay',[39.2,27.2,39.1,27.6,39.0,28.1,38.9,28.5]],['Köprüçay',[37.1,31.0,36.9,31.2,36.7,31.4]],['Aksu',[37.0,30.8,36.8,30.7,36.5,30.7]],['Asi',[36.7,36.3,36.5,36.1,36.2,36.0]],['Tunca',[41.9,26.6,41.7,26.7,41.5,26.7]],['Porsuk',[39.8,30.5,39.7,30.9,39.6,31.3,39.4,31.6]]],
 lakes:[['Mogan Gölü',39.75,32.80,13,7],['Eymir Gölü',39.82,32.86,10,5],['Abant Gölü',40.60,31.28,9,6],['Tortum Gölü',40.67,41.65,12,6],['Bafa Gölü',37.48,27.48,17,9],['Kovada Gölü',37.63,30.86,12,6],['Köyceğiz Gölü',36.93,28.69,16,9],['Işıklı Gölü',38.25,29.95,14,7],['Yarışlı Gölü',37.55,29.90,11,6],['Büyükçekmece Gölü',41.03,28.58,13,6],['Küçükçekmece Gölü',40.99,28.77,10,5],['Terkos Gölü',41.32,28.68,13,8]],
 plains:[['Bafra Ovası',41.48,36.18,28,11],['Çarşamba Ovası',41.20,36.73,25,10],['Düzce Ovası',40.84,31.15,27,10],['Gönen Ovası',40.15,27.65,25,10],['Söke Ovası',37.75,27.40,25,9],['Menemen Ovası',38.60,27.05,25,9],['Antalya Ovası',36.95,30.70,28,11],['Tercan Ovası',39.78,40.40,23,9],['Pasinler Ovası',39.98,41.68,24,9],['Yüksekova',37.55,44.28,25,10],['Bismil Ovası',37.75,40.95,30,11],['Nizip Ovası',37.00,37.80,22,9]],
 mountains:[['Aydos Dağı',41.10,29.35],['Samanlı Dağları',40.60,29.80],['Geyik Dağları',36.95,32.75],['Sultan Dağları',38.30,31.10],['Akdağlar',37.35,29.45],['Sandras Dağı',37.45,28.90],['Honaz Dağı',37.75,29.25],['Sakarya Dağları',39.70,30.90],['Kargapazarı Dağları',40.05,41.55],['Allahuekber Dağları',40.50,42.65],['Mescit Dağları',40.55,41.05],['Amanos Dağları',36.80,36.40]],
 plateaus:[['Obruk Platosu',38.20,33.25,32,13],['Bozok Platosu',39.55,35.35,38,15],['Haymana Platosu',39.25,32.75,30,13],['Cihanbeyli Platosu',38.80,32.85,38,14],['Teke Platosu',37.15,29.75,28,13],['Taşeli Platosu',36.85,32.95,27,13],['Erzurum-Kars Platosu',40.05,42.95,48,19],['Gaziantep Platosu',37.05,37.35,28,13],['Şanlıurfa Platosu',37.20,38.80,35,15],['Mardin-Midyat Platosu',37.45,40.75,28,13]],
 mines:[['Bor',39.91,33.50],['Kömür',38.32,27.35],['Linyit',38.50,28.70],['Krom',36.90,29.10],['Demir',39.80,40.55],['Bakır',40.95,40.90],['Petrol',37.90,41.10],['Doğal gaz',41.05,27.85],['Altın',38.50,27.05],['Mermer',38.00,30.50],['Manyezit',39.70,30.50],['Zımpara taşı',37.80,27.80]]
};
const norm=v=>String(v??'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c').trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const first=v=>clean(v).split(/[,;•/]/).map(x=>x.trim()).filter(Boolean)[0]||'—';
const province=n=>DATA.find(p=>norm(p.name)===norm(n))||null;
const getName=f=>f?.properties?.name||f?.properties?.NAME_1||f?.properties?.NAME||'';
let state={mode:'standard',selected:'',labels:true},geo=null,root=null;
try{state={...state,...JSON.parse(localStorage.getItem('yb41_atlas')||'{}')}}catch{}
const save=()=>{try{localStorage.setItem('yb41_atlas',JSON.stringify(state))}catch{}};
function allFeatures(){return {rivers:[...(FEATURES.rivers||[]),...EXTRA.rivers.map(([name,a])=>({name,points:[[a[0],a[1]],[a[2],a[3]],[a[4],a[5]],[a[6],a[7]],[a[8],a[9]]]}))],lakes:[...(FEATURES.lakes||[]),...EXTRA.lakes.map(x=>({name:x[0],lat:x[1],lon:x[2],rx:x[3],ry:x[4]}))],plains:[...(FEATURES.plains||[]),...EXTRA.plains.map(x=>({name:x[0],lat:x[1],lon:x[2],rx:x[3],ry:x[4]}))],mountains:[...(FEATURES.mountains||[]),...EXTRA.mountains.map(x=>({name:x[0],lat:x[1],lon:x[2]}))],mines:[...(FEATURES.mines||[]),...EXTRA.mines.map(x=>({name:x[0],lat:x[1],lon:x[2]}))],plateaus:EXTRA.plateaus.map(x=>({name:x[0],lat:x[1],lon:x[2],rx:x[3],ry:x[4]}))}}
function bounds(fs){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;const walk=g=>{if(!g)return;if(g.type==='Polygon')g.coordinates.flat(1).forEach(c=>{minX=Math.min(minX,c[0]);maxX=Math.max(maxX,c[0]);minY=Math.min(minY,c[1]);maxY=Math.max(maxY,c[1])});else if(g.type==='MultiPolygon')g.coordinates.flat(2).forEach(c=>{minX=Math.min(minX,c[0]);maxX=Math.max(maxX,c[0]);minY=Math.min(minY,c[1]);maxY=Math.max(maxY,c[1])})};fs.forEach(f=>walk(f.geometry));return{minX,minY,maxX,maxY}}
function projectFactory(b){const sx=880/(b.maxX-b.minX||1),sy=470/(b.maxY-b.minY||1),s=Math.min(sx,sy);return(lon,lat)=>[60+(lon-b.minX)*s,500-(lat-b.minY)*s]}
function pathFor(g,p){if(g.type==='Polygon')return g.coordinates.map(r=>r.map((c,i)=>{const[x,y]=p(c[0],c[1]);return(i?'L':'M')+x.toFixed(1)+' '+y.toFixed(1)}).join(' ')+' Z').join(' ');if(g.type==='MultiPolygon')return g.coordinates.map(poly=>poly.map(r=>r.map((c,i)=>{const[x,y]=p(c[0],c[1]);return(i?'L':'M')+x.toFixed(1)+' '+y.toFixed(1)}).join(' ')+' Z').join(' ')).join(' ');return ''}
function centroid(g,p){const ring=g.type==='Polygon'?g.coordinates[0]:g.type==='MultiPolygon'?g.coordinates.reduce((a,b)=>b[0].length>a[0].length?b:a)[0]:[];if(!ring.length)return[0,0];let x=0,y=0;ring.forEach(c=>{const q=p(c[0],c[1]);x+=q[0];y+=q[1]});return[x/ring.length,y/ring.length]}
function color(p){const m=state.mode,r=norm(p?.region),c=norm(p?.climate),a=norm(first(p?.agriculture));if(m==='region')return({marmara:'#4d86b7',ege:'#c78654',akdeniz:'#3e9d83',ic_anadolu:'#8d73ae',karadeniz:'#4c9aab',dogu_anadolu:'#b98c55',guneydogu_anadolu:'#a95e62'})[r]||'#617c8f';if(m==='climate')return c.includes('akdeniz')?'#3e9d83':c.includes('karadeniz')?'#4d9fb6':c.includes('karasal')?'#bd8b55':'#7188a0';if(m==='agriculture')return a.includes('bugday')||a.includes('arpa')?'#bd9a43':a.includes('findik')||a.includes('cay')?'#559b75':a.includes('zeytin')?'#71935e':a.includes('pamuk')?'#bd7880':'#6b8794';if(m==='population'){const n=Number(String(POP[p?.name]||p?.population||'').replace(/\D/g,''))||0;return n>3000000?'#b95360':n>1500000?'#c77d56':n>750000?'#b79a52':n>300000?'#638ca4':'#59788c'}return '#456a7d'}
function el(tag,attrs={}){const x=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>x.setAttribute(k,v));return x}
function ellipse(p,lat,lon,rx,ry){const[x,y]=p(lon,lat),pts=[];for(let i=0;i<36;i++){const a=i*Math.PI*2/36;pts.push([(x+Math.cos(a)*(rx||12)).toFixed(1)+','+(y+Math.sin(a)*(ry||7)).toFixed(1)])}return pts.join(' ')}
function featureGroup(svg,p,all){const g=el('g',{class:'yb41-feature-layer '+state.mode});const active=['standard','landform'].includes(state.mode);const drawWater=state.mode==='water'||active,drawLand=state.mode==='landform'||active,drawMine=state.mode==='mining';if(drawWater){all.rivers.forEach((r,i)=>{const q=el('path',{d:r.points.map(([lat,lon],j)=>{const[x,y]=p(lon,lat);return(j?'L':'M')+x.toFixed(1)+' '+y.toFixed(1)}).join(' '),class:'yb41-river'});q.dataset.name=r.name;q.onclick=()=>showFeature(r.name,'Akarsu','🌊');g.appendChild(q)});all.lakes.forEach(l=>{const q=el('polygon',{points:ellipse(p,l.lat,l.lon,l.rx,l.ry),class:'yb41-lake'});q.onclick=()=>showFeature(l.name,'Göl','💧');g.appendChild(q);label(g,p(l.lon,l.lat),l.name,'water')})}if(drawLand){all.plains.forEach(x=>{const q=el('polygon',{points:ellipse(p,x.lat,x.lon,x.rx,x.ry),class:'yb41-plain'});g.appendChild(q);label(g,p(x.lon,x.lat),x.name,'plain')});all.plateaus.forEach(x=>{const q=el('polygon',{points:ellipse(p,x.lat,x.lon,x.rx,x.ry),class:'yb41-plateau'});g.appendChild(q);label(g,p(x.lon,x.lat),x.name,'plateau')});all.mountains.forEach(x=>{const q=el('circle',{cx:p(x.lon,x.lat)[0],cy:p(x.lon,x.lat)[1],r:4.5,class:'yb41-mountain'});q.onclick=()=>showFeature(x.name,'Dağ','⛰️');g.appendChild(q);label(g,p(x.lon,x.lat),'▲ '+x.name,'mountain')})}if(drawMine){all.mines.forEach(x=>{const q=el('circle',{cx:p(x.lon,x.lat)[0],cy:p(x.lon,x.lat)[1],r:5.5,class:'yb41-mine'});q.onclick=()=>showFeature(x.name,'Maden','⛏️');g.appendChild(q);label(g,p(x.lon,x.lat),'⛏ '+x.name,'mine')})}svg.appendChild(g)}
function label(g,pos,text,type){const t=el('text',{x:pos[0]+6,y:pos[1]-5,class:'yb41-feature-label '+type});t.textContent=text;g.appendChild(t)}
function showFeature(name,type,icon){const card=$('[data-yb41-info]');if(!card)return;card.innerHTML=`<div class="yb41-info-kicker">${icon} ${esc(type)}</div><h3>${esc(name)}</h3><p>Haritadaki bu unsur KPSS Coğrafya Atlası'nın ${esc(type.toLocaleLowerCase('tr-TR'))} katmanında gösteriliyor.</p><button class="yb41-clear" data-yb41-clear>Seçimi temizle</button>`}
function provinceInfo(p){const f=FACTS[p.name]||{};const related=allFeatures();const near=(arr,limit=4)=>arr.filter(x=>{const s=norm(p.name);return norm(x.name).includes(s.replace(' ili',''))}).slice(0,limit);const rivers=f.rivers||first(p.rivers),lakes=f.lakes||first(p.lakes),plains=f.plains||first(p.plains);return `<div class="yb41-info-kicker">📍 İL ÇALIŞMA KARTI</div><h3>${esc(p.name)}</h3><div class="yb41-sub">${esc(p.region||'')} • ${esc(p.climate||'')}</div><div class="yb41-fact"><b>🗺️ Yer şekilleri</b><span>${esc(f.terrain||p.terrain||'—')}</span></div><div class="yb41-fact"><b>🌊 Akarsular</b><span>${esc(rivers||'—')}</span></div><div class="yb41-fact"><b>💧 Göller</b><span>${esc(lakes||'—')}</span></div><div class="yb41-fact"><b>🌾 Ovalar</b><span>${esc(plains||'—')}</span></div><div class="yb41-fact"><b>🌱 Tarım</b><span>${esc(f.agriculture||first(p.agriculture)||'—')}</span></div><div class="yb41-actions"><button data-yb41-open-province="${esc(p.name)}">İl çalışma kartını aç →</button></div>`}
function render(){if(!root)return;root.innerHTML=`<div class="yb41-atlas"><header class="yb41-hero"><div><span class="eyebrow">2026 KPSS • ETKİLEŞİMLİ TÜRKİYE ATLASI</span><h1>Türkiye'yi <em>haritada</em> öğren.</h1><p>81 il, akarsular, göller, ovalar, dağlar, platolar, madenler ve nüfus katmanları tek kanonik haritada.</p></div><div class="yb41-status"><b>ATLAS 41</b><span>Yerel veri • çevrimdışı yedekli</span></div></header><div class="yb41-controls"><label>⌕<input data-yb41-search placeholder="İl veya coğrafi unsur ara…" autocomplete="off"></label><div class="yb41-modes">${MODES.map(x=>`<button data-yb41-mode="${x[0]}" class="${state.mode===x[0]?'active':''}"><b>${x[1]}</b><small>${x[2]}</small></button>`).join('')}</div></div><div class="yb41-counts"><span>🏛️ <b>${geo?.features?.length||81}</b> il</span><span>🌊 <b>${allFeatures().rivers.length}</b> akarsu</span><span>💧 <b>${allFeatures().lakes.length}</b> göl</span><span>🌾 <b>${allFeatures().plains.length}</b> ova</span><span>⛰️ <b>${allFeatures().mountains.length}</b> dağ</span><span>🟣 <b>${allFeatures().plateaus.length}</b> plato</span><span>⛏️ <b>${allFeatures().mines.length}</b> maden</span></div><div class="yb41-layout"><section class="yb41-map-card"><div class="yb41-map-head"><b data-yb41-map-title>81 İl • ${MODES.find(x=>x[0]===state.mode)?.[1]}</b><button data-yb41-reset>↺ Sıfırla</button></div><div class="yb41-map-wrap"><svg data-yb41-svg viewBox="0 0 1000 560" role="img" aria-label="Türkiye il ve coğrafi unsur haritası"></svg><div class="yb41-map-hint">💡 Bir ile dokun. İl kartı sağda açılır.</div></div><div class="yb41-legend" data-yb41-legend></div></section><aside class="yb41-info" data-yb41-info><div class="yb41-empty"><b>Haritadan bir il seç</b><span>İl sınırı, temel coğrafya bilgileri ve KPSS için önemli unsurlar burada açılacak.</span><div><i>🌊 Akarsu</i><i>💧 Göl</i><i>🌾 Ova</i><i>⛰️ Dağ</i><i>🟣 Plato</i></div></div></aside></div><section class="yb41-learning"><div><span class="eyebrow">HARİTADAN ÇALIŞ</span><h2>Katmanları ezber yerine ilişkilendir.</h2><p>Bir ili seçtiğinde o ilin yer şekilleri, suları ve tarımsal özellikleri aynı kartta görünür. Katman değiştirerek soru mantığını haritaya bağla.</p></div><div class="yb41-learn-grid"><article><b>01</b><strong>Konum</strong><span>İl + bölge + iklim</span></article><article><b>02</b><strong>Yer şekli</strong><span>Ova + dağ + plato</span></article><article><b>03</b><strong>Su</strong><span>Akarsu + göl</span></article><article><b>04</b><strong>Üretim</strong><span>Tarım + maden</span></article></div></section></div>`;bind();draw()}
async function loadGeo(){if(geo)return geo;const urls=['data/provinces.geojson','https://raw.githubusercontent.com/B4htsizBedevevi/Yurdunu-Bil/main/data/provinces.geojson'];for(const u of urls){try{const r=await fetch(u,{cache:'no-store'});if(r.ok){const x=await r.json();if(x?.features?.length){geo=x;return x}}}catch{}}throw new Error('İl haritası verisi yüklenemedi')}
function draw(){const svg=$('[data-yb41-svg]',root);if(!svg||!geo)return;svg.innerHTML='';const b=bounds(geo.features),p=projectFactory(b);const base=el('g',{class:'yb41-province-layer'});geo.features.forEach(f=>{const n=getName(f),pr=province(n);const q=el('path',{d:pathFor(f.geometry,p),class:'yb41-province '+(state.selected&&norm(state.selected)===norm(n)?'selected':''),fill:color(pr)});q.dataset.name=n;q.onclick=()=>{state.selected=n;save();draw();updateInfo(pr)};base.appendChild(q)});svg.appendChild(base);geo.features.forEach(f=>{const n=getName(f),pr=province(n),[x,y]=centroid(f.geometry,p);if(!n)return;const t=el('text',{x,y,class:'yb41-province-label'});t.textContent=pr?.shortName||n;svg.appendChild(t)});featureGroup(svg,p,allFeatures());legend();
}
function updateInfo(p){const box=$('[data-yb41-info]',root);if(box&&p)box.innerHTML=provinceInfo(p);}
function legend(){const e=$('[data-yb41-legend]',root);if(!e)return;const m=state.mode;const items=m==='region'?[['#4d86b7','Marmara'],['#c78654','Ege'],['#3e9d83','Akdeniz'],['#8d73ae','İç Anadolu'],['#4c9aab','Karadeniz'],['#b98c55','Doğu Anadolu'],['#a95e62','Güneydoğu']]:m==='landform'?[['#d5bd63','Ovalar'],['#9d82c2','Platolar'],['#7d8d96','Dağlar']]:m==='water'?[['#37bce9','Akarsular'],['#268fd0','Göller']]:m==='mining'?[['#c08348','Maden noktaları']]:m==='population'?[['#b95360','3 milyon+'],['#c77d56','1,5–3 milyon'],['#b79a52','750 bin–1,5 milyon'],['#638ca4','300–750 bin']]:[['#456a7d','81 il']];e.innerHTML=items.map(x=>`<span><i style="background:${x[0]}"></i>${x[1]}</span>`).join('')}
function bind(){const search=$('[data-yb41-search]',root);search.oninput=()=>{const q=norm(search.value);if(!q){draw();return}const hit=geo.features.find(f=>norm(getName(f)).includes(q));if(hit){state.selected=getName(hit);save();draw();updateInfo(province(getName(hit)))}else{const all=allFeatures();const found=[...all.rivers,...all.lakes,...all.plains,...all.mountains,...all.plateaus,...all.mines].find(x=>norm(x.name).includes(q));if(found)showFeature(found.name,'Coğrafi unsur','🔎')}};$$('[data-yb41-mode]',root).forEach(b=>b.onclick=()=>{state.mode=b.dataset.yb41Mode;save();render()});$('[data-yb41-reset]',root).onclick=()=>{state={...state,mode:'standard',selected:''};save();render()};$('[data-yb41-info]',root).onclick=e=>{const b=e.target.closest('[data-yb41-open-province]');if(b){const n=b.dataset.yb41OpenProvince;document.querySelector('[data-view="provinceStudy"]')?.click();setTimeout(()=>{window.dispatchEvent(new CustomEvent('yb:province',{detail:{name:n}}))},120)}}}
function replaceDashboard(){const d=$('#view-dashboard');if(!d)return;const atlas=d.querySelector('.dashboard-layout');if(atlas){const card=atlas.querySelector('.atlas-card');if(card)card.outerHTML=`<section class="yb41-dashboard-bridge surface"><div><span class="eyebrow">TEK KANONİK HARİTA</span><h2>Türkiye Coğrafya Atlası</h2><p>Harita artık tek yerde. 81 il ve tüm coğrafya katmanları için Türkiye Haritası'na geç.</p></div><button class="btn primary" data-view="map">Haritayı aç →</button></section>`;const side=d.querySelector('.dashboard-side');if(side)side.remove()}}
function dedupeMobileNav(){const nav=$('.mobile-nav');if(!nav)return;const seen=new Set();$$('[data-view]',nav).forEach(b=>{const v=b.dataset.view;if(seen.has(v))b.remove();else seen.add(v)});const mapBtns=$$('[data-view="map"]',nav);if(mapBtns.length>1)mapBtns.slice(1).forEach(x=>x.remove())}
async function boot(){root=$('#view-map');if(!root)return;replaceDashboard();dedupeMobileNav();try{geo=await loadGeo();render()}catch(e){root.innerHTML=`<div class="yb41-fatal"><b>Harita verisi yüklenemedi.</b><span>Yerel GeoJSON ve yedek kaynak denenmesine rağmen il sınırları alınamadı.</span><button onclick="location.reload()">Tekrar dene</button></div>`;console.error('YB41',e)}}
const obs=new MutationObserver(()=>{replaceDashboard();dedupeMobileNav();if(root?.classList.contains('active')&&!root.querySelector('.yb41-atlas')&&!root.querySelector('.yb41-fatal'))boot()});obs.observe(document.body,{subtree:true,childList:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
