/* Yurdunu Bil 45 — study-first mode
 * Map is temporarily parked. Study library, question bank and activities take priority.
 */
(()=>{
'use strict';
if(window.__YB45_STUDY__)return;
window.__YB45_STUDY__=true;
const VERSION='45.0.0';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const qs=(s,r=document)=>r.querySelector(s), qsa=(s,r=document)=>[...r.querySelectorAll(s)];
const topics=()=>Array.isArray(window.TOPICS)?window.TOPICS:[];
const bank=()=>Array.isArray(window.QUESTION_BANK)?window.QUESTION_BANK:[];
const activityData=[
['🧠','Hızlı eşleştirme','İklim → bitki → ürün','Bir iklim özelliğini doğru bitki veya tarım ürünüyle eşleştir.'],
['⛰️','Yer şekli avı','Dağ mı, ova mı, plato mu?','Verilen özelliğin hangi yer şekline ait olduğunu 60 saniyede bul.'],
['💧','Su kaynakları','Akarsu → deniz / göl → oluşum','Akarsu ve gölleri oluşumlarıyla birlikte sınıflandır.'],
['🌾','Tarım kodları','Ürün → bölge → il','Çay, fındık, zeytin, pamuk ve buğdayı konumlarıyla eşleştir.'],
['⛏️','Maden hafızası','Maden → çıkarıldığı alan','Bor, taş kömürü, krom, demir ve bakır için hızlı tekrar yap.'],
['👥','Nüfus mantığı','Yoğunluk neden değişir?','İklim + yer şekli + ekonomi üçlüsüyle nüfus sorularını çöz.'],
['🗺️','Bölge kartları','7 bölgeyi tek bakışta ayır','Her bölge için ayırt edici 3 ipucunu hatırla.'],
['⚡','KPSS hız turu','10 soruda karma tekrar','Kısa bir karma testle zayıf olduğun konuyu yakala.'],
['✍️','Boşluk doldur','Cümleyi tamamla','Coğrafi kavramları eksik kelimeyi bulma yöntemiyle pekiştir.'],
['🔗','Neden–sonuç zinciri','Konum → sonuç','Bir coğrafi özelliğin sonucunu adım adım kur.'],
['🎯','Yanlış avcısı','Çeldiriciyi yakala','KPSS tipi seçeneklerde kesinlik ve neden-sonuç hatalarını ayıkla.'],
['🏁','Gün sonu tekrar','3 dakika kapanış','Bugün öğrendiğin bilgileri mini kartlarla tekrar et.']
];
function topicCount(id){return bank().filter(q=>String(q.topic)===String(id)).length}
function ensureEventsView(){const wrap=qs('#page-wrap');if(!wrap)return null;let v=qs('#view-events');if(!v){v=document.createElement('section');v.id='view-events';v.className='view';wrap.appendChild(v)}return v}
function addNav(){const side=qs('.side-nav');if(side&&!qs('.nav-item[data-view="events"]',side)){const b=document.createElement('button');b.className='nav-item yb45-events-nav';b.dataset.view='events';b.innerHTML='<span>◈</span>Etkinlikler <em>Yeni</em>';const anchor=qs('.nav-item[data-view="quiz"]',side);if(anchor)anchor.after(b);else side.appendChild(b)}qsa('.nav-item[data-view="map"]').forEach(b=>{b.classList.add('yb45-map-soon');if(!b.querySelector('.yb45-soon')){const s=document.createElement('em');s.className='yb45-soon';s.textContent='Yakında';b.appendChild(s)}})}
function comingSoon(){return `<div class="yb45-soon-page"><div class="yb45-orbit"><span>⌖</span></div><span class="eyebrow">HARİTA MODÜLÜ • GELİŞTİRİLİYOR</span><h1>Harita yakında yeniden geliyor.</h1><p>Harita motorunu daha sağlam, daha doğru ve KPSS'ye daha faydalı hale getiriyoruz. Şimdilik haritayı kapattık; çalışma deneyimini <b>Kütüphane + Soru Bankası + Etkinlikler</b> üzerinden büyütüyoruz.</p><div class="yb45-soon-grid"><article><b>01</b><strong>81 il</strong><span>İl kartları ve konum ilişkileri</span></article><article><b>02</b><strong>Katmanlar</strong><span>Dağ, ova, plato, göl ve akarsu</span></article><article><b>03</b><strong>KPSS bağlantısı</strong><span>Harita bilgisi doğrudan sorulara bağlanacak</span></article></div><div class="yb45-soon-actions"><button class="btn primary" data-view="library">📚 Kütüphaneye geç</button><button class="btn secondary" data-view="quiz">⚡ Soru bankasını aç</button><button class="btn secondary" data-view="events">◈ Etkinliklere bak</button></div><div class="yb45-coming-pill"><i></i> Yakında sizlerle • Harita 2.0 hazırlanıyor</div></div>`}
function renderMap(){const v=qs('#view-map');if(!v)return;v.innerHTML=comingSoon();v.dataset.yb45='map-parked'}
function library(){const v=qs('#view-library');if(!v)return;const total=bank().length;v.innerHTML=`<div class="yb45-head"><div><span class="eyebrow">ÇALIŞMA KÜTÜPHANESİ • 45</span><h1>Ezber değil, bağlantı kur.</h1><p>Her konu kısa özet, sınav mantığı, hızlı tekrar ve soru bankasıyla birlikte çalışılır.</p></div><div class="yb45-head-actions"><button class="btn primary" data-view="quiz">⚡ Soru çöz</button><button class="btn secondary" data-view="events">◈ Etkinlikler</button></div></div><div class="yb45-stat-strip"><div><b>${topics().length}</b><span>ana konu</span></div><div><b>${total}+</b><span>soru</span></div><div><b>${activityData.length}</b><span>etkinlik</span></div><div><b>∞</b><span>tekrar</span></div></div><section class="yb45-topic-grid">${topics().map((t,i)=>`<article class="yb45-topic-card" data-topic-card="${esc(t.id)}"><div class="yb45-topic-top"><span>${esc(t.icon||'📘')}</span><small>${String(i+1).padStart(2,'0')} • ${esc(t.level||'KPSS')}</small></div><h2>${esc(t.title)}</h2><p>${esc(t.desc||'')}</p><div class="yb45-topic-meta"><span>⏱ ${Number(t.minutes||10)} dk</span><span>✓ ${topicCount(t.id)} soru</span></div><div class="yb45-topic-actions"><button class="btn secondary yb45-read" data-topic="${esc(t.id)}">Hızlı notları aç</button><button class="btn ghost" data-topic-quiz="${esc(t.id)}">Bu konudan çöz →</button></div></article>`).join('')}</section><section class="yb45-study-banner"><div><span class="eyebrow">BUGÜNÜN ÇALIŞMA DÖNGÜSÜ</span><h2>15 dk öğren → 10 soru çöz → 1 etkinlik yap.</h2><p>Önce kavramı öğren, sonra soru kökünde gör, en son etkinlikle kalıcılaştır.</p></div><button class="btn primary" data-view="events">Çalışmaya başla →</button></section>`;qsa('[data-topic]',v).forEach(b=>b.addEventListener('click',()=>openTopic(b.dataset.topic)));qsa('[data-topic-quiz]',v).forEach(b=>b.addEventListener('click',()=>quizStart(b.dataset.topic)))}
function openTopic(id){const t=topics().find(x=>String(x.id)===String(id));if(!t)return;let m=qs('#yb45-modal');if(!m){m=document.createElement('div');m.id='yb45-modal';document.body.appendChild(m)}m.innerHTML=`<div class="yb45-modal-backdrop" data-close></div><article class="yb45-modal-card"><button class="yb45-modal-close" data-close>×</button><span class="eyebrow">${esc(t.level||'KPSS')}</span><h2>${esc(t.icon||'📘')} ${esc(t.title)}</h2><p>${esc(t.desc||'')}</p><div class="yb45-note-list">${(Array.isArray(t.bullets)?t.bullets:[]).map((x,i)=>`<div><b>${String(i+1).padStart(2,'0')}</b><span>${esc(x)}</span></div>`).join('')}</div><div class="yb45-tip"><strong>🎯 KPSS PÜF NOKTASI</strong><p>${esc(t.tip||'Bu başlığı soru köküyle birlikte tekrar et.')}</p></div><div class="yb45-modal-actions"><button class="btn primary" data-modal-quiz="${esc(t.id)}">Bu konudan 10 soru çöz</button><button class="btn secondary" data-close>Kapat</button></div></article></div>`;m.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>m.remove());m.querySelector('[data-modal-quiz]').onclick=()=>{m.remove();quizStart(t.id)}}
function questionBankView(){const v=qs('#view-quiz');if(!v)return;const counts={all:bank().length,kolay:bank().filter(q=>q.difficulty==='kolay').length,orta:bank().filter(q=>q.difficulty==='orta').length,zor:bank().filter(q=>q.difficulty==='zor').length};v.innerHTML=`<div class="yb45-head"><div><span class="eyebrow">SORU BANKASI • KPSS MANTIĞI</span><h1>Önce düşün, sonra işaretle.</h1><p>Soru kökü + çeldirici + açıklama mantığıyla çalış. Her test sonunda hangi konuda zorlandığını gör.</p></div></div><div class="yb45-quiz-dashboard"><article class="yb45-quiz-launch"><span>⚡</span><div><small>HIZLI TEST</small><h2>10 soruluk karma tur</h2><p>Konular dengeli karışır, süre baskısı olmadan çözersin.</p></div><button class="btn primary" data-start-quiz="all">Başlat →</button></article><article class="yb45-quiz-launch"><span>🎯</span><div><small>ZAYIF KONU</small><h2>Bir konu seç</h2><p>Kütüphaneden konu seçerek sadece o başlıktan soru çöz.</p></div><button class="btn secondary" data-view="library">Konu seç →</button></article></div><div class="yb45-difficulty"><div><b>${counts.all}</b><span>Toplam</span></div><div><b>${counts.kolay}</b><span>Kolay</span></div><div><b>${counts.orta}</b><span>Orta</span></div><div><b>${counts.zor}</b><span>Zor</span></div></div><section class="yb45-bank-list"><div class="yb45-section-title"><div><span class="eyebrow">KONU DAĞILIMI</span><h2>Hangi başlıkta kaç soru var?</h2></div></div>${topics().map(t=>`<button class="yb45-bank-row" data-bank-topic="${esc(t.id)}"><span>${esc(t.icon||'📘')}</span><div><b>${esc(t.title)}</b><small>${esc(t.desc||'')}</small></div><strong>${topicCount(t.id)} soru →</strong></button>`).join('')}</section>`;qsa('[data-start-quiz]',v).forEach(b=>b.onclick=()=>quizStart(null));qsa('[data-bank-topic]',v).forEach(b=>b.onclick=()=>quizStart(b.dataset.bankTopic))}
let quizState=null;
function quizStart(topicId){const src=topicId?bank().filter(q=>String(q.topic)===String(topicId)):bank();const list=[...src].sort(()=>Math.random()-.5).slice(0,Math.min(10,src.length));if(!list.length)return;quizState={list,index:0,correct:0,answered:false,topic:topicId};const v=qs('#view-quiz');if(v)renderQuizQuestion()}
function renderQuizQuestion(){const v=qs('#view-quiz'),s=quizState,q=s.list[s.index];if(!v||!q)return;const t=topics().find(x=>String(x.id)===String(q.topic));v.innerHTML=`<div class="yb45-question-wrap"><div class="yb45-q-top"><button class="btn ghost" data-view="quiz">← Soru bankası</button><span>${s.index+1} / ${s.list.length}</span></div><div class="yb45-progress"><i style="width:${((s.index)/s.list.length)*100}%"></i></div><article class="yb45-question-card"><div class="yb45-q-meta"><span>${esc(t?.icon||'📘')} ${esc(t?.title||'Türkiye Coğrafyası')}</span><span>${esc(q.difficulty||'orta')}</span></div><h1>${esc(q.q)}</h1><div class="yb45-options">${q.options.map((o,i)=>`<button data-answer="${i}"><b>${String.fromCharCode(65+i)}</b><span>${esc(o)}</span></button>`).join('')}</div><div class="yb45-explain" hidden></div></article></div>`;qsa('[data-answer]',v).forEach(b=>b.onclick=()=>answer(Number(b.dataset.answer)))}
function answer(i){const s=quizState,q=s.list[s.index],v=qs('#view-quiz');if(!v||s.answered)return;s.answered=true;qsa('[data-answer]',v).forEach((b,n)=>{b.disabled=true;b.classList.toggle('correct',n===Number(q.answer));b.classList.toggle('wrong',n===i&&n!==Number(q.answer))});if(i===Number(q.answer))s.correct++;const box=qs('.yb45-explain',v);if(box){box.hidden=false;box.innerHTML=`<strong>${i===Number(q.answer)?'✓ Doğru!':'✕ Bu kez olmadı.'}</strong><p>${esc(q.explain||'Doğru seçeneği soru köküyle ilişkilendirerek tekrar et.')}</p><button class="btn primary" data-next>${s.index+1<s.list.length?'Sonraki soru →':'Sonucu gör →'}</button>`;box.querySelector('[data-next]').onclick=()=>{if(s.index+1<s.list.length){s.index++;s.answered=false;renderQuizQuestion()}else quizResult()}}}
function quizResult(){const s=quizState,v=qs('#view-quiz'),pct=Math.round(s.correct/s.list.length*100);try{const a=JSON.parse(localStorage.getItem('yb_v45_results')||'[]');a.push({correct:s.correct,total:s.list.length,score:pct,topic:s.topic||'all',created_at:new Date().toISOString()});localStorage.setItem('yb_v45_results',JSON.stringify(a.slice(-50)))}catch{};v.innerHTML=`<div class="yb45-result"><span class="eyebrow">TEST TAMAMLANDI</span><div class="yb45-score-ring"><strong>%${pct}</strong><span>${s.correct} / ${s.list.length} doğru</span></div><h1>Güzel. Şimdi yanlışlarını avantaja çevir.</h1><p>${pct>=80?'Bu konu oturmaya başlamış. Şimdi daha zor çeldiricilere geç.':pct>=60?'Temel var; birkaç hedefli tekrar netlerini yükseltir.':'Sorun değil. Kütüphaneden kısa notları okuyup aynı konudan tekrar çöz.'}</p><div class="yb45-result-actions"><button class="btn primary" data-retry>Tekrar çöz</button><button class="btn secondary" data-view="library">Kütüphaneye dön</button><button class="btn secondary" data-view="events">Etkinlik yap</button></div></div>`;v.querySelector('[data-retry]').onclick=()=>quizStart(s.topic)}
function events(){const v=ensureEventsView();if(!v)return;v.innerHTML=`<div class="yb45-head"><div><span class="eyebrow">ETKİLEŞİMLİ ÇALIŞMA • YENİ</span><h1>Bilgiyi harekete geçir.</h1><p>Okuduktan sonra uygula. Kısa etkinlikler, coğrafya bilgisini soru çözme hızına dönüştürmek için tasarlandı.</p></div><div class="yb45-head-actions"><button class="btn primary" data-view="quiz">⚡ Teste geç</button></div></div><div class="yb45-activity-intro"><div><b>12</b><span>mini etkinlik</span></div><p>Bugün yalnızca 2 tane yapman bile yeterli. Amaç çok şey açmak değil, öğrendiğini kullanmak.</p></div><section class="yb45-activity-grid">${activityData.map((a,i)=>`<article class="yb45-activity-card"><div class="yb45-activity-icon">${a[0]}</div><span>${String(i+1).padStart(2,'0')} • ${esc(a[1])}</span><h2>${esc(a[2])}</h2><p>${esc(a[3])}</p><button class="btn secondary" data-activity="${i}">Etkinliği başlat →</button></article>`).join('')}</section>`;qsa('[data-activity]',v).forEach(b=>b.onclick=()=>openActivity(Number(b.dataset.activity)))}
function openActivity(i){const a=activityData[i];let m=qs('#yb45-modal');if(!m){m=document.createElement('div');m.id='yb45-modal';document.body.appendChild(m)}m.innerHTML=`<div class="yb45-modal-backdrop" data-close></div><article class="yb45-modal-card"><button class="yb45-modal-close" data-close>×</button><span class="eyebrow">${esc(a[1])}</span><h2>${a[0]} ${esc(a[2])}</h2><p>${esc(a[3])}</p><div class="yb45-activity-task"><strong>🎯 Görev</strong><p>Önce cevabı kendi zihninde kur. Ardından Kütüphane'den ilgili başlığın hızlı notlarını aç ve cevabını kontrol et.</p><button class="btn primary" data-view="library">İlgili notlara git →</button></div><div class="yb45-tip"><strong>⏱ 3–5 DAKİKA</strong><p>Etkinliği kısa tut. Takıldığın noktayı not alıp hemen 5–10 soruluk tekrar yap.</p></div><button class="btn secondary" data-close>Kapat</button></article></div>`;m.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>m.remove());m.querySelector('[data-view]')?.addEventListener('click',()=>m.remove())}
function setActive(v){qsa('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));qsa('.nav-item[data-view],.mobile-nav [data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const title={library:'Kütüphane',quiz:'Mini Test',events:'Etkinlikler',map:'Türkiye Haritası'}[v]||'Genel Bakış';const p=qs('#page-title');if(p)p.textContent=title;const wrap=qs('#page-wrap');if(wrap)wrap.scrollTop=0}
function render(v){addNav();if(v==='map'){renderMap();setActive('map');return}if(v==='library'){library();setActive('library');return}if(v==='quiz'){if(!quizState)questionBankView();else renderQuizQuestion();setActive('quiz');return}if(v==='events'){events();setActive('events');return}}
function hideDashboardMap(){const d=qs('#view-dashboard');if(!d)return;const layout=qs('.dashboard-layout',d);if(layout){layout.dataset.yb45Hidden='1';layout.style.display='none'}qsa('.atlas-shell,.atlas-card',d).forEach(x=>{if(!x.closest('.yb45-study-focus'))x.style.display='none'});if(!qs('.yb45-study-focus',d)){const intro=qs('.dashboard-intro',d);if(intro){const s=document.createElement('section');s.className='yb45-study-focus';s.innerHTML=`<div><span class="eyebrow">HARİTA GEÇİCİ OLARAK KAPALI • ÇALIŞMA ODAĞI AÇIK</span><h2>Şimdi bilgi → soru → etkinlik döngüsüne geç.</h2><p>Harita motorunu yenilerken içerik tarafını büyütüyoruz. Kütüphanede konuyu öğren, soru bankasında ölç, etkinliklerle pekiştir.</p></div><div><button class="btn primary" data-view="library">📚 Kütüphane</button><button class="btn secondary" data-view="quiz">⚡ Soru Bankası</button><button class="btn secondary" data-view="events">◈ Etkinlikler</button></div>`;intro.after(s)}}}
function hook(){addNav();document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;const v=b.dataset.view;if(v==='events'||v==='map'||v==='library'||v==='quiz'){setTimeout(()=>render(v),0)}});const obs=new MutationObserver(()=>{const a=qs('.view.active')?.id?.replace('view-','');if(a==='dashboard')hideDashboardMap();if(a==='map')renderMap();if(a==='library'&&!qs('.yb45-topic-grid'))library();if(a==='quiz'&&!qs('.yb45-quiz-dashboard')&&!qs('.yb45-question-wrap')&&!qs('.yb45-result'))questionBankView();if(a==='events'&&!qs('.yb45-activity-grid'))events();addNav()});obs.observe(document.body,{childList:true,subtree:true});hideDashboardMap()}
window.YB45={version:VERSION,render,topics,questions:bank,activities:activityData};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',hook,{once:true});else hook();
})();
