/* Yurdunu Bil 48 — stable event games hub */
(()=>{'use strict';
if(window.__YB48_GAMES__)return;window.__YB48_GAMES__=true;
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)],esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),n=v=>String(v??'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c').trim();
const REG=[['Marmara','Sanayi, ticaret ve ulaşım gelişmiştir.'],['Ege','Zeytin, üzüm ve incir üretimi önemlidir.'],['Akdeniz','Turunçgil, seracılık ve yaz turizmi gelişmiştir.'],['Karadeniz','Her mevsim yağışlı; çay ve fındık öne çıkar.'],['İç Anadolu','Bozkır yaygın; buğday tarımı önemlidir.'],['Doğu Anadolu','Yükselti fazla; nüfus yoğunluğu genellikle düşüktür.'],['Güneydoğu Anadolu','Yazlar sıcak-kurak; Antep fıstığı önemlidir.']];
const BLANK=[['Türkiye’nin yüz ölçümü en büyük ili ____ ilidir.','Konya',['Konya','Sivas','Ankara','Erzurum']],['Türkiye’nin en uzun akarsuyu ____’dır.','Kızılırmak',['Kızılırmak','Fırat','Dicle','Sakarya']],['Çay tarımında ____ ili öne çıkar.','Rize',['Rize','Ordu','Aydın','Konya']],['Taş kömürü ile özdeşleşen il ____’dır.','Zonguldak',['Zonguldak','Soma','Batman','Elazığ']],['Türkiye’nin en büyük gölü ____ Gölü’dür.','Van',['Van','Tuz','Beyşehir','Eğirdir']],['Bafra Ovası ____ Nehri deltasındadır.','Kızılırmak',['Kızılırmak','Yeşilırmak','Sakarya','Meriç']],['Menteşe Yöresi ____ Bölgesi’ndedir.','Ege',['Ege','Akdeniz','Marmara','Karadeniz']],['Karstik şekiller en çok ____ Bölgesi’nde görülür.','Akdeniz',['Akdeniz','Marmara','Karadeniz','Doğu Anadolu']],['Türkiye’nin en doğusundaki il ____’dır.','Iğdır',['Iğdır','Kars','Ardahan','Van']],['Çukurova ____ ve Ceyhan’ın alüvyonlarıyla oluşmuştur.','Seyhan',['Seyhan','Fırat','Dicle','Gediz']]];
const TF=[['Türkiye’de yağışın en fazla olduğu kıyı kuşağı genel olarak Karadeniz’dir.',true],['Konya, yüz ölçümü bakımından Türkiye’nin en büyük ilidir.',true],['Tuz Gölü Türkiye’nin en büyük gölüdür.',false],['Ege’de horst-graben sistemi görülür.',true],['Zonguldak taş kömürü ile özdeşleşmiştir.',true],['Nüfus yoğunluğu en yüksek bölge Doğu Anadolu’dur.',false],['Çukurova Akdeniz Bölgesi’ndedir.',true],['Bafra Ovası Yeşilırmak deltasında oluşmuştur.',false],['Bozkır İç Anadolu’da yaygındır.',true],['Menteşe Yöresi Karadeniz Bölgesi’ndedir.',false]];
const CLUE=[['İç Anadolu’da; yüz ölçümü Türkiye’nin en büyük ilidir.','Konya'],['Çay tarımıyla özdeşleşen Doğu Karadeniz ilidir.','Rize'],['Taş kömürü havzasının merkezidir.','Zonguldak'],['Marmara’nın nüfus ve sanayi merkezidir.','İstanbul'],['Palandöken Dağları ile özdeşleşmiştir.','Erzurum'],['Fındık üretimiyle Karadeniz’de öne çıkar.','Ordu'],['Aras Nehri havzasında, Türkiye’nin en doğusundadır.','Iğdır'],['Ege’de zeytin ve pamuk tarımıyla öne çıkar.','Aydın']];
const PROV=['Adana','Afyonkarahisar','Ağrı','Amasya','Ankara','Antalya','Artvin','Aydın','Balıkesir','Bursa','Çanakkale','Erzurum','Iğdır','İstanbul','İzmir','Konya','Manisa','Mersin','Ordu','Rize','Samsun','Sivas','Trabzon','Van','Zonguldak'];
const S={mode:'',i:0,score:0,used:false,timer:null,deadline:0};
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function css(){if(q('#yb48-css'))return;const s=document.createElement('style');s.id='yb48-css';s.textContent=`#view-events .yb48{max-width:1180px;margin:auto;padding:8px 0 72px}.yb48-hero{padding:25px 4px}.yb48-k{font-size:10px;font-weight:900;letter-spacing:.16em;color:#72e6d5}.yb48 h1{margin:8px 0;font-size:clamp(27px,4vw,42px);letter-spacing:-.04em}.yb48 p{color:#91a4ba;line-height:1.6}.yb48-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.yb48-card,.yb48-box{border:1px solid rgba(255,255,255,.08);border-radius:22px;background:rgba(255,255,255,.045);box-shadow:0 16px 50px rgba(0,0,0,.18)}.yb48-card{padding:20px;min-height:190px}.yb48-card h3{margin:10px 0 7px}.yb48-card p{font-size:13px;min-height:44px}.yb48-icon{font-size:28px}.yb48-btn{border:0;border-radius:12px;padding:11px 15px;background:#79e6d6;color:#06101d;font-weight:850;cursor:pointer}.yb48-btn.alt{background:rgba(255,255,255,.08);color:#dce7f0}.yb48-box{padding:22px}.yb48-top{display:flex;gap:9px;justify-content:space-between;flex-wrap:wrap}.yb48-pill{padding:8px 11px;border-radius:99px;background:rgba(255,255,255,.07);font-size:12px;font-weight:800}.yb48-q{font-size:clamp(21px,3vw,30px);font-weight:850;line-height:1.35;margin:25px 0}.yb48-opts{display:grid;grid-template-columns:repeat(2,1fr);gap:11px}.yb48-opt{border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.045);color:#e8f0f7;border-radius:15px;padding:16px;text-align:left;font-weight:750;cursor:pointer}.yb48-opt.good{border-color:#65e6c8;background:rgba(65,220,180,.12)}.yb48-opt.bad{border-color:#ff8799;background:rgba(255,80,110,.1)}.yb48-match{display:grid;grid-template-columns:1fr 1fr;gap:16px}.yb48-col{display:grid;gap:9px}.yb48-opt.active{outline:2px solid #79e6d6}.yb48-feedback{min-height:25px;margin-top:15px;font-weight:750;color:#9aacbf}.yb48-result{text-align:center;padding:40px}.yb48-big{font-size:64px;font-weight:950}.yb48-actions{display:flex;justify-content:center;gap:10px;flex-wrap:wrap;margin-top:22px}@media(max-width:800px){.yb48-grid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.yb48-grid,.yb48-opts,.yb48-match{grid-template-columns:1fr}.yb48-box{padding:16px}}`;document.head.appendChild(s)}
function stats(){try{return JSON.parse(localStorage.getItem('yb48_stats')||'{"xp":0,"games":0}')}catch{return {xp:0,games:0}}}
function award(xp){const s=stats();s.xp+=xp;s.games++;try{localStorage.setItem('yb48_stats',JSON.stringify(s))}catch{}return s}
function shell(title,sub,body){const v=q('#view-events');v.innerHTML=`<div class="yb48"><section class="yb48-hero"><div class="yb48-k">OYUN MERKEZİ</div><h1>${title}</h1><p>${sub}</p></section><section class="yb48-box">${body}</section></div>`;return v}
function done(title,msg,score,max=100){if(S.timer)clearInterval(S.timer);const pct=Math.max(0,Math.min(100,Math.round(score/max*100))),xp=Math.max(10,Math.round(pct*.7)),st=award(xp),v=q('#view-events');v.innerHTML=`<div class="yb48"><section class="yb48-box yb48-result"><div class="yb48-k">TUR TAMAMLANDI</div><div class="yb48-big">${pct}%</div><h2>${title}</h2><p>${msg}</p><div class="yb48-pill">+${xp} XP • Toplam ${st.xp} XP</div><div class="yb48-actions"><button class="yb48-btn" data-again>Tekrar Oyna</button><button class="yb48-btn alt" data-back>Etkinliklere Dön</button></div></section></div>`;q('[data-again]',v).onclick=()=>start(S.mode);q('[data-back]',v).onclick=events}
function events(){css();const v=q('#view-events');if(!v)return;v.dataset.yb48='1';const s=stats();v.innerHTML=`<div class="yb48"><section class="yb48-hero"><div class="yb48-k">YURDUNU BİL • ETKİNLİKLER</div><h1>Öğrenmeyi oyuna çevir.</h1><p>Eşleştir, boşluk doldur, doğru bilgiyi yakala ve il ipuçlarını çöz. Oyunlar gerçekten çalışır ve her tur XP kazandırır.</p><div class="yb48-pill">${s.xp} XP • ${s.games} tamamlanan oyun • 5 oyun modu</div></section><section class="yb48-grid">${[['🔗','Bölge Eşleştirme','7 bölgeyi doğru özelliğiyle eşleştir.','match'],['✍️','Boşluk Doldur','10 KPSS cümlesindeki eksik kavramı bul.','blank'],['⚖️','Doğru / Yanlış','10 bilgiyle tuzakları yakala.','tf'],['🧭','İl Avı','8 konum ve üretim ipucundan ili bul.','province'],['⚡','Hızlı 10','90 saniyede 10 soru çöz.','speed']].map(x=>`<article class="yb48-card"><div class="yb48-icon">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p><button class="yb48-btn" data-start="${x[3]}">Oyuna Başla →</button></article>`).join('')}</section></div>`;qa('[data-start]',v).forEach(b=>b.onclick=()=>start(b.dataset.start))}
function start(mode){S.mode=mode;S.i=0;S.score=0;S.used=false;S.selected=null;if(S.timer)clearInterval(S.timer);if(mode==='match')match();else if(mode==='blank')blank();else if(mode==='tf')tf();else if(mode==='province')province();else speed()}
function match(){S.pairs=shuffle(REG);S.left=shuffle(S.pairs.map(x=>x[0]));S.right=shuffle(S.pairs.map(x=>x[1]));renderMatch()}
function renderMatch(){const v=shell('Bölge Eşleştirme','Bir bölge seç, sonra doğru özelliğine dokun.',`<div class="yb48-top"><span class="yb48-pill">${S.i+1} / 7 eşleşme</span><span class="yb48-pill">${Math.round(S.score)} puan</span></div><div class="yb48-match"><div class="yb48-col" id="ml">${S.left.map(x=>`<button class="yb48-opt" data-left="${esc(x)}">${esc(x)}</button>`).join('')}</div><div class="yb48-col" id="mr">${S.right.map(x=>`<button class="yb48-opt" data-right="${esc(x)}">${esc(x)}</button>`).join('')}</div></div><div class="yb48-feedback" id="mf">Önce bir bölge seç.</div>`);qa('[data-left]',v).forEach(b=>b.onclick=()=>{qa('[data-left]',v).forEach(x=>x.classList.remove('active'));b.classList.add('active');S.selected=b.dataset.left;q('#mf').textContent='Şimdi doğru özelliği seç.'});qa('[data-right]',v).forEach(b=>b.onclick=()=>{if(!S.selected)return;const pair=S.pairs.find(x=>x[0]===S.selected),ok=n(pair?.[1])===n(b.dataset.right);if(ok){S.score+=100/7;S.i++;b.classList.add('good');q('#mf').textContent='Doğru eşleşme!';setTimeout(()=>S.i>=7?done('Bölgeleri eşleştirdin!','İklim, tarım, nüfus ve ekonomi bağlarını kurdun.',S.score):match(),350)}else{b.classList.add('bad');q('#mf').textContent='Yanlış. İklim ve üretim özelliğini düşün.';setTimeout(()=>b.classList.remove('bad'),450)}})}
function blank(){S.items=shuffle(BLANK);renderBlank()}
function renderBlank(){const x=S.items[S.i],v=shell('Boşluk Doldur','Eksik kavramı seç ve hemen geri bildirim al.',`<div class="yb48-top"><span class="yb48-pill">Tur ${S.i+1} / 10</span><span class="yb48-pill">${S.score} puan</span></div><div class="yb48-q">${esc(x[0])}</div><div class="yb48-opts">${shuffle(x[2]).map(o=>`<button class="yb48-opt" data-o="${esc(o)}">${esc(o)}</button>`).join('')}</div><div class="yb48-feedback" id="bf"></div>`);qa('[data-o]',v).forEach(b=>b.onclick=()=>{if(S.used)return;S.used=true;const ok=n(b.dataset.o)===n(x[1]);b.classList.add(ok?'good':'bad');if(ok)S.score+=10;qa('[data-o]',v).forEach(o=>o.disabled=true);q('#bf').textContent=ok?'Doğru!':'Doğru cevap: '+x[1];setTimeout(()=>{S.used=false;S.i++;S.i>=10?done('Boşluklar tamam!','10 kritik bilgiyi pekiştirdin.',S.score):renderBlank()},450)})}
function tf(){S.items=shuffle(TF);renderTF()}
function renderTF(){const x=S.items[S.i],v=shell('Doğru / Yanlış','Bilginin doğru mu yoksa KPSS tuzağı mı olduğunu seç.',`<div class="yb48-top"><span class="yb48-pill">Tur ${S.i+1} / 10</span><span class="yb48-pill">${S.score} puan</span></div><div class="yb48-q">${esc(x[0])}</div><div class="yb48-opts"><button class="yb48-opt" data-t="1">✓ Doğru</button><button class="yb48-opt" data-t="0">✕ Yanlış</button></div><div class="yb48-feedback" id="tf"></div>`);qa('[data-t]',v).forEach(b=>b.onclick=()=>{if(S.used)return;S.used=true;const ok=Number(b.dataset.t)===Number(x[1]);b.classList.add(ok?'good':'bad');if(ok)S.score+=10;qa('[data-t]',v).forEach(o=>o.disabled=true);q('#tf').textContent=ok?'Doğru karar!':`Cevap: ${x[1]?'Doğru':'Yanlış'}`;setTimeout(()=>{S.used=false;S.i++;S.i>=10?done('Tuzakları yakaladın!','Doğru/yanlış refleksini geliştirdin.',S.score):renderTF()},400)})}
function province(){S.items=shuffle(CLUE);renderProvince()}
function renderProvince(){const x=S.items[S.i],opts=shuffle([x[1],...shuffle(PROV.filter(p=>n(p)!==n(x[1]))).slice(0,3)]),v=shell('İl Avı','İpucunu oku ve doğru ili seç.',`<div class="yb48-top"><span class="yb48-pill">İpucu ${S.i+1} / 8</span><span class="yb48-pill">${Math.round(S.score)} puan</span></div><div class="yb48-q">${esc(x[0])}</div><div class="yb48-opts">${opts.map(o=>`<button class="yb48-opt" data-p="${esc(o)}">${esc(o)}</button>`).join('')}</div><div class="yb48-feedback" id="pf"></div>`);qa('[data-p]',v).forEach(b=>b.onclick=()=>{if(S.used)return;S.used=true;const ok=n(b.dataset.p)===n(x[1]);b.classList.add(ok?'good':'bad');if(ok)S.score+=12.5;qa('[data-p]',v).forEach(o=>o.disabled=true);q('#pf').textContent=ok?'İsabet!':'Doğru il: '+x[1];setTimeout(()=>{S.used=false;S.i++;S.i>=8?done('İl Avı tamam!','Konum ve üretim ipuçlarını doğru illere bağladın.',S.score):renderProvince()},450)})}
function speed(){S.items=shuffle(BLANK.map(x=>[x[0],x[1],x[2]])).slice(0,10);S.deadline=Date.now()+90000;renderSpeed();S.timer=setInterval(()=>{const left=Math.max(0,Math.ceil((S.deadline-Date.now())/1000)),t=q('#st');if(t)t.textContent=left+' sn';if(left<=0){clearInterval(S.timer);done('Süre doldu!','Hızlı 10 turunu tamamladın.',S.score)}},500)}
function renderSpeed(){const x=S.items[S.i],v=shell('Hızlı 10','90 saniye. Her doğru +10 puan.',`<div class="yb48-top"><span class="yb48-pill">Tur ${S.i+1} / 10</span><span class="yb48-pill">${S.score} puan</span><span class="yb48-pill" id="st">90 sn</span></div><div class="yb48-q">${esc(x[0])}</div><div class="yb48-opts">${shuffle(x[2]).map(o=>`<button class="yb48-opt" data-s="${esc(o)}">${esc(o)}</button>`).join('')}</div><div class="yb48-feedback" id="sf"></div>`);qa('[data-s]',v).forEach(b=>b.onclick=()=>{if(S.used)return;S.used=true;const ok=n(b.dataset.s)===n(x[1]);b.classList.add(ok?'good':'bad');if(ok)S.score+=10;qa('[data-s]',v).forEach(o=>o.disabled=true);q('#sf').textContent=ok?'Doğru!':'Doğru cevap: '+x[1];setTimeout(()=>{S.used=false;S.i++;S.i>=10?done('Hızlı 10 tamam!','Süreli turu bitirdin.',S.score):renderSpeed()},250)})}
function install(){css();let tries=0;const tick=()=>{tries++;if(q('#view-events')&&!q('#view-events').dataset.yb48){events();return}if(tries<50)setTimeout(tick,200)};tick();new MutationObserver(()=>{if(q('#view-events')&&!q('#view-events').dataset.yb48)events()}).observe(document.body,{subtree:true,childList:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();window.YB48Games={events,start,version:'48.0.0'};
})();