/* Yurdunu Bil 52 — progression, streaks, missions, wrong notebook */
(()=>{'use strict';
if(window.__YB52_GAMES__)return;window.__YB52_GAMES__=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEY='yb52_progress_v1';
const DEF={xp:0,answers:0,correct:0,bestStreak:0,streak:0,lastDay:'',wrong:[],modes:{},achievements:[],daily:{date:'',answers:0,correct:0,reviewed:0}};
let data=load(),lastFeedbackKey='';
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return {...DEF,...x,modes:x.modes||{},wrong:Array.isArray(x.wrong)?x.wrong:[],achievements:Array.isArray(x.achievements)?x.achievements:[],daily:{...DEF.daily,...(x.daily||{})}}}catch{return {...DEF}}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(data))}catch{}}
function today(){return new Date().toLocaleDateString('en-CA',{timeZone:'Europe/Istanbul'})}
function level(xp){const thresholds=[0,100,250,500,850,1300,1900,2600,3500,4600,6000];let l=1;for(let i=0;i<thresholds.length;i++)if(xp>=thresholds[i])l=i+1;return l}
function levelProgress(xp){const l=level(xp),cur=[0,100,250,500,850,1300,1900,2600,3500,4600,6000][l-1]||0,next=[100,250,500,850,1300,1900,2600,3500,4600,6000,8000][l-1]||8000;return {l,cur,next,pct:Math.max(0,Math.min(100,Math.round((xp-cur)/(next-cur)*100)))}}
function day(){const d=today();if(data.lastDay!==d){const prev=new Date(Date.now()-86400000).toLocaleDateString('en-CA',{timeZone:'Europe/Istanbul'});data.streak=data.lastDay===prev?data.streak:0;data.lastDay=d}if(data.daily.date!==d)data.daily={date:d,answers:0,correct:0,reviewed:0};save()}
function award(ok,mode='Etkinlik'){day();data.answers++;data.daily.answers++;if(ok){data.correct++;data.daily.correct++;data.streak++;data.bestStreak=Math.max(data.bestStreak,data.streak);const bonus=Math.min(25,Math.max(0,(data.streak-1)*2));data.xp+=10+bonus}else data.streak=0;const k=String(mode||'Etkinlik');data.modes[k]=data.modes[k]||{a:0,c:0};data.modes[k].a++;if(ok)data.modes[k].c++;achievements();save();renderHub()}
function achievements(){const a=new Set(data.achievements);if(data.correct>=1)a.add('first');if(data.correct>=10)a.add('correct10');if(data.correct>=25)a.add('correct25');if(data.bestStreak>=5)a.add('streak5');if(data.answers>=100)a.add('answers100');if(data.xp>=1000)a.add('xp1000');data.achievements=[...a]}
function missions(){day();return[{id:'q10',label:'10 soru çöz',goal:10,value:data.daily.answers},{id:'c7',label:'7 doğru yap',goal:7,value:data.daily.correct},{id:'s3',label:'3 seri yakala',goal:3,value:Math.min(data.streak,3)},{id:'r1',label:'1 yanlışını tekrar et',goal:1,value:data.daily.reviewed}]}
function decorate(){const v=$('#view-events');if(!v||v.dataset.yb52Decorated==='1')return;if(!v.querySelector('.yb51'))return;v.dataset.yb52Decorated='1';const p=levelProgress(data.xp),ms=missions(),old=v.querySelector('.yb51-hero');const dash=document.createElement('section');dash.className='yb52-dashboard';dash.innerHTML=`<div class="yb52-profile"><div class="yb52-level"><span>SEVİYE ${p.l}</span><b>${data.xp.toLocaleString('tr-TR')} XP</b><div class="yb52-bar"><i style="width:${p.pct}%"></i></div><small>${Math.max(0,p.next-data.xp)} XP sonra seviye ${p.l+1}</small></div><div class="yb52-streak"><strong>🔥 ${data.streak}</strong><span>Günlük seri</span><small>En iyi: ${data.bestStreak}</small></div><div class="yb52-correct"><strong>${data.correct}/${data.answers}</strong><span>Doğruluk</span><small>${data.answers?Math.round(data.correct/data.answers*100):0}%</small></div></div><div class="yb52-missions"><div class="yb52-title"><div><span>BUGÜN</span><h3>Günlük görevlerin</h3></div><button class="yb52-wrong-btn" data-yb52-wrongs>📕 Yanlışlarım (${data.wrong.length})</button></div><div class="yb52-mission-grid">${ms.map(m=>`<div class="yb52-mission"><div><b>${m.value>=m.goal?'✓':'○'}</b><span>${m.label}</span></div><small>${Math.min(m.value,m.goal)} / ${m.goal}</small><div class="yb52-mini"><i style="width:${Math.min(100,m.value/m.goal*100)}%"></i></div></div>`).join('')}</div></div>`;old?.insertAdjacentElement('afterend',dash);const arena=document.createElement('article');arena.className='yb52-arena-card';arena.innerHTML=`<div class="yb52-arena-icon">⚔️</div><div><span class="yb52-kicker">CANLI MULTIPLAYER</span><h3>Arena 1 VS 1</h3><p>Gerçek oyuncuya karşı canlı skor, aynı sorular ve reytingli düello.</p></div><button class="btn primary" data-yb52-arena>Arenaya Gir →</button>`;const grid=v.querySelector('.yb51-grid');if(grid)grid.appendChild(arena);$$('.yb52-wrong-btn',v).forEach(b=>b.onclick=showWrongs);$('[data-yb52-arena]',v)?.addEventListener('click',()=>window.YBArena?.open?.())}
function renderHub(){const v=$('#view-events');if(!v||!v.querySelector('.yb51'))return;v.dataset.yb52Decorated='';decorate()}
function wrongFromFeedback(){const f=$('#yb51-feedback');if(!f||!f.textContent.trim()||f.dataset.yb52Seen)return;f.dataset.yb52Seen='1';const text=f.textContent.trim();const ok=/doğru|✓/i.test(text)&&!/yanlış|✕|süre doldu/i.test(text);const q=$('.yb51-q')?.textContent?.trim()||$('.yb51-question')?.textContent?.trim()||'';if(!q)return;const mode=$('.yb51-pill')?.textContent?.trim()||'Etkinlik';const key=q.slice(0,180);if(lastFeedbackKey===key)return;lastFeedbackKey=key;if(!ok){const exists=data.wrong.find(x=>x.key===key);if(!exists){data.wrong.unshift({key,q,answer:(f.querySelector('b')?.textContent||'Doğru cevap'),note:text,mode,at:Date.now()});data.wrong=data.wrong.slice(0,60)}}award(ok,mode)}
function showWrongs(){const v=$('#view-events');if(!v)return;day();data.daily.reviewed=1;save();const items=data.wrong;const box=document.createElement('div');box.className='yb52-modal';box.innerHTML=`<div class="yb52-modal-card"><div class="yb52-modal-head"><div><span>TEKRAR DEFTERİ</span><h2>Yanlışlarım</h2></div><button data-yb52-close>×</button></div>${items.length?`<div class="yb52-wrong-list">${items.map((x,i)=>`<article><span>${i+1}</span><div><b>${escapeHtml(x.q)}</b><p>${escapeHtml(x.note)}</p><small>${escapeHtml(x.mode)}</small></div><button data-yb52-remove="${i}" title="Öğrendim">✓</button></article>`).join('')}</div>`:'<div class="yb52-empty">🎉 Şimdilik yanlış kaydın yok. Böyle devam!</div>'}<button class="btn secondary full" data-yb52-close>Kapat</button></div>`;document.body.appendChild(box);box.onclick=e=>{if(e.target===box||e.target.closest('[data-yb52-close]'))box.remove();const r=e.target.closest('[data-yb52-remove]');if(r){data.wrong.splice(Number(r.dataset.yb52Remove),1);save();box.remove();showWrongs()}}}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const observer=new MutationObserver(()=>{decorate();wrongFromFeedback()});observer.observe(document.body,{childList:true,subtree:true});setInterval(()=>{const v=$('#view-events');if(v?.querySelector('.yb51')&&!v.querySelector('.yb52-dashboard')){v.dataset.yb52Decorated='';decorate()}},800);window.YB52={get:()=>({...data}),level:()=>levelProgress(data.xp)};
})();
