/* Yurdunu Bil 59 — öğrenme merkezi + aralıklı tekrar */
(()=>{'use strict';if(window.__YB59_STUDY__)return;window.__YB59_STUDY__=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='yb59_mastery_v1',REC='yb59_recent_v1';
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}},save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
let mastery=load(KEY,{}),recent=load(REC,[]),filter='all',query='',detail=null;
const bank=()=>Array.isArray(window.QUESTION_BANK)?window.QUESTION_BANK:[], topics=()=>Array.isArray(window.TOPICS)?window.TOPICS:[];
function topicQuestions(id){return bank().filter(q=>String(q.topic||q.topic_id)===String(id))}
function stats(){const ts=topics(),done=ts.filter(t=>(mastery[t.id]?.level||0)>=3).length;return{done,total:ts.length,pct:ts.length?Math.round(done/ts.length*100):0}}
function touch(id,ok){const x=mastery[id]||{level:0,seen:0,correct:0,wrong:0,next:0};x.seen++;ok?x.correct++:x.wrong++;const acc=x.seen?x.correct/x.seen:0;x.level=Math.max(0,Math.min(5,Math.round(acc*4)+(x.seen>=5?1:0)));const days=ok?[1,2,4,7,14,30][Math.min(x.level,5)]:0.25;x.next=Date.now()+days*86400000;mastery[id]=x;save(KEY,mastery)}
function due(){const now=Date.now();return bank().filter(q=>{const m=mastery[q.id];return !m||!m.next||m.next<=now})}
function pickQuestions(id){let pool=id?topicQuestions(id):due();if(!pool.length)pool=id?topicQuestions(id):bank();const recentSet=new Set(recent);const fresh=pool.filter(q=>!recentSet.has(q.id));const source=fresh.length?fresh:pool;return [...source].sort(()=>Math.random()-.5).slice(0,10)}
function remember(ids){recent=[...ids,...recent.filter(x=>!ids.includes(x))].slice(0,60);save(REC,recent)}
function toast(t){const e=document.createElement('div');e.className='yb59-toast';e.textContent=t;document.body.appendChild(e);requestAnimationFrame(()=>e.classList.add('show'));setTimeout(()=>{e.classList.remove('show');setTimeout(()=>e.remove(),200)},1800)}
function render(){const el=$('#view-library');if(!el||!el.classList.contains('active'))return;const s=stats();if(detail){renderDetail(el);return}const list=topics().filter(t=>{const hit=!query||`${t.title} ${t.desc} ${(t.bullets||[]).join(' ')}`.toLocaleLowerCase('tr-TR').includes(query.toLocaleLowerCase('tr-TR'));const level=t.level||'Orta';const f=filter==='all'||(filter==='high'&&level==='Yüksek Getiri')||(filter==='new'&&!mastery[t.id]);return hit&&f});el.innerHTML=`<div class="yb59-wrap"><section class="yb59-hero"><span class="yb59-kicker">YENİ • ÖĞRENME & PEKİŞTİRME SİSTEMİ</span><h1>Kütüphane artık sadece not değil. 🧠</h1><p>Konuyu oku, kısa tekrar yap, ardından sorularla kendini yokla. Sistem yanlışlarını ve tekrar zamanını cihazında takip eder.</p><div class="yb59-actions"><button class="btn primary" id="yb59-due">🔁 Akıllı Tekrar</button><button class="btn secondary" id="yb59-random">🎯 Hızlı Pekiştir</button><button class="btn secondary" id="yb59-open-games">🎮 Oyunlara Hazırla</button><button class="btn ghost" id="yb59-reset">↺ İlerlemeyi sıfırla</button></div><div class="yb59-progress"><div class="yb59-progress-row"><span>Konu hakimiyeti</span><strong>%${s.pct} • ${s.done}/${s.total} konu</strong></div><div class="yb59-track"><i style="width:${s.pct}%"></i></div></div></section><div class="yb59-toolbar surface"><label class="yb59-search">⌕<input id="yb59-search" value="${esc(query)}" placeholder="Konu, kavram veya bilgi ara..."></label><div class="yb59-filters"><button class="${filter==='all'?'active':''}" data-f="all">Tümü</button><button class="${filter==='high'?'active':''}" data-f="high">Yüksek Getiri</button><button class="${filter==='new'?'active':''}" data-f="new">Yeni / Başlanmadı</button></div></div><div class="yb59-grid">${list.map(card).join('')||'<div class="yb59-empty">Aramana uygun konu bulunamadı.</div>'}</div></div>`;bind()}
function card(t){const m=mastery[t.id]||{level:0,seen:0,correct:0};const qn=topicQuestions(t.id).length;return `<article class="yb59-topic"><div class="yb59-topic-top"><span class="yb59-icon">${t.icon||'📚'}</span><span class="yb59-level">${esc(t.level||'KPSS')}</span></div><h2>${esc(t.title||t.name)}</h2><p>${esc(t.desc||'')}</p><div class="yb59-meta"><span>⏱ ${t.minutes||10} dk</span><span>❓ ${qn} soru</span><span>🧠 Seviye ${m.level}/5</span></div><div class="yb59-card-actions"><button class="btn secondary" data-detail="${esc(t.id)}">Notları Aç</button><button class="btn primary" data-practice="${esc(t.id)}">Pekiştir</button></div></article>`}
function renderDetail(el){const t=topics().find(x=>String(x.id)===String(detail));if(!t){detail=null;render();return}const qn=topicQuestions(t.id).length,m=mastery[t.id]||{level:0,seen:0,correct:0};el.innerHTML=`<div class="yb59-wrap"><section class="yb59-detail surface"><button class="back-link" id="yb59-back">← Kütüphaneye dön</button><div class="yb59-detail-head"><span class="yb59-icon">${t.icon||'📚'}</span><div><span class="yb59-kicker">${esc(t.level||'KPSS')} • ${t.minutes||10} DK</span><h1>${esc(t.title)}</h1><p>${esc(t.desc||'')}</p></div></div><div class="yb59-meta"><span>❓ ${qn} soru</span><span>🧠 Hakimiyet ${m.level}/5</span><span>✓ ${m.correct||0} doğru</span><span>✕ ${m.wrong||0} yanlış</span></div><div class="yb59-points">${(t.bullets||[]).map((x,i)=>`<article class="yb59-point"><b>${String(i+1).padStart(2,'0')}</b><p>${esc(x)}</p></article>`).join('')}</div><div class="yb59-tip"><strong>⚡ SINAV İPUCU</strong><p>${esc(t.tip||'Anahtar kavramları neden-sonuç ilişkisiyle tekrar et.')}</p></div><div class="study-actions"><button class="btn primary" id="yb59-practice">🧠 Bu konuyu pekiştir</button><button class="btn secondary" id="yb59-games">🎮 Oyunda kullan</button></div></section></div>`;$('#yb59-back').onclick=()=>{detail=null;render()};$('#yb59-practice').onclick=()=>startReview(t.id);$('#yb59-games').onclick=()=>{const b=$('.mobile-nav [data-view="events"],.nav-item[data-view="events"]');b?.click();toast('Oyun merkezinden seçtiğin konuyu pekiştirebilirsin.')}}
function review(id){const qs=pickQuestions(id);if(!qs.length){toast('Bu konu için henüz soru yok.');return}let i=0,c=0;remember(qs.map(q=>q.id));const modal=document.createElement('div');modal.className='modal-backdrop';modal.innerHTML=`<section class="modal-card yb59-review"><div class="section-head"><div><span class="eyebrow">AKILLI PEKİŞTİRME</span><h2>Bilgini yokla</h2></div><button class="icon-btn" id="yb59-close">×</button></div><div id="yb59-rbody"></div></section>`;document.body.appendChild(modal);$('#yb59-close').onclick=()=>modal.remove();const body=$('#yb59-rbody',modal);function draw(){const q=qs[i];body.innerHTML=`<div class="yb59-review-foot"><span>${i+1}/${qs.length}</span><span class="yb59-mastery">${id?'Konu tekrarı':'Eksik/unutulan bilgiler'}</span></div><div class="yb59-review-q">${esc(q.q||q.question)}</div><div class="yb59-review-options">${(q.options||[]).map((a,k)=>`<button data-a="${k}">${String.fromCharCode(65+k)} · ${esc(a)}</button>`).join('')}</div><div id="yb59-rfeedback"></div>`;$$('[data-a]',body).forEach(b=>b.onclick=()=>answer(+b.dataset.a));}function answer(a){const q=qs[i],ci=+q.answer,ok=a===ci;if(ok)c++;touch(q.id,ok);$$('[data-a]',body).forEach(b=>{b.disabled=true;const k=+b.dataset.a;if(k===ci)b.classList.add('correct');if(k===a&&a!==ci)b.classList.add('wrong')});$('#yb59-rfeedback',body).innerHTML=`<div class="yb59-tip"><strong>${ok?'DOĞRU 🎯':'TEKRAR ET ⚡'}</strong><p>${esc(q.explain||'Doğru cevabı tekrar ederek pekiştir.')}</p><button class="btn primary full" id="yb59-next">${i===qs.length-1?'Sonucu gör':'Sonraki →'}</button></div>`;$('#yb59-next').onclick=()=>{i++;if(i>=qs.length){body.innerHTML=`<div class="yb59-empty"><h2>${c}/${qs.length} doğru 🎉</h2><p>${c===qs.length?'Mükemmel. Bu konunun tekrar aralığını uzattık.':'Yanlışlarını kaydettik; kısa süre sonra tekrar karşına çıkaracağız.'}</p><button class="btn primary full" id="yb59-done">Kapat</button></div>`;$('#yb59-done').onclick=()=>modal.remove()}else draw()};}draw()}
function startReview(id){review(id||null)}
function bind(){$('#yb59-search')?.addEventListener('input',e=>{query=e.target.value;render()});$$('[data-f]').forEach(b=>b.onclick=()=>{filter=b.dataset.f;render()});$$('[data-detail]').forEach(b=>b.onclick=()=>{detail=b.dataset.detail;render()});$$('[data-practice]').forEach(b=>b.onclick=()=>startReview(b.dataset.practice));$('#yb59-due')?.addEventListener('click',()=>startReview(null));$('#yb59-random')?.addEventListener('click',()=>startReview(null));$('#yb59-open-games')?.addEventListener('click',()=>$('.mobile-nav [data-view="events"],.nav-item[data-view="events"]')?.click());$('#yb59-reset')?.addEventListener('click',()=>{if(confirm('Konu hakimiyeti ve tekrar kayıtları sıfırlansın mı?')){mastery={};save(KEY,mastery);render()}})}
new MutationObserver(()=>requestAnimationFrame(render)).observe(document.body,{childList:true,subtree:true});window.YB59Study={render,startReview,mastery:()=>mastery};setTimeout(render,120);
})();
