/* Yurdunu Bil 63 — single orchestration layer */
(()=>{'use strict';if(window.__YB63_CORE__)return;window.__YB63_CORE__=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],V='63.0.0';
const G=[['sprint','⚡','Bilgi Sprinti','60 saniye • hız ve doğruluk'],['ten','🎯','10’da 10','10 soru • seri bonusu'],['hint','💡','İpucu Avı','İpucu kullan • riski yönet'],['lives','❤️','3 Can','3 hata hakkı • sonuna kadar'],['streak','🔥','Seri Ustası','Seriyi koru • çarpanı büyüt'],['region','🧭','Bölge Blitz','Türkiye bölgeleri • hızlı tur']];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const go=v=>{const b=$(`.nav-item[data-view="${v}"],.mobile-nav [data-view="${v}"],.yb63-nav [data-view="${v}"]`);if(b){b.click();return true}return false};
function toast(m,t='ok'){if(window.showToast)return window.showToast(m,t);const r=$('#toast-root');if(!r)return;const x=document.createElement('div');x.className=`toast ${t} show`;x.textContent=m;r.appendChild(x);setTimeout(()=>x.remove(),2300)}
function openGame(id){if(window.YB55Games?.start){window.YB55Games.start(id);return}toast('Oyun motoru henüz hazır değil.','error')}
function events(){const v=$('#view-events');if(!v)return;v.dataset.yb63='1';v.innerHTML=`<div class="yb63-hub"><section class="yb63-hero"><span>🎮 YURDUNU BİL • OYUN MERKEZİ</span><h1>Çalışmayı oyuna çevir.</h1><p>Mini oyunlarda pratik yap, günlük görevini tamamla; istersen Arena’da seçtiğin oyunla rakibine karşı oyna.</p><div class="yb63-actions"><button class="btn primary" data-a="arena">🏆 Arena</button><button class="btn secondary" data-a="quiz">⚡ Hızlı Test</button></div></section><section class="yb63-daily"><div><b>Bugünün rotası</b><span>10 soru + 1 oyun + yanlış tekrarı</span></div><strong>🎯</strong></section><div class="yb63-title"><div><span>6 OYUN</span><h2>Mini Oyunlar</h2></div><small>Tek dokunuşla başlat</small></div><section class="yb63-games">${G.map(g=>`<article class="yb63-game"><div class="yb63-game-top"><span>${g[1]}</span><em>OYNA</em></div><h3>${g[2]}</h3><p>${g[3]}</p><button class="btn secondary full" data-game="${g[0]}">Başlat →</button></article>`).join('')}</section></div>`;v.querySelector('[data-a="arena"]').onclick=()=>window.YBArena?.open?.();v.querySelector('[data-a="quiz"]').onclick=()=>go('quiz');v.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>openGame(b.dataset.game))}
function settings(){const v=$('#view-settings');if(!v)return;v.dataset.yb63='1';const get=k=>localStorage.getItem(k)!=='off',perm=typeof Notification==='undefined'?'unsupported':Notification.permission;v.innerHTML=`<div class="yb63-hub"><section class="yb63-hero"><span>⚙ HESAP MERKEZİ</span><h1>Profil & Ayarlar</h1><p>Profil, bildirim ve çalışma tercihlerini tek merkezden yönet.</p></section><section class="yb63-settings"><article><span>👤</span><div><b>Profil</b><small>Kullanıcı adı ve avatar hesabının kimliği.</small></div><button data-s="profile">Düzenle</button></article><article><span>🔔</span><div><b>Günlük tekrar</b><small>Bugünkü hedefin için akşam hatırlatması.</small></div><input id="yb63-daily" type="checkbox" ${get('yb62_reminders')?'checked':''}></article><article><span>🔥</span><div><b>Seri uyarısı</b><small>Serini kaybetmeden önce hatırlat.</small></div><input id="yb63-streak" type="checkbox" ${get('yb63_streak')?'checked':''}></article><article><span>🚀</span><div><b>Güncelleme bildirimleri</b><small>Yeni sürüm çıktığında haber ver.</small></div><input id="yb63-updates" type="checkbox" ${get('yb63_updates')?'checked':''}></article><article><span>✨</span><div><b>Animasyonlar</b><small>Geçişleri ve mikro animasyonları kullan.</small></div><input id="yb63-motion" type="checkbox" ${get('yb62_motion')?'checked':''}></article></section><section class="yb63-notify"><div><span>🔔</span><div><b>Tarayıcı bildirimleri</b><small>İzin: ${esc(perm)}</small></div></div><button class="btn primary" id="yb63-enable">${perm==='granted'?'Bildirimler Açık ✓':'Bildirimleri Aç'}</button></section><section class="yb63-card"><b>Hesap ve veri</b><p>İlerleme ve profil bilgilerin hesabınla eşleşir. Yerel tercihlerini istediğin zaman değiştirebilirsin.</p><button class="btn secondary" data-s="stats">İstatistiklerime Git →</button></section></div>`;v.querySelector('[data-s="profile"]').onclick=()=>{window.YB62Profile?.sync?.();toast('Profil bilgilerin üst menüdeki avatar ve hesap alanından güncellenebilir.')};v.querySelector('[data-s="stats"]').onclick=()=>go('stats');v.querySelector('#yb63-daily').onchange=e=>pref('yb62_reminders',e.target.checked);v.querySelector('#yb63-streak').onchange=e=>pref('yb63_streak',e.target.checked);v.querySelector('#yb63-updates').onchange=e=>pref('yb63_updates',e.target.checked);v.querySelector('#yb63-motion').onchange=e=>{pref('yb62_motion',e.target.checked);document.documentElement.classList.toggle('yb63-no-motion',!e.target.checked)};v.querySelector('#yb63-enable').onclick=notify}
function pref(k,on){localStorage.setItem(k,on?'on':'off');syncPrefs()}
async function syncPrefs(){if(!window.supabase?.createClient)return;const c=window.YURDUNUBIL_CONFIG||{};try{const s=window.supabase.createClient(c.SUPABASE_URL,c.SUPABASE_PUBLISHABLE_KEY);const u=await s.auth.getUser();if(!u.data?.user)return;await s.rpc('set_user_preferences',{p_daily_reminders:localStorage.getItem('yb62_reminders')!=='off',p_streak_reminders:localStorage.getItem('yb63_streak')!=='off',p_update_notifications:localStorage.getItem('yb63_updates')!=='off',p_push_enabled:typeof Notification!=='undefined'&&Notification.permission==='granted',p_motion_enabled:localStorage.getItem('yb62_motion')!=='off'})}catch{}}
async function notify(){if(typeof Notification==='undefined'){toast('Bu tarayıcı bildirim desteklemiyor.','error');return}const p=await Notification.requestPermission();toast(p==='granted'?'🔔 Bildirimler açıldı.':'Bildirim izni verilmedi.',p==='granted'?'ok':'error');if(p==='granted'){try{const r=await navigator.serviceWorker?.ready;r?.showNotification?.('Yurdunu Bil',{body:'Bildirim sistemi hazır. Bugünkü tekrarını unutma. 📚',icon:'/icon-192.svg',data:{url:'/'}})}catch{}syncPrefs();settings()}}
function notificationBadge(){const target=$('[data-yb62-notify]');if(!target||target.querySelector('.yb63-dot'))return;if(typeof Notification!=='undefined'&&Notification.permission==='granted'){const d=document.createElement('i');d.className='yb63-dot';target.style.position='relative';target.appendChild(d)}}
function updateCheck(){if(window.__YB63_UPDATE_CHECK__)return;window.__YB63_UPDATE_CHECK__=true;fetch(`/yb-release.json?v=${Date.now()}`,{cache:'no-store'}).then(r=>r.ok?r.json():null).then(d=>{const current=document.querySelector('meta[name="yb-version"]')?.content||V;if(!d?.version||d.version===current||localStorage.getItem('yb63_updates')==='off')return;const old=String(localStorage.getItem('yb63_seen_release')||'');if(old===d.version)return;localStorage.setItem('yb63_seen_release',d.version);const n=document.createElement('aside');n.className='yb63-update';n.innerHTML=`<span>🚀 YENİ SÜRÜM</span><b>Yurdunu Bil ${esc(d.version)}</b><p>${esc(d.message||'Yeni sürüm hazır.')}</p><div><button class="btn primary" data-u>Güncelle</button><button class="btn ghost" data-l>Sonra</button></div></aside>`;document.body.appendChild(n);n.querySelector('[data-l]').onclick=()=>n.remove();n.querySelector('[data-u]').onclick=()=>{const u=new URL(location.href);u.searchParams.set('yb-force',d.version);u.searchParams.set('yb-update',Date.now());location.replace(u.href)}}).catch(()=>{})}
function boot(){events();settings();notificationBadge();updateCheck();syncPrefs();setTimeout(()=>{$$('.yb62-update').forEach(x=>x.remove())},900);window.addEventListener('yb:navigate',()=>setTimeout(()=>{if($('#view-events')?.classList.contains('active'))events();if($('#view-settings')?.classList.contains('active'))settings()},90));document.addEventListener('click',e=>{if(e.target.closest('[data-view="events"]'))setTimeout(events,100);if(e.target.closest('[data-view="settings"]'))setTimeout(settings,100)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else setTimeout(boot,30);window.YB63={events,settings,openGame,notify,syncPrefs};})();