/* Yurdunu Bil 82 — dedicated home dashboard */
(()=>{'use strict';
if(window.__YB82_HOME__)return;window.__YB82_HOME__=true;
const $=(s,r=document)=>r.querySelector(s);
function state(){try{return JSON.parse(localStorage.getItem('yb_state_70')||'{}')}catch{return {}}}
function build(){
 const v=$('#view-home');if(!v)return;
 const s=state(),rs=Array.isArray(s.results)?s.results:[],correct=rs.reduce((n,x)=>n+Number(x.correct||0),0),total=rs.reduce((n,x)=>n+Number(x.total||0),0),acc=total?Math.round(correct/total*100):0,name=($('#top-name')?.textContent||'Öğrenci').trim().split(/\s+/)[0]||'Öğrenci';
 const qs=Array.isArray(window.QUESTION_BANK)?window.QUESTION_BANK.length:0,topics=Array.isArray(window.TOPICS)?window.TOPICS.length:0;
 v.innerHTML=`<div class="yb82-home"><section class="yb82-hero"><div class="yb82-hero-copy"><span class="yb82-kicker">YURDUNU BİL • KPSS COĞRAFYA</span><h1>Hoş geldin <strong>${name}.</strong><br>Bugün biraz ilerleyelim.</h1><p>Kısa bir konu tekrarı yap, birkaç soru çöz ve ardından hızını oyun merkezinde test et. İstersen doğrudan Arena'ya geçebilirsin.</p><div class="yb82-actions"><button class="btn primary" data-home="library">📚 Kütüphaneye devam et</button><button class="btn secondary" data-home="events">⚡ Hızlı oyun</button><button class="btn ghost" data-home="arena">⚔️ Arena</button></div></div><div class="yb82-hero-stats"><div class="yb82-stat"><b>${qs}+</b><span>soru havuzu</span></div><div class="yb82-stat"><b>${topics}</b><span>ana konu</span></div><div class="yb82-stat"><b>${rs.length}</b><span>tamamlanan test</span></div><div class="yb82-stat"><b>${total?acc+'%':'—'}</b><span>genel doğruluk</span></div></div></section><section class="yb82-grid"><article class="yb82-card"><div class="yb82-icon">🧠</div><h3>Öğren</h3><p>32 çalışma modülünden birini seç, kısa notları ve sınav ipuçlarını çalış.</p><button class="btn secondary" data-home="library">Kütüphaneyi aç →</button></article><article class="yb82-card"><div class="yb82-icon">🎮</div><h3>Pekiştir</h3><p>6 mini oyunla bilgiyi farklı reflekslerle tekrar et ve skorunu yükselt.</p><button class="btn secondary" data-home="events">Oyun merkezine git →</button></article><article class="yb82-card"><div class="yb82-icon">⚔️</div><h3>Rekabet et</h3><p>Bir oyun modunu seç, gerçek oyuncuya karşı yarış ve reytingini yükselt.</p><button class="btn secondary" data-home="arena">Arena'yı aç →</button></article></section><section class="yb82-strip"><div><span>BUGÜNÜN HEDEFİ</span><h3>10 soru çöz, serini başlat.</h3><p>Her küçük tur uzun vadeli tekrarın bir parçası.</p></div><div class="yb82-progress"><div class="yb82-progress-top"><span>Genel doğruluk</span><b>${total?acc+'%':'İlk turun'}</b></div><div class="yb82-progress-bar"><i style="width:${acc}%"></i></div></div></section></div>`;
 v.querySelectorAll('[data-home]').forEach(b=>{b.addEventListener('click',()=>{const x=b.dataset.home;if(x==='library'||x==='events'){window.navigate?.(x)}else if(x==='arena'){window.YBArena?.open?.()}})});
}
function install(){
 const pw=$('#page-wrap');if(!pw)return;
 let v=$('#view-home');if(!v){v=document.createElement('section');v.id='view-home';v.className='view';pw.insertBefore(v,pw.firstChild)}
 const nav=$('.side-nav');if(nav&&!$('.yb81-home-nav',nav)){const b=document.createElement('button');b.type='button';b.className='yb81-nav-item yb81-home-nav';b.innerHTML='<span class="yb81-icon">⌂</span><span>Ana Sayfa</span>';const lib=$('.nav-item[data-view="library"]',nav);if(lib)lib.insertAdjacentElement('beforebegin',b);b.addEventListener('click',()=>{document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));v.classList.add('active');document.querySelectorAll('.nav-item[data-view],.yb81-nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');const t=$('#page-title');if(t)t.textContent='Ana Sayfa';build();const sc=$('#page-wrap');if(sc)sc.scrollTop=0})}
}
window.addEventListener('load',()=>{install();build()});document.addEventListener('yb:navigate',e=>{if(e.detail?.view==='library')setTimeout(build,100)});setInterval(install,1000);
})();
