/* Yurdunu Bil — onboarding feature */
(()=>{
'use strict';
if(window.__YB_ONBOARDING__)return;window.__YB_ONBOARDING__=true;
const STORAGE_KEY='yb_onboarding_done',PROFILE_KEY='yb_profile_v1';
const AVATARS=[{id:'harita',emoji:'🗺️',label:'Haritacı'},{id:'pusola',emoji:'🧭',label:'Pusulacı'},{id:'dag',emoji:'⛰️',label:'Dağcı'},{id:'su',emoji:'💧',label:'Su Bilgini'},{id:'kitap',emoji:'📚',label:'Kitap Kurdu'},{id:'yildiz',emoji:'⭐',label:'Yıldız Aday'},{id:'roket',emoji:'🚀',label:'Roketçi'},{id:'kalkan',emoji:'🛡️',label:'Şampiyon'},{id:'lens',emoji:'🔍',label:'Araştırmacı'},{id:'kupa',emoji:'🏆',label:'Kupacı'},{id:'fener',emoji:'🔦',label:'Kaşif'},{id:'bey',emoji:'♟️',label:'Stratejist'}];
function getProfile(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'{}')}catch{return {}}}
function saveProfile(p){try{localStorage.setItem(PROFILE_KEY,JSON.stringify(p))}catch{}}
function paint(p){if(!p?.username)return;['side-name','top-name','menu-name'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=p.username});['side-avatar','top-avatar','menu-avatar'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent=p.avatarEmoji||'🧭'});const s=window.YURDUNUBIL_STATE;if(s){s.profile=s.profile||{};s.profile.displayName=p.username;s.profile.username=p.username;s.profile.avatarEmoji=p.avatarEmoji||'🧭';s.profile.avatarId=p.avatarId||'pusola';s.profile.avatarLabel=p.avatarLabel||'Pusulacı';try{localStorage.setItem('yb_state_70',JSON.stringify(s))}catch{}}}
function applyProfile(p){if(!p?.username)return;const clean={...p,username:String(p.username).trim().slice(0,20)};saveProfile(clean);localStorage.setItem(STORAGE_KEY,'1');paint(clean);window.dispatchEvent(new CustomEvent('yb:profile-set',{detail:clean}))}
function client(){try{const c=window.YURDUNUBIL_CONFIG||{};if(!c.SUPABASE_URL||!c.SUPABASE_PUBLISHABLE_KEY||!window.supabase)return null;return window.supabase.createClient(c.SUPABASE_URL,c.SUPABASE_PUBLISHABLE_KEY)}catch{return null}}
async function hydrateFromSupabase(){const sb=client();if(!sb)return false;try{const{data:sessionData}=await sb.auth.getSession();const session=sessionData?.session;if(!session?.user)return false;const uid=session.user.id;const{data:p,error}=await sb.from('profiles').select('id,display_name,avatar_id,avatar_emoji,avatar_label').eq('id',uid).maybeSingle();if(error)return false;if(p?.display_name){const av=AVATARS.find(a=>a.id===p.avatar_id);applyProfile({username:p.display_name,avatarId:p.avatar_id||av?.id||'pusola',avatarEmoji:p.avatar_emoji||av?.emoji||'🧭',avatarLabel:p.avatar_label||av?.label||'Pusulacı',updatedAt:new Date().toISOString()});return true}const meta=session.user.user_metadata||{};if(meta.display_name){const a=AVATARS[0];const fallback={username:String(meta.display_name).trim().slice(0,20),avatarId:a.id,avatarEmoji:a.emoji,avatarLabel:a.label,updatedAt:new Date().toISOString()};applyProfile(fallback);await saveSupabase(fallback);return true}return false}catch(e){console.warn('profile hydrate',e);return false}}
function needsOnboarding(){const p=getProfile();return !p.username||!p.avatarId}
async function isUsernameTaken(username,currentUid){const sb=client();if(!sb||!username)return false;try{const{data,error}=await sb.from('profiles').select('id,display_name').ilike('display_name',username).limit(10);if(error||!Array.isArray(data))return false;return data.some(x=>x.id!==currentUid&&String(x.display_name||'').trim().toLocaleLowerCase('tr-TR')===username.toLocaleLowerCase('tr-TR'))}catch{return false}}
function open(){if(!needsOnboarding())return;const old=document.getElementById('yb-onboarding');if(old)return;const w=document.createElement('div');w.id='yb-onboarding';w.innerHTML=`<div class="yb-ob-backdrop"></div><section class="yb-ob-card" role="dialog" aria-modal="true"><div class="yb-ob-step" id="yb-ob-step1"><div class="yb-ob-logo">⌖</div><span class="eyebrow">YURDUNU BİL'E HOŞ GELDİN</span><h2>Sana nasıl seslenelim?</h2><p>Arena ve sıralamada görünecek kullanıcı adını seç.</p><div class="yb-ob-name-wrap"><input id="yb-ob-name" type="text" maxlength="20" placeholder="Kullanıcı adın (maks 20 karakter)" autocomplete="off"><span class="yb-ob-name-count" id="yb-ob-name-count">0/20</span></div><div id="yb-ob-name-err" class="yb-ob-err"></div><button class="btn primary yb-ob-next" id="yb-ob-to-avatar">Avatarımı Seç →</button></div><div class="yb-ob-step hidden" id="yb-ob-step2"><span class="eyebrow">2. ADIM</span><h2>Avatarını seç.</h2><p>Profilinde ve Arena'da görünecek.</p><div class="yb-ob-avatar-grid" id="yb-ob-avatar-grid">${AVATARS.map(a=>`<button type="button" class="yb-ob-av-btn" data-av="${a.id}"><span class="yb-ob-av-emoji">${a.emoji}</span><small>${a.label}</small></button>`).join('')}</div><div class="yb-ob-step2-actions"><button class="btn ghost" id="yb-ob-back">← Geri</button><button class="btn primary" id="yb-ob-finish" disabled>Başlayalım! 🚀</button></div></div></section>`;document.body.appendChild(w);requestAnimationFrame(()=>w.classList.add('yb-ob-visible'));let av=null;const name=w.querySelector('#yb-ob-name');const err=w.querySelector('#yb-ob-name-err');name?.addEventListener('input',()=>w.querySelector('#yb-ob-name-count').textContent=`${name.value.length}/20`);w.querySelector('#yb-ob-to-avatar').onclick=async()=>{const value=name.value.trim();if(value.length<2){err.textContent='En az 2 karakter yazmalısın.';return}const sb=client();let uid=null;try{uid=(await sb?.auth.getUser())?.data?.user?.id||null}catch{}if(await isUsernameTaken(value,uid)){err.textContent='Bu kullanıcı adı zaten kullanılıyor. Başka bir ad seç.';return}err.textContent='';w.querySelector('#yb-ob-step1').classList.add('hidden');w.querySelector('#yb-ob-step2').classList.remove('hidden')};w.querySelector('#yb-ob-back').onclick=()=>{w.querySelector('#yb-ob-step2').classList.add('hidden');w.querySelector('#yb-ob-step1').classList.remove('hidden')};w.querySelectorAll('.yb-ob-av-btn').forEach(b=>b.onclick=()=>{w.querySelectorAll('.yb-ob-av-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');av=b.dataset.av;w.querySelector('#yb-ob-finish').disabled=false});w.querySelector('#yb-ob-finish').onclick=async()=>{const a=AVATARS.find(x=>x.id===av)||AVATARS[0],p={username:name.value.trim(),avatarId:a.id,avatarEmoji:a.emoji,avatarLabel:a.label,createdAt:new Date().toISOString()};applyProfile(p);await saveSupabase(p);w.classList.remove('yb-ob-visible');setTimeout(()=>w.remove(),350);window.dispatchEvent(new CustomEvent('yb:onboarding-done'))}}
async function saveSupabase(p){const sb=client();if(!sb)return false;try{const{data}=await sb.auth.getSession();const uid=data?.session?.user?.id;if(!uid)return false;const row={id:uid,display_name:p.username,avatar_id:p.avatarId,avatar_emoji:p.avatarEmoji,avatar_label:p.avatarLabel};const{error}=await sb.from('profiles').upsert(row,{onConflict:'id'});return !error}catch(e){console.warn('profile save',e);return false}}
async function authProfileSync(){const sb=client();if(!sb)return;try{const{data}=await sb.auth.getSession();if(data?.session?.user)await hydrateFromSupabase();sb.auth.onAuthStateChange(async(event,session)=>{if(event==='SIGNED_IN'&&session?.user){const ok=await hydrateFromSupabase();if(!ok)setTimeout(open,500)}if(event==='SIGNED_OUT'){localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(PROFILE_KEY)}})}catch(e){console.warn('auth profile sync',e)}}
window.YBOnboarding={open,getProfile,getAvatarEmoji:()=>getProfile().avatarEmoji||'🧭',getUsername:()=>getProfile().username||window.YURDUNUBIL_STATE?.profile?.displayName||'Öğrenci',hydrateFromSupabase,hydrateFromRemote:async()=>hydrateFromSupabase(),saveSupabase,reset:()=>{localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(PROFILE_KEY)}};
window.addEventListener('yb:app-ready',()=>setTimeout(async()=>{if(!await hydrateFromSupabase())open()},700));
window.addEventListener('load',async()=>{const restored=await hydrateFromSupabase();if(!restored){const p=getProfile();if(p.username)paint(p)}else{localStorage.setItem(STORAGE_KEY,'1')}if(document.getElementById('app-shell')&&!document.getElementById('app-shell').classList.contains('hidden')&&!restored)setTimeout(open,700);authProfileSync()});
})();