/* Yurdunu Bil 46.0.1 — deterministic first-paint runtime */
(()=>{
'use strict';
if(window.__YB46_RUNTIME__)return;window.__YB46_RUNTIME__=true;
const VERSION='46.0.1',root=window.YB44=window.YB44||{};root.version=VERSION;root.modules=root.modules||{};root.env={production:!['localhost','127.0.0.1'].includes(location.hostname),mobile:matchMedia('(max-width:700px)').matches};root.register=(name,api={})=>{root.modules[name]={...api,version:VERSION};return root.modules[name]};root.ready=name=>Boolean(root.modules[name]);root.require=name=>root.modules[name]||null;root.diagnostics=()=>({version:VERSION,modules:Object.keys(root.modules),views:document.querySelectorAll('.view').length});root.onReady=fn=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn,{once:true}):queueMicrotask(fn);root.register('runtime',{boot:true});
/* Legacy v45 boot is disabled. One controller owns the first paint now. */
window.__YB45_BOOT_EXPERIENCE__=true;
const style=document.createElement('style');style.id='yb46-critical-boot-style';style.textContent=`html.yb46-booting,body.yb46-booting{background:#06101d!important}#auth-screen.hidden{display:none}#yb46-critical-loader{position:fixed;inset:0;z-index:2147483647;display:grid;place-items:center;padding:24px;background:radial-gradient(circle at 50% 18%,rgba(67,190,255,.15),transparent 34%),radial-gradient(circle at 20% 82%,rgba(53,224,195,.08),transparent 30%),#06101d;color:#fff;opacity:1;visibility:visible;pointer-events:auto;transition:opacity .3s ease,visibility .3s ease}#yb46-critical-loader.is-out{opacity:0;visibility:hidden;pointer-events:none}.yb46-critical-card{width:min(420px,92vw);text-align:center}.yb46-critical-logo{width:78px;height:78px;margin:0 auto 21px;border:1px solid rgba(112,231,216,.28);border-radius:24px;display:grid;place-items:center;background:rgba(255,255,255,.055);box-shadow:0 0 70px rgba(63,192,255,.15);animation:yb46p 1.7s ease-in-out infinite}.yb46-critical-logo span{font-size:35px;animation:yb46f 1.5s ease-in-out infinite}.yb46-critical-kicker{font:800 10px/1.2 Inter,system-ui,sans-serif;letter-spacing:.18em;color:#72e6d5}.yb46-critical-title{margin:9px 0 6px;font:900 25px/1.12 Inter,system-ui,sans-serif;letter-spacing:-.04em}.yb46-critical-text{margin:0;color:#9eb0c4;font:500 13px/1.6 Inter,system-ui,sans-serif}.yb46-critical-bar{height:5px;width:min(285px,80vw);margin:22px auto 0;border-radius:99px;background:rgba(255,255,255,.08);overflow:hidden;position:relative}.yb46-critical-bar:before{content:"";position:absolute;inset:0;background:linear-gradient(90deg,transparent,#73e7d6,#8ed8ff,transparent);transform:translateX(-100%);animation:yb46l 1.15s ease-in-out infinite}.yb46-critical-status{margin-top:10px;color:#6f8195;font:600 10px/1.2 Inter,system-ui,sans-serif;min-height:12px}@keyframes yb46p{0%,100%{transform:scale(1);box-shadow:0 0 55px rgba(34,211,194,.09)}50%{transform:scale(1.045);box-shadow:0 0 90px rgba(34,211,194,.22)}}@keyframes yb46f{0%,100%{transform:translateY(0)}50%{transform:translateY(-4px)}}@keyframes yb46l{0%{transform:translateX(-100%)}55%{transform:translateX(15%)}100%{transform:translateX(110%)}}@media(prefers-reduced-motion:reduce){.yb46-critical-logo,.yb46-critical-logo span,.yb46-critical-bar:before{animation:none}.yb46-critical-bar:before{transform:none}}`;(document.head||document.documentElement).appendChild(style);document.documentElement.classList.add('yb46-booting');document.body?.classList.add('yb46-booting');
const loader=document.createElement('div');loader.id='yb46-critical-loader';loader.setAttribute('role','status');loader.setAttribute('aria-live','polite');loader.innerHTML='<div class="yb46-critical-card"><div class="yb46-critical-logo"><span>⌖</span></div><div class="yb46-critical-kicker">YURDUNU BİL • KPSS COĞRAFYA</div><div class="yb46-critical-title">Çalışma alanın hazırlanıyor</div><p class="yb46-critical-text">Haritalar, sorular ve öğrenme araçları yükleniyor…</p><div class="yb46-critical-bar"></div><div class="yb46-critical-status">Çekirdek başlatılıyor…</div></div>';(document.body||document.documentElement).appendChild(loader);
let finished=false;const finish=(msg='Hazır. Hoş geldin!')=>{if(finished)return;finished=true;const s=loader.querySelector('.yb46-critical-status');if(s)s.textContent=msg;document.documentElement.classList.add('yb45-runtime-ready');document.documentElement.classList.remove('yb46-booting');document.body?.classList.add('yb45-ready');document.body?.classList.remove('yb46-booting','yb45-booting');setTimeout(()=>{loader.classList.add('is-out');setTimeout(()=>loader.remove(),360)},140)};
function forceAuth(){const a=document.getElementById('auth-screen'),app=document.getElementById('app-shell');if(a&&!app?.classList.contains('hidden'))return false;if(a&&!app?.classList.contains('hidden')===false&&app?.classList.contains('hidden')){a.classList.remove('hidden');a.style.removeProperty('display');a.style.removeProperty('visibility');a.style.removeProperty('opacity');return true}return !!a}
function watch(){let n=0;const iv=setInterval(()=>{n++;const a=document.getElementById('auth-screen'),app=document.getElementById('app-shell');if(app&&!app.classList.contains('hidden')){clearInterval(iv);finish('Hazır. Hoş geldin!');return}if(a&&!a.classList.contains('hidden')){if(n>=3){clearInterval(iv);finish('Giriş alanı hazır.');return}}if(n>=25){clearInterval(iv);if(a){a.classList.remove('hidden');a.style.removeProperty('display');a.style.removeProperty('visibility');a.style.removeProperty('opacity')}if(app)app.classList.add('hidden');finish('Güvenli başlangıç tamamlandı.')}} ,100);window.addEventListener('load',()=>{setTimeout(()=>{const a=document.getElementById('auth-screen'),app=document.getElementById('app-shell');if(app&&!app.classList.contains('hidden'))finish('Hazır. Hoş geldin!');else if(a){a.classList.remove('hidden');finish('Giriş alanı hazır.')}},700)},{once:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch,{once:true});else watch();window.YB46Runtime={version:VERSION};window.YB46Boot={finish};
})();
