/* Yurdunu Bil — Türkiye harita oyunları */
(()=>{'use strict';
if(window.__YB99_MAP_GAMES__)return;window.__YB99_MAP_GAMES__=true;
const GEO_URL='https://raw.githubusercontent.com/cihadturhan/tr-geojson/master/geo/tr-cities-utf8.json';
const CACHE_KEY='yb99_turkey_geojson_v1';
const REGION={Marmara:['Balıkesir','Bilecik','Bursa','Çanakkale','Edirne','İstanbul','Kırklareli','Kocaeli','Sakarya','Tekirdağ','Yalova'],Ege:['Afyonkarahisar','Aydın','Denizli','İzmir','Kütahya','Manisa','Muğla','Uşak'],Akdeniz:['Adana','Antalya','Burdur','Hatay','Isparta','Kahramanmaraş','Mersin','Osmaniye'],'İç Anadolu':['Aksaray','Ankara','Çankırı','Eskişehir','Karaman','Kayseri','Kırıkkale','Kırşehir','Konya','Nevşehir','Niğde','Sivas','Yozgat'],Karadeniz:['Amasya','Artvin','Bartın','Bayburt','Bolu','Çorum','Düzce','Giresun','Gümüşhane','Karabük','Kastamonu','Ordu','Rize','Samsun','Sinop','Tokat','Trabzon','Zonguldak'],'Doğu Anadolu':['Ağrı','Ardahan','Bingöl','Bitlis','Elazığ','Erzincan','Erzurum','Hakkari','Iğdır','Kars','Malatya','Muş','Tunceli','Van'],'Güneydoğu Anadolu':['Adıyaman','Batman','Diyarbakır','Gaziantep','Kilis','Mardin','Siirt','Şanlıurfa','Şırnak']};
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('tr-TR');
let geo=null,game=null;
const provinces=()=>Array.isArray(window.PROVINCE_DATA)?window.PROVINCE_DATA:[];
const toast=m=>typeof window.toast==='function'&&window.toast(m);
function css(){if(document.getElementById('yb99-style'))return;const s=document.createElement('style');s.id='yb99-style';s.textContent='.yb99-map-modal{position:fixed;inset:0;z-index:10050;display:grid;place-items:center;padding:14px;background:rgba(2,8,18,.82);backdrop-filter:blur(12px)}.yb99-map-panel{width:min(1080px,100%);max-height:94vh;overflow:auto;border:1px solid rgba(117,211,255,.22);border-radius:24px;background:linear-gradient(145deg,#0d2133,#081522);color:#eef8ff;box-shadow:0 30px 100px rgba(0,0,0,.5)}.yb99-map-head{display:flex;justify-content:space-between;gap:14px;padding:18px 20px;border-bottom:1px solid rgba(255,255,255,.07)}.yb99-map-head h2{margin:0}.yb99-map-head p{margin:4px 0 0;color:#8fa9ba;font-size:12px}.yb99-map-close{width:40px;height:40px;border-radius:12px;border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.05);color:#fff;font-size:22px}.yb99-map-gamebar{display:flex;flex-wrap:wrap;gap:8px;padding:14px 20px}.yb99-map-gamebar button{border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.04);color:#dcecf7;border-radius:10px;padding:9px 12px;font-weight:800}.yb99-map-gamebar button.active{background:rgba(49,196,255,.14);border-color:rgba(49,196,255,.35);color:#75ddff}.yb99-map-status{margin:0 20px 12px;padding:12px 14px;border-radius:14px;background:rgba(255,255,255,.035);display:flex;justify-content:space-between}.yb99-map-score{font-weight:900;color:#69e1b3}.yb99-map-stage{margin:0 20px 20px;min-height:410px;border-radius:18px;background:rgba(2,10,18,.45);border:1px solid rgba(255,255,255,.06);display:grid;place-items:center;overflow:hidden}.yb99-svg{width:100%;height:clamp(360px,55vh,620px)}.yb99-province{fill:rgba(71,148,187,.38);stroke:rgba(173,225,246,.52);stroke-width:.7;vector-effect:non-scaling-stroke;cursor:pointer}.yb99-province:hover{fill:rgba(53,211,255,.62)}.yb99-province.target{fill:rgba(255,190,74,.65)}.yb99-province.correct{fill:rgba(67,224,157,.72)}.yb99-province.wrong{fill:rgba(255,90,111,.62)}.yb99-fallback{display:grid;grid-template-columns:repeat(auto-fit,minmax(105px,1fr));gap:8px;padding:18px;width:100%;max-height:55vh;overflow:auto}.yb99-fallback button{padding:10px 7px;border:1px solid rgba(255,255,255,.08);background:rgba(255,255,255,.04);color:#dcecf7;border-radius:10px;font-weight:700}@media(max-width:650px){.yb99-map-panel{border-radius:18px}.yb99-map-stage{min-height:330px;margin:0 12px 14px}.yb99-map-status{margin:0 12px 10px}.yb99-map-gamebar{padding:10px 12px}.yb99-map-head{padding:14px}}';document.head.appendChild(s)}
function modal(){let el=document.querySelector('.yb99-map-modal');if(el)return el;el=document.createElement('div');el.className='yb99-map-modal';el.innerHTML='<section class="yb99-map-panel"><header class="yb99-map-head"><div><h2>🗺️ Türkiye Harita Merkezi</h2><p>Haritayı öğren, hedef ili bul, hızını ve doğruluğunu geliştir.</p></div><button class="yb99-map-close" aria-label="Kapat">×</button></header><div class="yb99-map-gamebar"><button data-mode="province" class="active">📍 İli Bul</button><button data-mode="region">🧭 Bölge Avı</button><button data-mode="sprint">⚡ Harita Sprint</button><button data-mode="explore">🔎 Haritayı İncele</button></div><div class="yb99-map-status"><strong id="yb99-prompt">Harita hazırlanıyor…</strong><span id="yb99-score" class="yb99-map-score">0 XP</span></div><div class="yb99-map-stage" id="yb99-stage">Harita yükleniyor…</div></section></div>';document.body.appendChild(el);el.querySelector('.yb99-map-close').onclick=()=>el.remove();el.addEventListener('click',e=>{if(e.target===el)el.remove()});el.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));return el}
function path(f){const g=f.geometry;if(!g)return'';const polys=g.type==='Polygon'?[g.coordinates]:g.type==='MultiPolygon'?g.coordinates:[];let d='';for(const poly of polys)for(const ring of poly){ring.forEach((p,i)=>d+=(i?'L':'M')+p[0]+' '+(-p[1]));d+='Z'}return d}
function bounds(fs){let x1=180,x2=-180,y1=90,y2=-90;const scan=a=>{if(typeof a[0]==='number'){x1=Math.min(x1,a[0]);x2=Math.max(x2,a[0]);y1=Math.min(y1,a[1]);y2=Math.max(y2,a[1])}else a.forEach(scan)};fs.forEach(f=>f.geometry&&scan(f.geometry.coordinates));return{x1,x2,y1,y2}}
function render(){const stage=document.getElementById('yb99-stage');if(!stage)return;if(!geo?.features){fallback();return}const fs=geo.features.filter(f=>f.geometry&&(f.geometry.type==='Polygon'||f.geometry.type==='MultiPolygon'));if(!fs.length){fallback();return}const b=bounds(fs),W=1000,H=620,pad=18,scale=Math.min((W-pad*2)/(b.x2-b.x1),(H-pad*2)/(b.y2-b.y1)),tx=pad+(W-pad*2-(b.x2-b.x1)*scale)/2-b.x1*scale,ty=pad+(H-pad*2-(b.y2-b.y1)*scale)/2+b.y2*scale,svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox',`0 0 ${W} ${H}`);svg.classList.add('yb99-svg');fs.forEach(f=>{const name=f.properties?.name||f.properties?.NAME||f.properties?.il_adi||f.properties?.city||'';const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',path(f));p.setAttribute('transform',`translate(${tx} ${ty}) scale(${scale} ${-scale})`);p.dataset.norm=norm(name);p.setAttribute('aria-label',name);p.classList.add('yb99-province');p.onclick=()=>pick(name,p);svg.appendChild(p)});stage.replaceChildren(svg)}
function fallback(){const stage=document.getElementById('yb99-stage');if(!stage)return;stage.innerHTML='<div class="yb99-fallback">'+provinces().map(p=>`<button type="button" data-name="${String(p.name).replace(/"/g,'&quot;')}">${p.name}</button>`).join('')+'</div>';stage.querySelectorAll('[data-name]').forEach(b=>b.onclick=()=>pick(b.dataset.name,b))}
function target(mode){const ps=provinces();if(mode==='region'){const rs=Object.keys(REGION),r=rs[Math.floor(Math.random()*rs.length)],list=REGION[r];return{target:list[Math.floor(Math.random()*list.length)],q:`${r} Bölgesi'ne ait bir il bul`}}const t=ps[Math.floor(Math.random()*ps.length)]?.name||'Ankara';return{target:t,q:mode==='sprint'?`⚡ ${t} ilini en hızlı şekilde bul`:`${t} ilini haritada bul`}}
function start(mode='province'){css();const el=modal();el.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));game={mode,score:0,round:0,total:mode==='sprint'?10:Infinity,locked:false};if(mode==='explore'){document.getElementById('yb99-prompt').textContent='Haritayı keşfet';document.getElementById('yb99-score').textContent='Keşif modu';render();return}next()}
function next(){if(game.total!==Infinity&&game.round>=game.total)return finish();const t=target(game.mode);game.target=norm(t.target);game.round++;document.getElementById('yb99-prompt').textContent=t.q;document.getElementById('yb99-score').textContent=`${game.score} XP • ${game.round}${game.total===Infinity?'':'/'+game.total}`;render()}
function pick(name,node){if(!game||game.locked)return;if(game.mode==='explore'){document.getElementById('yb99-prompt').textContent=name;return}game.locked=true;const ok=norm(name)===game.target;if(node?.classList)node.classList.add(ok?'correct':'wrong');game.score=Math.max(0,game.score+(ok?(game.mode==='sprint'?20:15):-5));document.getElementById('yb99-prompt').textContent=ok?'✅ Doğru!':'❌ Tekrar bak';document.getElementById('yb99-score').textContent=`${game.score} XP • ${game.round}${game.total===Infinity?'':'/'+game.total}`;setTimeout(()=>{game.locked=false;next()},700)}
function finish(){document.getElementById('yb99-prompt').textContent='🏁 Harita Sprint tamamlandı!';toast(`Harita Sprint: ${game.score} XP`)}
async function loadGeo(){try{const c=localStorage.getItem(CACHE_KEY);if(c){geo=JSON.parse(c);return render()}}catch{}try{const r=await fetch(GEO_URL,{cache:'force-cache'});if(!r.ok)throw Error('geo');geo=await r.json();try{localStorage.setItem(CACHE_KEY,JSON.stringify(geo))}catch{}render()}catch{fallback();toast('Harita verisi alınamadı; yedek il listesi açıldı.')}}
function open(){css();modal();start('province');loadGeo()}
function inject(){const root=document.getElementById('view-events');if(!root||root.querySelector('[data-yb99-map-card]'))return;const grid=root.querySelector('.yb86-game-grid,.game-grid,.games-grid');if(!grid)return;const card=document.createElement('article');card.className='yb86-game-card yb99-card';card.dataset.yb99MapCard='1';card.innerHTML='<div class="yb86-game-top"><div class="yb86-game-icon">🗺️</div><span class="yb86-pool">81 il</span></div><h3>Türkiye Harita Görevi</h3><p>İli bul, bölgeyi yakala ve Sprint modunda yarış.</p><button class="btn primary" type="button">Haritayı Aç →</button>';card.querySelector('button').onclick=open;grid.appendChild(card)}
const watch=()=>{inject();if(document.querySelector('#view-events.active'))setTimeout(inject,120)};document.addEventListener('yb:navigate',e=>{if(e.detail?.view==='events')setTimeout(watch,80)});window.addEventListener('load',()=>setTimeout(watch,300));window.YBMapGames={open,start};
})();