-- Distribution hardening migration. Production was applied with the same SQL.
-- Seed/refresh the server-authoritative Arena bank from the canonical v61 question set.
insert into public.arena_question_bank(question_key,topic,question_text,options,correct_index,difficulty,active) values
('v61-k-01','konum','Türkiye’nin 26°-45° doğu meridyenleri arasında yer alması aşağıdakilerden hangisini doğrudan açıklar?','["Kuzey-güney sıcaklık farkını","Doğu-batı yerel saat farkını","Dört mevsimin yaşanmasını","Denizlerin dağılışını"]'::jsonb,1,2,true),
('v61-k-02','konum','Türkiye’de kuzeye gidildikçe genel olarak sıcaklığın azalmasının temel nedeni nedir?','["Boylam","Enlem","Yükselti","Bakı"]'::jsonb,1,2,true),
('v61-k-03','konum','Aşağıdakilerden hangisi Türkiye’nin özel konumunun sonucudur?','["Yerel saat farkının oluşması","Güneş ışınlarının geliş açısının değişmesi","Boğazların stratejik önemi","Gece-gündüz sürelerinin değişmesi"]'::jsonb,2,3,true),
('v61-ik-01','iklim','Karadeniz kıyılarında yıllık yağışın fazla olmasında aşağıdakilerden hangisi daha etkilidir?','["Nemli hava ve dağların yükselmeye zorlaması","Çöl rüzgârları","Sürekli yüksek basınç","Kutup hava kütlelerinin yıl boyu etkisi"]'::jsonb,0,2,true),
('v61-ik-02','iklim','İç Anadolu’da gece-gündüz sıcaklık farkının kıyılara göre fazla olmasının temel nedeni hangisidir?','["Denizelliğin güçlü olması","Karasallık","Nem oranının çok yüksek olması","Gelgit"]'::jsonb,1,2,true),
('v61-ik-03','iklim','Akdeniz kıyılarında kış yağışlarının belirgin olması hangi iklim özelliğini gösterir?','["Yaz kuraklığı-kış yağışı","Her mevsim eşit yağış","Yaz yağışlarının baskınlığı","Muson rejimi"]'::jsonb,0,2,true),
('v61-yer-01','yerseki','Türkiye’de karstik şekillerin yaygınlaşmasında hangi kayaç türünün yaygınlığı önemlidir?','["Kalker","Granit","Bazalt","Gnays"]'::jsonb,0,2,true),
('v61-yer-02','yerseki','Dağların kıyıya paralel uzanması aşağıdakilerden hangisini zorlaştırabilir?','["Kıyı ile iç kesimler arasındaki ulaşımı","Güneşlenmeyi","Yerel saat farkını","Enlem değişimini"]'::jsonb,0,2,true),
('v61-yer-03','yerseki','Bir akarsuyun denize ulaştığı yerde delta oluşturabilmesi için aşağıdakilerden hangisinin zayıf olması beklenir?','["Alüvyon birikimi","Kıyıdaki güçlü dalga ve akıntılar","Akarsu taşıması","Sığ kıyı koşulları"]'::jsonb,1,3,true),
('v61-ak-01','akarsular','Türkiye akarsularının rejimlerinin genellikle düzensiz olmasının temel nedeni hangisidir?','["Yağışın yıl içine eşit dağılmaması","Okyanus gelgitleri","Akarsuların çok kısa olması","Her yerde aynı iklimin görülmesi"]'::jsonb,0,2,true),
('v61-ak-02','akarsular','Akarsu yatağının eğiminin artması aşağıdakilerden hangisini genellikle artırır?','["Aşındırma gücünü","Delta oluşumunu","Rejimin düzenliliğini","Yerel saati"]'::jsonb,0,2,true),
('v61-ak-03','akarsular','Aşağıdakilerden hangisi Türkiye’de hidroelektrik potansiyelin yüksek olmasının nedenlerinden biridir?','["Yükselti farklarının fazla olması","Gelgitin güçlü olması","Akarsuların tamamının düzenli rejimli olması","Okyanus kıyılarının geniş olması"]'::jsonb,0,3,true),
('v61-nufus-01','nufus','Türkiye’de nüfusun kıyı kuşağında bazı iç kesimlere göre daha yoğun olmasında hangisi etkili olabilir?','["İklim ve ekonomik faaliyet çeşitliliği","Her yerde aynı yükselti","Kutup koşulları","Çöl iklimi"]'::jsonb,0,2,true),
('v61-nufus-02','nufus','Aşağıdakilerden hangisi nüfus yoğunluğunu artırabilecek beşerî faktördür?','["Sanayi ve istihdam olanakları","Dağlık arazi","Kuraklık","Uzun kış koşulları"]'::jsonb,0,2,true),
('v61-nufus-03','nufus','Kırdan kente göçün sonuçlarından biri aşağıdakilerden hangisidir?','["Kentlerde nüfus artışı","Tüm tarım alanlarının artması","Ulaşım ihtiyacının azalması","Kentleşmenin yavaşlaması"]'::jsonb,0,2,true),
('v61-tar-01','tarim','Sulama imkânlarının artırılması aşağıdakilerden hangisini doğrudan destekler?','["Kurak bölgelerde tarımsal üretimi","Dağların yükselmesini","Yerel saat farkını","Kıyıların oluşumunu"]'::jsonb,0,2,true),
('v61-tar-02','tarim','Çay tarımının Doğu Karadeniz’de gelişmesinde hangisi önemlidir?','["Nemli iklim koşulları","Yazların çok kurak olması","Çöl toprağı","Yıl boyu don"]'::jsonb,0,2,true),
('v61-tar-03','tarim','Zeytin üretimi için aşağıdaki koşullardan hangisi daha uygundur?','["Kışların ılık geçmesi","Uzun süreli sert don","Yıl boyu kar örtüsü","Tundra iklimi"]'::jsonb,0,2,true),
('v61-maden-01','maden','Bir maden yatağının işletilebilmesi için yalnızca rezervin bulunması neden yeterli değildir?','["Tenör, ulaşım ve ekonomik koşullar da önemlidir","Madenler her yerde aynı miktardadır","İklim hiçbir rol oynamaz","Pazarın önemi yoktur"]'::jsonb,0,3,true),
('v61-maden-02','maden','Türkiye’de bor minerallerinin önemli olmasının temel nedeni nedir?','["Dünya rezervlerinde önemli paya sahip olması","Hiç işlenememesi","Sadece kıyılarda bulunması","Yalnızca enerji üretiminde kullanılması"]'::jsonb,0,2,true),
('v61-enerji-01','enerji','Jeotermal enerji potansiyelinin Batı Anadolu’da yüksek olmasında hangi yapı daha önemlidir?','["Fay sistemleri ve tektonik hareketlilik","Buzullar","Musonlar","Mercan resifleri"]'::jsonb,0,3,true),
('v61-enerji-02','enerji','Rüzgâr enerjisi için aşağıdakilerden hangisi temel avantajdır?','["Rüzgârın yeterli hız ve sürekliliğe sahip olması","Yıl boyu tamamen durgun hava","Yoğun orman örtüsü","Yüksek yeraltı suyu"]'::jsonb,0,2,true),
('v61-ulasim-01','ulasim','Ege Bölgesi’nde dağların kıyıya dik uzanması hangi sonucu destekler?','["Kıyı ile iç kesimler arasında ulaşımın görece kolaylaşmasını","Kıyıların tamamen kapalı olmasını","Yerel saat farkının artmasını","Kışların kutup koşullarına dönüşmesini"]'::jsonb,0,2,true),
('v61-ulasim-02','ulasim','Bir limanın hinterlandının geniş olması aşağıdakilerden hangisini olumlu etkileyebilir?','["Limanın ticari önemini","Deprem riskini sıfırlamayı","Yağış miktarını","Enlem değerini"]'::jsonb,0,3,true),
('v61-tur-01','turizm','Pamukkale’nin turizm değerinde aşağıdakilerden hangisi öne çıkar?','["Traverten ve termal kaynaklar","Kutup buzulları","Tropikal yağmur ormanları","Mercan adaları"]'::jsonb,0,2,true),
('v61-tur-02','turizm','Kış turizminin gelişmesi için aşağıdakilerden hangisi daha gereklidir?','["Yeterli kar ve uygun eğim-yükselti koşulları","Yıl boyu deniz suyu sıcaklığı","Çölleşme","Gelgit"]'::jsonb,0,2,true),
('v61-cev-01','cevre','Erozyonla mücadelede aşağıdakilerden hangisi daha etkilidir?','["Bitki örtüsünü korumak","Eğimli arazide çıplak toprağı artırmak","Ormanları azaltmak","Yanlış sulamayı yaygınlaştırmak"]'::jsonb,0,2,true),
('v61-cev-02','cevre','Plansız kentleşmenin sel riskini artırabilmesinin nedeni hangisidir?','["Geçirimsiz yüzeylerin artması ve doğal drenajın bozulması","Bitki örtüsünün her yerde artması","Akarsu yataklarının genişlemesi","Yağışın tamamen durması"]'::jsonb,0,3,true),
('v61-afet-01','dogal-afetler','Heyelan riskinin yüksek olması beklenen bir alanda aşağıdakilerden hangisinin birlikte bulunması daha olasıdır?','["Eğimli arazi ve bol yağış","Düz arazi ve sürekli kuraklık","Çöl ve eğimsiz yüzey","Mercan adası"]'::jsonb,0,2,true),
('v61-afet-02','dogal-afetler','Çığ riskini artıran koşullardan biri hangisidir?','["Eğimli yüksek dağlık alan ve kalın kar örtüsü","Düz ve sıcak kıyı","Kurak ova","Deniz seviyesi"]'::jsonb,0,2,true)
on conflict(question_key) do update set topic=excluded.topic,question_text=excluded.question_text,options=excluded.options,correct_index=excluded.correct_index,difficulty=excluded.difficulty,active=true,updated_at=now();

create or replace function public.arena_create_match(p_mode text default 'duel',p_topic text default null,p_question_count integer default 10) returns public.arena_matches language plpgsql security definer set search_path to 'public','pg_catalog' as $function$
declare m public.arena_matches; n text; g text; s jsonb; q_count integer; begin
if auth.uid() is null then raise exception 'auth_required'; end if;
g:=coalesce((select game_type from public.arena_game_preferences where user_id=auth.uid()),'ten'); s:=coalesce((select settings from public.arena_game_preferences where user_id=auth.uid()),'{}'::jsonb); n:=coalesce((select raw_user_meta_data->>'display_name' from auth.users where id=auth.uid()),(select raw_user_meta_data->>'full_name' from auth.users where id=auth.uid()),'Oyuncu'); q_count:=least(greatest(coalesce(p_question_count,10),5),20);
perform public.arena_sync_profile(n); insert into public.arena_ratings(user_id) values(auth.uid()) on conflict(user_id) do nothing;
insert into public.arena_matches(code,mode,topic,question_count,created_by,game_type,game_settings,expires_at) values(public.arena_make_code(),coalesce(nullif(p_mode,''),'duel'),nullif(trim(p_topic),''),q_count,auth.uid(),g,s,now()+interval '30 minutes') returning * into m;
insert into public.arena_players(match_id,user_id,display_name,rating) values(m.id,auth.uid(),n,coalesce((select rating from public.arena_ratings where user_id=auth.uid()),1000));
insert into public.arena_match_questions(match_id,question_index,question_id) select m.id,row_number() over(order by random())-1,id from public.arena_question_bank where active and (m.topic is null or topic=m.topic) order by random() limit q_count;
if (select count(*) from public.arena_match_questions where match_id=m.id)<q_count then delete from public.arena_match_questions where match_id=m.id; insert into public.arena_match_questions(match_id,question_index,question_id) select m.id,row_number() over(order by random())-1,id from public.arena_question_bank where active order by random() limit q_count; end if; return m; end;$function$;

create or replace function public.arena_submit_answer(p_match_id uuid,p_player_id uuid,p_question_index integer,p_answer_index integer,p_is_correct boolean default null,p_response_ms integer default null,p_points integer default null) returns jsonb language plpgsql security definer set search_path to 'public' as $function$
declare v_uid uuid:=auth.uid(); v_qid uuid; v_correct smallint; v_correct_now boolean; v_points integer; v_response integer; v_match public.arena_matches; v_players integer; v_answered integer; v_new_index integer; v_done boolean; v_winner uuid; begin
if v_uid is null then raise exception 'authentication required'; end if; select * into v_match from public.arena_matches where id=p_match_id for update; if not found or v_match.status not in('active','waiting') then raise exception 'match unavailable'; end if; if not exists(select 1 from public.arena_players where id=p_player_id and match_id=p_match_id and user_id=v_uid) then raise exception 'player mismatch'; end if; if p_question_index<>v_match.current_question then raise exception 'stale_question'; end if; select question_id into v_qid from public.arena_match_questions where match_id=p_match_id and question_index=p_question_index; if v_qid is null then raise exception 'server question not configured'; end if; select correct_index into v_correct from public.arena_question_bank where id=v_qid and active; if v_correct is null then raise exception 'question unavailable'; end if; if p_answer_index<0 or p_answer_index>5 then raise exception 'invalid answer'; end if; if exists(select 1 from public.arena_answers where player_id=p_player_id and question_index=p_question_index) then raise exception 'answer already submitted'; end if;
if v_match.question_started_at is null then update public.arena_matches set question_started_at=now(),last_activity_at=now() where id=p_match_id returning * into v_match; end if; v_correct_now:=p_answer_index=v_correct; v_response:=greatest(0,least(extract(epoch from(clock_timestamp()-v_match.question_started_at))::integer,120000)); v_points:=case when v_correct_now then greatest(10,1000-least(v_response,99000)/100) else 0 end;
insert into public.arena_answers(match_id,player_id,question_index,answer_index,is_correct,response_ms,points) values(p_match_id,p_player_id,p_question_index,p_answer_index,v_correct_now,v_response,v_points); update public.arena_players set score=score+v_points,correct=correct+case when v_correct_now then 1 else 0 end,answered=answered+1 where id=p_player_id;
select count(*) into v_players from public.arena_players where match_id=p_match_id; select count(*) into v_answered from public.arena_answers where match_id=p_match_id and question_index=p_question_index; v_new_index:=p_question_index+1; v_done:=v_new_index>=v_match.question_count;
if v_answered>=v_players then if v_done then select user_id into v_winner from public.arena_players where match_id=p_match_id order by score desc,correct desc,answered asc limit 1; update public.arena_matches set status='finished',finished_at=now(),current_question=v_new_index,current_round=v_new_index,winner_user_id=v_winner,question_started_at=null,last_activity_at=now(),result_applied=true where id=p_match_id; else update public.arena_matches set current_question=v_new_index,current_round=v_new_index,question_started_at=now(),last_activity_at=now() where id=p_match_id; end if; else update public.arena_matches set last_activity_at=now() where id=p_match_id; end if;
return jsonb_build_object('accepted',true,'is_correct',v_correct_now,'points',v_points,'response_ms',v_response,'current_question',case when v_answered>=v_players then v_new_index else p_question_index end,'finished',v_done and v_answered>=v_players,'winner_user_id',v_winner); end;$function$;

revoke execute on function public.get_learning_dashboard() from anon;
revoke execute on function public.record_learning_answer(text,boolean,text,integer) from anon;
grant execute on function public.get_learning_dashboard() to authenticated;
grant execute on function public.record_learning_answer(text,boolean,text,integer) to authenticated;